(function() { 
var g=function(a){this.ta=0;this.G=null;this.ra=false;this.l=null;this.L=false;var b=this,c=function(e){b.l=e.target;if(e.target.tagName=="INPUT"||e.target.tagName=="SELECT"||e.target.tagName=="TEXTAREA")b.L=true;return true};document.addEventListener("focus",c,true);var d=function(e){b.ba(b.l,"aria-activedescendant");b.l=null;if(e.target.tagName=="INPUT"||e.target.tagName=="SELECT"||e.target.tagName=="TEXTAREA")b.L=false;return true};document.addEventListener("blur",d,true);if(a){this.ra=true;document.addEventListener("keypress",
function(e){b.Ra(e,b)},true);document.body.Ta=true}this.R=document.body};g.prototype.p=function(){var a=this.R;while(a.nodeType!=9)a=a.parentNode;return a};g.prototype.qa=function(a,b){if(!a.id)this.ia(a);if(b){this.v(a,"live","rude");this.v(a,"atomic","true");var c=this.p(),d=c.createElement("div");d.textContent=" ";d.name="AxsJAX_dummyNode";if(a.lastChild&&a.lastChild.name&&a.lastChild.name==d.name)a.removeChild(a.lastChild);a.appendChild(d)}else{var e=this.Ga(a,"role");this.v(a,"role","row");var f=
this.l;if(!f||f.nodeType==9){this.R.tabIndex=-1;f=this.R}this.v(f,"activedescendant",null);f.focus();this.v(f,"activedescendant",a.id);var h=this;window.setTimeout(function(){if(e)h.v(a,"role",e);else h.ba(a,"role")},0)}};g.prototype.F=function(a,b){var c="AxsJAX_pixelAudioNode",d="AxsJAX_pixelAudioNode",e="data:image/gif;base64,R0lGODlhAQABAIAAANvf7wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",f=this.p(),h=null;if(b){if(b.previousSibling&&b.previousSibling.name==d)h=b.previousSibling;else{h=f.createElement("img");
h.name=d;h.setAttribute("tabindex",0);h.style.outline="none";h.src=e;b.parentNode.insertBefore(h,b);this.Da(h)}h.setAttribute("alt",a);h.setAttribute("title",a);window.setTimeout(function(){h.blur();h.focus()},0)}else{h=f.getElementById(c);if(!h){h=f.createElement("img");h.id=c;h.src=e;f.body.appendChild(h)}h.setAttribute("alt",a);h.setAttribute("title",a);this.qa(h)}};g.prototype.Aa=function(a,b){var c=this.p(),d=c.createEvent("MouseEvents");d.initMouseEvent("mousedown",true,true,c.defaultView,1,
0,0,0,0,false,false,b,false,0,null);try{a.dispatchEvent(d)}catch(e){}d=c.createEvent("MouseEvents");d.initMouseEvent("mouseup",true,true,c.defaultView,1,0,0,0,0,false,false,b,false,0,null);try{a.dispatchEvent(d)}catch(e){}d=c.createEvent("MouseEvents");d.initMouseEvent("click",true,true,c.defaultView,1,0,0,0,0,false,false,b,false,0,null);try{a.dispatchEvent(d)}catch(e){}if(a.tagName=="A"&&a.href&&(a.href.indexOf("http")===0||a.href.indexOf("javascript:")===0))if(b)window.open(a.href);else document.location=
a.href};g.prototype.ia=function(a,b){if(!a)return"";if(a.id)return a.id;var c=b||"AxsJAX_ID_";a.id=c+this.ta++;return a.id};g.prototype.pa=function(a){if(!a)return false;if(a.tagName=="A"||a.tagName=="INPUT"){this.G=a;return true}var b=a.getElementsByTagName("*");for(var c=0,d;d=b[c];c++)if(d.tagName=="A"||d.tagName=="INPUT"||d.hasAttribute("tabindex")&&d.tabIndex!=-1){this.G=d;return true}return false};g.prototype.Ra=function(a,b){if(!b.ra)return true;if(a.keyCode==9&&b.G){b.G.focus();b.G=null}return true};
g.prototype.U=function(a){this.qa(a);a.scrollIntoView(true);this.pa(a)};g.prototype.v=function(a,b,c){if(!a)return;b=b.toLowerCase();switch(b){case "live":b="aria-live";break;case "activedescendant":b="aria-activedescendant";break;case "atomic":b="aria-atomic";break;default:break}a.setAttribute(b,c)};g.prototype.Ga=function(a,b){return a.getAttribute(b)};g.prototype.ba=function(a,b){if(a&&a.removeAttribute)a.removeAttribute(b)};g.prototype.Da=function(a){var b=this.ia(a),c=this.p(),d=c.$a,e=d.indexOf("#");
if(e!=-1)d=d.substring(0,e);c.location=d+"#"+b};g.prototype.t=function(a,b){try{var c=b.ownerDocument.evaluate(a,b,null,XPathResult.ORDERED_NODE_ITERATOR_TYPE,null)}catch(d){return[]}var e=[];for(var f=c.iterateNext();f;f=c.iterateNext())e.push(f);return e};var j=function(a){this.Z="";this.aa="";this.c=[];this.a=0;this.d=[];this.j=null;this.P=[];this.r={};this.s={};this.o=[];this.q=[];this.e=a;this.m=null;this.n=null;this.ua="list";this.ga="item";this.ha="wrap";this.u=null};j.ab={Ya:", next list. ",Za:", previous list. ",Xa:", go forward. ",Wa:", go backwards. ",Ua:", cycle next. ",Va:", cycle previous. "};j.prototype.M=function(a){var b=[],c=a.getElementsByTagName("item");for(var d=0,e;e=c[d];d++)try{var f=e.textContent;f=f.replace(/^\s\s*/,"").replace(/\s\s*$/,
"");var h=this.e.p().documentElement,k=this.e.t(f,h),i=e.getAttribute("index")||"0",q=parseInt(i,10),n=k.length-q,l=e.getAttribute("count")||"*";if(l!="*")n=parseInt(l,10);var r=n+q,o=e.getAttribute("action")||null;while(q<r){var p={};p.action=o;p.f=k[q];if(typeof p.f!="undefined"){if(typeof p.f.z=="undefined")p.f.z={};p.f.z[this.c.length]=b.length;b.push(p)}q++}}catch(t){}return b};j.prototype.fa=function(a){var b=true;if(a.type=="dynamic"&&a.i.length===0){if(this.m!==null)this.m.view(null);a.i=
this.M(a.J);a.ea=this.oa(a.J);this.d[this.a]=-1}if(a.i.length===0&&a.S===null)b=false;return b};j.prototype.la=function(){var a=this.K(),b=a.S,c=null;if(b!==null){this.H(b);c=this.T(b.action)}if(c===null){this.va();if(this.n!==null)this.n.play(this.ua)}};j.prototype.Ma=function(){if(this.c.length<1)return null;for(var a=0,b;b=this.c[a];a++){this.a++;if(this.a>=this.c.length)this.a=0;if(this.fa(this.c[this.a]))break}return this.K()};j.prototype.Oa=function(){if(this.c.length<1)return null;for(var a=
0,b;b=this.c[a];a++){this.a--;if(this.a<0)this.a=this.c.length-1;if(this.fa(this.c[this.a]))break}return this.K()};j.prototype.K=function(){return this.c[this.a]};j.prototype.va=function(){this.e.F(this.K().title)};j.prototype.O=function(){if(this.c.length<1)return null;var a=this.c[this.a],b=a.i;if(b.length<1)return null;if(this.j){var c=this.j.f.z[this.a];if(typeof c!="undefined")this.d[this.a]=c}this.d[this.a]++;var d=false;if(this.d[this.a]>=b.length){this.d[this.a]=0;d=true}var e=this.d[this.a];
if(b[e].f.parentNode===null){if(this.m!==null)this.m.view(null);a.i=this.M(a.J);this.d[this.a]=0;e=this.d[this.a]}this.j=b[e];if(this.n!==null)if(d)this.n.play(this.ha);else this.n.play(this.ga);return this.j};j.prototype.Ea=function(){var a=this.c[this.a],b=this.d[this.a];if(a.da!==null&&b+1>=a.i.length){this.H(a.da);this.d[this.a]=0;return null}var c=this.O();return c};j.prototype.$=function(){if(this.c.length<1)return null;var a=this.c[this.a],b=a.i;if(b.length<1)return null;if(this.j){var c=this.j.f.z[this.a];
if(typeof c!="undefined")this.d[this.a]=c}this.d[this.a]--;var d=false;if(this.d[this.a]<0){this.d[this.a]=b.length-1;d=true}var e=this.d[this.a];if(b[e].f.parentNode===null){if(this.m!==null)this.m.view(null);a.i=this.M(a.J);this.d[this.a]=a.i.length;e=this.d[this.a]}this.j=b[e];if(this.n!==null)if(d)this.n.play(this.ha);else this.n.play(this.ga);return this.j};j.prototype.ya=function(){var a=this.c[this.a],b=this.d[this.a];if(a.V!==null&&b-1<=-1){this.H(a.V);this.d[this.a]=a.i.length;return null}var c=
this.$();return c};j.prototype.Ba=function(){if(this.c.length<1)return null;if(this.j){var a=this.j.f.z[this.a];if(typeof a!="undefined")this.d[this.a]=a}var b=this.c[this.a],c=b.i,d=this.d[this.a];this.j=c[d];return this.j};j.prototype.T=function(a){var b=null;if(a!==null&&a.indexOf&&a.indexOf("CALL:")===0&&a.indexOf("(")===-1)try{b=eval(a.substring(5))}catch(c){}return b};j.prototype.A=function(a){if(a!==null){var b=this,c=function(){var f=b.T(a.action);if(f)f(a);else{if(b.m!==null)b.m.view(a.f);
b.e.U(a.f)}};if(this.e.l&&this.e.l.blur){var d=this.e.l;this.e.l=null;if(d.removeAttribute)this.e.ba(d,"aria-activedescendant");var e=function(f){f.target.removeEventListener("blur",e,true);c()};d.addEventListener("blur",e,true);d.blur()}else c()}};j.prototype.k=function(a,b,c,d){for(var e=0;e<a.length;e++){var f=a[e];if(f=="LEFT")c[37]=d;else if(f=="UP")c[38]=d;else if(f=="RIGHT")c[39]=d;else if(f=="DOWN")c[40]=d;else if(f=="PGUP")c[33]=d;else if(f=="PGDOWN")c[34]=d;else if(f=="ENTER")c[13]=d;else if(f==
"DEL")c[46]=d;else b[f.charCodeAt(0)]=d}};j.prototype.I=function(a,b,c){var d=[];if(a==="")return;d=a.split(" ");var e=this;if(c=="prev")this.k(d,this.o[b],this.q[b],function(){e.A(e.$())});else if(c=="next")this.k(d,this.o[b],this.q[b],function(){e.A(e.O())});else if(c=="back")this.k(d,this.o[b],this.q[b],function(){e.A(e.ya())});else this.k(d,this.o[b],this.q[b],function(){e.A(e.Ea())})};j.prototype.xa=function(a,b,c){var d=[];if(a==="")return;d=a.split(" ");var e=this;this.k(d,this.r,this.s,function(){if(!e.fa(e.c[b])){e.e.F(c);
return}e.a=b;e.A(e.O())})};j.prototype.wa=function(a,b){var c=[];if(a==="")return;c=a.split(" ");var d=this;this.k(c,this.r,this.s,function(){d.e.F(b)})};j.prototype.ja=function(a,b,c){var d=[];if(a.X==="")return;d=a.X.split(" ");var e=this;this.k(d,b,c,function(){e.H(a)})};j.prototype.H=function(a){var b=a.w,c=this.e.p().documentElement;if(b.indexOf(".")===0)c=this.Ba().f;var d=this.e.t(b,c);if(d.length<1)this.e.F(a.C);else{var e=this.T(a.action);if(e){var f={};f.action=a.action;f.f=d[0];e(f)}else{this.e.Aa(d[0],
false);d[0].scrollIntoView(true)}this.e.pa(d[0])}};j.prototype.Qa=function(a,b){var c=this,d=a.firstChild,e;this.r={};this.s={};this.o=[];this.q=[];var f;for(e=0,f;f=this.P[e];e++)this.ja(f,this.r,this.s);var h=[];this.Z=d.getAttribute("next")||"";if(this.Z!=="")h=this.Z.split(" ");this.k(h,this.r,this.s,function(){c.Ma();c.la()});h=[];this.aa=d.getAttribute("prev")||"";if(this.aa!=="")h=this.aa.split(" ");this.k(h,this.r,this.s,function(){c.Oa();c.la()});var k;for(e=0,k;k=this.c[e];e++){var i={},
q={};this.o.push(i);this.q.push(q);this.I(k.La,e,"next");this.I(k.Na,e,"prev");this.I(k.Fa,e,"fwd");this.I(k.za,e,"back");this.xa(k.W,e,k.C);var n;for(n=0,f;f=k.ea[n];n++)this.ja(f,i,q)}var l;for(e=0,l;l=b[e];e++)this.wa(l.W,l.C);this.u=function(r){if(r.ctrlKey)return true;if(c.e.L)return true;var o=c.a,p=c.q[o][r.keyCode]||c.o[o][r.charCode];if(p)return p();p=c.s[r.keyCode]||c.r[r.charCode];if(p)return p()};document.addEventListener("keypress",this.u,true)};j.prototype.oa=function(a){var b=[],c=
a.getElementsByTagName("target");for(var d=0,e;e=c[d];d++){var f={};f.w=e.textContent;f.w=f.w.replace(/^\s\s*/,"").replace(/\s\s*$/,"");f.title=e.getAttribute("title")||"";f.Q=e.getAttribute("trigger")||"key";f.X=e.getAttribute("hotkey")||"";f.action=e.getAttribute("action")||"click";f.C=e.getAttribute("onEmpty")||"";b.push(f)}return b};j.prototype.Ka=function(a,b){var c=new DOMParser,d=c.parseFromString(a,"text/xml"),e=d.getElementsByTagName("list");this.c=[];this.a=0;this.d=[];var f=[],h,k;for(h=
0,k;k=e[h];h++){var i={};i.J=k;i.title=k.getAttribute("title")||"";i.W=k.getAttribute("hotkey")||"";i.La=k.getAttribute("next")||"";i.Na=k.getAttribute("prev")||"";i.Fa=k.getAttribute("fwd")||"";i.za=k.getAttribute("back")||"";i.C=k.getAttribute("onEmpty")||"";i.type=k.getAttribute("type")||"";i.da=null;i.V=null;i.S=null;i.i=this.M(k);i.ea=this.oa(k);for(var q=0,n;n=i.ea[q];q++)if(n.Q=="listTail")i.da=n;else if(n.Q=="listHead")i.V=n;else if(n.Q=="listEntry")i.S=n;if(i.i.length>0||i.type=="dynamic"){this.c.push(i);
this.d.push(-1)}else if(i.W!=="")f.push(i)}this.P=[];this.bb=0;var l,r=d.firstChild;for(h=0,l;l=r.childNodes[h];h++)if(l.tagName=="target"){var o={};o.w=l.textContent;o.w=o.w.replace(/^\s\s*/,"").replace(/\s\s*$/,"");o.title=l.getAttribute("title")||"";o.Q=l.getAttribute("trigger")||"key";o.X=l.getAttribute("hotkey")||"";o.action=l.getAttribute("action")||"click";o.C=l.getAttribute("onEmpty")||"";this.P.push(o)}if(this.u!==null)document.removeEventListener("keypress",this.u,true);if(b===null||typeof b==
"undefined")this.Qa(d,f);else b(d,this.c,f,this.P)};j.prototype.Pa=function(a){this.m=a};var m=function(a){this.N=1.5;var b=a.p();this.b=b.createElement("span");this.b.style.backgroundColor="#CCE6FF";this.b.style.borderColor="#0000CC";this.b.style.borderWidth="medium";this.b.style.borderStyle="groove";this.b.style.position="absolute";this.Y();this.b.style.display="none";b.body.appendChild(this.b)};m.prototype.view=function(a){while(this.b.firstChild)this.b.removeChild(this.b.firstChild);if(a===null){this.b.style.display="none";return}var b=0,c=0,d=a;if(d.offsetParent){b=d.offsetLeft;
c=d.offsetTop;d=d.offsetParent;while(d!==null){b+=d.offsetLeft;c+=d.offsetTop;d=d.offsetParent}}this.b.appendChild(a.cloneNode(true));this.Y();this.ma();this.b.style.top=c+"px";this.b.style.left=b+"px";this.b.style.zIndex=999;this.b.style.display="block"};m.prototype.ca=function(a){this.N=a;this.Y();this.ma()};m.prototype.ma=function(){var a=this.b.getElementsByTagName("img");for(var b=0,c;c=a[b];b++){if(!c.hasAttribute("Axs_OrigHeight")){c.setAttribute("Axs_OrigHeight",c.height);c.setAttribute("Axs_OrigWidth",
c.width)}c.height=c.getAttribute("Axs_OrigHeight")*this.N;c.width=c.getAttribute("Axs_OrigWidth")*this.N}};m.prototype.Y=function(){var a=this.N*0.52;this.b.style.fontSizeAdjust=a};var s={};s.Sa='.//*[text() == "Information is temporarily unavailable."]';s.sa="The following shortcut keys are available. N, next gadget. P, previous gadget. Slash, jump to search field. Escape, leave the search field. Equals, increase magnification. Minus, decrease magnification. ";s.h=null;s.B=null;s.g=null;s.D=1.5;s.Ja=function(){s.h=new g(true);s.B=new j(s.h);s.g=new m(s.h);s.B.Pa(s.g);s.g.ca(s.D);var a="<cnr next='' prev=''><list title='Gadgets' hotkey='' next='' prev=''><item>id('modules')//div[@class='modbox']</item></list></cnr>";
s.B.Ka(a,null);document.addEventListener("keypress",s.u,true);window.setTimeout(s.na,100)};s.u=function(a){if(a.ctrlKey)return true;if(a.keyCode==27){s.h.l.blur();return false}if(s.h.L)return true;if(a.charCode==47){document.getElementsByName("q")[0].focus();document.getElementsByName("q")[0].select();return false}if(a.charCode==45){s.Ca();return false}if(a.charCode==61){s.Ia();return false}if(a.charCode==110){s.na();return false}if(a.charCode==112){s.Ha();return false}if(a.charCode==63){s.h.F(s.sa);
return false}return true};s.Ia=function(){s.D+=0.1;s.g.ca(s.D)};s.Ca=function(){s.D-=0.1;s.g.ca(s.D)};s.ka=function(){var a=s.h.t(".//a[@class='ddbox']",s.g.b)[0],b=s.h.t(".//a[@class='minbox']",s.g.b)[0],c=s.h.t(".//a[@class='delbox']",s.g.b)[0];a.tabIndex=-1;b.tabIndex=-1;c.tabIndex=-1;var d=s.h.t(s.Sa,s.g.b);if(d===null)return;for(var e=0,f;f=d[e];e++)f.textContent=""};s.na=function(){var a=s.B.O().f;s.g.view(a);s.ka();s.h.U(s.g.b)};s.Ha=function(){var a=s.B.$().f;s.g.view(a);s.ka();s.h.U(s.g.b)};
window.setTimeout(function(){s.Ja()},1000);
 })();
