(function() { var h=true,i=null,j=false,k,n=function(a){this.dc=0;this.fa=i;this.Nb=j;this.q=i;this.Q=j;var b=this;this.za=document.body;this.uc();if(a){this.Nb=h;document.addEventListener("keypress",function(d){b.yd(d,b)},h);document.body.zd=h}this.O(document.body,"role","application")};k=n.prototype;
k.uc=function(){var a=this.A(),b=this,d=function(c){b.q=c.target;if(c.target.tagName=="INPUT"||c.target.tagName=="SELECT"||c.target.tagName=="TEXTAREA")b.Q=h;return h};a.addEventListener("focus",d,h);d=function(c){b.Ua(b.q,"aria-activedescendant");b.q=i;if(c.target.tagName=="INPUT"||c.target.tagName=="SELECT"||c.target.tagName=="TEXTAREA")b.Q=j;return h};a.addEventListener("blur",d,h)};k.A=function(){for(var a=this.za;a.nodeType!=9;)a=a.parentNode;return a};
k.Za=function(a,b){a.id||this.na(a);if(b){this.O(a,"live","rude");this.O(a,"atomic","true");var d=this.A();d=d.createElement("div");d.textContent=" ";d.name="AxsJAX_dummyNode";a.lastChild&&a.lastChild.name&&a.lastChild.name==d.name&&a.removeChild(a.lastChild);a.appendChild(d)}else{var c=this.Mc(a,"role");this.O(a,"role","row");d=this.q;if(!d||d.nodeType==9){this.za.tabIndex=-1;d=this.za}this.O(d,"activedescendant",i);d.focus&&d.focus();this.O(d,"activedescendant",a.id);var e=this;window.setTimeout(function(){c?
e.O(a,"role",c):e.Ua(a,"role")},0)}};
k.o=function(a,b){var d="AxsJAX_pixelAudioNode",c="AxsJAX_pixelAudioNode",e="data:image/gif;base64,R0lGODlhAQABAIAAANvf7wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",f=this.A(),g=i;if(b){if(b.previousSibling&&b.previousSibling.name==c)g=b.previousSibling;else{g=f.createElement("img");g.name=c;g.setAttribute("tabindex",0);g.style.outline="none";g.src=e;b.parentNode.insertBefore(g,b);this.Jc(g)}g.setAttribute("alt",a);g.setAttribute("title",a);window.setTimeout(function(){g.blur();g.focus()},0)}else{if((g=
f.getElementById(d))&&g.alt==a)a+=" ";if(!g){g=f.createElement("img");g.id=d;g.src=e;f.body.appendChild(g)}g.setAttribute("alt",a);g.setAttribute("title",a);this.Za(g)}};
k.Dc=function(a,b){var d=this.A(),c=d.createEvent("MouseEvents");c.initMouseEvent("mousedown",h,h,d.defaultView,1,0,0,0,0,j,j,b,j,0,i);try{a.dispatchEvent(c)}catch(e){}c=d.createEvent("MouseEvents");c.initMouseEvent("mouseup",h,h,d.defaultView,1,0,0,0,0,j,j,b,j,0,i);try{a.dispatchEvent(c)}catch(f){}c=d.createEvent("MouseEvents");c.initMouseEvent("click",h,h,d.defaultView,1,0,0,0,0,j,j,b,j,0,i);try{a.dispatchEvent(c)}catch(g){}d=a.getAttribute("href");if(a.tagName=="A"&&d&&d!="#")if(b)window.open(a.href);
else document.location=a.href};k.na=function(a,b){if(!a)return"";if(a.id)return a.id;var d=b||"AxsJAX_ID_";a.id=d+this.dc++;return a.id};k.aa=function(a){if(!a)return j;if(a.tagName=="A"||a.tagName=="INPUT"){this.fa=a;return h}a=a.getElementsByTagName("*");for(var b=0,d;d=a[b];b++)if(d.tagName=="A"||d.tagName=="INPUT"||d.hasAttribute("tabindex")&&d.tabIndex!=-1){this.fa=d;return h}return j};k.yd=function(a,b){if(!b.Nb)return h;if(a.keyCode==9&&b.fa){b.fa.focus();b.fa=i}return h};
k.Pc=function(a){this.Za(a);a.scrollIntoView(h);this.aa(a)};k.O=function(a,b,d){if(a){b=b.toLowerCase();switch(b){case "live":b="aria-live";break;case "activedescendant":b="aria-activedescendant";break;case "atomic":b="aria-atomic";break;default:break}a.setAttribute(b,d)}};k.Mc=function(a,b){return a.getAttribute(b)};k.Ua=function(a,b){a&&a.removeAttribute&&a.removeAttribute(b)};
k.Jc=function(a){a=this.na(a);var b=this.A(),d=b.baseURI,c=d.indexOf("#");if(c!=-1)d=d.substring(0,c);b.location=d+"#"+a};k.t=function(a,b){try{var d=b.ownerDocument.evaluate(a,b,i,XPathResult.ORDERED_NODE_ITERATOR_TYPE,i)}catch(c){return[]}for(var e=[],f=d.iterateNext();f;f=d.iterateNext())e.push(f);return e};n.Pd=function(a){window.addEventListener("load",function(){a()},h)};var o=function(a){this.ua=this.ta="";this.c=[];this.b=0;this.h=[];this.r=i;this.ga=[];this.J={};this.K={};this.M=[];this.H=[];this.f=a;this.G=this.B=this.F=i;this.fc="list";this.db="item";this.jb="wrap";this.I=i};o.a={gc:"next list",lc:"previous list",bc:"go forward",ac:"go backwards",Vb:"cycle next",Wb:"cycle previous",pc:"Select available action",hc:"No available actions",gb:"Page up",fb:"Page down",T:"Enter",Dd:"Escape",Cd:"Delete",ka:"Up",ha:"Down",eb:"Left",ib:"Right"};k=o.prototype;
k.rd=function(a,b){if(b){this.B=a;this.B.j===i&&this.Gc();var d=this,c=new Array(b);this.v(c,this.J,this.K,function(){d.ud()})}};k.va=function(a){var b=h;if(a.type=="dynamic"&&a.l.length===0){this.F!==i&&this.F.view(i);a.l=this.sa(a.da);a.p=this.Eb(a.da);if(this.c[this.b]===a)this.h[this.b]=-1;else for(var d=0,c;c=this.c[d];d++)if(c===a){this.h[d]=-1;break}}if(a.l.length===0&&a.Fa===i)b=j;return b};
k.qb=function(){var a=this.P();a=a.Fa;var b=i;if(a!==i){this.la(a);b=this.Ha(a.action)}if(b===i){this.wc();this.G!==i&&this.G.play(this.fc)}};k.$c=function(){if(this.c.length<1)return i;for(var a=0;this.c[a];a++){this.b++;if(this.b>=this.c.length)this.b=0;if(this.va(this.c[this.b]))break}return this.P()};k.dd=function(){if(this.c.length<1)return i;for(var a=0;this.c[a];a++){this.b--;if(this.b<0)this.b=this.c.length-1;if(this.va(this.c[this.b]))break}return this.P()};k.P=function(){return this.c[this.b]};
k.wc=function(){this.f.o(this.P().title)};k.Oa=function(){if(this.c.length<1)return i;var a=this.c[this.b],b=a.l;if(b.length<1)return i;if(this.r){var d=this.Ka(a);d=this.r.k.S[d];if(typeof d!="undefined")this.h[this.b]=d}this.h[this.b]++;d=j;if(this.h[this.b]>=b.length){this.h[this.b]=0;d=h}var c=this.h[this.b];if(b[c].k.parentNode===i){this.F!==i&&this.F.view(i);a.l=this.sa(a.da);this.h[this.b]=0;c=this.h[this.b]}this.r=b[c];if(this.G!==i)d?this.G.play(this.jb):this.G.play(this.db);return this.r};
k.Lc=function(){var a=this.c[this.b],b=this.h[this.b];if(a.$a!==i&&b+1>=a.l.length){this.la(a.$a);this.h[this.b]=0;return i}return a=this.Oa()};
k.Jb=function(){if(this.c.length<1)return i;var a=this.c[this.b],b=a.l;if(b.length<1)return i;if(this.r){var d=this.Ka(a);d=this.r.k.S[d];if(typeof d!="undefined")this.h[this.b]=d}this.h[this.b]--;d=j;if(this.h[this.b]<0){this.h[this.b]=b.length-1;d=h}var c=this.h[this.b];if(b[c].k.parentNode===i){this.F!==i&&this.F.view(i);a.l=this.sa(a.da);this.h[this.b]=a.l.length;c=this.h[this.b]}this.r=b[c];if(this.G!==i)d?this.G.play(this.jb):this.G.play(this.db);return this.r};
k.Ac=function(){var a=this.c[this.b],b=this.h[this.b];if(a.Ma!==i&&b<=0){this.la(a.Ma);this.h[this.b]=a.l.length-1;return i}return a=this.Jb()};k.pb=function(){if(this.c.length<1)return i;var a=this.c[this.b];if(this.r){var b=this.Ka(a);b=this.r.k.S[b];if(typeof b!="undefined")this.h[this.b]=b}a=a.l;b=this.h[this.b];return this.r=a[b]};k.Ha=function(a){var b=i;if(a!==i&&a.indexOf&&a.indexOf("CALL:")===0&&a.indexOf("(")===-1)try{b=eval(a.substring(5))}catch(d){}return b};
k.U=function(a){if(a!==i){var b=this,d=function(){var f=b.Ha(a.action);if(f)f(a);else{b.F!==i&&b.F.view(a.k);b.f.Pc(a.k)}};if(this.f.q&&this.f.q.blur){var c=this.f.q;this.f.q=i;c.removeAttribute&&this.f.Ua(c,"aria-activedescendant");var e=function(f){f.target.removeEventListener("blur",e,h);d()};c.addEventListener("blur",e,h);c.blur()}else d()}else{c=this.c[this.b];c.type=="dynamic"&&this.f.o(c.onEmpty)}};
k.v=function(a,b,d,c){for(var e=0,f;f=a[e];e++)if(f=="LEFT")d[37]=c;else if(f=="UP")d[38]=c;else if(f=="RIGHT")d[39]=c;else if(f=="DOWN")d[40]=c;else if(f=="PGUP")d[33]=c;else if(f=="PGDOWN")d[34]=c;else if(f=="ENTER")d[13]=c;else if(f=="ESC")d[27]=c;else if(f=="DEL")d[46]=c;else b[f.charCodeAt(0)]=c};
k.oa=function(a,b,d){var c=[];if(a!==""){c=a.split(" ");var e=this;if(d=="prev")this.v(c,this.M[b],this.H[b],function(){e.U(e.Jb())});else if(d=="next")this.v(c,this.M[b],this.H[b],function(){e.U(e.Oa())});else d=="back"?this.v(c,this.M[b],this.H[b],function(){var f=e.Ac();f!==i&&e.U(f)}):this.v(c,this.M[b],this.H[b],function(){var f=e.Lc();f!=i&&e.U(f)})}};k.zc=function(a,b,d){var c=[];if(a!==""){c=a.split(" ");var e=this;this.v(c,this.J,this.K,function(){if(e.va(e.c[b])){e.b=b;e.U(e.Oa())}else e.f.o(d)})}};
k.yc=function(a,b){var d=[];if(a!==""){d=a.split(" ");var c=this;this.v(d,this.J,this.K,function(){c.f.o(b)})}};k.kb=function(a,b,d){var c=[];if(a.hotkey!==""){c=a.hotkey.split(" ");var e=this;this.v(c,b,d,function(){e.la(a)})}};k.la=function(a){a.action=="click"?this.Ec(a):this.Bc(a)};k.Bc=function(a){var b=this.ub(a);if(b.length<1)this.f.o(a.onEmpty);else{var d=this.Ha(a.action);if(d){var c={};c.action=a.action;c.k=b[0];d(c);this.f.aa(b[0])}else throw new Error("Invalid action: "+a.action);}};
k.Ec=function(a){var b=this.ub(a);if(b.length<1)this.f.o(a.onEmpty);else{this.f.Dc(b[0],j);b[0].scrollIntoView(h);this.f.aa(b[0])}};k.ub=function(a){a=a.u;var b=this.f.A().documentElement;if(a.indexOf(".")===0)b=this.pb().k;return this.f.t(a,b)};k.Ia=function(a,b){var d=i,c=this.b;if(c<this.H.length)d=this.H[c][a]||this.M[c][b]||i;if(d===i)d=this.K[a]||this.J[b];return d};
k.Zc=function(a,b){var d={};d.Cb=[];var c=new DOMParser,e=c.parseFromString(a,"text/xml"),f=e.getElementsByTagName("list"),g;for(c=0;g=f[c];c++){var l={};l.title=g.getAttribute("title");l.hotkey=g.getAttribute("hotkey");l.next=g.getAttribute("next");l.Sa=g.getAttribute("prev");l.Kc=g.getAttribute("fwd");l.back=g.getAttribute("back");l.onEmpty=g.getAttribute("onEmpty");l.type=g.getAttribute("type");var p,m,r,q;l.l=[];var s=g.getElementsByTagName("item");for(p=0;m=s[p];p++){var u={};u.u=m.textContent;
if(m.attributes instanceof NamedNodeMap){r=m.attributes;q=r.length;for(m=0;m<q;m++){var t=r.item(m);u[t.nodeName]=t.value}}l.l.push(u)}l.p=[];s=g.getElementsByTagName("target");for(p=0;m=s[p];p++){g={};g.u=m.textContent;if(m.attributes instanceof NamedNodeMap){r=m.attributes;q=r.length;for(m=0;m<q;m++){t=r.item(m);g[t.nodeName]=t.value}}l.p.push(g)}d.Cb.push(l)}d.p=[];var v=e.firstChild;for(c=0;e=v.childNodes[c];c++)if(e.tagName=="target"){g={};g.u=e.textContent;if(e.attributes instanceof NamedNodeMap){r=
e.attributes;q=r.length;for(m=0;m<q;m++){t=r.item(m);g[t.nodeName]=t.value}}d.p.push(g)}d.next=v.getAttribute("next");d.Sa=v.getAttribute("prev");if(b===i||typeof b=="undefined")this.Fb(d,b);else{c=new (function(C,z,A,B){b(v,z,A,B)});this.Fb(d,c)}};
k.Oc=function(){for(var a=this.Ja(),b="",d=0,c;c=a[d];d++)b=b+c.Z+", "+c.title+". ";b=b+this.ta+", "+o.a.gc;b=b+this.ua+", "+o.a.lc;b=b.replace("PGUP",o.a.gb);b=b.replace("PGDOWN",o.a.fb);b=b.replace("ENTER",o.a.T);b=b.replace("DEL",o.a.Xb);b=b.replace("UP",o.a.ka);b=b.replace("DOWN",o.a.ha);b=b.replace("LEFT",o.a.eb);return b=b.replace("RIGHT",o.a.ib)};
k.Wc=function(){for(var a=this.La(),b="",d=0,c;c=a[d];d++)b=b+c.Z+", "+c.title+". ";a=this.P();if(a.Pa!=="")b=b+a.Pa+", "+o.a.Vb+". ";if(a.Ta!=="")b=b+a.Ta+", "+o.a.Wb+". ";if(a.Ga!=="")b=b+a.Ga+", "+o.a.bc+". ";if(a.Aa!=="")b=b+a.Aa+", "+o.a.ac+". ";b=b.replace("PGUP",o.a.gb);b=b.replace("PGDOWN",o.a.fb);b=b.replace("ENTER",o.a.T);b=b.replace("DEL",o.a.Xb);b=b.replace("UP",o.a.ka);b=b.replace("DOWN",o.a.ha);b=b.replace("LEFT",o.a.eb);return b=b.replace("RIGHT",o.a.ib)};k.qd=function(a){this.F=a};
k.sd=function(a){this.G=a};k.gd=function(a){if(a===i)return j;var b=j;a=this.Ic(a);if(a>-1){b=this.c[a];b.l=[];b.p=[];b=this.va(b)}return b};k.ud=function(){if(this.B!==i){var a=this.Ja(),b=this.La();if(a.length+b.length===0)this.f.o(o.a.hc);else{var d=[],c=0,e="";for(c=0;e=b[c];c++)d.push(e.title);for(c=0;e=a[c];c++)d.push(e.title);this.B.nd(d);this.B.Ob("visible",h,40,20)}}};
k.Ja=function(){for(var a=[],b,d=0,c;c=this.c[d];d++)if(c.Y!==""){b={};b.title=c.title;b.Z=c.Y;a.push(b)}for(d=0;c=this.ga[d];d++)if(this.Ab(c)){b={};b.title=c.title;b.Z=c.hotkey;a.push(b)}return a};k.La=function(){for(var a=[],b=this.P(),d=0,c;c=b.p[d];d++)if(this.Ab(c)){var e={};e.title=c.title;e.Z=c.hotkey;a.push(e)}return a};
k.Gc=function(){var a=this.f.A().body,b=this,d=function(c,e){var f=b.La(),g=b.Ja();f=f.concat(g);f=f[e].Z;f=f.split(" ")[0];var l=g=-1;if(f=="LEFT")g=37;else if(f=="UP")g=38;else if(f=="RIGHT")g=39;else if(f=="DOWN")g=40;else if(f=="PGUP")g=33;else if(f=="PGDOWN")g=34;else if(f=="ENTER")g=13;else if(f=="DEL")g=46;else if(f=="ESC")g=27;else l=f.charCodeAt(0);b.B.j.blur();(f=b.Ia(g,l))&&f()};this.B.Fc(a,50,d,i,this.Id,j);this.B.od(o.a.pc);this.B.ld(h);this.B.Va()};
k.Ab=function(a){var b=j;if(a.hotkey!==""){a=a.u;var d=this.f.A().body;if(a.indexOf(".")===0){var c=this.pb();if(c)d=c.k}a=this.f.t(a,d);if(a.length>0)b=h}return b};
k.Fb=function(a,b){this.c=[];this.b=0;this.h=[];var d=[],c,e;for(c=0;e=a.Cb[c];c++){var f={};e.Na=c;f.Ld=i;f.da=e;f.title=e.title||"";f.Y=e.hotkey||"";f.Pa=e.next||"";f.Ta=e.Sa||"";f.Ga=e.Kc||"";f.Aa=e.back||"";f.onEmpty=e.onEmpty||"";f.type=e.type||"";f.$a=i;f.Ma=i;f.Fa=i;f.l=this.sa(e);f.p=this.Eb(e);e=0;for(var g;g=f.p[e];e++)if(g.trigger=="listTail")f.$a=g;else if(g.trigger=="listHead")f.Ma=g;else if(g.trigger=="listEntry")f.Fa=g;if(f.l.length>0||f.type=="dynamic"){this.c.push(f);this.h.push(-1)}else f.Y!==
""&&d.push(f)}this.ga=[];this.Rd=0;if(a.p)for(c=0;f=a.p[c];c++){e={};e.u=f.u;e.u=e.u.replace(/^\s\s*/,"").replace(/\s\s*$/,"");e.title=f.title||"";e.trigger=f.trigger||"key";e.hotkey=f.hotkey||"";e.action=f.action||"click";e.onEmpty=f.onEmpty||"";this.ga.push(e)}this.I!==i&&document.removeEventListener("keypress",this.I,h);b===i||typeof b=="undefined"?this.td(a,d):b(a,this.c,d,this.ga)};
k.sa=function(a){var b=[];if(!a.l)return b;for(var d=0,c;c=a.l[d];d++)try{var e=c.u.replace(/^\s\s*/,"").replace(/\s\s*$/,""),f=this.f.A().documentElement,g=this.f.t(e,f),l=c.index||"0",p=parseInt(l,10),m=g.length-p,r=c.Md||"*";if(r!="*")m=parseInt(r,10);for(var q=m+p,s=c.action||i;p<q;){c={};c.action=s;c.k=g[p];if(typeof c.k!="undefined"){if(typeof c.k.S=="undefined")c.k.S={};if(typeof a.Na=="undefined")throw new Error("list does not have an id");c.k.S[a.Na]=b.length;b.push(c)}p++}}catch(u){}return b};
k.Eb=function(a){var b=[];if(!a.p)return b;for(var d=0,c;c=a.p[d];d++){var e={};e.u=c.u.replace(/^\s\s*/,"").replace(/\s\s*$/,"");e.title=c.title||"";e.trigger=c.trigger||"key";e.hotkey=c.hotkey||"";e.action=c.action||"click";e.onEmpty=c.onEmpty||"";b.push(e)}return b};
k.td=function(a,b){var d=this,c;this.J={};this.K={};this.M=[];this.H=[];var e;for(c=0;e=this.ga[c];c++)this.kb(e,this.J,this.K);c=[];this.ta=a.next||"";if(this.ta!=="")c=this.ta.split(" ");this.v(c,this.J,this.K,function(){d.$c();d.qb()});c=[];this.ua=a.Sa||"";if(this.ua!=="")c=this.ua.split(" ");this.v(c,this.J,this.K,function(){d.dd();d.qb()});var f;for(c=0;f=this.c[c];c++){var g={},l={};this.M.push(g);this.H.push(l);this.oa(f.Pa,c,"next");this.oa(f.Ta,c,"prev");this.oa(f.Ga,c,"fwd");this.oa(f.Aa,
c,"back");this.zc(f.Y,c,f.onEmpty);var p;for(p=0;e=f.p[p];p++)this.kb(e,g,l)}for(c=0;e=b[c];c++)this.yc(e.Y,e.onEmpty);this.I=function(m){if(m.ctrlKey)return h;if(d.f.Q)return h;if(m=d.Ia(m.keyCode,m.charCode))return m()};document.addEventListener("keypress",this.I,h)};k.Ka=function(a){return a.da.Na};k.Ic=function(a){for(var b=0;b<this.c.length;b++){var d=this.c[b];if(d.title==a)break}return b<this.c.length?b:-1};var w=function(a){this.d=a;this.ba=1.5;this.padding=-1;this.kd=0;this.ma=a.A();this.e=this.ma.createElement("span");this.e.style.backgroundColor="#CCE6FF";this.e.style.borderColor="#0000CC";this.e.style.borderWidth="medium";this.e.style.borderStyle="groove";this.e.style.position="absolute";this.e.style.display="none";this.ma.body.appendChild(this.e);this.mb=function(){}};w.qc={Gd:0,Zb:1};k=w.prototype;
k.view=function(a){for(;this.e.firstChild;)this.e.removeChild(this.e.firstChild);if(a===i)this.e.style.display="none";else{var b=0,d=0,c=a;if(c.offsetParent){b=c.offsetLeft;d=c.offsetTop;for(c=c.offsetParent;c!==i;){b+=c.offsetLeft;d+=c.offsetTop;c=c.offsetParent}}this.e.appendChild(a.cloneNode(h));this.e.style.top=d+"px";this.e.style.left=b+"px";this.e.style.zIndex=999;this.e.style.display="block";this.Db()}};k.Wa=function(a){this.ba=a;this.Db()};
k.Db=function(){this.ma.body.removeChild(this.e);this.Xc();this.Hc();this.vc();this.ma.body.appendChild(this.e);this.mb&&this.mb(this.e);if(this.kd==w.qc.Zb){var a=this;window.setTimeout(function(){a.e.scrollIntoView(h)},0)}};k.vc=function(){if(!(this.padding<0)){var a="//*[not(.//*)]";a=this.d.t(a,this.e);for(var b=0,d;d=a[b];b++)d.style.padding=this.padding+"px"}};
k.Hc=function(){for(var a=this.e.getElementsByTagName("img"),b=0,d;d=a[b];b++){if(!d.hasAttribute("Axs_OrigHeight")){d.setAttribute("Axs_OrigHeight",d.height);d.setAttribute("Axs_OrigWidth",d.width)}d.height=d.getAttribute("Axs_OrigHeight")*this.ba;d.width=d.getAttribute("Axs_OrigWidth")*this.ba}};
k.Xc=function(){var a="fontSizeAdjust"in this.e.style;if(a){var b=this.ba*0.52;this.e.style.fontSizeAdjust=b}else{b=this.ba*100+"%";this.e.style.setProperty("font-size",b,"important")}b=this.e.getElementsByTagName("*");for(var d=0,c;c=b[d];d++){c.style.setProperty("line-height","normal","important");a||c.style.setProperty("font-size","100%","important")}};var x=function(a){var b="http://google-axsjax.googlecode.com/svn/trunk/";this.Nd=b+"common/earcons/axsEarcons.swf?sound=";this.qa=i;this.rb=a;this.vd=b+"thirdparty/soundmanager2/";this.wd=i;this.yb=j;this.Sd="minimal";this.Kd=j;this.Od=0};x.prototype.play=function(){};x.prototype.stop=function(){if(this.qa){this.qa.parentNode.removeChild(this.qa);this.qa=i}if(!this.rb)if(this.yb)this.wd.src=this.vd+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Stop()"};
x.prototype.getTime=function(){if(this.rb)return-1;if(!this.yb)return-1;var a="Time=",b=unescape(document.location.hash);if(b.indexOf(a)==-1)return-1;a=b.indexOf(a)+a.length;return b=parseInt(b.substring(a),10)};var y=function(a,b){this.X=a;this.nb=this.n=this.z=this.j=this.s=i;this.pa="Enter Completion";this.bd="No completions found";this.W=i;this.C=[];this.Yc={};this.i=-1;this.Xa=this.xb=j;this.Ba="#000000";this.Ca=0;this.Tc={};this.ra={};this.Jd={};if(b&&y.N)this.W=b;var d=this;this.V(window,y.wa.nc,function(c){d.cd.call(d,c)},i)};y.Qb=/^\<[A-Z|a-z|0-9|\-|\_]+\>$/;y.ec=/^(\s|\r|\n)+/;y.oc=/(\s|\r|\n)+$/;k=y.prototype;
k.V=function(a,b,d,c){if(y.N&&d)a.addEventListener(b,d,h);else y.m&&d&&a.attachEvent(b,function(g){d(g)});if(c){var e=new y.cb(c),f=this;this.V(a,b,function(g){e.Sc(g,e,f)},i)}};
k.Fc=function(a,b,d,c,e,f){var g=this,l,p,m,r,q;this.s&&this.s.parentNode.removeChild(this.s);do{l="completionField_"+Math.floor(Math.random()*1001);p="txt_"+l;r="div_"+l;q="bgdiv_"+l;m=document.getElementById(l)}while(m);m=document.createElement("div");m.id=q;m.style.display="none";q=document.createElement("div");q.id=l;q.style.position="absolute";l=document.createElement("input");l.type="text";l.id=p;l.size=b;l.value="";l.setAttribute("aria-owns",r);if(y.N)l.onkeypress=function(s){s.stopPropagation();
if(s.keyCode==y.D.xa)return j};if(l.readOnly=f)l.style.fontSize=0;b=document.createElement("div");b.id=r;b.setAttribute("tabindex",0);b.setAttribute("role","row");q.appendChild(b);q.appendChild(l);a.appendChild(m);a.appendChild(q);this.s=q;this.j=l;this.z=m;this.nb=b;this.s.className="pkHiddenStatus";this.j.className="pkOpaqueCompletionText";this.z.className="pkBackgroundHide";if(e){this.C=e;this.Yc[this.X]=[e,this.pa];this.g=this.C;for(a=0;e=this.C[a];a++)this.ra[e.toLowerCase()]=a;this.i=-1}this.V(this.j,
y.wa.ja,function(s){g.Rc.call(g,s,c,d)},i);this.V(this.j,y.wa.ia,function(s){g.Qc.call(g,s)},i);this.V(this.j,"blur",function(){g.xb&&g.Ob("hidden")},i)};k.ld=function(a){this.xb=a};k.od=function(a){this.pa=a};k.nd=function(a){this.g=this.C=a;this.ra={};a=0;for(var b;b=this.C[a];a++)this.ra[b.toLowerCase()]=a;this.i=-1};
k.Ob=function(a,b,d,c){if(a=="visible"){this.s.className=="pkHiddenStatus"&&this.R(this.pa);this.Ya(this.Xa,this.Ba,this.Ca);this.s.className="pkVisibleStatus";var e=this.j;window.setTimeout(function(){e.focus()},0)}else if(a=="hidden"){if(y.m&&this.n)this.n.innerText="";else if(this.n)if(y.m)this.n.innerText="";else this.n.textContent="";this.Ya(j,this.Ba,this.Ca);this.s.className="pkHiddenStatus";this.j.value="";this.i=-1}if(b){a=y.vb();d||(d=a.height-this.s.offsetHeight);c||(c=0);this.s.style.top=
d;this.s.style.left=c}};k.cd=function(){var a=this;window.setTimeout(function(){a.Xa&&a.z.style.display=="block"&&a.Ya(a.Xa,a.Ba,a.Ca)},0)};
k.Rc=function(a,b,d){if(this.j.value.length===0)this.g=this.C;if(a.keyCode!=y.D.ja&&a.keyCode!=y.D.ia&&a.keyCode!=y.D.T&&a.keyCode!=y.D.xa)if(this.j.value.length){this.g=this.wb(this.C,this.j.value,50);this.i=-1;if(this.g.length>0){this.R(this.g[0]);this.i=0}else this.R(this.bd)}else this.R(this.pa);if(a.keyCode==y.D.T)if(!this.j.readOnly){if(this.g&&this.g.length>0&&this.i>=0&&this.j.value!=this.g[this.i]&&(this.g[this.i].indexOf("<")<0||this.g[this.i].indexOf("<")>=0&&this.g[this.i].split(" ").length>
this.j.value.split(" ").length))this.Lb();var c=this.j.value;a=(y.m?this.n.innerText:this.n.textContent).toLowerCase();var e=a.indexOf("<"),f;if(e>=0){f=c.substr(0,e-1).toLowerCase();c=f+" "+c.substr(e)}else f=c=c.toLowerCase();e=j;if(b)e=this.tc.call(this,c,a,b);if(d&&!e){b=this.sb(c,a);d(f,this.ra[a],this.Tc[a],b)}this.j.value=""}};
k.Qc=function(a){if(a.keyCode==y.D.ja&&this.g&&this.g.length>0)this.ed();else if(a.keyCode==y.D.ia&&this.g&&this.g.length>0)this.ad();else a.keyCode==y.D.xa&&this.g&&this.g.length>0&&this.Lb()};k.Ya=function(a,b,d){if(a){this.z.className="pkBackgroundShow";this.z.style.display="block";a=y.vb();this.z.style.width=a.width+"px";this.z.style.height=a.height+"px";if(b)this.z.style.backgroundColor=b;d&&this.z.style.setProperty("-moz-opacity",d/100,"")}else this.z.style.display="none"};
k.wb=function(a,b,d){for(var c=a,e=a,f=b.split(" "),g=0,l;l=f[g];g++){e=c;c=[];if(l!==""){l=y.jd(l);var p=new RegExp("(^|\\W+)"+l,"i");l=0;for(var m;m=e[l];l++)String(m).match(p)&&c.push(m)}}e=a;for(l=0;m=e[l];l++){a=m.split(" ");f=[];for(g=0;p=a[g];g++){if(p.charAt(0)=="<")break;f.push(p)}g=f.join(" ");b.indexOf(g)===0&&c.push(m)}c.length>d&&c.slice(0,d-1);return c};
k.sb=function(a,b){a=a.replace(/\s+/g," ");b=b.replace(/\s+/g," ");var d=b.indexOf("<");if(d<0)return[];b=b.substr(d);a=a.substr(d);d=a.split(",");var c=b.split(",");if(d.length!=c.length)return[];for(var e=[],f=0,g,l;(g=d[f])&&(l=c[f]);f++){g=y.Bb(y.Kb(g));l=y.Bb(y.Kb(l));l.match(y.Qb)&&e.push(g)}return e};k.tc=function(a,b,d){this.sb(a,b);if((a=d[b])&&a[this.X]){a=a[this.X]+"(args);";window.setTimeout(a,0);return h}else return j};
k.ed=function(){if(this.i<0)this.i=0;this.i=(this.i||this.g.length)-1;this.i>=0&&this.R(this.g[this.i])};k.ad=function(){this.i=(this.i+1)%this.g.length;this.i<this.g.length&&this.R(this.g[this.i])};k.Lb=function(){this.j.value=this.g[this.i>=0?this.i:0];this.g=this.wb(this.C,this.j.value,50);this.W&&y.N&&this.W.o(this.j.value);this.i=0};
k.R=function(a){if(!this.n){this.n=document.createElement("div");this.n.id="listElem_"+Math.floor(Math.random()*1001);this.nb.appendChild(this.n)}if(y.m)this.n.innerText=a;else this.n.textContent=a;this.W&&y.N&&this.W.Za(this.n,j)};k.Va=function(){y.Va()};y.cb=function(a){this.ya=a};
y.cb.prototype.Sc=function(a,b,d){if(b.ya)if(a.keyCode){var c=""+a.keyCode,e=String.fromCharCode(a.keyCode).toLowerCase();if(a.ctrlKey){c="Ctrl+"+c;e="Ctrl+"+e}if(a.altKey){c="Alt+"+c;e="Alt+"+e}if(a.shiftKey){c="Shift+"+c;e="Shift+"+e}a=i;(a=b.ya[e])||(a=b.ya[c]);if(a)(b=a[d.X]?a[d.X]:a["*"])&&b()}};y.sc=function(a,b){this.width=a?a:undefined;this.height=b?b:undefined};y.Bb=function(a){return a.replace(y.ec,"")};y.Kb=function(a){return a.replace(y.oc,"")};
y.jd=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
y.vb=function(){var a=0,b=0;if(typeof window.innerWidth=="number"){a=window.innerWidth;b=window.innerHeight}else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){a=document.documentElement.clientWidth;b=document.documentElement.clientHeight}else if(document.body&&(document.body.clientWidth||document.body.clientHeight)){a=document.body.clientWidth;b=document.body.clientHeight}return new y.sc(a,b)};y.m=j;y.N=j;
y.md=function(){var a=navigator.userAgent.toLowerCase();y.N=a.indexOf("gecko")!=-1;y.m=a.indexOf("msie")!=-1&&a.indexOf("opera")==-1};y.md();y.wa={ja:y.m?"onkeyup":"keyup",ia:y.m?"onkeydown":"keydown",Fd:y.m?"onkeypress":"keypress",Bd:y.m?"onclick":"click",nc:y.m?"onresize":"resize",Ed:y.m?"onfocus":"focus",Ad:y.m?"onblur":"blur"};y.ob=".pkHiddenStatus {display: none; position: absolute;}.pkVisibleStatus {display: block; position: absolute; left: 2px; top: 2px; line-height: 1.2em; z-index: 10001; background-color: #000000; padding: 2px; color: #fff; font-family: Arial, Sans-serif; font-size: 20px; filter: alpha(opacity=80); -moz-opacity: .80;}.pkOpaqueCompletionText {border-style: none; background-color:transparent; font-family: Arial, Helvetica, sans-serif; font-size: 35px; font-weight: bold; color: #fff; width: 1000px; height: 50px;}.pkBackgroundShow {position: absolute; width: 0px;height: 0px; background-color: #000000; filter: alpha(opacity=70);  -moz-opacity: .70; left: 0px; top: 0px; z-index: 10000;}";
y.Va=function(){var a,b;if(a=document.getElementsByTagName("head")[0]){b=document.createElement("style");b.type="text/css";if(y.m)b.Qd=y.ob;else if(y.N)b.innerHTML=y.ob;a.appendChild(b)}};y.Hd=function(a){var b=document.getElementsByTagName("head")[0],d=document.createElement("link");d.type="text/css";d.rel="stylesheet";d.href=a;b.appendChild(d)};y.D={ja:38,ia:40,T:13,xa:9};var axsFinance={};axsFinance.cc="The following shortcut keys are available. ";axsFinance.a={ic:"or",ka:" up by ",rc:"+",ha:" down by ",Yb:"-",jc:" percent",kc:"%",$b:"Google Finance Currency",Sb:"Currency converter opened",bb:"Currency converter closed",Pb:"Amount",Tb:"Conversion result.",Ub:"{0}, {1}, {2} or {3}.",mc:"{0}, {1}, or {2}.",hb:"PM",ab:"AM"};axsFinance.Gb={};axsFinance.Ra={};axsFinance.Ra[axsFinance.a.Yb]=axsFinance.a.ha;axsFinance.Ra[axsFinance.a.rc]=axsFinance.a.ka;axsFinance.Mb={};
axsFinance.Mb[axsFinance.a.kc]=axsFinance.a.jc;axsFinance.Rb='<cnr next="RIGHT l" prev="LEFT h"><target title="Markets" hotkey="m">(//li[@class="nav-item"])[1]//a</target><target title="News" hotkey="e">(//li[@class="nav-item"])[2]//a</target><target title="Portfolios" hotkey="o">(//li[@class="nav-item"])[3]//a</target><target title="Stock screener" hotkey="s">(//li[@class="nav-item"])[4]//a</target><target title="Google domestic trends" hotkey="g">(//li[@class="nav-item"])[5]//a</target><target title="Announce currency ratio" hotkey="t" action="CALL:axsFinance.announceCurrencyRatio">//html</target><target title="View reversed ratio" hotkey="v">id("currency_reverse")</target><target title="Open or close currency converter" hotkey="c" action="CALL:axsFinance.openCloseCurrencyConverter">//html</target><target title="Go to link" hotkey="ENTER">.//descendant-or-self::a</target><target title="Create portfolio from quotes" hotkey="r" onEmpty="No recent quotes.">id("rq-create")</target><list title="Recent quotes" next="DOWN j" prev="UP k" fwd="n" back="p" type="dynamic" onEmpty="No recent quotes"><item action="CALL:axsFinance.readRecentQuote">id("rq")//tr</item></list><list title="Recent activity" next="DOWN j" prev="UP k" fwd="n" back="p" type="dynamic"><item>//li[@class="ra-entry"]//a</item></list><list title="News" next="DOWN j" prev="UP k" fwd="n" back="p"><item action="CALL:axsFinance.readNews">//div[@class="news-item"]</item><target title="View all news" hotkey="a">//a[contains(text(), "View all news for")]</target><target title="Subscribe" hotkey="u">//a[./img[@id="subscribe"]]</target></list><list title="Value in other currencies" next="DOWN j" prev="UP k" fwd="n" back="p" type="dynamic"><item action="CALL:axsFinance.readInOtherCurrency">//table[@class="currencies"]//tr</item></list></cnr>';
axsFinance.d=i;axsFinance.w=i;axsFinance.L=i;axsFinance.lb=i;axsFinance.Ib=i;axsFinance.$=2.5;axsFinance.Da=i;axsFinance.Ea=j;
axsFinance.Uc=function(){axsFinance.d=new n(h);axsFinance.w=new o(axsFinance.d);axsFinance.w.Zc(axsFinance.Rb,i);axsFinance.L=new w(axsFinance.d);axsFinance.L.Wa(axsFinance.$);axsFinance.w.qd(axsFinance.L);axsFinance.lb=new x(h);axsFinance.w.sd(axsFinance.lb);axsFinance.Ib=new y("list",axsFinance.d);axsFinance.w.rd(axsFinance.Ib,".");document.addEventListener("keypress",axsFinance.I,h);var a=document.getElementById("searchbox"),b=axsFinance.zb;a.addEventListener("keypress",b,h);document.addEventListener("DOMNodeInserted",
axsFinance.hd,j);axsFinance.xc();axsFinance.instrumentInnerIframe()};axsFinance.xc=function(){var a=axsFinance.a.$b+" "+axsFinance.tb(),b=document.getElementById("currency_value");axsFinance.ea(b,a)};axsFinance.hd=function(a){a.target.className==="d-quotes"&&axsFinance.w.gd("Recent quotes")};
axsFinance.instrumentInnerIframe=function(){var a='//iframe[contains(@src,"/finance/converter")]',b=axsFinance.d.t(a,document.body)[0];a="currency_converter_result";a=b.contentDocument.getElementById(a);if(b.contentDocument.Vc===undefined&&a){a=axsFinance.I;b.contentDocument.addEventListener("keypress",a,h);a=axsFinance.w.I;b.contentDocument.addEventListener("keypress",a,h);a=function(){b.contentDocument.Vc=h;axsFinance.instrumentInnerIframe();axsFinance.openCloseCurrencyConverter(i)};b.contentDocument.addEventListener("submit",
a,h);a=function(d){axsFinance.d.q=d.target;if(d.target.tagName=="INPUT"||d.target.tagName=="SELECT"||d.target.tagName=="TEXTAREA")axsFinance.d.Q=h;return h};b.contentDocument.addEventListener("focus",a,h);a=function(d){axsFinance.d.q=i;if(d.target.tagName=="INPUT"||d.target.tagName=="SELECT"||d.target.tagName=="TEXTAREA")axsFinance.d.Q=j;return h};b.contentDocument.addEventListener("blur",a,h);axsFinance.pd(b);axsFinance.fd()}else window.setTimeout(axsFinance.instrumentInnerIframe,100)};
axsFinance.fd=function(){var a='//iframe[contains(@src,"/finance/converter")]';a=axsFinance.d.t(a,document.body)[0];var b="currency_converter_result";a=a.contentDocument.getElementById(b);b=axsFinance.ca(a.textContent);if(b!==""){var d=axsFinance.a.bb;d=d+" "+axsFinance.a.Tb+" "+b;axsFinance.L.view(a);a.scrollIntoView(h);axsFinance.d.aa(a);window.setTimeout(function(){axsFinance.d.o(d)},0)}};
axsFinance.zb=function(a){axsFinance.d.o("");a.target.blur();a.stopPropagation();a.preventDefault();(a=axsFinance.w.Ia(a.keyCode,a.charCode))&&a();a=axsFinance.zb;var b=document.getElementById("searchbox");b.removeEventListener("keypress",a,h)};axsFinance.announceCurrencyRatio=function(){var a=axsFinance.tb(),b=document.getElementById("currency_value");axsFinance.ea(b,a)};
axsFinance.tb=function(){var a=document.getElementById("currency_value");a=axsFinance.ca(a.textContent);a=a.replace(axsFinance.a.ab," "+axsFinance.a.ab);a=a.replace(axsFinance.a.hb," "+axsFinance.a.hb);a=a.replace(" ("," "+axsFinance.a.ic+" ");return axsFinance.Qa(a)};axsFinance.readRecentQuote=function(a){a=a.k;var b="./td[not(.//b)]";b=axsFinance.d.t(b,a);for(var d=[],c=0,e=b.length;c<e;c++){d[c]=axsFinance.Nc(b[c]);d[c]=axsFinance.ca(d[c])}b=axsFinance.Hb(axsFinance.a.mc,d);axsFinance.ea(a,b)};
axsFinance.readNews=function(a){a=a.k;var b='.//div[@class="cluster"]';b=axsFinance.d.t(b,a)[0];axsFinance.ea(a,b.textContent)};axsFinance.Nc=function(a){var b="",d='.//descendant-or-self::*[not(contains(@style,"display: none;"))]/text()';a=axsFinance.d.t(d,a);d=0;for(var c=a.length;d<c;d++)b=b+a[d].textContent+" ";return b};
axsFinance.readInOtherCurrency=function(a){a=a.k;var b="./td[not(.//b)]";b=axsFinance.d.t(b,a);for(var d=[],c=0,e=0,f=b.length;e<f;e++){var g=axsFinance.ca(b[e].textContent);if(g!=""){if(g.indexOf("(")>0){g=g.split("(");d[c++]=axsFinance.Qa(g[0]);g=axsFinance.Qa(g[1])}d[c++]=g}}b=axsFinance.Hb(axsFinance.a.Ub,d);axsFinance.ea(a,b)};
axsFinance.openCloseCurrencyConverter=function(){if(axsFinance.Ea){axsFinance.Ea=j;var a=document.getElementsByTagName("INPUT")[0];a.focus();axsFinance.d.o(axsFinance.a.bb);a.blur()}else{axsFinance.Ea=h;var b='//iframe[contains(@src,"/finance/converter")]';b=axsFinance.d.t(b,document.body)[0];a=b.contentDocument.getElementsByTagName("INPUT")[0];var d=a.title;a.title=axsFinance.a.Sb+". "+a.title;b=function(){a.focus();a.select();a.title=d};window.setTimeout(b,1E3)}};
axsFinance.pd=function(a){var b=a.contentDocument.getElementsByTagName("INPUT"),d=b[0];d.title=axsFinance.a.Pb;b=b[1];var c=a.contentDocument.getElementsByTagName("SELECT");a=c[0];var e=document.createTextNode("From currency: "),f=axsFinance.d.na(a),g=document.createElement("LABEL");g.setAttribute("for",String(f));g.appendChild(e);a.parentNode.insertBefore(g,a);c=c[1];e=document.createTextNode("To currency: ");f=axsFinance.d.na(c);g=document.createElement("LABEL");g.setAttribute("for",String(f));
g.appendChild(e);c.parentNode.insertBefore(g,c);d=new Array(d,a,c,b);axsFinance.Da=d};axsFinance.Hb=function(a,b){for(var d=new String(a),c=0;c<b.length;c++)d=d.replace("{"+c+"}",b[c]);return d};axsFinance.xd=function(a){for(var b=a.target,d=axsFinance.Da,c=d.length,e=-1,f=0,g;g=d[f];f++)if(b===g){e=f;break}if(a.shiftKey){e--;if(e<0)e=c-1}else{e++;if(e==c)e=0}b=d[e];b.focus();b.tagName=="INPUT"&&b.select();a.stopPropagation();a.preventDefault()};
axsFinance.ea=function(a,b){axsFinance.L.view(a);axsFinance.d.o(b);a.scrollIntoView(h);axsFinance.d.aa(a)};
axsFinance.Qa=function(a){var b="";if(a==="")return a;a=axsFinance.ca(a);var d=axsFinance.Gb[a];if(d!=undefined)return d;a=a.split(" ");for(d=0;a[d];d++){var c=a[d],e=axsFinance.Gb[c];if(e!=undefined)c=e;else{if(c.length>0&&c.charAt(0)==="(")c=c.substring(1);if(c.length>1&&c.charAt(c.length-1)===")")c=c.substring(0,c.length-1);e=axsFinance.Ra[c.charAt(0)];if(e!=undefined)c=e+" "+c.substring(1);e=c.charAt(c.length-1);e=axsFinance.Mb[e];if(e!=undefined)c=c.substring(0,c.length-1)+" "+e}b=b+" "+c}return b};
axsFinance.ca=function(a){a=new String(a);a=a.replace(/^\s\s*/,"").replace(/\s\s*$/,"");a=a.replace(/\s+/g," ");return a.replace(/\n+/g,"").replace(/\r+/g,"")};axsFinance.I=function(a){if(a.ctrlKey)return h;if(a.keyCode==27){axsFinance.d.q&&axsFinance.d.q.blur();return j}a.keyCode==9&&axsFinance.Da!==i&&axsFinance.xd(a);if(axsFinance.d.Q)return h;if(a=axsFinance.Cc[a.charCode])return a();return h};
axsFinance.Cc={47:function(){document.getElementById("searchbox").focus();document.getElementById("searchbox").select();return j},63:function(){var a=axsFinance.cc+axsFinance.w.Wc()+axsFinance.w.Oc();axsFinance.d.o(a);return j},45:function(){axsFinance.$-=0.1;axsFinance.L.Wa(axsFinance.$);return j},61:function(){axsFinance.$+=0.1;axsFinance.L.Wa(axsFinance.$);return j}};window.addEventListener("load",axsFinance.Uc,h); })();
