(function() { var h=true,i=null,j=false,l,n=function(a){this.gc=0;this.ea=i;this.Ob=j;this.D=i;this.qa=j;var b=this;this.Ca=document.body;this.Dc();if(a){this.Ob=h;document.addEventListener("keypress",function(d){b.Nd(d,b)},h);document.body.Od=h}this.O(document.body,"role","application")};l=n.prototype;
l.Dc=function(){var a=this.z(),b=this,d=function(c){b.D=c.target;if(c.target.tagName=="INPUT"||c.target.tagName=="SELECT"||c.target.tagName=="TEXTAREA")b.qa=h;return h};a.addEventListener("focus",d,h);d=function(c){b.Va(b.D,"aria-activedescendant");b.D=i;if(c.target.tagName=="INPUT"||c.target.tagName=="SELECT"||c.target.tagName=="TEXTAREA")b.qa=j;return h};a.addEventListener("blur",d,h)};l.z=function(){for(var a=this.Ca;a.nodeType!=9;)a=a.parentNode;return a};
l.$a=function(a,b){a.id||this.jb(a);if(b){this.O(a,"live","rude");this.O(a,"atomic","true");var d=this.z();d=d.createElement("div");d.textContent=" ";d.name="AxsJAX_dummyNode";a.lastChild&&a.lastChild.name&&a.lastChild.name==d.name&&a.removeChild(a.lastChild);a.appendChild(d)}else{var c=this.$c(a,"role");this.O(a,"role","row");d=this.D;if(!d||d.nodeType==9){this.Ca.tabIndex=-1;d=this.Ca}this.O(d,"activedescendant",i);d.focus&&d.focus();this.O(d,"activedescendant",a.id);var e=this;window.setTimeout(function(){c?
e.O(a,"role",c):e.Va(a,"role")},0)}};
l.r=function(a,b){var d="AxsJAX_pixelAudioNode",c="AxsJAX_pixelAudioNode",e="data:image/gif;base64,R0lGODlhAQABAIAAANvf7wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",f=this.z(),g=i;if(b){if(b.previousSibling&&b.previousSibling.name==c)g=b.previousSibling;else{g=f.createElement("img");g.name=c;g.setAttribute("tabindex",0);g.style.outline="none";g.src=e;b.parentNode.insertBefore(g,b);this.Uc(g)}g.setAttribute("alt",a);g.setAttribute("title",a);window.setTimeout(function(){g.blur();g.focus()},0)}else{if((g=
f.getElementById(d))&&g.alt==a)a+=" ";if(!g){g=f.createElement("img");g.id=d;g.src=e;f.body.appendChild(g)}g.setAttribute("alt",a);g.setAttribute("title",a);this.$a(g)}};
l.nb=function(a,b){var d=this.z(),c=d.createEvent("MouseEvents");c.initMouseEvent("mousedown",h,h,d.defaultView,1,0,0,0,0,j,j,b,j,0,i);try{a.dispatchEvent(c)}catch(e){}c=d.createEvent("MouseEvents");c.initMouseEvent("mouseup",h,h,d.defaultView,1,0,0,0,0,j,j,b,j,0,i);try{a.dispatchEvent(c)}catch(f){}c=d.createEvent("MouseEvents");c.initMouseEvent("click",h,h,d.defaultView,1,0,0,0,0,j,j,b,j,0,i);try{a.dispatchEvent(c)}catch(g){}d=a.getAttribute("href");if(a.tagName=="A"&&d&&d!="#")if(b)window.open(a.href);
else document.location=a.href};l.jb=function(a,b){if(!a)return"";if(a.id)return a.id;var d=b||"AxsJAX_ID_";a.id=d+this.gc++;return a.id};l.sa=function(a){if(!a)return j;if(a.tagName=="A"||a.tagName=="INPUT"){this.ea=a;return h}a=a.getElementsByTagName("*");for(var b=0,d;d=a[b];b++)if(d.tagName=="A"||d.tagName=="INPUT"||d.hasAttribute("tabindex")&&d.tabIndex!=-1){this.ea=d;return h}return j};l.Nd=function(a,b){if(!b.Ob)return h;if(a.keyCode==9&&b.ea){b.ea.focus();b.ea=i}return h};
l.cd=function(a){this.$a(a);a.scrollIntoView(h);this.sa(a)};l.O=function(a,b,d){if(a){b=b.toLowerCase();switch(b){case "live":b="aria-live";break;case "activedescendant":b="aria-activedescendant";break;case "atomic":b="aria-atomic";break;default:break}a.setAttribute(b,d)}};l.$c=function(a,b){return a.getAttribute(b)};l.Va=function(a,b){a&&a.removeAttribute&&a.removeAttribute(b)};
l.Uc=function(a){a=this.jb(a);var b=this.z(),d=b.baseURI,c=d.indexOf("#");if(c!=-1)d=d.substring(0,c);b.location=d+"#"+a};l.w=function(a,b){try{var d=b.ownerDocument.evaluate(a,b,i,XPathResult.ORDERED_NODE_ITERATOR_TYPE,i)}catch(c){return[]}for(var e=[],f=d.iterateNext();f;f=d.iterateNext())e.push(f);return e};n.de=function(a){window.addEventListener("load",function(){a()},h)};var o=function(a){this.va=this.ta="";this.c=[];this.b=0;this.e=[];this.q=i;this.fa=[];this.J={};this.K={};this.M=[];this.I=[];this.f=a;this.H=this.A=this.F=i;this.kc="list";this.db="item";this.ib="wrap";this.Q=i};o.a={nc:"next list",rc:"previous list",ec:"go forward",dc:"go backwards",Wb:"cycle next",Xb:"cycle previous",vc:"Select available action",oc:"No available actions",gb:"Page up",fb:"Page down",T:"Enter",Sd:"Escape",Rd:"Delete",ja:"Up",ga:"Down",eb:"Left",hb:"Right"};l=o.prototype;
l.Gd=function(a,b){if(b){this.A=a;this.A.j===i&&this.Pc();var d=this,c=new Array(b);this.u(c,this.J,this.K,function(){d.Jd()})}};l.wa=function(a){var b=h;if(a.type=="dynamic"&&a.l.length===0){this.F!==i&&this.F.view(i);a.l=this.ra(a.da);a.p=this.Hb(a.da);if(this.c[this.b]===a)this.e[this.b]=-1;else for(var d=0,c;c=this.c[d];d++)if(c===a){this.e[d]=-1;break}}if(a.l.length===0&&a.Ga===i)b=j;return b};
l.rb=function(){var a=this.P();a=a.Ga;var b=i;if(a!==i){this.ka(a);b=this.Ia(a.action)}if(b===i){this.Gc();this.H!==i&&this.H.play(this.kc)}};l.qd=function(){if(this.c.length<1)return i;for(var a=0;this.c[a];a++){this.b++;if(this.b>=this.c.length)this.b=0;if(this.wa(this.c[this.b]))break}return this.P()};l.vd=function(){if(this.c.length<1)return i;for(var a=0;this.c[a];a++){this.b--;if(this.b<0)this.b=this.c.length-1;if(this.wa(this.c[this.b]))break}return this.P()};l.P=function(){return this.c[this.b]};
l.Gc=function(){this.f.r(this.P().title)};l.Oa=function(){if(this.c.length<1)return i;var a=this.c[this.b],b=a.l;if(b.length<1)return i;if(this.q){var d=this.Ka(a);d=this.q.k.S[d];if(typeof d!="undefined")this.e[this.b]=d}this.e[this.b]++;d=j;if(this.e[this.b]>=b.length){this.e[this.b]=0;d=h}var c=this.e[this.b];if(b[c].k.parentNode===i){this.F!==i&&this.F.view(i);a.l=this.ra(a.da);this.e[this.b]=0;c=this.e[this.b]}this.q=b[c];if(this.H!==i)d?this.H.play(this.ib):this.H.play(this.db);return this.q};
l.Wc=function(){var a=this.c[this.b],b=this.e[this.b];if(a.ab!==i&&b+1>=a.l.length){this.ka(a.ab);this.e[this.b]=0;return i}return a=this.Oa()};
l.Kb=function(){if(this.c.length<1)return i;var a=this.c[this.b],b=a.l;if(b.length<1)return i;if(this.q){var d=this.Ka(a);d=this.q.k.S[d];if(typeof d!="undefined")this.e[this.b]=d}this.e[this.b]--;d=j;if(this.e[this.b]<0){this.e[this.b]=b.length-1;d=h}var c=this.e[this.b];if(b[c].k.parentNode===i){this.F!==i&&this.F.view(i);a.l=this.ra(a.da);this.e[this.b]=a.l.length;c=this.e[this.b]}this.q=b[c];if(this.H!==i)d?this.H.play(this.ib):this.H.play(this.db);return this.q};
l.Kc=function(){var a=this.c[this.b],b=this.e[this.b];if(a.Ma!==i&&b<=0){this.ka(a.Ma);this.e[this.b]=a.l.length-1;return i}return a=this.Kb()};l.qb=function(){if(this.c.length<1)return i;var a=this.c[this.b];if(this.q){var b=this.Ka(a);b=this.q.k.S[b];if(typeof b!="undefined")this.e[this.b]=b}a=a.l;b=this.e[this.b];return this.q=a[b]};l.Ia=function(a){var b=i;if(a!==i&&a.indexOf&&a.indexOf("CALL:")===0&&a.indexOf("(")===-1)try{b=eval(a.substring(5))}catch(d){}return b};
l.U=function(a){if(a!==i){var b=this,d=function(){var f=b.Ia(a.action);if(f)f(a);else{b.F!==i&&b.F.view(a.k);b.f.cd(a.k)}};if(this.f.D&&this.f.D.blur){var c=this.f.D;this.f.D=i;c.removeAttribute&&this.f.Va(c,"aria-activedescendant");var e=function(f){f.target.removeEventListener("blur",e,h);d()};c.addEventListener("blur",e,h);c.blur()}else d()}else{c=this.c[this.b];c.type=="dynamic"&&this.f.r(c.onEmpty)}};
l.u=function(a,b,d,c){for(var e=0,f;f=a[e];e++)if(f=="LEFT")d[37]=c;else if(f=="UP")d[38]=c;else if(f=="RIGHT")d[39]=c;else if(f=="DOWN")d[40]=c;else if(f=="PGUP")d[33]=c;else if(f=="PGDOWN")d[34]=c;else if(f=="ENTER")d[13]=c;else if(f=="ESC")d[27]=c;else if(f=="DEL")d[46]=c;else b[f.charCodeAt(0)]=c};
l.ma=function(a,b,d){var c=[];if(a!==""){c=a.split(" ");var e=this;if(d=="prev")this.u(c,this.M[b],this.I[b],function(){e.U(e.Kb())});else if(d=="next")this.u(c,this.M[b],this.I[b],function(){e.U(e.Oa())});else d=="back"?this.u(c,this.M[b],this.I[b],function(){var f=e.Kc();f!==i&&e.U(f)}):this.u(c,this.M[b],this.I[b],function(){var f=e.Wc();f!=i&&e.U(f)})}};l.Jc=function(a,b,d){var c=[];if(a!==""){c=a.split(" ");var e=this;this.u(c,this.J,this.K,function(){if(e.wa(e.c[b])){e.b=b;e.U(e.Oa())}else e.f.r(d)})}};
l.Ic=function(a,b){var d=[];if(a!==""){d=a.split(" ");var c=this;this.u(d,this.J,this.K,function(){c.f.r(b)})}};l.kb=function(a,b,d){var c=[];if(a.hotkey!==""){c=a.hotkey.split(" ");var e=this;this.u(c,b,d,function(){e.ka(a)})}};l.ka=function(a){a.action=="click"?this.Nc(a):this.Lc(a)};l.Lc=function(a){var b=this.vb(a);if(b.length<1)this.f.r(a.onEmpty);else{var d=this.Ia(a.action);if(d){var c={};c.action=a.action;c.k=b[0];d(c);this.f.sa(b[0])}else throw new Error("Invalid action: "+a.action);}};
l.Nc=function(a){var b=this.vb(a);if(b.length<1)this.f.r(a.onEmpty);else{this.f.nb(b[0],j);b[0].scrollIntoView(h);this.f.sa(b[0])}};l.vb=function(a){a=a.t;var b=this.f.z().documentElement;if(a.indexOf(".")===0)b=this.qb().k;return this.f.w(a,b)};l.wb=function(a,b){var d=i,c=this.b;if(c<this.I.length)d=this.I[c][a]||this.M[c][b]||i;if(d===i)d=this.K[a]||this.J[b];return d};
l.pd=function(a,b){var d={};d.Fb=[];var c=new DOMParser,e=c.parseFromString(a,"text/xml"),f=e.getElementsByTagName("list"),g;for(c=0;g=f[c];c++){var k={};k.title=g.getAttribute("title");k.hotkey=g.getAttribute("hotkey");k.next=g.getAttribute("next");k.Ta=g.getAttribute("prev");k.Vc=g.getAttribute("fwd");k.back=g.getAttribute("back");k.onEmpty=g.getAttribute("onEmpty");k.type=g.getAttribute("type");var p,m,r,q;k.l=[];var s=g.getElementsByTagName("item");for(p=0;m=s[p];p++){var u={};u.t=m.textContent;
if(m.attributes instanceof NamedNodeMap){r=m.attributes;q=r.length;for(m=0;m<q;m++){var t=r.item(m);u[t.nodeName]=t.value}}k.l.push(u)}k.p=[];s=g.getElementsByTagName("target");for(p=0;m=s[p];p++){g={};g.t=m.textContent;if(m.attributes instanceof NamedNodeMap){r=m.attributes;q=r.length;for(m=0;m<q;m++){t=r.item(m);g[t.nodeName]=t.value}}k.p.push(g)}d.Fb.push(k)}d.p=[];var v=e.firstChild;for(c=0;e=v.childNodes[c];c++)if(e.tagName=="target"){g={};g.t=e.textContent;if(e.attributes instanceof NamedNodeMap){r=
e.attributes;q=r.length;for(m=0;m<q;m++){t=r.item(m);g[t.nodeName]=t.value}}d.p.push(g)}d.next=v.getAttribute("next");d.Ta=v.getAttribute("prev");if(b===i||typeof b=="undefined")this.Ib(d,b);else{c=new (function(C,z,A,B){b(v,z,A,B)});this.Ib(d,c)}};
l.bd=function(){for(var a=this.Ja(),b="",d=0,c;c=a[d];d++)b=b+c.aa+", "+c.title+". ";b=b+this.ta+", "+o.a.nc;b=b+this.va+", "+o.a.rc;b=b.replace("PGUP",o.a.gb);b=b.replace("PGDOWN",o.a.fb);b=b.replace("ENTER",o.a.T);b=b.replace("DEL",o.a.$b);b=b.replace("UP",o.a.ja);b=b.replace("DOWN",o.a.ga);b=b.replace("LEFT",o.a.eb);return b=b.replace("RIGHT",o.a.hb)};
l.md=function(){for(var a=this.La(),b="",d=0,c;c=a[d];d++)b=b+c.aa+", "+c.title+". ";a=this.P();if(a.Pa!=="")b=b+a.Pa+", "+o.a.Wb+". ";if(a.Ua!=="")b=b+a.Ua+", "+o.a.Xb+". ";if(a.Ha!=="")b=b+a.Ha+", "+o.a.ec+". ";if(a.Da!=="")b=b+a.Da+", "+o.a.dc+". ";b=b.replace("PGUP",o.a.gb);b=b.replace("PGDOWN",o.a.fb);b=b.replace("ENTER",o.a.T);b=b.replace("DEL",o.a.$b);b=b.replace("UP",o.a.ja);b=b.replace("DOWN",o.a.ga);b=b.replace("LEFT",o.a.eb);return b=b.replace("RIGHT",o.a.hb)};l.Fd=function(a){this.F=a};
l.Hd=function(a){this.H=a};l.xd=function(a){if(a===i)return j;var b=j;a=this.Tc(a);if(a>-1){b=this.c[a];b.l=[];b.p=[];b=this.wa(b)}return b};l.Jd=function(){if(this.A!==i){var a=this.Ja(),b=this.La();if(a.length+b.length===0)this.f.r(o.a.oc);else{var d=[],c=0,e="";for(c=0;e=b[c];c++)d.push(e.title);for(c=0;e=a[c];c++)d.push(e.title);this.A.Dd(d);this.A.Pb("visible",h,40,20)}}};
l.Ja=function(){for(var a=[],b,d=0,c;c=this.c[d];d++)if(c.$!==""){b={};b.title=c.title;b.aa=c.$;a.push(b)}for(d=0;c=this.fa[d];d++)if(this.Cb(c)){b={};b.title=c.title;b.aa=c.hotkey;a.push(b)}return a};l.La=function(){for(var a=[],b=this.P(),d=0,c;c=b.p[d];d++)if(this.Cb(c)){var e={};e.title=c.title;e.aa=c.hotkey;a.push(e)}return a};
l.Pc=function(){var a=this.f.z().body,b=this,d=function(c,e){var f=b.La(),g=b.Ja();f=f.concat(g);f=f[e].aa;f=f.split(" ")[0];var k=g=-1;if(f=="LEFT")g=37;else if(f=="UP")g=38;else if(f=="RIGHT")g=39;else if(f=="DOWN")g=40;else if(f=="PGUP")g=33;else if(f=="PGDOWN")g=34;else if(f=="ENTER")g=13;else if(f=="DEL")g=46;else if(f=="ESC")g=27;else k=f.charCodeAt(0);b.A.j.blur();(f=b.wb(g,k))&&f()};this.A.Oc(a,50,d,i,this.Xd,j);this.A.Ed(o.a.vc);this.A.Bd(h);this.A.Wa()};
l.Cb=function(a){var b=j;if(a.hotkey!==""){a=a.t;var d=this.f.z().body;if(a.indexOf(".")===0){var c=this.qb();if(c)d=c.k}a=this.f.w(a,d);if(a.length>0)b=h}return b};
l.Ib=function(a,b){this.c=[];this.b=0;this.e=[];var d=[],c,e;for(c=0;e=a.Fb[c];c++){var f={};e.Na=c;f.$d=i;f.da=e;f.title=e.title||"";f.$=e.hotkey||"";f.Pa=e.next||"";f.Ua=e.Ta||"";f.Ha=e.Vc||"";f.Da=e.back||"";f.onEmpty=e.onEmpty||"";f.type=e.type||"";f.ab=i;f.Ma=i;f.Ga=i;f.l=this.ra(e);f.p=this.Hb(e);e=0;for(var g;g=f.p[e];e++)if(g.trigger=="listTail")f.ab=g;else if(g.trigger=="listHead")f.Ma=g;else if(g.trigger=="listEntry")f.Ga=g;if(f.l.length>0||f.type=="dynamic"){this.c.push(f);this.e.push(-1)}else f.$!==
""&&d.push(f)}this.fa=[];this.fe=0;if(a.p)for(c=0;f=a.p[c];c++){e={};e.t=f.t;e.t=e.t.replace(/^\s\s*/,"").replace(/\s\s*$/,"");e.title=f.title||"";e.trigger=f.trigger||"key";e.hotkey=f.hotkey||"";e.action=f.action||"click";e.onEmpty=f.onEmpty||"";this.fa.push(e)}this.Q!==i&&document.removeEventListener("keypress",this.Q,h);b===i||typeof b=="undefined"?this.Id(a,d):b(a,this.c,d,this.fa)};
l.ra=function(a){var b=[];if(!a.l)return b;for(var d=0,c;c=a.l[d];d++)try{var e=c.t.replace(/^\s\s*/,"").replace(/\s\s*$/,""),f=this.f.z().documentElement,g=this.f.w(e,f),k=c.index||"0",p=parseInt(k,10),m=g.length-p,r=c.ae||"*";if(r!="*")m=parseInt(r,10);for(var q=m+p,s=c.action||i;p<q;){c={};c.action=s;c.k=g[p];if(typeof c.k!="undefined"){if(typeof c.k.S=="undefined")c.k.S={};if(typeof a.Na=="undefined")throw new Error("list does not have an id");c.k.S[a.Na]=b.length;b.push(c)}p++}}catch(u){}return b};
l.Hb=function(a){var b=[];if(!a.p)return b;for(var d=0,c;c=a.p[d];d++){var e={};e.t=c.t.replace(/^\s\s*/,"").replace(/\s\s*$/,"");e.title=c.title||"";e.trigger=c.trigger||"key";e.hotkey=c.hotkey||"";e.action=c.action||"click";e.onEmpty=c.onEmpty||"";b.push(e)}return b};
l.Id=function(a,b){var d=this,c;this.J={};this.K={};this.M=[];this.I=[];var e;for(c=0;e=this.fa[c];c++)this.kb(e,this.J,this.K);c=[];this.ta=a.next||"";if(this.ta!=="")c=this.ta.split(" ");this.u(c,this.J,this.K,function(){d.qd();d.rb()});c=[];this.va=a.Ta||"";if(this.va!=="")c=this.va.split(" ");this.u(c,this.J,this.K,function(){d.vd();d.rb()});var f;for(c=0;f=this.c[c];c++){var g={},k={};this.M.push(g);this.I.push(k);this.ma(f.Pa,c,"next");this.ma(f.Ua,c,"prev");this.ma(f.Ha,c,"fwd");this.ma(f.Da,
c,"back");this.Jc(f.$,c,f.onEmpty);var p;for(p=0;e=f.p[p];p++)this.kb(e,g,k)}for(c=0;e=b[c];c++)this.Ic(e.$,e.onEmpty);this.Q=function(m){if(m.ctrlKey)return h;if(d.f.qa)return h;if(m=d.wb(m.keyCode,m.charCode))return m()};document.addEventListener("keypress",this.Q,h)};l.Ka=function(a){return a.da.Na};l.Tc=function(a){for(var b=0;b<this.c.length;b++){var d=this.c[b];if(d.title==a)break}return b<this.c.length?b:-1};var w=function(a){this.i=a;this.ca=1.5;this.padding=-1;this.Ad=0;this.la=a.z();this.d=this.la.createElement("span");this.d.style.backgroundColor="#CCE6FF";this.d.style.borderColor="#0000CC";this.d.style.borderWidth="medium";this.d.style.borderStyle="groove";this.d.style.position="absolute";this.d.style.display="none";this.la.body.appendChild(this.d);this.mb=function(){}};w.yc={Vd:0,bc:1};l=w.prototype;
l.view=function(a){for(;this.d.firstChild;)this.d.removeChild(this.d.firstChild);if(a===i)this.d.style.display="none";else{var b=0,d=0,c=a;if(c.offsetParent){b=c.offsetLeft;d=c.offsetTop;for(c=c.offsetParent;c!==i;){b+=c.offsetLeft;d+=c.offsetTop;c=c.offsetParent}}this.d.appendChild(a.cloneNode(h));this.d.style.top=d+"px";this.d.style.left=b+"px";this.d.style.zIndex=999;this.d.style.display="block";this.Gb()}};l.Xa=function(a){this.ca=a;this.Gb()};
l.Gb=function(){this.la.body.removeChild(this.d);this.nd();this.Rc();this.Ec();this.la.body.appendChild(this.d);this.mb&&this.mb(this.d);if(this.Ad==w.yc.bc){var a=this;window.setTimeout(function(){a.d.scrollIntoView(h)},0)}};l.Ec=function(){if(!(this.padding<0)){var a="//*[not(.//*)]";a=this.i.w(a,this.d);for(var b=0,d;d=a[b];b++)d.style.padding=this.padding+"px"}};
l.Rc=function(){for(var a=this.d.getElementsByTagName("img"),b=0,d;d=a[b];b++){if(!d.hasAttribute("Axs_OrigHeight")){d.setAttribute("Axs_OrigHeight",d.height);d.setAttribute("Axs_OrigWidth",d.width)}d.height=d.getAttribute("Axs_OrigHeight")*this.ca;d.width=d.getAttribute("Axs_OrigWidth")*this.ca}};
l.nd=function(){var a="fontSizeAdjust"in this.d.style;if(a){var b=this.ca*0.52;this.d.style.fontSizeAdjust=b}else{b=this.ca*100+"%";this.d.style.setProperty("font-size",b,"important")}b=this.d.getElementsByTagName("*");for(var d=0,c;c=b[d];d++){c.style.setProperty("line-height","normal","important");a||c.style.setProperty("font-size","100%","important")}};var x=function(a){var b="http://google-axsjax.googlecode.com/svn/trunk/";this.be=b+"common/earcons/axsEarcons.swf?sound=";this.oa=i;this.sb=a;this.Kd=b+"thirdparty/soundmanager2/";this.Ld=i;this.Ab=j;this.ge="minimal";this.Zd=j;this.ce=0};x.prototype.play=function(){};x.prototype.stop=function(){if(this.oa){this.oa.parentNode.removeChild(this.oa);this.oa=i}if(!this.sb)if(this.Ab)this.Ld.src=this.Kd+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Stop()"};
x.prototype.getTime=function(){if(this.sb)return-1;if(!this.Ab)return-1;var a="Time=",b=unescape(document.location.hash);if(b.indexOf(a)==-1)return-1;a=b.indexOf(a)+a.length;return b=parseInt(b.substring(a),10)};var y=function(a,b){this.X=a;this.ob=this.n=this.v=this.j=this.s=i;this.na="Enter Completion";this.sd="No completions found";this.W=i;this.B=[];this.od={};this.h=-1;this.Ya=this.zb=j;this.Ea="#000000";this.Fa=0;this.hd={};this.pa={};this.Yd={};if(b&&y.N)this.W=b;var d=this;this.V(window,y.za.tc,function(c){d.td.call(d,c)},i)};y.Sb=/^\<[A-Z|a-z|0-9|\-|\_]+\>$/;y.jc=/^(\s|\r|\n)+/;y.uc=/(\s|\r|\n)+$/;l=y.prototype;
l.V=function(a,b,d,c){if(y.N&&d)a.addEventListener(b,d,h);else y.m&&d&&a.attachEvent(b,function(g){d(g)});if(c){var e=new y.cb(c),f=this;this.V(a,b,function(g){e.gd(g,e,f)},i)}};
l.Oc=function(a,b,d,c,e,f){var g=this,k,p,m,r,q;this.s&&this.s.parentNode.removeChild(this.s);do{k="completionField_"+Math.floor(Math.random()*1001);p="txt_"+k;r="div_"+k;q="bgdiv_"+k;m=document.getElementById(k)}while(m);m=document.createElement("div");m.id=q;m.style.display="none";q=document.createElement("div");q.id=k;q.style.position="absolute";k=document.createElement("input");k.type="text";k.id=p;k.size=b;k.value="";k.setAttribute("aria-owns",r);if(y.N)k.onkeypress=function(s){s.stopPropagation();
if(s.keyCode==y.C.Aa)return j};if(k.readOnly=f)k.style.fontSize=0;b=document.createElement("div");b.id=r;b.setAttribute("tabindex",0);b.setAttribute("role","row");q.appendChild(b);q.appendChild(k);a.appendChild(m);a.appendChild(q);this.s=q;this.j=k;this.v=m;this.ob=b;this.s.className="pkHiddenStatus";this.j.className="pkOpaqueCompletionText";this.v.className="pkBackgroundHide";if(e){this.B=e;this.od[this.X]=[e,this.na];this.g=this.B;for(a=0;e=this.B[a];a++)this.pa[e.toLowerCase()]=a;this.h=-1}this.V(this.j,
y.za.ia,function(s){g.fd.call(g,s,c,d)},i);this.V(this.j,y.za.ha,function(s){g.ed.call(g,s)},i);this.V(this.j,"blur",function(){g.zb&&g.Pb("hidden")},i)};l.Bd=function(a){this.zb=a};l.Ed=function(a){this.na=a};l.Dd=function(a){this.g=this.B=a;this.pa={};a=0;for(var b;b=this.B[a];a++)this.pa[b.toLowerCase()]=a;this.h=-1};
l.Pb=function(a,b,d,c){if(a=="visible"){this.s.className=="pkHiddenStatus"&&this.R(this.na);this.Za(this.Ya,this.Ea,this.Fa);this.s.className="pkVisibleStatus";var e=this.j;window.setTimeout(function(){e.focus()},0)}else if(a=="hidden"){if(y.m&&this.n)this.n.innerText="";else if(this.n)if(y.m)this.n.innerText="";else this.n.textContent="";this.Za(j,this.Ea,this.Fa);this.s.className="pkHiddenStatus";this.j.value="";this.h=-1}if(b){a=y.xb();d||(d=a.height-this.s.offsetHeight);c||(c=0);this.s.style.top=
d;this.s.style.left=c}};l.td=function(){var a=this;window.setTimeout(function(){a.Ya&&a.v.style.display=="block"&&a.Za(a.Ya,a.Ea,a.Fa)},0)};
l.fd=function(a,b,d){if(this.j.value.length===0)this.g=this.B;if(a.keyCode!=y.C.ia&&a.keyCode!=y.C.ha&&a.keyCode!=y.C.T&&a.keyCode!=y.C.Aa)if(this.j.value.length){this.g=this.yb(this.B,this.j.value,50);this.h=-1;if(this.g.length>0){this.R(this.g[0]);this.h=0}else this.R(this.sd)}else this.R(this.na);if(a.keyCode==y.C.T)if(!this.j.readOnly){if(this.g&&this.g.length>0&&this.h>=0&&this.j.value!=this.g[this.h]&&(this.g[this.h].indexOf("<")<0||this.g[this.h].indexOf("<")>=0&&this.g[this.h].split(" ").length>
this.j.value.split(" ").length))this.Mb();var c=this.j.value;a=(y.m?this.n.innerText:this.n.textContent).toLowerCase();var e=a.indexOf("<"),f;if(e>=0){f=c.substr(0,e-1).toLowerCase();c=f+" "+c.substr(e)}else f=c=c.toLowerCase();e=j;if(b)e=this.Cc.call(this,c,a,b);if(d&&!e){b=this.ub(c,a);d(f,this.pa[a],this.hd[a],b)}this.j.value=""}};
l.ed=function(a){if(a.keyCode==y.C.ia&&this.g&&this.g.length>0)this.wd();else if(a.keyCode==y.C.ha&&this.g&&this.g.length>0)this.rd();else a.keyCode==y.C.Aa&&this.g&&this.g.length>0&&this.Mb()};l.Za=function(a,b,d){if(a){this.v.className="pkBackgroundShow";this.v.style.display="block";a=y.xb();this.v.style.width=a.width+"px";this.v.style.height=a.height+"px";if(b)this.v.style.backgroundColor=b;d&&this.v.style.setProperty("-moz-opacity",d/100,"")}else this.v.style.display="none"};
l.yb=function(a,b,d){for(var c=a,e=a,f=b.split(" "),g=0,k;k=f[g];g++){e=c;c=[];if(k!==""){k=y.zd(k);var p=new RegExp("(^|\\W+)"+k,"i");k=0;for(var m;m=e[k];k++)String(m).match(p)&&c.push(m)}}e=a;for(k=0;m=e[k];k++){a=m.split(" ");f=[];for(g=0;p=a[g];g++){if(p.charAt(0)=="<")break;f.push(p)}g=f.join(" ");b.indexOf(g)===0&&c.push(m)}c.length>d&&c.slice(0,d-1);return c};
l.ub=function(a,b){a=a.replace(/\s+/g," ");b=b.replace(/\s+/g," ");var d=b.indexOf("<");if(d<0)return[];b=b.substr(d);a=a.substr(d);d=a.split(",");var c=b.split(",");if(d.length!=c.length)return[];for(var e=[],f=0,g,k;(g=d[f])&&(k=c[f]);f++){g=y.Db(y.Lb(g));k=y.Db(y.Lb(k));k.match(y.Sb)&&e.push(g)}return e};l.Cc=function(a,b,d){this.ub(a,b);if((a=d[b])&&a[this.X]){a=a[this.X]+"(args);";window.setTimeout(a,0);return h}else return j};
l.wd=function(){if(this.h<0)this.h=0;this.h=(this.h||this.g.length)-1;this.h>=0&&this.R(this.g[this.h])};l.rd=function(){this.h=(this.h+1)%this.g.length;this.h<this.g.length&&this.R(this.g[this.h])};l.Mb=function(){this.j.value=this.g[this.h>=0?this.h:0];this.g=this.yb(this.B,this.j.value,50);this.W&&y.N&&this.W.r(this.j.value);this.h=0};
l.R=function(a){if(!this.n){this.n=document.createElement("div");this.n.id="listElem_"+Math.floor(Math.random()*1001);this.ob.appendChild(this.n)}if(y.m)this.n.innerText=a;else this.n.textContent=a;this.W&&y.N&&this.W.$a(this.n,j)};l.Wa=function(){y.Wa()};y.cb=function(a){this.Ba=a};
y.cb.prototype.gd=function(a,b,d){if(b.Ba)if(a.keyCode){var c=""+a.keyCode,e=String.fromCharCode(a.keyCode).toLowerCase();if(a.ctrlKey){c="Ctrl+"+c;e="Ctrl+"+e}if(a.altKey){c="Alt+"+c;e="Alt+"+e}if(a.shiftKey){c="Shift+"+c;e="Shift+"+e}a=i;(a=b.Ba[e])||(a=b.Ba[c]);if(a)(b=a[d.X]?a[d.X]:a["*"])&&b()}};y.Ac=function(a,b){this.width=a?a:undefined;this.height=b?b:undefined};y.Db=function(a){return a.replace(y.jc,"")};y.Lb=function(a){return a.replace(y.uc,"")};
y.zd=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
y.xb=function(){var a=0,b=0;if(typeof window.innerWidth=="number"){a=window.innerWidth;b=window.innerHeight}else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){a=document.documentElement.clientWidth;b=document.documentElement.clientHeight}else if(document.body&&(document.body.clientWidth||document.body.clientHeight)){a=document.body.clientWidth;b=document.body.clientHeight}return new y.Ac(a,b)};y.m=j;y.N=j;
y.Cd=function(){var a=navigator.userAgent.toLowerCase();y.N=a.indexOf("gecko")!=-1;y.m=a.indexOf("msie")!=-1&&a.indexOf("opera")==-1};y.Cd();y.za={ia:y.m?"onkeyup":"keyup",ha:y.m?"onkeydown":"keydown",Ud:y.m?"onkeypress":"keypress",Qd:y.m?"onclick":"click",tc:y.m?"onresize":"resize",Td:y.m?"onfocus":"focus",Pd:y.m?"onblur":"blur"};y.pb=".pkHiddenStatus {display: none; position: absolute;}.pkVisibleStatus {display: block; position: absolute; left: 2px; top: 2px; line-height: 1.2em; z-index: 10001; background-color: #000000; padding: 2px; color: #fff; font-family: Arial, Sans-serif; font-size: 20px; filter: alpha(opacity=80); -moz-opacity: .80;}.pkOpaqueCompletionText {border-style: none; background-color:transparent; font-family: Arial, Helvetica, sans-serif; font-size: 35px; font-weight: bold; color: #fff; width: 1000px; height: 50px;}.pkBackgroundShow {position: absolute; width: 0px;height: 0px; background-color: #000000; filter: alpha(opacity=70);  -moz-opacity: .70; left: 0px; top: 0px; z-index: 10000;}";
y.Wa=function(){var a,b;if(a=document.getElementsByTagName("head")[0]){b=document.createElement("style");b.type="text/css";if(y.m)b.ee=y.pb;else if(y.N)b.innerHTML=y.pb;a.appendChild(b)}};y.Wd=function(a){var b=document.getElementsByTagName("head")[0],d=document.createElement("link");d.type="text/css";d.rel="stylesheet";d.href=a;b.appendChild(d)};y.C={ia:38,ha:40,T:13,Aa:9};var axsFinance={};axsFinance.a={Bc:'id("{0}")//tbody/tr[position() &gt;= {1} and position() &lt;= {2}]',mc:"03",lc:"March",ic:"06",hc:"June",xc:"09",wc:"September",Zb:"12",Yb:"December",qc:"-",pc:"Not available",Rb:"&",Qb:"and",zc:"+",ja:"up by ",ac:"-",ga:"down by ",sc:"{0}, {1}, change {2}.",cc:"Google Finance",fc:"The following shortcut keys are available. "};axsFinance.Vb='<cnr next="RIGHT l" prev="LEFT h"><target title="Markets" hotkey="m">(//li[@class="nav-item"])[1]//a</target><target title="News" hotkey="e">(//li[@class="nav-item"])[2]//a</target><target title="Portfolios" hotkey="o">(//li[@class="nav-item"])[3]//a</target><target title="Stock screener" hotkey="s">(//li[@class="nav-item"])[4]//a</target><target title="Google domestic trends" hotkey="g">(//li[@class="nav-item"])[5]//a</target><target title="Create portfolio from quotes" hotkey="t" onEmpty="No recent quotes.">id("rq-create")</target><target title="Go to link" hotkey="ENTER">.//descendant-or-self::a</target><target title="Quarterly data" hotkey="q" onEmpty="Quarterly data already opened" action="CALL:axsFinance.storeCurrentPositionAndClickOnLink">id("interim")[@class="nac"]</target><target title="Annual data" hotkey="a" onEmpty="Annual data already opened" action="CALL:axsFinance.storeCurrentPositionAndClickOnLink">id("annual")[@class="nac"]</target><target title="Income statement" hotkey="i" onEmpty="Income statement already opened">id("fs-type-tabs")//div[@id=":0" and not(contains(@class, "selected"))]/a</target><target title="Balance sheet" hotkey="b" onEmpty="Balance sheet already opened">id("fs-type-tabs")//div[@id=":1" and not(contains(@class, "selected"))]/a</target><target title="Cash flow" hotkey="c" onEmpty="Cash flow already opened">id("fs-type-tabs")//div[@id=":2" and not(contains(@class, "selected"))]/a</target><list title="Recent quotes" next="DOWN j" prev="UP k" fwd="n" back="p" type="dynamic" onEmpty="No recent quotes"><item action="CALL:axsFinance.readRecentQuote">id("rq")//tr</item></list><list title="Recent activity" next="DOWN j" prev="UP k" fwd="n" back="p" type="dynamic" onEmpty="No recent activities"><item>//li[@class="ra-entry"]//a</item></list>';
axsFinance.Tb='<list title="{0}" fwd="DOWN j n" back="UP k p"><item action="CALL:axsFinance.readTableRow">{1}</item></list>';axsFinance.Ub="</cnr>";axsFinance.G={};axsFinance.G[axsFinance.a.mc]=axsFinance.a.lc;axsFinance.G[axsFinance.a.ic]=axsFinance.a.hc;axsFinance.G[axsFinance.a.xc]=axsFinance.a.wc;axsFinance.G[axsFinance.a.Zb]=axsFinance.a.Yb;axsFinance.G[axsFinance.a.qc]=axsFinance.a.pc;axsFinance.G[axsFinance.a.Rb]=axsFinance.a.Qb;axsFinance.Sa={};axsFinance.Sa[axsFinance.a.ac]=axsFinance.a.ga;
axsFinance.Sa[axsFinance.a.zc]=axsFinance.a.ja;axsFinance.Md={};axsFinance.Z={};axsFinance.ya=300;axsFinance.i=i;axsFinance.o=i;axsFinance.L=i;axsFinance.lb=i;axsFinance.Jb=i;axsFinance.ba=2.5;axsFinance.Y=i;axsFinance.Eb="";axsFinance.xa="incinterimdiv";
axsFinance.jd=function(){axsFinance.i=new n(h);axsFinance.L=new w(axsFinance.i);axsFinance.L.Xa(axsFinance.ba);axsFinance.lb=new x(h);axsFinance.o=new o(axsFinance.i);axsFinance.o.Fd(axsFinance.L);axsFinance.Jb=new y("list",axsFinance.i);axsFinance.Bb();axsFinance.o.Hd(axsFinance.lb);var a=axsFinance.Q;document.addEventListener("keypress",a,h);document.addEventListener("DOMNodeInserted",axsFinance.yd,j);a=axsFinance.Qc;document.addEventListener("DOMSubtreeModified",a,h);axsFinance.Hc()};
axsFinance.Hc=function(){var a='//div[@class="hdg top"]//h3';a=axsFinance.i.w(a,document.body)[0];a=axsFinance.a.cc+", "+axsFinance.Qa(a.textContent)+", "+axsFinance.tb();axsFinance.i.r(a,j)};axsFinance.yd=function(a){a.target.className==="d-quotes"&&axsFinance.o.xd("Recent quotes")};axsFinance.dd=function(){axsFinance.o.b=2};axsFinance.Bb=function(){var a=axsFinance.Zc();axsFinance.Eb=a;a=axsFinance.Xc();axsFinance.o.pd(a);axsFinance.o.Gd(axsFinance.Jb,".")};
axsFinance.Fc=function(){var a=axsFinance.tb();axsFinance.i.r(a,i)};axsFinance.tb=function(){var a='//div[contains(@class,"goog-tab-selected") or @class="gf-table-control-plain"]//a[@class="t" or @class="ac"]',b=axsFinance.i.w(a,document.body);a=b[0].textContent;b=b[1].textContent;return a+", "+b};axsFinance.storeCurrentPositionAndClickOnLink=function(a){var b=axsFinance.o.b,d=axsFinance.o.e[b],c={};c.ld=b;c.kd=d;axsFinance.Y=c;a=a.k;axsFinance.i.nb(a,j)};
axsFinance.Xc=function(){var a=axsFinance.Vb,b="",d="",c=b=0;c='id("'+axsFinance.xa+'")//tbody/tr';for(var e=axsFinance.i.w(c,document.body),f=0;d=e[f];f++)if(d.className==="hilite"||f===e.length-1){c=f+1;d=axsFinance.Ra(d.childNodes[1].textContent);b=axsFinance.Yc(d,b,c);a+=b;b=c+1}a+=axsFinance.Ub;return a};axsFinance.Yc=function(a,b,d){b=new Array(axsFinance.xa,b,d);b=axsFinance.ua(axsFinance.a.Bc,b);b=new Array(a,b);return a=axsFinance.ua(axsFinance.Tb,b)};
axsFinance.Zc=function(){var a='id("'+axsFinance.xa+'")//thead//th[not(@class="lm lft nwp")]';a=axsFinance.i.w(a,document.body);for(var b="{0}, ",d=0,c;c=a[d];d++){c=c.textContent;var e=c.lastIndexOf(" "),f=c.substring(e+1);c=c.substring(0,e);c=c+" "+axsFinance.ud(f);e=d+1;b=b+c+", {"+e+"}. "}return b=axsFinance.Qa(b)};axsFinance.ud=function(a){var b=a.split("-");a=b[0];b=b[1];return a=axsFinance.G[b]+" "+a};
axsFinance.readTableRow=function(a){a=a.k;for(var b=[],d=1,c;c=a.childNodes[d];d+=2)b.push(axsFinance.Ra(c.textContent));b=axsFinance.ua(axsFinance.Eb,b);axsFinance.Nb(a,b)};axsFinance.readRecentQuote=function(a){a=a.k;var b="./td[not(.//b)]";b=axsFinance.i.w(b,a);for(var d=[],c=0,e=b.length;c<e;c++){d[c]=axsFinance.ad(b[c]);d[c]=axsFinance.Ra(d[c])}b=axsFinance.ua(axsFinance.a.sc,d);axsFinance.Nb(a,b)};
axsFinance.ad=function(a){var b="",d='.//descendant-or-self::*[not(contains(@style,"display: none;"))]/text()';a=axsFinance.i.w(d,a);d=0;for(var c=a.length;d<c;d++)b=b+a[d].textContent+" ";return b};
axsFinance.Qc=function(a){var b=a.target;if(b.id=="incinterimdiv"||b.id=="incannualdiv"||b.id=="balinterimdiv"||b.id=="balannualdiv"||b.id=="casinterimdiv"||b.id=="casannualdiv"){axsFinance.xa=b.id;b=function(){axsFinance.Bb();axsFinance.dd();axsFinance.Fc();if(axsFinance.Y){var d=axsFinance.Y.ld,c=axsFinance.Y.kd;axsFinance.o.b=d;axsFinance.o.e[d]=c;axsFinance.Y=i}axsFinance.L.view(i)};axsFinance.Sc(b,a)}};
axsFinance.Sc=function(a,b){if(axsFinance.Z[a.toString()]){b.bb=(new Date).getTime()+axsFinance.ya;axsFinance.Z[a.toString()]=b}else{b.bb=(new Date).getTime()+axsFinance.ya;axsFinance.Z[a.toString()]=b;var d=function(){var c=(new Date).getTime(),e=a.toString();e=axsFinance.Z[e];if(e.bb>c)window.setTimeout(d,e.bb-c);else{a(e);axsFinance.Z[a.toString()]=i}};window.setTimeout(d,axsFinance.ya)}};axsFinance.Nb=function(a,b){axsFinance.L.view(a);axsFinance.i.r(b);a.scrollIntoView(h);axsFinance.i.sa(a)};
axsFinance.ua=function(a,b){for(var d=new String(a),c=0;c<b.length;c++){var e=new RegExp("{("+c+")}","g");d=d.replace(e,b[c])}return d};
axsFinance.Ra=function(a){var b="";if(a==="")return a;a=axsFinance.Qa(a);var d=axsFinance.G[a];if(d!=undefined)return d;a=a.split(" ");for(d=0;a[d];d++){var c=a[d],e=axsFinance.G[c];if(e!=undefined)c=e;else{if(c.length>0&&c.charAt(0)==="(")c=c.substring(1);if(c.length>1&&c.charAt(c.length-1)===")")c=c.substring(0,c.length-1);e=axsFinance.Sa[c.charAt(0)];if(e!=undefined)c=e+" "+c.substring(1);e=c.charAt(c.length-1);e=axsFinance.Md[e];if(e!=undefined)c=c.substring(0,c.length-1)+" "+e}b=b+" "+c}return b};
axsFinance.Qa=function(a){a=a.replace(/^\s\s*/,"").replace(/\s\s*$/,"");a=a.replace(/\s+/g," ");return a.replace(/\n+/g,"").replace(/\r+/g,"")};axsFinance.Q=function(a){if(a.ctrlKey)return h;if(a.keyCode==27){axsFinance.i.D.blur();return j}if(axsFinance.i.qa)return h;if(a=axsFinance.Mc[a.charCode])return a();return h};
axsFinance.Mc={47:function(){document.getElementById("searchbox").focus();document.getElementById("searchbox").select();return j},63:function(){var a=axsFinance.a.fc+axsFinance.o.md()+axsFinance.o.bd();axsFinance.i.r(a);return j},45:function(){axsFinance.ba-=0.1;axsFinance.L.Xa(axsFinance.ba);return j},61:function(){axsFinance.ba+=0.1;axsFinance.L.Xa(axsFinance.ba);return j}};window.addEventListener("load",axsFinance.jd,h); })();
