(function() { 
var b=function(a){this.na=0;this.Q=null;this.ia=false;this.t=null;this.O=false;var c=this,d=function(g){c.t=g.target;if(g.target.tagName=="INPUT"||g.target.tagName=="SELECT"||g.target.tagName=="TEXTAREA")c.O=true;return true};document.addEventListener("focus",d,true);var e=function(g){c.ea(c.t,"aria-activedescendant");c.t=null;if(g.target.tagName=="INPUT"||g.target.tagName=="SELECT"||g.target.tagName=="TEXTAREA")c.O=false;return true};document.addEventListener("blur",e,true);if(a){this.ia=true;document.addEventListener("keypress",
function(g){c.eb(g,c)},true);document.body.gb=true}this.M=document.body};b.prototype.s=function(){var a=this.M;while(a.nodeType!=9)a=a.parentNode;return a};b.prototype.ha=function(a,c){if(!a.id)this.W(a);if(c){this.u(a,"live","rude");this.u(a,"atomic","true");var d=this.s(),e=d.createElement("div");e.textContent=" ";e.name="AxsJAX_dummyNode";if(a.lastChild&&a.lastChild.name&&a.lastChild.name==e.name)a.removeChild(a.lastChild);a.appendChild(e)}else{var g=this.Fa(a,"role");this.u(a,"role","row");var i=
this.t;if(!i||i.nodeType==9){this.M.tabIndex=-1;i=this.M}this.u(i,"activedescendant",null);i.focus();this.u(i,"activedescendant",a.id);var h=this;window.setTimeout(function(){if(g)h.u(a,"role",g);else h.ea(a,"role")},0)}};b.prototype.j=function(a,c){var d="AxsJAX_pixelAudioNode",e="AxsJAX_pixelAudioNode",g="data:image/gif;base64,R0lGODlhAQABAIAAANvf7wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",i=this.s(),h=null;if(c){if(c.previousSibling&&c.previousSibling.name==e)h=c.previousSibling;else{h=i.createElement("img");
h.name=e;h.setAttribute("tabindex",0);h.style.outline="none";h.src=g;c.parentNode.insertBefore(h,c);this.Ea(h)}h.setAttribute("alt",a);h.setAttribute("title",a);window.setTimeout(function(){h.blur();h.focus()},0)}else{h=i.getElementById(d);if(!h){h=i.createElement("img");h.id=d;h.src=g;i.body.appendChild(h)}h.setAttribute("alt",a);h.setAttribute("title",a);this.ha(h)}};b.prototype.q=function(a,c){var d=this.s(),e=d.createEvent("MouseEvents");e.initMouseEvent("mousedown",true,true,d.defaultView,1,
0,0,0,0,false,false,c,false,0,null);try{a.dispatchEvent(e)}catch(g){}e=d.createEvent("MouseEvents");e.initMouseEvent("mouseup",true,true,d.defaultView,1,0,0,0,0,false,false,c,false,0,null);try{a.dispatchEvent(e)}catch(g){}e=d.createEvent("MouseEvents");e.initMouseEvent("click",true,true,d.defaultView,1,0,0,0,0,false,false,c,false,0,null);try{a.dispatchEvent(e)}catch(g){}if(a.tagName=="A"&&a.href&&(a.href.indexOf("http")===0||a.href.indexOf("javascript:")===0))if(c)window.open(a.href);else document.location=
a.href};b.prototype.W=function(a,c){if(!a)return"";if(a.id)return a.id;var d=c||"AxsJAX_ID_";a.id=d+this.na++;return a.id};b.prototype.eb=function(a,c){if(!c.ia)return true;if(a.keyCode==9&&c.Q){c.Q.focus();c.Q=null}return true};b.prototype.u=function(a,c,d){if(!a)return;c=c.toLowerCase();switch(c){case "live":c="aria-live";break;case "activedescendant":c="aria-activedescendant";break;case "atomic":c="aria-atomic";break;default:break}a.setAttribute(c,d)};b.prototype.Fa=function(a,c){return a.getAttribute(c)};
b.prototype.ea=function(a,c){if(a&&a.removeAttribute)a.removeAttribute(c)};b.prototype.Ea=function(a){var c=this.W(a),d=this.s(),e=d.mb,g=e.indexOf("#");if(g!=-1)e=e.substring(0,g);d.location=e+"#"+c};b.prototype.z=function(a,c){try{var d=c.ownerDocument.evaluate(a,c,null,XPathResult.ORDERED_NODE_ITERATOR_TYPE,null)}catch(e){return[]}var g=[];for(var i=d.iterateNext();i;i=d.iterateNext())g.push(i);return g};var f=function(a,c){this.G=a;this.h=null;this.d=null;this.nb=null;this.N="Enter Completion";this.ca="No completions found";this.w=null;this.g=null;this.X=null;this.m=[];this.c=-1;this.aa=false;this.Oa={};this.I={};if(c&&f.A)this.w=c};f.ka=/^\<[A-Z|a-z|0-9|\-|\_]+\>$/;f.oa=/^(\s|\r|\n)+/;f.sa=/(\s|\r|\n)+$/;f.prototype.F=function(a,c,d,e){if(f.A&&d)a.addEventListener(c,d,true);else if(f.i&&d)a.attachEvent(c,function(h){d(h)});if(e){var g=new f.S(e),i=this;this.F(a,c,function(h){g.Na(h,g,i)},null)}};
f.prototype.Aa=function(a,c,d,e,g,i){var h=this,j,m,r,o;if(this.h)this.h.parentNode.removeChild(this.h);do{j="completionField_"+Math.floor(Math.random()*1001);m="txt_"+j;o="div_"+j;r=document.getElementById(j)}while(r);var k=document.createElement("div");k.id=j;k.style.position="absolute";var n=document.createElement("input");n.type="text";n.id=m;n.size=c;n.value="";n.setAttribute("onkeypress","if (event.keyCode == PowerKey.keyCodes.TAB){return false;}");n.readOnly=i;if(i)n.style.fontSize=0;var p=
document.createElement("div");p.id=o;p.setAttribute("tabindex",0);p.setAttribute("role","row");k.appendChild(p);k.appendChild(n);a.appendChild(k);this.h=k;this.d=n;this.X=p;this.h.className="pkHiddenStatus";this.d.className="pkOpaqueCompletionText";if(g){this.m=g;this.b=this.m;for(var q=0,s;s=this.m[q];q++)this.I[s.toLowerCase()]=q;this.c=-1}this.F(this.d,f.U.D,function(t){h.Ma.call(h,t,e,d)},null);this.F(this.d,f.U.C,function(t){h.La.call(h,t)},null);this.F(this.d,"blur",function(){if(h.aa)h.R("hidden")},
null)};f.prototype.Ma=function(a,c,d){if(this.d.value.length===0)this.b=this.m;if(a.keyCode!=f.n.D&&a.keyCode!=f.n.C&&a.keyCode!=f.n.T&&a.keyCode!=f.n.V)if(this.d.value.length){this.b=this.Z(this.m,this.d.value,50);this.c=-1;if(this.b.length>0){this.v(this.b[0]);this.c=0}else this.v(this.ca)}else this.v(this.N);if(a.keyCode==f.n.T){if(this.d.readOnly)return;if(this.b&&this.b.length>0&&this.d.value!=this.b[this.c]&&(this.b[this.c].indexOf("<")<0||this.b[this.c].indexOf("<")>=0&&this.b[this.c].split(" ").length>
this.d.value.split(" ").length)){this.ga();return}var e=this.d.value,g=(f.i?this.g.innerText:this.g.textContent).toLowerCase(),i=g.indexOf("<"),h;if(i>=0){h=e.substr(0,i-1).toLowerCase();e=h+" "+e.substr(i)}else{e=e.toLowerCase();h=e}var j=false;if(c)j=this.wa.call(this,e,g,c);if(d&&!j){var m=this.Y(e,g);d(h,this.I[g],this.Oa[g],m)}this.d.value=""}};f.prototype.La=function(a){if(a.keyCode==f.n.D&&this.b&&this.b.length>0)this.Ua();else if(a.keyCode==f.n.C&&this.b&&this.b.length>0)this.Ta();else if(a.keyCode==
f.n.V)if(this.b&&this.b.length>0)this.ga()};f.prototype.Xa=function(a){this.aa=a};f.prototype.$a=function(a){this.N=a};f.prototype.bb=function(a){this.ca=a};f.prototype.Za=function(a){this.m=a;this.b=this.m;this.I={};for(var c=0,d;d=this.m[c];c++)this.I[d.toLowerCase()]=c;this.c=-1};f.prototype.R=function(a,c,d,e){if(a=="visible"){if(this.h.className=="pkHiddenStatus")this.v(this.N);this.h.className="pkVisibleStatus";var g=this.d;window.setTimeout(function(){g.focus()},0)}else if(a=="hidden"){if(f.i&&
this.g)this.g.innerText="";else if(this.g)this.g.textContent="";this.h.className="pkHiddenStatus";this.d.value="";this.c=-1}if(c){var i=f.Ga();if(!d)d=i.height-this.h.offsetHeight;if(!e)e=0;this.h.style.top=d;this.h.style.left=e}};f.prototype.Z=function(a,c,d){var e=a,g=a,i=c.split(" ");for(var h=0,j;j=i[h];h++){g=e;e=[];if(j!==""){var m=f.Wa(j),r=new RegExp("(^|\\W+)"+m,"i");for(var o=0,k;k=g[o];o++)if(String(k).match(r))e.push(k)}}g=a;for(o=0;k=g[o];o++){var n=k.split(" "),p=[],q;for(h=0;q=n[h];h++){if(q.charAt(0)==
"<")break;p.push(q)}var s=p.join(" ");if(c.indexOf(s)===0)e.push(k)}if(e.length>d)e.slice(0,d-1);return e};f.prototype.Y=function(a,c){a=a.replace(/\s+/g," ");c=c.replace(/\s+/g," ");var d=c.indexOf("<");if(d<0)return[];c=c.substr(d);a=a.substr(d);var e=a.split(","),g=c.split(",");if(e.length!=g.length)return[];var i=[];for(var h=0,j,m;(j=e[h])&&(m=g[h]);h++){j=f.ba(f.fa(j));m=f.ba(f.fa(m));if(m.match(f.ka))i.push(j)}return i};f.prototype.wa=function(a,c,d){this.Y(a,c);var e=d[c];if(e&&e[this.G]){var g=
e[this.G]+"(args);";window.setTimeout(g,0);return true}else return false};f.prototype.Ua=function(){if(this.c<0)this.c=0;this.c=(this.c||this.b.length)-1;if(this.c>=0)this.v(this.b[this.c])};f.prototype.Ta=function(){this.c=(this.c+1)%this.b.length;if(this.c<this.b.length)this.v(this.b[this.c])};f.prototype.ga=function(){this.d.value=this.b[this.c>=0?this.c:0];this.b=this.Z(this.m,this.d.value,50);if(this.w&&f.A)this.w.j(this.d.value);this.c=0};f.prototype.v=function(a){if(!this.g){this.g=document.createElement("div");
this.g.id="listElem_"+Math.floor(Math.random()*1001);this.X.appendChild(this.g)}if(f.i)this.g.innerText=a;else this.g.textContent=a;if(this.w&&f.A)this.w.ha(this.g,false)};f.S=function(a){this.L=a};f.S.prototype.Na=function(a,c,d){if(!c.L)return;if(a.keyCode){var e=""+a.keyCode,g=String.fromCharCode(a.keyCode).toLowerCase();if(a.ctrlKey){e="Ctrl+"+e;g="Ctrl+"+g}if(a.altKey){e="Alt+"+e;g="Alt+"+g}if(a.shiftKey){e="Shift+"+e;g="Shift+"+g}var i=null;i=c.L[g];if(!i)i=c.L[e];if(i)if(i[d.G]){var h=i[d.G];
h()}}};f.va=function(a,c){this.width=a?a:undefined;this.height=c?c:undefined};f.ba=function(a){return a.replace(f.oa,"")};f.fa=function(a){return a.replace(f.sa,"")};f.Wa=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};f.Ga=function(){var a=0,c=0;if(typeof window.innerWidth=="number"){a=window.innerWidth;c=window.innerHeight}else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){a=document.documentElement.clientWidth;
c=document.documentElement.clientHeight}else if(document.body&&(document.body.clientWidth||document.body.clientHeight)){a=document.body.clientWidth;c=document.body.clientHeight}return new f.va(a,c)};f.i=false;f.A=false;f.Ya=function(){var a=navigator.userAgent.toLowerCase();f.A=a.indexOf("gecko")!=-1;f.i=a.indexOf("msie")!=-1&&a.indexOf("opera")==-1};f.Ya();f.U={D:f.i?"onkeyup":"keyup",C:f.i?"onkeydown":"keydown",kb:f.i?"onkeypress":"keypress",ib:f.i?"onclick":"click",lb:f.i?"onresize":"resize",jb:f.i?
"onfocus":"focus",hb:"blur"};f.Ba=".pkHiddenStatus {display: none; position: absolute;}.pkVisibleStatus {display: block; position: absolute; left: 2px; top: 2px; line-height: 1.2em; z-index: 10000; background-color: #000000; padding: 2px; color: #fff; font-family: Arial, Sans-serif; font-size: 20px; filter: alpha(opacity=85); -moz-opacity: .80;}.pkOpaqueStatusText { background-color: transparent; font-family: Arial, Helvetica, sans-serif; font-size: 30px; color: #fff;}.pkOpaqueCompletionText {border-style: none; background-color:transparent; font-family: Arial, Helvetica, sans-serif; font-size: 35px; font-weight: bold; color: #fff; width: 1000px; height: 50px;}";
f.ab=function(){var a,c;a=document.getElementsByTagName("head")[0];if(!a)return;c=document.createElement("style");c.type="text/css";c.innerHTML=f.Ba;a.appendChild(c)};f.n={D:38,C:40,T:13,V:9};var l={};l.ma="The following shortcut keys are available. T, today. N or J, next day. P or K, previous day. Down arrow, next event. Up arrow, previous event. I, information about the current event. Q, quickly add an event. C, create event. G, get a friends calendar. L, next calendar. H, previous calendar. F, filter calendars. Space, toggle calendar selection. ";l.ua="Today. ";l.la=" events. ";l.K="No events.";l.pa="Not selected. ";l.ta="Selected. ";l.ra="Enter calendar name.";l.qa="No calendars found.";
l.p={B:0,J:1};l.r=l.p.J;l.a=null;l.o=null;l.f=-1;l.e=[];l.l=-1;l.k=[];l.Pa=function(){l.a=new b(true);document.addEventListener("keypress",l.Sa,true);l.f=-1;l.e=[];window.addEventListener("DOMNodeInserted",l.Da,true);l.o=new f("calendarList",l.a);var a=l.a.s().body,c=function(d,e){l.o.R("hidden",true,40,20);l.a.t.blur();l.l=e-1;l.$()};l.o.$a(l.ra);l.o.bb(l.qa);l.o.Aa(a,30,c,null,null,false);l.o.Xa(true);f.ab();window.setTimeout(l.db,100)};l.db=function(){var a=document.getElementById("mode-day");
l.a.q(a,false)};l.Da=function(a){var c=a.target,d=c.parentNode.id;if(d=="dateunderlay"){l.f=-1;l.ja();l.cb()}else if(d=="nt2")l.a.j(c.parentNode.textContent);else if(c.parentNode.parentNode.parentNode.id=="infowindow")l.Va()};l.H=function(){var a=document.getElementById("calendars"),c="//div[@class='calListRow']";l.k=l.a.z(c,a)};l.P=function(){var a=l.k[l.l],c=l.pa;if(a.getElementsByTagName("input")[0].checked)c=l.ta;l.a.j(c+a.textContent)};l.$=function(){l.r=l.p.B;if(l.k.length===0)l.H();l.l++;if(l.l>=
l.k.length)l.l=0;l.P();return false};l.Ja=function(){l.r=l.p.B;if(l.k.length===0)l.H();l.l--;if(l.l<0)l.l=l.k.length;l.P();return false};l.fb=function(){l.H();var a=l.k[l.l],c=".//div[@class='calMenuLabel']",d=l.a.z(c,a)[0];if(d)l.a.q(d,false);else{var e=a.getElementsByTagName("input")[0];l.a.q(e,false)}l.P();return false};l.da=function(){var a=document.getElementById("addP");if(!a){l.a.q(document.getElementById("addPT"),false);window.setTimeout(l.da,100);return false}var c=a.childNodes[2];l.a.q(c,
false);return false};l.ja=function(){var a=document.getElementById("allDayGrid"),c=".//div[@class='adc']",d=l.a.z(c,a);a=document.getElementById("grid");c=".//div[@class='chip']";var e=l.a.z(c,a);l.e=[];var g=0,i=null;for(;i=d[g];g++)l.e.push(i);g=0;i=null;for(;i=e[g];g++)l.e.push(i)};l.cb=function(){var a="";if(document.getElementById("todayButton").hasAttribute("disabled"))a=l.ua;var c=document.getElementById("chead0").textContent+" ",d=document.getElementById("dateunderlay").textContent+". ",e=
a+c+d+l.e.length+l.la;l.a.j(e)};l.Ia=function(){l.r=l.p.J;if(l.e.length===0){l.a.j(l.K);return false}l.f++;if(l.f>=l.e.length)l.f=0;var a=l.e[l.f];l.a.j(a.textContent);return false};l.Ka=function(){l.r=l.p.J;if(l.e.length===0){l.a.j(l.K);return false}l.f--;if(l.f<0)l.f=l.e.length;var a=l.e[l.f];l.a.j(a.textContent);return false};l.Va=function(){var a=document.getElementById("mtb"),c=a.parentNode.parentNode.nextSibling,d=a.textContent+". ";for(;c.className!="bubbleSeparator";c=c.nextSibling)d=d+c.textContent+
". ";l.a.j(d)};l.xa=function(){l.ja();if(l.e.length===0){l.a.j(l.K);return false}if(l.f<0)l.f=0;var a=l.e[l.f],c=l.a.s(),d=c.createEvent("MouseEvents");d.initMouseEvent("click",true,true,c.defaultView,1,0,0,0,0,false,false,false,false,0,null);try{a.dispatchEvent(d)}catch(e){}return false};l.Ca=function(){var a=document.getElementById("infowindow"),c=".//font/a[text()='Delete']",d=l.a.z(c,a)[0];l.a.q(d,false)};l.Ha=function(){l.r=l.p.B;if(l.k.length===0)l.H();var a=[];for(var c=0,d;d=l.k[c];c++)a.push(d.textContent);
l.o.Za(a);l.o.R("visible",true,40,20)};l.Sa=function(a){if(a.ctrlKey)return true;if(a.keyCode==27){l.a.t.blur();return false}if(l.a.O)return true;var c=null;if(l.r===l.p.B)c=l.Ra[a.keyCode]||l.za[a.charCode];if(c)return c();c=l.Qa[a.keyCode]||l.ya[a.charCode];if(c)return c();return true};l.Ra={};l.za={32:l.fb};l.Qa={46:l.Ca,40:l.Ia,38:l.Ka};l.ya={63:function(){l.a.j(l.ma);return false},103:l.da,105:l.xa,102:l.Ha,108:l.$,104:l.Ja};window.setTimeout(l.Pa,100);
 })();
