(function() { var h=true,i=null,j=false,l,n=function(a){this.bc=0;this.ca=i;this.Kb=j;this.B=i;this.qa=j;var b=this;this.Ba=document.body;this.Ac();if(a){this.Kb=h;document.addEventListener("keypress",function(d){b.yd(d,b)},h);document.body.zd=h}this.N(document.body,"role","application")};l=n.prototype;
l.Ac=function(){var a=this.v(),b=this,d=function(c){b.B=c.target;if(c.target.tagName=="INPUT"||c.target.tagName=="SELECT"||c.target.tagName=="TEXTAREA")b.qa=h;return h};a.addEventListener("focus",d,h);d=function(c){b.Sa(b.B,"aria-activedescendant");b.B=i;if(c.target.tagName=="INPUT"||c.target.tagName=="SELECT"||c.target.tagName=="TEXTAREA")b.qa=j;return h};a.addEventListener("blur",d,h)};l.v=function(){for(var a=this.Ba;a.nodeType!=9;)a=a.parentNode;return a};
l.Xa=function(a,b){a.id||this.gb(a);if(b){this.N(a,"live","rude");this.N(a,"atomic","true");var d=this.v();d=d.createElement("div");d.textContent=" ";d.name="AxsJAX_dummyNode";a.lastChild&&a.lastChild.name&&a.lastChild.name==d.name&&a.removeChild(a.lastChild);a.appendChild(d)}else{var c=this.Rc(a,"role");this.N(a,"role","row");d=this.B;if(!d||d.nodeType==9){this.Ba.tabIndex=-1;d=this.Ba}this.N(d,"activedescendant",i);d.focus&&d.focus();this.N(d,"activedescendant",a.id);var e=this;window.setTimeout(function(){c?
e.N(a,"role",c):e.Sa(a,"role")},0)}};
l.r=function(a,b){var d="AxsJAX_pixelAudioNode",c="AxsJAX_pixelAudioNode",e="data:image/gif;base64,R0lGODlhAQABAIAAANvf7wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",f=this.v(),g=i;if(b){if(b.previousSibling&&b.previousSibling.name==c)g=b.previousSibling;else{g=f.createElement("img");g.name=c;g.setAttribute("tabindex",0);g.style.outline="none";g.src=e;b.parentNode.insertBefore(g,b);this.Oc(g)}g.setAttribute("alt",a);g.setAttribute("title",a);window.setTimeout(function(){g.blur();g.focus()},0)}else{if((g=
f.getElementById(d))&&g.alt==a)a+=" ";if(!g){g=f.createElement("img");g.id=d;g.src=e;f.body.appendChild(g)}g.setAttribute("alt",a);g.setAttribute("title",a);this.Xa(g)}};
l.Jc=function(a,b){var d=this.v(),c=d.createEvent("MouseEvents");c.initMouseEvent("mousedown",h,h,d.defaultView,1,0,0,0,0,j,j,b,j,0,i);try{a.dispatchEvent(c)}catch(e){}c=d.createEvent("MouseEvents");c.initMouseEvent("mouseup",h,h,d.defaultView,1,0,0,0,0,j,j,b,j,0,i);try{a.dispatchEvent(c)}catch(f){}c=d.createEvent("MouseEvents");c.initMouseEvent("click",h,h,d.defaultView,1,0,0,0,0,j,j,b,j,0,i);try{a.dispatchEvent(c)}catch(g){}d=a.getAttribute("href");if(a.tagName=="A"&&d&&d!="#")if(b)window.open(a.href);
else document.location=a.href};l.gb=function(a,b){if(!a)return"";if(a.id)return a.id;var d=b||"AxsJAX_ID_";a.id=d+this.bc++;return a.id};l.sa=function(a){if(!a)return j;if(a.tagName=="A"||a.tagName=="INPUT"){this.ca=a;return h}a=a.getElementsByTagName("*");for(var b=0,d;d=a[b];b++)if(d.tagName=="A"||d.tagName=="INPUT"||d.hasAttribute("tabindex")&&d.tabIndex!=-1){this.ca=d;return h}return j};l.yd=function(a,b){if(!b.Kb)return h;if(a.keyCode==9&&b.ca){b.ca.focus();b.ca=i}return h};
l.Uc=function(a){this.Xa(a);a.scrollIntoView(h);this.sa(a)};l.N=function(a,b,d){if(a){b=b.toLowerCase();switch(b){case "live":b="aria-live";break;case "activedescendant":b="aria-activedescendant";break;case "atomic":b="aria-atomic";break;default:break}a.setAttribute(b,d)}};l.Rc=function(a,b){return a.getAttribute(b)};l.Sa=function(a,b){a&&a.removeAttribute&&a.removeAttribute(b)};
l.Oc=function(a){a=this.gb(a);var b=this.v(),d=b.baseURI,c=d.indexOf("#");if(c!=-1)d=d.substring(0,c);b.location=d+"#"+a};l.L=function(a,b){try{var d=b.ownerDocument.evaluate(a,b,i,XPathResult.ORDERED_NODE_ITERATOR_TYPE,i)}catch(c){return[]}for(var e=[],f=d.iterateNext();f;f=d.iterateNext())e.push(f);return e};n.Sd=function(a){window.addEventListener("load",function(){a()},h)};var o=function(a){this.va=this.ta="";this.d=[];this.b=0;this.g=[];this.o=i;this.da=[];this.I={};this.J={};this.K=[];this.G=[];this.e=a;this.D=this.w=this.C=i;this.dc="list";this.ab="item";this.fb="wrap";this.Q=i};o.a={ic:"next list",nc:"previous list",$b:"go forward",Zb:"go backwards",Sb:"cycle next",Tb:"cycle previous",rc:"Select available action",jc:"No available actions",db:"Page up",cb:"Page down",T:"Enter",Dd:"Escape",Cd:"Delete",ja:"Up",fa:"Down",bb:"Left",eb:"Right"};l=o.prototype;
l.td=function(a,b){if(b){this.w=a;this.w.i===i&&this.Mc();var d=this,c=new Array(b);this.t(c,this.I,this.J,function(){d.Jb()})}};l.Za=function(a){var b=h;if(a.type=="dynamic"&&a.k.length===0){this.C!==i&&this.C.view(i);a.k=this.ra(a.ba);a.p=this.Bb(a.ba);if(this.d[this.b]===a)this.g[this.b]=-1;else for(var d=0,c;c=this.d[d];d++)if(c===a){this.g[d]=-1;break}}if(a.k.length===0&&a.Fa===i)b=j;return b};
l.nb=function(){var a=this.P();a=a.Fa;var b=i;if(a!==i){this.ka(a);b=this.Ha(a.action)}if(b===i){this.Cc();this.D!==i&&this.D.play(this.dc)}};l.dd=function(){if(this.d.length<1)return i;for(var a=0;this.d[a];a++){this.b++;if(this.b>=this.d.length)this.b=0;if(this.Za(this.d[this.b]))break}return this.P()};l.jd=function(){if(this.d.length<1)return i;for(var a=0;this.d[a];a++){this.b--;if(this.b<0)this.b=this.d.length-1;if(this.Za(this.d[this.b]))break}return this.P()};l.P=function(){return this.d[this.b]};
l.Cc=function(){this.e.r(this.P().title)};l.Na=function(){if(this.d.length<1)return i;var a=this.d[this.b],b=a.k;if(b.length<1)return i;if(this.o){var d=this.Ja(a);d=this.o.j.S[d];if(typeof d!="undefined")this.g[this.b]=d}this.g[this.b]++;d=j;if(this.g[this.b]>=b.length){this.g[this.b]=0;d=h}var c=this.g[this.b];if(b[c].j.parentNode===i){this.C!==i&&this.C.view(i);a.k=this.ra(a.ba);this.g[this.b]=0;c=this.g[this.b]}this.o=b[c];if(this.D!==i)d?this.D.play(this.fb):this.D.play(this.ab);return this.o};
l.Qc=function(){var a=this.d[this.b],b=this.g[this.b];if(a.Ya!==i&&b+1>=a.k.length){this.ka(a.Ya);this.g[this.b]=0;return i}return a=this.Na()};
l.Fb=function(){if(this.d.length<1)return i;var a=this.d[this.b],b=a.k;if(b.length<1)return i;if(this.o){var d=this.Ja(a);d=this.o.j.S[d];if(typeof d!="undefined")this.g[this.b]=d}this.g[this.b]--;d=j;if(this.g[this.b]<0){this.g[this.b]=b.length-1;d=h}var c=this.g[this.b];if(b[c].j.parentNode===i){this.C!==i&&this.C.view(i);a.k=this.ra(a.ba);this.g[this.b]=a.k.length;c=this.g[this.b]}this.o=b[c];if(this.D!==i)d?this.D.play(this.fb):this.D.play(this.ab);return this.o};
l.Gc=function(){var a=this.d[this.b],b=this.g[this.b];if(a.La!==i&&b<=0){this.ka(a.La);this.g[this.b]=a.k.length-1;return i}return a=this.Fb()};l.mb=function(){if(this.d.length<1)return i;var a=this.d[this.b];if(this.o){var b=this.Ja(a);b=this.o.j.S[b];if(typeof b!="undefined")this.g[this.b]=b}a=a.k;b=this.g[this.b];return this.o=a[b]};l.Ha=function(a){var b=i;if(a!==i&&a.indexOf&&a.indexOf("CALL:")===0&&a.indexOf("(")===-1)try{b=eval(a.substring(5))}catch(d){}return b};
l.U=function(a){if(a!==i){var b=this,d=function(){var f=b.Ha(a.action);if(f)f(a);else{b.C!==i&&b.C.view(a.j);b.e.Uc(a.j)}};if(this.e.B&&this.e.B.blur){var c=this.e.B;this.e.B=i;c.removeAttribute&&this.e.Sa(c,"aria-activedescendant");var e=function(f){f.target.removeEventListener("blur",e,h);d()};c.addEventListener("blur",e,h);c.blur()}else d()}else{c=this.d[this.b];c.type=="dynamic"&&this.e.r(c.onEmpty)}};
l.t=function(a,b,d,c){for(var e=0,f;f=a[e];e++)if(f=="LEFT")d[37]=c;else if(f=="UP")d[38]=c;else if(f=="RIGHT")d[39]=c;else if(f=="DOWN")d[40]=c;else if(f=="PGUP")d[33]=c;else if(f=="PGDOWN")d[34]=c;else if(f=="ENTER")d[13]=c;else if(f=="ESC")d[27]=c;else if(f=="DEL")d[46]=c;else b[f.charCodeAt(0)]=c};
l.ma=function(a,b,d){var c=[];if(a!==""){c=a.split(" ");var e=this;if(d=="prev")this.t(c,this.K[b],this.G[b],function(){e.U(e.Fb())});else if(d=="next")this.t(c,this.K[b],this.G[b],function(){e.U(e.Na())});else d=="back"?this.t(c,this.K[b],this.G[b],function(){var f=e.Gc();f!==i&&e.U(f)}):this.t(c,this.K[b],this.G[b],function(){var f=e.Qc();f!=i&&e.U(f)})}};l.Fc=function(a,b,d){var c=[];if(a!==""){c=a.split(" ");var e=this;this.t(c,this.I,this.J,function(){if(e.Za(e.d[b])){e.b=b;e.U(e.Na())}else e.e.r(d)})}};
l.Ec=function(a,b){var d=[];if(a!==""){d=a.split(" ");var c=this;this.t(d,this.I,this.J,function(){c.e.r(b)})}};l.hb=function(a,b,d){var c=[];if(a.hotkey!==""){c=a.hotkey.split(" ");var e=this;this.t(c,b,d,function(){e.ka(a)})}};l.ka=function(a){a.action=="click"?this.Kc(a):this.Hc(a)};l.Hc=function(a){var b=this.qb(a);if(b.length<1)this.e.r(a.onEmpty);else{var d=this.Ha(a.action);if(d){var c={};c.action=a.action;c.j=b[0];d(c);this.e.sa(b[0])}else throw new Error("Invalid action: "+a.action);}};
l.Kc=function(a){var b=this.qb(a);if(b.length<1)this.e.r(a.onEmpty);else{this.e.Jc(b[0],j);b[0].scrollIntoView(h);this.e.sa(b[0])}};l.qb=function(a){a=a.s;var b=this.e.v().documentElement;if(a.indexOf(".")===0)b=this.mb().j;return this.e.L(a,b)};l.rb=function(a,b){var d=i,c=this.b;if(c<this.G.length)d=this.G[c][a]||this.K[c][b]||i;if(d===i)d=this.J[a]||this.I[b];return d};
l.cd=function(a,b){var d={};d.zb=[];var c=new DOMParser,e=c.parseFromString(a,"text/xml"),f=e.getElementsByTagName("list"),g;for(c=0;g=f[c];c++){var k={};k.title=g.getAttribute("title");k.hotkey=g.getAttribute("hotkey");k.next=g.getAttribute("next");k.Qa=g.getAttribute("prev");k.Pc=g.getAttribute("fwd");k.back=g.getAttribute("back");k.onEmpty=g.getAttribute("onEmpty");k.type=g.getAttribute("type");var p,m,r,q;k.k=[];var s=g.getElementsByTagName("item");for(p=0;m=s[p];p++){var u={};u.s=m.textContent;
if(m.attributes instanceof NamedNodeMap){r=m.attributes;q=r.length;for(m=0;m<q;m++){var t=r.item(m);u[t.nodeName]=t.value}}k.k.push(u)}k.p=[];s=g.getElementsByTagName("target");for(p=0;m=s[p];p++){g={};g.s=m.textContent;if(m.attributes instanceof NamedNodeMap){r=m.attributes;q=r.length;for(m=0;m<q;m++){t=r.item(m);g[t.nodeName]=t.value}}k.p.push(g)}d.zb.push(k)}d.p=[];var v=e.firstChild;for(c=0;e=v.childNodes[c];c++)if(e.tagName=="target"){g={};g.s=e.textContent;if(e.attributes instanceof NamedNodeMap){r=
e.attributes;q=r.length;for(m=0;m<q;m++){t=r.item(m);g[t.nodeName]=t.value}}d.p.push(g)}d.next=v.getAttribute("next");d.Qa=v.getAttribute("prev");if(b===i||typeof b=="undefined")this.Cb(d,b);else{c=new (function(C,z,A,B){b(v,z,A,B)});this.Cb(d,c)}};
l.Tc=function(){for(var a=this.Ia(),b="",d=0,c;c=a[d];d++)b=b+c.Z+", "+c.title+". ";b=b+this.ta+", "+o.a.ic;b=b+this.va+", "+o.a.nc;b=b.replace("PGUP",o.a.db);b=b.replace("PGDOWN",o.a.cb);b=b.replace("ENTER",o.a.T);b=b.replace("DEL",o.a.Ub);b=b.replace("UP",o.a.ja);b=b.replace("DOWN",o.a.fa);b=b.replace("LEFT",o.a.bb);return b=b.replace("RIGHT",o.a.eb)};
l.$c=function(){for(var a=this.Ka(),b="",d=0,c;c=a[d];d++)b=b+c.Z+", "+c.title+". ";a=this.P();if(a.Oa!=="")b=b+a.Oa+", "+o.a.Sb+". ";if(a.Ra!=="")b=b+a.Ra+", "+o.a.Tb+". ";if(a.Ga!=="")b=b+a.Ga+", "+o.a.$b+". ";if(a.Ca!=="")b=b+a.Ca+", "+o.a.Zb+". ";b=b.replace("PGUP",o.a.db);b=b.replace("PGDOWN",o.a.cb);b=b.replace("ENTER",o.a.T);b=b.replace("DEL",o.a.Ub);b=b.replace("UP",o.a.ja);b=b.replace("DOWN",o.a.fa);b=b.replace("LEFT",o.a.bb);return b=b.replace("RIGHT",o.a.eb)};l.sd=function(a){this.C=a};
l.ud=function(a){this.D=a};l.Jb=function(){if(this.w!==i){var a=this.Ia(),b=this.Ka();if(a.length+b.length===0)this.e.r(o.a.jc);else{var d=[],c=0,e="";for(c=0;e=b[c];c++)d.push(e.title);for(c=0;e=a[c];c++)d.push(e.title);this.w.qd(d);this.w.Lb("visible",h,40,20)}}};l.Ia=function(){for(var a=[],b,d=0,c;c=this.d[d];d++)if(c.Y!==""){b={};b.title=c.title;b.Z=c.Y;a.push(b)}for(d=0;c=this.da[d];d++)if(this.xb(c)){b={};b.title=c.title;b.Z=c.hotkey;a.push(b)}return a};
l.Ka=function(){for(var a=[],b=this.P(),d=0,c;c=b.p[d];d++)if(this.xb(c)){var e={};e.title=c.title;e.Z=c.hotkey;a.push(e)}return a};
l.Mc=function(){var a=this.e.v().body,b=this,d=function(c,e){var f=b.Ka(),g=b.Ia();f=f.concat(g);f=f[e].Z;f=f.split(" ")[0];var k=g=-1;if(f=="LEFT")g=37;else if(f=="UP")g=38;else if(f=="RIGHT")g=39;else if(f=="DOWN")g=40;else if(f=="PGUP")g=33;else if(f=="PGDOWN")g=34;else if(f=="ENTER")g=13;else if(f=="DEL")g=46;else if(f=="ESC")g=27;else k=f.charCodeAt(0);b.w.i.blur();(f=b.rb(g,k))&&f()};this.w.Lc(a,50,d,i,this.Kd,j);this.w.rd(o.a.rc);this.w.od(h);this.w.Ta()};
l.xb=function(a){var b=j;if(a.hotkey!==""){a=a.s;var d=this.e.v().body;if(a.indexOf(".")===0){var c=this.mb();if(c)d=c.j}a=this.e.L(a,d);if(a.length>0)b=h}return b};
l.Cb=function(a,b){this.d=[];this.b=0;this.g=[];var d=[],c,e;for(c=0;e=a.zb[c];c++){var f={};e.Ma=c;f.Nd=i;f.ba=e;f.title=e.title||"";f.Y=e.hotkey||"";f.Oa=e.next||"";f.Ra=e.Qa||"";f.Ga=e.Pc||"";f.Ca=e.back||"";f.onEmpty=e.onEmpty||"";f.type=e.type||"";f.Ya=i;f.La=i;f.Fa=i;f.k=this.ra(e);f.p=this.Bb(e);e=0;for(var g;g=f.p[e];e++)if(g.trigger=="listTail")f.Ya=g;else if(g.trigger=="listHead")f.La=g;else if(g.trigger=="listEntry")f.Fa=g;if(f.k.length>0||f.type=="dynamic"){this.d.push(f);this.g.push(-1)}else f.Y!==
""&&d.push(f)}this.da=[];this.Ud=0;if(a.p)for(c=0;f=a.p[c];c++){e={};e.s=f.s;e.s=e.s.replace(/^\s\s*/,"").replace(/\s\s*$/,"");e.title=f.title||"";e.trigger=f.trigger||"key";e.hotkey=f.hotkey||"";e.action=f.action||"click";e.onEmpty=f.onEmpty||"";this.da.push(e)}this.Q!==i&&document.removeEventListener("keypress",this.Q,h);b===i||typeof b=="undefined"?this.vd(a,d):b(a,this.d,d,this.da)};
l.ra=function(a){var b=[];if(!a.k)return b;for(var d=0,c;c=a.k[d];d++)try{var e=c.s.replace(/^\s\s*/,"").replace(/\s\s*$/,""),f=this.e.v().documentElement,g=this.e.L(e,f),k=c.index||"0",p=parseInt(k,10),m=g.length-p,r=c.Od||"*";if(r!="*")m=parseInt(r,10);for(var q=m+p,s=c.action||i;p<q;){c={};c.action=s;c.j=g[p];if(typeof c.j!="undefined"){if(typeof c.j.S=="undefined")c.j.S={};if(typeof a.Ma=="undefined")throw new Error("list does not have an id");c.j.S[a.Ma]=b.length;b.push(c)}p++}}catch(u){}return b};
l.Bb=function(a){var b=[];if(!a.p)return b;for(var d=0,c;c=a.p[d];d++){var e={};e.s=c.s.replace(/^\s\s*/,"").replace(/\s\s*$/,"");e.title=c.title||"";e.trigger=c.trigger||"key";e.hotkey=c.hotkey||"";e.action=c.action||"click";e.onEmpty=c.onEmpty||"";b.push(e)}return b};
l.vd=function(a,b){var d=this,c;this.I={};this.J={};this.K=[];this.G=[];var e;for(c=0;e=this.da[c];c++)this.hb(e,this.I,this.J);c=[];this.ta=a.next||"";if(this.ta!=="")c=this.ta.split(" ");this.t(c,this.I,this.J,function(){d.dd();d.nb()});c=[];this.va=a.Qa||"";if(this.va!=="")c=this.va.split(" ");this.t(c,this.I,this.J,function(){d.jd();d.nb()});var f;for(c=0;f=this.d[c];c++){var g={},k={};this.K.push(g);this.G.push(k);this.ma(f.Oa,c,"next");this.ma(f.Ra,c,"prev");this.ma(f.Ga,c,"fwd");this.ma(f.Ca,
c,"back");this.Fc(f.Y,c,f.onEmpty);var p;for(p=0;e=f.p[p];p++)this.hb(e,g,k)}for(c=0;e=b[c];c++)this.Ec(e.Y,e.onEmpty);this.Q=function(m){if(m.ctrlKey)return h;if(d.e.qa)return h;if(m=d.rb(m.keyCode,m.charCode))return m()};document.addEventListener("keypress",this.Q,h)};l.Ja=function(a){return a.ba.Ma};var w=function(a){this.l=a;this.aa=1.5;this.padding=-1;this.md=0;this.la=a.v();this.c=this.la.createElement("span");this.c.style.backgroundColor="#CCE6FF";this.c.style.borderColor="#0000CC";this.c.style.borderWidth="medium";this.c.style.borderStyle="groove";this.c.style.position="absolute";this.c.style.display="none";this.la.body.appendChild(this.c);this.jb=function(){}};w.sc={Hd:0,Xb:1};l=w.prototype;
l.view=function(a){for(;this.c.firstChild;)this.c.removeChild(this.c.firstChild);if(a===i)this.c.style.display="none";else{var b=0,d=0,c=a;if(c.offsetParent){b=c.offsetLeft;d=c.offsetTop;for(c=c.offsetParent;c!==i;){b+=c.offsetLeft;d+=c.offsetTop;c=c.offsetParent}}this.c.appendChild(a.cloneNode(h));this.c.style.top=d+"px";this.c.style.left=b+"px";this.c.style.zIndex=999;this.c.style.display="block";this.Ab()}};l.Ua=function(a){this.aa=a;this.Ab()};
l.Ab=function(){this.la.body.removeChild(this.c);this.ad();this.Nc();this.Bc();this.la.body.appendChild(this.c);this.jb&&this.jb(this.c);if(this.md==w.sc.Xb){var a=this;window.setTimeout(function(){a.c.scrollIntoView(h)},0)}};l.Bc=function(){if(!(this.padding<0)){var a="//*[not(.//*)]";a=this.l.L(a,this.c);for(var b=0,d;d=a[b];b++)d.style.padding=this.padding+"px"}};
l.Nc=function(){for(var a=this.c.getElementsByTagName("img"),b=0,d;d=a[b];b++){if(!d.hasAttribute("Axs_OrigHeight")){d.setAttribute("Axs_OrigHeight",d.height);d.setAttribute("Axs_OrigWidth",d.width)}d.height=d.getAttribute("Axs_OrigHeight")*this.aa;d.width=d.getAttribute("Axs_OrigWidth")*this.aa}};
l.ad=function(){var a="fontSizeAdjust"in this.c.style;if(a){var b=this.aa*0.52;this.c.style.fontSizeAdjust=b}else{b=this.aa*100+"%";this.c.style.setProperty("font-size",b,"important")}b=this.c.getElementsByTagName("*");for(var d=0,c;c=b[d];d++){c.style.setProperty("line-height","normal","important");a||c.style.setProperty("font-size","100%","important")}};var x=function(a){var b="http://google-axsjax.googlecode.com/svn/trunk/";this.Pd=b+"common/earcons/axsEarcons.swf?sound=";this.oa=i;this.ob=a;this.wd=b+"thirdparty/soundmanager2/";this.xd=i;this.wb=j;this.Vd="minimal";this.Md=j;this.Rd=0};x.prototype.play=function(){};x.prototype.stop=function(){if(this.oa){this.oa.parentNode.removeChild(this.oa);this.oa=i}if(!this.ob)if(this.wb)this.xd.src=this.wd+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Stop()"};
x.prototype.getTime=function(){if(this.ob)return-1;if(!this.wb)return-1;var a="Time=",b=unescape(document.location.hash);if(b.indexOf(a)==-1)return-1;a=b.indexOf(a)+a.length;return b=parseInt(b.substring(a),10)};var y=function(a,b){this.X=a;this.kb=this.n=this.u=this.i=this.q=i;this.na="Enter Completion";this.fd="No completions found";this.W=i;this.z=[];this.bd={};this.h=-1;this.Va=this.vb=j;this.Da="#000000";this.Ea=0;this.Yc={};this.pa={};this.Ld={};if(b&&y.M)this.W=b;var d=this;this.V(window,y.ya.pc,function(c){d.gd.call(d,c)},i)};y.Qb=/^\<[A-Z|a-z|0-9|\-|\_]+\>$/;y.cc=/^(\s|\r|\n)+/;y.qc=/(\s|\r|\n)+$/;l=y.prototype;
l.V=function(a,b,d,c){if(y.M&&d)a.addEventListener(b,d,h);else y.m&&d&&a.attachEvent(b,function(g){d(g)});if(c){var e=new y.$a(c),f=this;this.V(a,b,function(g){e.Xc(g,e,f)},i)}};
l.Lc=function(a,b,d,c,e,f){var g=this,k,p,m,r,q;this.q&&this.q.parentNode.removeChild(this.q);do{k="completionField_"+Math.floor(Math.random()*1001);p="txt_"+k;r="div_"+k;q="bgdiv_"+k;m=document.getElementById(k)}while(m);m=document.createElement("div");m.id=q;m.style.display="none";q=document.createElement("div");q.id=k;q.style.position="absolute";k=document.createElement("input");k.type="text";k.id=p;k.size=b;k.value="";k.setAttribute("aria-owns",r);if(y.M)k.onkeypress=function(s){s.stopPropagation();
if(s.keyCode==y.A.za)return j};if(k.readOnly=f)k.style.fontSize=0;b=document.createElement("div");b.id=r;b.setAttribute("tabindex",0);b.setAttribute("role","row");q.appendChild(b);q.appendChild(k);a.appendChild(m);a.appendChild(q);this.q=q;this.i=k;this.u=m;this.kb=b;this.q.className="pkHiddenStatus";this.i.className="pkOpaqueCompletionText";this.u.className="pkBackgroundHide";if(e){this.z=e;this.bd[this.X]=[e,this.na];this.f=this.z;for(a=0;e=this.z[a];a++)this.pa[e.toLowerCase()]=a;this.h=-1}this.V(this.i,
y.ya.ha,function(s){g.Wc.call(g,s,c,d)},i);this.V(this.i,y.ya.ga,function(s){g.Vc.call(g,s)},i);this.V(this.i,"blur",function(){g.vb&&g.Lb("hidden")},i)};l.od=function(a){this.vb=a};l.rd=function(a){this.na=a};l.qd=function(a){this.f=this.z=a;this.pa={};a=0;for(var b;b=this.z[a];a++)this.pa[b.toLowerCase()]=a;this.h=-1};
l.Lb=function(a,b,d,c){if(a=="visible"){this.q.className=="pkHiddenStatus"&&this.R(this.na);this.Wa(this.Va,this.Da,this.Ea);this.q.className="pkVisibleStatus";var e=this.i;window.setTimeout(function(){e.focus()},0)}else if(a=="hidden"){if(y.m&&this.n)this.n.innerText="";else if(this.n)if(y.m)this.n.innerText="";else this.n.textContent="";this.Wa(j,this.Da,this.Ea);this.q.className="pkHiddenStatus";this.i.value="";this.h=-1}if(b){a=y.tb();d||(d=a.height-this.q.offsetHeight);c||(c=0);this.q.style.top=
d;this.q.style.left=c}};l.gd=function(){var a=this;window.setTimeout(function(){a.Va&&a.u.style.display=="block"&&a.Wa(a.Va,a.Da,a.Ea)},0)};
l.Wc=function(a,b,d){if(this.i.value.length===0)this.f=this.z;if(a.keyCode!=y.A.ha&&a.keyCode!=y.A.ga&&a.keyCode!=y.A.T&&a.keyCode!=y.A.za)if(this.i.value.length){this.f=this.ub(this.z,this.i.value,50);this.h=-1;if(this.f.length>0){this.R(this.f[0]);this.h=0}else this.R(this.fd)}else this.R(this.na);if(a.keyCode==y.A.T)if(!this.i.readOnly){if(this.f&&this.f.length>0&&this.h>=0&&this.i.value!=this.f[this.h]&&(this.f[this.h].indexOf("<")<0||this.f[this.h].indexOf("<")>=0&&this.f[this.h].split(" ").length>
this.i.value.split(" ").length))this.Ib();var c=this.i.value;a=(y.m?this.n.innerText:this.n.textContent).toLowerCase();var e=a.indexOf("<"),f;if(e>=0){f=c.substr(0,e-1).toLowerCase();c=f+" "+c.substr(e)}else f=c=c.toLowerCase();e=j;if(b)e=this.zc.call(this,c,a,b);if(d&&!e){b=this.pb(c,a);d(f,this.pa[a],this.Yc[a],b)}this.i.value=""}};
l.Vc=function(a){if(a.keyCode==y.A.ha&&this.f&&this.f.length>0)this.kd();else if(a.keyCode==y.A.ga&&this.f&&this.f.length>0)this.ed();else a.keyCode==y.A.za&&this.f&&this.f.length>0&&this.Ib()};l.Wa=function(a,b,d){if(a){this.u.className="pkBackgroundShow";this.u.style.display="block";a=y.tb();this.u.style.width=a.width+"px";this.u.style.height=a.height+"px";if(b)this.u.style.backgroundColor=b;d&&this.u.style.setProperty("-moz-opacity",d/100,"")}else this.u.style.display="none"};
l.ub=function(a,b,d){for(var c=a,e=a,f=b.split(" "),g=0,k;k=f[g];g++){e=c;c=[];if(k!==""){k=y.ld(k);var p=new RegExp("(^|\\W+)"+k,"i");k=0;for(var m;m=e[k];k++)String(m).match(p)&&c.push(m)}}e=a;for(k=0;m=e[k];k++){a=m.split(" ");f=[];for(g=0;p=a[g];g++){if(p.charAt(0)=="<")break;f.push(p)}g=f.join(" ");b.indexOf(g)===0&&c.push(m)}c.length>d&&c.slice(0,d-1);return c};
l.pb=function(a,b){a=a.replace(/\s+/g," ");b=b.replace(/\s+/g," ");var d=b.indexOf("<");if(d<0)return[];b=b.substr(d);a=a.substr(d);d=a.split(",");var c=b.split(",");if(d.length!=c.length)return[];for(var e=[],f=0,g,k;(g=d[f])&&(k=c[f]);f++){g=y.yb(y.Gb(g));k=y.yb(y.Gb(k));k.match(y.Qb)&&e.push(g)}return e};l.zc=function(a,b,d){this.pb(a,b);if((a=d[b])&&a[this.X]){a=a[this.X]+"(args);";window.setTimeout(a,0);return h}else return j};
l.kd=function(){if(this.h<0)this.h=0;this.h=(this.h||this.f.length)-1;this.h>=0&&this.R(this.f[this.h])};l.ed=function(){this.h=(this.h+1)%this.f.length;this.h<this.f.length&&this.R(this.f[this.h])};l.Ib=function(){this.i.value=this.f[this.h>=0?this.h:0];this.f=this.ub(this.z,this.i.value,50);this.W&&y.M&&this.W.r(this.i.value);this.h=0};
l.R=function(a){if(!this.n){this.n=document.createElement("div");this.n.id="listElem_"+Math.floor(Math.random()*1001);this.kb.appendChild(this.n)}if(y.m)this.n.innerText=a;else this.n.textContent=a;this.W&&y.M&&this.W.Xa(this.n,j)};l.Ta=function(){y.Ta()};y.$a=function(a){this.Aa=a};
y.$a.prototype.Xc=function(a,b,d){if(b.Aa)if(a.keyCode){var c=""+a.keyCode,e=String.fromCharCode(a.keyCode).toLowerCase();if(a.ctrlKey){c="Ctrl+"+c;e="Ctrl+"+e}if(a.altKey){c="Alt+"+c;e="Alt+"+e}if(a.shiftKey){c="Shift+"+c;e="Shift+"+e}a=i;(a=b.Aa[e])||(a=b.Aa[c]);if(a)(b=a[d.X]?a[d.X]:a["*"])&&b()}};y.wc=function(a,b){this.width=a?a:undefined;this.height=b?b:undefined};y.yb=function(a){return a.replace(y.cc,"")};y.Gb=function(a){return a.replace(y.qc,"")};
y.ld=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
y.tb=function(){var a=0,b=0;if(typeof window.innerWidth=="number"){a=window.innerWidth;b=window.innerHeight}else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){a=document.documentElement.clientWidth;b=document.documentElement.clientHeight}else if(document.body&&(document.body.clientWidth||document.body.clientHeight)){a=document.body.clientWidth;b=document.body.clientHeight}return new y.wc(a,b)};y.m=j;y.M=j;
y.pd=function(){var a=navigator.userAgent.toLowerCase();y.M=a.indexOf("gecko")!=-1;y.m=a.indexOf("msie")!=-1&&a.indexOf("opera")==-1};y.pd();y.ya={ha:y.m?"onkeyup":"keyup",ga:y.m?"onkeydown":"keydown",Gd:y.m?"onkeypress":"keypress",Bd:y.m?"onclick":"click",pc:y.m?"onresize":"resize",Fd:y.m?"onfocus":"focus",Ad:y.m?"onblur":"blur"};y.lb=".pkHiddenStatus {display: none; position: absolute;}.pkVisibleStatus {display: block; position: absolute; left: 2px; top: 2px; line-height: 1.2em; z-index: 10001; background-color: #000000; padding: 2px; color: #fff; font-family: Arial, Sans-serif; font-size: 20px; filter: alpha(opacity=80); -moz-opacity: .80;}.pkOpaqueCompletionText {border-style: none; background-color:transparent; font-family: Arial, Helvetica, sans-serif; font-size: 35px; font-weight: bold; color: #fff; width: 1000px; height: 50px;}.pkBackgroundShow {position: absolute; width: 0px;height: 0px; background-color: #000000; filter: alpha(opacity=70);  -moz-opacity: .70; left: 0px; top: 0px; z-index: 10000;}";
y.Ta=function(){var a,b;if(a=document.getElementsByTagName("head")[0]){b=document.createElement("style");b.type="text/css";if(y.m)b.Td=y.lb;else if(y.M)b.innerHTML=y.lb;a.appendChild(b)}};y.Jd=function(a){var b=document.getElementsByTagName("head")[0],d=document.createElement("link");d.type="text/css";d.rel="stylesheet";d.href=a;b.appendChild(d)};y.A={ha:38,ga:40,T:13,za:9};var axsFinance={};axsFinance.a={ja:" up by ",vc:"+",fa:" down by ",Wb:"-",lc:" percent",mc:"%",ec:" million",fc:"M",Ob:" billion",Pb:"B",uc:"-",tc:"to",xc:"Fifty two week",yc:"52Wk",Mb:"Average volume",Nb:"Avg Vol:",hc:"-",gc:"Not available",Yb:"Google Finance Index",oc:"{0}, {1}, change {2}.",ac:"The following shortcut keys are available.",Vb:"- Disclaimer",kc:"or",ia:"PM",ea:"AM"};axsFinance.Id="id('md')//span[@class='pr']/..";axsFinance.H={};axsFinance.H[axsFinance.a.yc]=axsFinance.a.xc;
axsFinance.H[axsFinance.a.hc]=axsFinance.a.gc;axsFinance.H[axsFinance.a.Nb]=axsFinance.a.Mb;axsFinance.H[axsFinance.a.uc]=axsFinance.a.tc;axsFinance.H[axsFinance.a.ia]=axsFinance.a.ia;axsFinance.H[axsFinance.a.ea]=axsFinance.a.ea;axsFinance.Pa={};axsFinance.Pa[axsFinance.a.Wb]=axsFinance.a.fa;axsFinance.Pa[axsFinance.a.vc]=axsFinance.a.ja;axsFinance.xa={};axsFinance.xa[axsFinance.a.Pb]=axsFinance.a.Ob;axsFinance.xa[axsFinance.a.fc]=axsFinance.a.ec;axsFinance.xa[axsFinance.a.mc]=axsFinance.a.lc;
axsFinance.Rb='<cnr next="RIGHT l" prev="LEFT h"><target title="Markets" hotkey="m">(//li[@class="nav-item"])[1]//a</target><target title="News" hotkey="e">(//li[@class="nav-item"])[2]//a</target><target title="Portfolios" hotkey="o">(//li[@class="nav-item"])[3]//a</target><target title="Stock screener" hotkey="s">(//li[@class="nav-item"])[4]//a</target><target title="Google domestic trends" hotkey="g">(//li[@class="nav-item"])[5]//a</target><target title="Go to link" hotkey="ENTER">.//descendant-or-self::a</target><target title="Read current quote" hotkey="q" action="CALL:axsFinance.readCurrentQuote">id("price-panel")</target><target title="Create portfolio from quotes" hotkey="t" onEmpty="No recent quotes.">id("rq-create")</target><list title="Recent quotes" next="DOWN j" prev="UP k" fwd="n" back="p" type="dynamic" onEmpty="No recent quotes"><item action="CALL:axsFinance.readRecentQuote">id("rq")//tr</item></list><list title="Recent activity" next="DOWN j" prev="UP k" fwd="n" back="p" type="dynamic" onEmpty="No recent activities"><item>//li[@class="ra-entry"]//a</item></list><list title="Market data" next="DOWN j" prev="UP k" fwd="n" back="p"><item action="CALL:axsFinance.readMarketData">id("snap-data")/li</item></list><list title="News" next="DOWN j" prev="UP k" fwd="n" back="p" type="dynamic"><item>//div[@class="cluster"]</item><target title="View all news" hotkey="a">(id("news-sidebar-footer")//a[text()])[1]</target><target title="Subscribe" hotkey="u">(id("news-sidebar-footer")//a[text()])[2]</target></list><list title="Discussions" next="DOWN j" prev="UP k" fwd="n" back="p" type="dynamic"><item>id("groups")//div[@class="item"]</item><target title="All discussions" hotkey="a">//div[@class="sfe-break-top"]//a</target></list></cnr>';
axsFinance.l=i;axsFinance.F=i;axsFinance.O=i;axsFinance.ib=i;axsFinance.Eb=i;axsFinance.$=2.5;axsFinance.Hb=j;axsFinance.Ed=300;axsFinance.Qd={};
axsFinance.Zc=function(){axsFinance.l=new n(h);axsFinance.F=new o(axsFinance.l);axsFinance.F.cd(axsFinance.Rb,i);axsFinance.O=new w(axsFinance.l);axsFinance.F.sd(axsFinance.O);axsFinance.O.Ua(axsFinance.$);axsFinance.ib=new x(h);axsFinance.F.ud(axsFinance.ib);axsFinance.Eb=new y("list",axsFinance.l);axsFinance.F.td(axsFinance.Eb,".");document.addEventListener("keypress",axsFinance.Q,h);var a=document.getElementById("searchbox");a.addEventListener("focus",axsFinance.nd,j);axsFinance.Dc()};
axsFinance.readRecentQuote=function(a){a=a.j;var b="./td[not(.//b)]";b=axsFinance.l.L(b,a);for(var d=[],c=0,e=b.length;c<e;c++){d[c]=axsFinance.Sc(b[c]);d[c]=axsFinance.ua(d[c])}b=axsFinance.hd(axsFinance.a.oc,d);axsFinance.wa(a,b)};axsFinance.Sc=function(a){var b="",d='.//descendant-or-self::*[not(contains(@style,"display: none;"))]/text()';a=axsFinance.l.L(d,a);d=0;for(var c=a.length;d<c;d++)b=b+a[d].textContent+" ";return b};axsFinance.nd=function(a){if(!axsFinance.Hb){axsFinance.l.r(" ");a.target.blur()}};
axsFinance.Dc=function(){var a='id("companyheader")//h3';if(a=axsFinance.l.L(a,document.body)[0]){a=axsFinance.ua(a.textContent);a=axsFinance.a.Yb+". "+a;var b=axsFinance.sb();a=a+" "+b;b=document.getElementById("price-panel");axsFinance.wa(b,a)}};
axsFinance.sb=function(){var a=document.getElementById("price-panel");a=axsFinance.Db(a.textContent);a=a.replace(axsFinance.a.Vb,"");a=a.replace(axsFinance.a.ea," "+axsFinance.a.ea);a=a.replace(axsFinance.a.ia," "+axsFinance.a.ia);a=a.replace(" ("," "+axsFinance.a.kc+" ");return axsFinance.ua(a)};axsFinance.readMarketData=function(a){a=a.j;var b=axsFinance.ua(a.textContent);axsFinance.wa(a,b)};axsFinance.readCurrentQuote=function(a){var b=axsFinance.sb();axsFinance.wa(a.j,b)};
axsFinance.wa=function(a,b){axsFinance.O.view(a);axsFinance.l.r(b);a.scrollIntoView(h);axsFinance.l.sa(a)};axsFinance.hd=function(a,b){for(var d=new String(a),c=0;c<b.length;c++)d=d.replace("{"+c+"}",b[c]);return d};
axsFinance.ua=function(a){var b="";if(a==="")return a;a=axsFinance.Db(a);var d=axsFinance.H[a];if(d!=undefined)return d;a=a.split(" ");for(d=0;a[d];d++){var c=a[d],e=axsFinance.H[c];if(e!=undefined)c=e;else{if(c.length>0&&c.charAt(0)==="(")c=c.substring(1);if(c.length>1&&c.charAt(c.length-1)===")")c=c.substring(0,c.length-1);e=axsFinance.Pa[c.charAt(0)];if(e!=undefined)c=e+" "+c.substring(1);e=c.charAt(c.length-1);e=axsFinance.xa[e];if(e!=undefined)c=c.substring(0,c.length-1)+" "+e}b=b+" "+c}return b};
axsFinance.Db=function(a){a=a.replace(/^\s\s*/,"").replace(/\s\s*$/,"");a=a.replace(/\s+/g," ");return a.replace(/\n+/g,"").replace(/\r+/g,"")};axsFinance.Q=function(a){if(a.ctrlKey)return h;if(a.keyCode==27){axsFinance.l.B.blur();return j}if(axsFinance.l.qa)return h;a.charCode==46&&axsFinance.F.Jb();if(a=axsFinance.Ic[a.charCode])return a();return h};
axsFinance.Ic={47:function(){axsFinance.Hb=h;document.getElementById("searchbox").focus();document.getElementById("searchbox").select();return j},63:function(){var a=axsFinance.a.ac+axsFinance.F.$c()+axsFinance.F.Tc();axsFinance.l.r(a);return j},45:function(){axsFinance.$-=0.1;axsFinance.O.Ua(axsFinance.$);return j},61:function(){axsFinance.$+=0.1;axsFinance.O.Ua(axsFinance.$);return j}};window.addEventListener("load",axsFinance.Zc,h); })();
