(function() { var h=true,i=null,j=false,l,n=function(a){this.Rb=0;this.ca=i;this.Eb=j;this.D=i;this.oa=j;var b=this;this.xa=document.body;this.hc();if(a){this.Eb=h;document.addEventListener("keypress",function(d){b.kd(d,b)},h);document.body.ld=h}this.N(document.body,"role","application")};l=n.prototype;
l.hc=function(){var a=this.v(),b=this,d=function(c){b.D=c.target;if(c.target.tagName=="INPUT"||c.target.tagName=="SELECT"||c.target.tagName=="TEXTAREA")b.oa=h;return h};a.addEventListener("focus",d,h);d=function(c){b.Pa(b.D,"aria-activedescendant");b.D=i;if(c.target.tagName=="INPUT"||c.target.tagName=="SELECT"||c.target.tagName=="TEXTAREA")b.oa=j;return h};a.addEventListener("blur",d,h)};l.v=function(){for(var a=this.xa;a.nodeType!=9;)a=a.parentNode;return a};
l.Ua=function(a,b){a.id||this.cb(a);if(b){this.N(a,"live","rude");this.N(a,"atomic","true");var d=this.v();d=d.createElement("div");d.textContent=" ";d.name="AxsJAX_dummyNode";a.lastChild&&a.lastChild.name&&a.lastChild.name==d.name&&a.removeChild(a.lastChild);a.appendChild(d)}else{var c=this.zc(a,"role");this.N(a,"role","row");d=this.D;if(!d||d.nodeType==9){this.xa.tabIndex=-1;d=this.xa}this.N(d,"activedescendant",i);d.focus&&d.focus();this.N(d,"activedescendant",a.id);var e=this;window.setTimeout(function(){c?
e.N(a,"role",c):e.Pa(a,"role")},0)}};
l.q=function(a,b){var d="AxsJAX_pixelAudioNode",c="AxsJAX_pixelAudioNode",e="data:image/gif;base64,R0lGODlhAQABAIAAANvf7wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",f=this.v(),g=i;if(b){if(b.previousSibling&&b.previousSibling.name==c)g=b.previousSibling;else{g=f.createElement("img");g.name=c;g.setAttribute("tabindex",0);g.style.outline="none";g.src=e;b.parentNode.insertBefore(g,b);this.wc(g)}g.setAttribute("alt",a);g.setAttribute("title",a);window.setTimeout(function(){g.blur();g.focus()},0)}else{if((g=
f.getElementById(d))&&g.alt==a)a+=" ";if(!g){g=f.createElement("img");g.id=d;g.src=e;f.body.appendChild(g)}g.setAttribute("alt",a);g.setAttribute("title",a);this.Ua(g)}};
l.qc=function(a,b){var d=this.v(),c=d.createEvent("MouseEvents");c.initMouseEvent("mousedown",h,h,d.defaultView,1,0,0,0,0,j,j,b,j,0,i);try{a.dispatchEvent(c)}catch(e){}c=d.createEvent("MouseEvents");c.initMouseEvent("mouseup",h,h,d.defaultView,1,0,0,0,0,j,j,b,j,0,i);try{a.dispatchEvent(c)}catch(f){}c=d.createEvent("MouseEvents");c.initMouseEvent("click",h,h,d.defaultView,1,0,0,0,0,j,j,b,j,0,i);try{a.dispatchEvent(c)}catch(g){}d=a.getAttribute("href");if(a.tagName=="A"&&d&&d!="#")if(b)window.open(a.href);
else document.location=a.href};l.cb=function(a,b){if(!a)return"";if(a.id)return a.id;var d=b||"AxsJAX_ID_";a.id=d+this.Rb++;return a.id};l.qa=function(a){if(!a)return j;if(a.tagName=="A"||a.tagName=="INPUT"){this.ca=a;return h}a=a.getElementsByTagName("*");for(var b=0,d;d=a[b];b++)if(d.tagName=="A"||d.tagName=="INPUT"||d.hasAttribute("tabindex")&&d.tabIndex!=-1){this.ca=d;return h}return j};l.kd=function(a,b){if(!b.Eb)return h;if(a.keyCode==9&&b.ca){b.ca.focus();b.ca=i}return h};
l.Cc=function(a){this.Ua(a);a.scrollIntoView(h);this.qa(a)};l.N=function(a,b,d){if(a){b=b.toLowerCase();switch(b){case "live":b="aria-live";break;case "activedescendant":b="aria-activedescendant";break;case "atomic":b="aria-atomic";break;default:break}a.setAttribute(b,d)}};l.zc=function(a,b){return a.getAttribute(b)};l.Pa=function(a,b){a&&a.removeAttribute&&a.removeAttribute(b)};
l.wc=function(a){a=this.cb(a);var b=this.v(),d=b.baseURI,c=d.indexOf("#");if(c!=-1)d=d.substring(0,c);b.location=d+"#"+a};l.B=function(a,b){try{var d=b.ownerDocument.evaluate(a,b,i,XPathResult.ORDERED_NODE_ITERATOR_TYPE,i)}catch(c){return[]}for(var e=[],f=d.iterateNext();f;f=d.iterateNext())e.push(f);return e};n.Cd=function(a){window.addEventListener("load",function(){a()},h)};var o=function(a){this.sa=this.ra="";this.c=[];this.a=0;this.g=[];this.p=i;this.da=[];this.I={};this.J={};this.K=[];this.H=[];this.e=a;this.G=this.w=this.F=i;this.Tb="list";this.Xa="item";this.bb="wrap";this.Q=i};o.b={Vb:"next list",Yb:"previous list",Pb:"go forward",Ob:"go backwards",Jb:"cycle next",Kb:"cycle previous",bc:"Select available action",Xb:"No available actions",$a:"Page up",Za:"Page down",T:"Enter",pd:"Escape",od:"Delete",ha:"Up",ea:"Down",Ya:"Left",ab:"Right"};l=o.prototype;
l.cd=function(a,b){if(b){this.w=a;this.w.i===i&&this.tc();var d=this,c=new Array(b);this.t(c,this.I,this.J,function(){d.Db()})}};l.ta=function(a){var b=h;if(a.type=="dynamic"&&a.l.length===0){this.F!==i&&this.F.view(i);a.l=this.pa(a.ba);a.o=this.wb(a.ba);if(this.c[this.a]===a)this.g[this.a]=-1;else for(var d=0,c;c=this.c[d];d++)if(c===a){this.g[d]=-1;break}}if(a.l.length===0&&a.Ba===i)b=j;return b};
l.jb=function(){var a=this.P();a=a.Ba;var b=i;if(a!==i){this.ia(a);b=this.Da(a.action)}if(b===i){this.jc();this.G!==i&&this.G.play(this.Tb)}};l.Mc=function(){if(this.c.length<1)return i;for(var a=0;this.c[a];a++){this.a++;if(this.a>=this.c.length)this.a=0;if(this.ta(this.c[this.a]))break}return this.P()};l.Sc=function(){if(this.c.length<1)return i;for(var a=0;this.c[a];a++){this.a--;if(this.a<0)this.a=this.c.length-1;if(this.ta(this.c[this.a]))break}return this.P()};l.P=function(){return this.c[this.a]};
l.jc=function(){this.e.q(this.P().title)};l.Ja=function(){if(this.c.length<1)return i;var a=this.c[this.a],b=a.l;if(b.length<1)return i;if(this.p){var d=this.Fa(a);d=this.p.k.S[d];if(typeof d!="undefined")this.g[this.a]=d}this.g[this.a]++;d=j;if(this.g[this.a]>=b.length){this.g[this.a]=0;d=h}var c=this.g[this.a];if(b[c].k.parentNode===i){this.F!==i&&this.F.view(i);a.l=this.pa(a.ba);this.g[this.a]=0;c=this.g[this.a]}this.p=b[c];if(this.G!==i)d?this.G.play(this.bb):this.G.play(this.Xa);return this.p};
l.yc=function(){var a=this.c[this.a],b=this.g[this.a];if(a.Va!==i&&b+1>=a.l.length){this.ia(a.Va);this.g[this.a]=0;return i}return a=this.Ja()};
l.Ab=function(){if(this.c.length<1)return i;var a=this.c[this.a],b=a.l;if(b.length<1)return i;if(this.p){var d=this.Fa(a);d=this.p.k.S[d];if(typeof d!="undefined")this.g[this.a]=d}this.g[this.a]--;d=j;if(this.g[this.a]<0){this.g[this.a]=b.length-1;d=h}var c=this.g[this.a];if(b[c].k.parentNode===i){this.F!==i&&this.F.view(i);a.l=this.pa(a.ba);this.g[this.a]=a.l.length;c=this.g[this.a]}this.p=b[c];if(this.G!==i)d?this.G.play(this.bb):this.G.play(this.Xa);return this.p};
l.nc=function(){var a=this.c[this.a],b=this.g[this.a];if(a.Ha!==i&&b<=0){this.ia(a.Ha);this.g[this.a]=a.l.length-1;return i}return a=this.Ab()};l.ib=function(){if(this.c.length<1)return i;var a=this.c[this.a];if(this.p){var b=this.Fa(a);b=this.p.k.S[b];if(typeof b!="undefined")this.g[this.a]=b}a=a.l;b=this.g[this.a];return this.p=a[b]};l.Da=function(a){var b=i;if(a!==i&&a.indexOf&&a.indexOf("CALL:")===0&&a.indexOf("(")===-1)try{b=eval(a.substring(5))}catch(d){}return b};
l.U=function(a){if(a!==i){var b=this,d=function(){var f=b.Da(a.action);if(f)f(a);else{b.F!==i&&b.F.view(a.k);b.e.Cc(a.k)}};if(this.e.D&&this.e.D.blur){var c=this.e.D;this.e.D=i;c.removeAttribute&&this.e.Pa(c,"aria-activedescendant");var e=function(f){f.target.removeEventListener("blur",e,h);d()};c.addEventListener("blur",e,h);c.blur()}else d()}else{c=this.c[this.a];c.type=="dynamic"&&this.e.q(c.onEmpty)}};
l.t=function(a,b,d,c){for(var e=0,f;f=a[e];e++)if(f=="LEFT")d[37]=c;else if(f=="UP")d[38]=c;else if(f=="RIGHT")d[39]=c;else if(f=="DOWN")d[40]=c;else if(f=="PGUP")d[33]=c;else if(f=="PGDOWN")d[34]=c;else if(f=="ENTER")d[13]=c;else if(f=="ESC")d[27]=c;else if(f=="DEL")d[46]=c;else b[f.charCodeAt(0)]=c};
l.ka=function(a,b,d){var c=[];if(a!==""){c=a.split(" ");var e=this;if(d=="prev")this.t(c,this.K[b],this.H[b],function(){e.U(e.Ab())});else if(d=="next")this.t(c,this.K[b],this.H[b],function(){e.U(e.Ja())});else d=="back"?this.t(c,this.K[b],this.H[b],function(){var f=e.nc();f!==i&&e.U(f)}):this.t(c,this.K[b],this.H[b],function(){var f=e.yc();f!=i&&e.U(f)})}};l.mc=function(a,b,d){var c=[];if(a!==""){c=a.split(" ");var e=this;this.t(c,this.I,this.J,function(){if(e.ta(e.c[b])){e.a=b;e.U(e.Ja())}else e.e.q(d)})}};
l.lc=function(a,b){var d=[];if(a!==""){d=a.split(" ");var c=this;this.t(d,this.I,this.J,function(){c.e.q(b)})}};l.db=function(a,b,d){var c=[];if(a.hotkey!==""){c=a.hotkey.split(" ");var e=this;this.t(c,b,d,function(){e.ia(a)})}};l.ia=function(a){a.action=="click"?this.rc(a):this.oc(a)};l.oc=function(a){var b=this.mb(a);if(b.length<1)this.e.q(a.onEmpty);else{var d=this.Da(a.action);if(d){var c={};c.action=a.action;c.k=b[0];d(c);this.e.qa(b[0])}else throw new Error("Invalid action: "+a.action);}};
l.rc=function(a){var b=this.mb(a);if(b.length<1)this.e.q(a.onEmpty);else{this.e.qc(b[0],j);b[0].scrollIntoView(h);this.e.qa(b[0])}};l.mb=function(a){a=a.s;var b=this.e.v().documentElement;if(a.indexOf(".")===0)b=this.ib().k;return this.e.B(a,b)};l.nb=function(a,b){var d=i,c=this.a;if(c<this.H.length)d=this.H[c][a]||this.K[c][b]||i;if(d===i)d=this.J[a]||this.I[b];return d};
l.Lc=function(a,b){var d={};d.ub=[];var c=new DOMParser,e=c.parseFromString(a,"text/xml"),f=e.getElementsByTagName("list"),g;for(c=0;g=f[c];c++){var k={};k.title=g.getAttribute("title");k.hotkey=g.getAttribute("hotkey");k.next=g.getAttribute("next");k.Ma=g.getAttribute("prev");k.xc=g.getAttribute("fwd");k.back=g.getAttribute("back");k.onEmpty=g.getAttribute("onEmpty");k.type=g.getAttribute("type");var p,m,r,q;k.l=[];var s=g.getElementsByTagName("item");for(p=0;m=s[p];p++){var u={};u.s=m.textContent;
if(m.attributes instanceof NamedNodeMap){r=m.attributes;q=r.length;for(m=0;m<q;m++){var t=r.item(m);u[t.nodeName]=t.value}}k.l.push(u)}k.o=[];s=g.getElementsByTagName("target");for(p=0;m=s[p];p++){g={};g.s=m.textContent;if(m.attributes instanceof NamedNodeMap){r=m.attributes;q=r.length;for(m=0;m<q;m++){t=r.item(m);g[t.nodeName]=t.value}}k.o.push(g)}d.ub.push(k)}d.o=[];var v=e.firstChild;for(c=0;e=v.childNodes[c];c++)if(e.tagName=="target"){g={};g.s=e.textContent;if(e.attributes instanceof NamedNodeMap){r=
e.attributes;q=r.length;for(m=0;m<q;m++){t=r.item(m);g[t.nodeName]=t.value}}d.o.push(g)}d.next=v.getAttribute("next");d.Ma=v.getAttribute("prev");if(b===i||typeof b=="undefined")this.xb(d,b);else{c=new (function(C,z,A,B){b(v,z,A,B)});this.xb(d,c)}};
l.Bc=function(){for(var a=this.Ea(),b="",d=0,c;c=a[d];d++)b=b+c.Z+", "+c.title+". ";b=b+this.ra+", "+o.b.Vb;b=b+this.sa+", "+o.b.Yb;b=b.replace("PGUP",o.b.$a);b=b.replace("PGDOWN",o.b.Za);b=b.replace("ENTER",o.b.T);b=b.replace("DEL",o.b.Lb);b=b.replace("UP",o.b.ha);b=b.replace("DOWN",o.b.ea);b=b.replace("LEFT",o.b.Ya);return b=b.replace("RIGHT",o.b.ab)};
l.Ic=function(){for(var a=this.Ga(),b="",d=0,c;c=a[d];d++)b=b+c.Z+", "+c.title+". ";a=this.P();if(a.Ka!=="")b=b+a.Ka+", "+o.b.Jb+". ";if(a.Na!=="")b=b+a.Na+", "+o.b.Kb+". ";if(a.Ca!=="")b=b+a.Ca+", "+o.b.Pb+". ";if(a.ya!=="")b=b+a.ya+", "+o.b.Ob+". ";b=b.replace("PGUP",o.b.$a);b=b.replace("PGDOWN",o.b.Za);b=b.replace("ENTER",o.b.T);b=b.replace("DEL",o.b.Lb);b=b.replace("UP",o.b.ha);b=b.replace("DOWN",o.b.ea);b=b.replace("LEFT",o.b.Ya);return b=b.replace("RIGHT",o.b.ab)};l.bd=function(a){this.F=a};
l.dd=function(a){this.G=a};l.Uc=function(a){if(a===i)return j;var b=j;a=this.vc(a);if(a>-1){b=this.c[a];b.l=[];b.o=[];b=this.ta(b)}return b};l.Db=function(){if(this.w!==i){var a=this.Ea(),b=this.Ga();if(a.length+b.length===0)this.e.q(o.b.Xb);else{var d=[],c=0,e="";for(c=0;e=b[c];c++)d.push(e.title);for(c=0;e=a[c];c++)d.push(e.title);this.w.$c(d);this.w.Fb("visible",h,40,20)}}};
l.Ea=function(){for(var a=[],b,d=0,c;c=this.c[d];d++)if(c.Y!==""){b={};b.title=c.title;b.Z=c.Y;a.push(b)}for(d=0;c=this.da[d];d++)if(this.sb(c)){b={};b.title=c.title;b.Z=c.hotkey;a.push(b)}return a};l.Ga=function(){for(var a=[],b=this.P(),d=0,c;c=b.o[d];d++)if(this.sb(c)){var e={};e.title=c.title;e.Z=c.hotkey;a.push(e)}return a};
l.tc=function(){var a=this.e.v().body,b=this,d=function(c,e){var f=b.Ga(),g=b.Ea();f=f.concat(g);f=f[e].Z;f=f.split(" ")[0];var k=g=-1;if(f=="LEFT")g=37;else if(f=="UP")g=38;else if(f=="RIGHT")g=39;else if(f=="DOWN")g=40;else if(f=="PGUP")g=33;else if(f=="PGDOWN")g=34;else if(f=="ENTER")g=13;else if(f=="DEL")g=46;else if(f=="ESC")g=27;else k=f.charCodeAt(0);b.w.i.blur();(f=b.nb(g,k))&&f()};this.w.sc(a,50,d,i,this.vd,j);this.w.ad(o.b.bc);this.w.Yc(h);this.w.Qa()};
l.sb=function(a){var b=j;if(a.hotkey!==""){a=a.s;var d=this.e.v().body;if(a.indexOf(".")===0){var c=this.ib();if(c)d=c.k}a=this.e.B(a,d);if(a.length>0)b=h}return b};
l.xb=function(a,b){this.c=[];this.a=0;this.g=[];var d=[],c,e;for(c=0;e=a.ub[c];c++){var f={};e.Ia=c;f.yd=i;f.ba=e;f.title=e.title||"";f.Y=e.hotkey||"";f.Ka=e.next||"";f.Na=e.Ma||"";f.Ca=e.xc||"";f.ya=e.back||"";f.onEmpty=e.onEmpty||"";f.type=e.type||"";f.Va=i;f.Ha=i;f.Ba=i;f.l=this.pa(e);f.o=this.wb(e);e=0;for(var g;g=f.o[e];e++)if(g.trigger=="listTail")f.Va=g;else if(g.trigger=="listHead")f.Ha=g;else if(g.trigger=="listEntry")f.Ba=g;if(f.l.length>0||f.type=="dynamic"){this.c.push(f);this.g.push(-1)}else f.Y!==
""&&d.push(f)}this.da=[];this.Ed=0;if(a.o)for(c=0;f=a.o[c];c++){e={};e.s=f.s;e.s=e.s.replace(/^\s\s*/,"").replace(/\s\s*$/,"");e.title=f.title||"";e.trigger=f.trigger||"key";e.hotkey=f.hotkey||"";e.action=f.action||"click";e.onEmpty=f.onEmpty||"";this.da.push(e)}this.Q!==i&&document.removeEventListener("keypress",this.Q,h);b===i||typeof b=="undefined"?this.ed(a,d):b(a,this.c,d,this.da)};
l.pa=function(a){var b=[];if(!a.l)return b;for(var d=0,c;c=a.l[d];d++)try{var e=c.s.replace(/^\s\s*/,"").replace(/\s\s*$/,""),f=this.e.v().documentElement,g=this.e.B(e,f),k=c.index||"0",p=parseInt(k,10),m=g.length-p,r=c.zd||"*";if(r!="*")m=parseInt(r,10);for(var q=m+p,s=c.action||i;p<q;){c={};c.action=s;c.k=g[p];if(typeof c.k!="undefined"){if(typeof c.k.S=="undefined")c.k.S={};if(typeof a.Ia=="undefined")throw new Error("list does not have an id");c.k.S[a.Ia]=b.length;b.push(c)}p++}}catch(u){}return b};
l.wb=function(a){var b=[];if(!a.o)return b;for(var d=0,c;c=a.o[d];d++){var e={};e.s=c.s.replace(/^\s\s*/,"").replace(/\s\s*$/,"");e.title=c.title||"";e.trigger=c.trigger||"key";e.hotkey=c.hotkey||"";e.action=c.action||"click";e.onEmpty=c.onEmpty||"";b.push(e)}return b};
l.ed=function(a,b){var d=this,c;this.I={};this.J={};this.K=[];this.H=[];var e;for(c=0;e=this.da[c];c++)this.db(e,this.I,this.J);c=[];this.ra=a.next||"";if(this.ra!=="")c=this.ra.split(" ");this.t(c,this.I,this.J,function(){d.Mc();d.jb()});c=[];this.sa=a.Ma||"";if(this.sa!=="")c=this.sa.split(" ");this.t(c,this.I,this.J,function(){d.Sc();d.jb()});var f;for(c=0;f=this.c[c];c++){var g={},k={};this.K.push(g);this.H.push(k);this.ka(f.Ka,c,"next");this.ka(f.Na,c,"prev");this.ka(f.Ca,c,"fwd");this.ka(f.ya,
c,"back");this.mc(f.Y,c,f.onEmpty);var p;for(p=0;e=f.o[p];p++)this.db(e,g,k)}for(c=0;e=b[c];c++)this.lc(e.Y,e.onEmpty);this.Q=function(m){if(m.ctrlKey)return h;if(d.e.oa)return h;if(m=d.nb(m.keyCode,m.charCode))return m()};document.addEventListener("keypress",this.Q,h)};l.Fa=function(a){return a.ba.Ia};l.vc=function(a){for(var b=0;b<this.c.length;b++){var d=this.c[b];if(d.title==a)break}return b<this.c.length?b:-1};var w=function(a){this.j=a;this.aa=1.5;this.padding=-1;this.Xc=0;this.ja=a.v();this.d=this.ja.createElement("span");this.d.style.backgroundColor="#CCE6FF";this.d.style.borderColor="#0000CC";this.d.style.borderWidth="medium";this.d.style.borderStyle="groove";this.d.style.position="absolute";this.d.style.display="none";this.ja.body.appendChild(this.d);this.fb=function(){}};w.cc={sd:0,Nb:1};l=w.prototype;
l.view=function(a){for(;this.d.firstChild;)this.d.removeChild(this.d.firstChild);if(a===i)this.d.style.display="none";else{var b=0,d=0,c=a;if(c.offsetParent){b=c.offsetLeft;d=c.offsetTop;for(c=c.offsetParent;c!==i;){b+=c.offsetLeft;d+=c.offsetTop;c=c.offsetParent}}this.d.appendChild(a.cloneNode(h));this.d.style.top=d+"px";this.d.style.left=b+"px";this.d.style.zIndex=999;this.d.style.display="block";this.vb()}};l.Ra=function(a){this.aa=a;this.vb()};
l.vb=function(){this.ja.body.removeChild(this.d);this.Jc();this.uc();this.ic();this.ja.body.appendChild(this.d);this.fb&&this.fb(this.d);if(this.Xc==w.cc.Nb){var a=this;window.setTimeout(function(){a.d.scrollIntoView(h)},0)}};l.ic=function(){if(!(this.padding<0)){var a="//*[not(.//*)]";a=this.j.B(a,this.d);for(var b=0,d;d=a[b];b++)d.style.padding=this.padding+"px"}};
l.uc=function(){for(var a=this.d.getElementsByTagName("img"),b=0,d;d=a[b];b++){if(!d.hasAttribute("Axs_OrigHeight")){d.setAttribute("Axs_OrigHeight",d.height);d.setAttribute("Axs_OrigWidth",d.width)}d.height=d.getAttribute("Axs_OrigHeight")*this.aa;d.width=d.getAttribute("Axs_OrigWidth")*this.aa}};
l.Jc=function(){var a="fontSizeAdjust"in this.d.style;if(a){var b=this.aa*0.52;this.d.style.fontSizeAdjust=b}else{b=this.aa*100+"%";this.d.style.setProperty("font-size",b,"important")}b=this.d.getElementsByTagName("*");for(var d=0,c;c=b[d];d++){c.style.setProperty("line-height","normal","important");a||c.style.setProperty("font-size","100%","important")}};var x=function(a){var b="http://google-axsjax.googlecode.com/svn/trunk/";this.Ad=b+"common/earcons/axsEarcons.swf?sound=";this.ma=i;this.kb=a;this.fd=b+"thirdparty/soundmanager2/";this.gd=i;this.rb=j;this.Fd="minimal";this.xd=j;this.Bd=0};x.prototype.play=function(){};x.prototype.stop=function(){if(this.ma){this.ma.parentNode.removeChild(this.ma);this.ma=i}if(!this.kb)if(this.rb)this.gd.src=this.fd+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Stop()"};
x.prototype.getTime=function(){if(this.kb)return-1;if(!this.rb)return-1;var a="Time=",b=unescape(document.location.hash);if(b.indexOf(a)==-1)return-1;a=b.indexOf(a)+a.length;return b=parseInt(b.substring(a),10)};var y=function(a,b){this.X=a;this.gb=this.n=this.u=this.i=this.r=i;this.la="Enter Completion";this.Oc="No completions found";this.W=i;this.A=[];this.Kc={};this.h=-1;this.Sa=this.qb=j;this.za="#000000";this.Aa=0;this.Gc={};this.na={};this.wd={};if(b&&y.L)this.W=b;var d=this;this.V(window,y.ua.$b,function(c){d.Pc.call(d,c)},i)};y.Gb=/^\<[A-Z|a-z|0-9|\-|\_]+\>$/;y.Sb=/^(\s|\r|\n)+/;y.ac=/(\s|\r|\n)+$/;l=y.prototype;
l.V=function(a,b,d,c){if(y.L&&d)a.addEventListener(b,d,h);else y.m&&d&&a.attachEvent(b,function(g){d(g)});if(c){var e=new y.Wa(c),f=this;this.V(a,b,function(g){e.Fc(g,e,f)},i)}};
l.sc=function(a,b,d,c,e,f){var g=this,k,p,m,r,q;this.r&&this.r.parentNode.removeChild(this.r);do{k="completionField_"+Math.floor(Math.random()*1001);p="txt_"+k;r="div_"+k;q="bgdiv_"+k;m=document.getElementById(k)}while(m);m=document.createElement("div");m.id=q;m.style.display="none";q=document.createElement("div");q.id=k;q.style.position="absolute";k=document.createElement("input");k.type="text";k.id=p;k.size=b;k.value="";k.setAttribute("aria-owns",r);if(y.L)k.onkeypress=function(s){s.stopPropagation();
if(s.keyCode==y.C.va)return j};if(k.readOnly=f)k.style.fontSize=0;b=document.createElement("div");b.id=r;b.setAttribute("tabindex",0);b.setAttribute("role","row");q.appendChild(b);q.appendChild(k);a.appendChild(m);a.appendChild(q);this.r=q;this.i=k;this.u=m;this.gb=b;this.r.className="pkHiddenStatus";this.i.className="pkOpaqueCompletionText";this.u.className="pkBackgroundHide";if(e){this.A=e;this.Kc[this.X]=[e,this.la];this.f=this.A;for(a=0;e=this.A[a];a++)this.na[e.toLowerCase()]=a;this.h=-1}this.V(this.i,
y.ua.ga,function(s){g.Ec.call(g,s,c,d)},i);this.V(this.i,y.ua.fa,function(s){g.Dc.call(g,s)},i);this.V(this.i,"blur",function(){g.qb&&g.Fb("hidden")},i)};l.Yc=function(a){this.qb=a};l.ad=function(a){this.la=a};l.$c=function(a){this.f=this.A=a;this.na={};a=0;for(var b;b=this.A[a];a++)this.na[b.toLowerCase()]=a;this.h=-1};
l.Fb=function(a,b,d,c){if(a=="visible"){this.r.className=="pkHiddenStatus"&&this.R(this.la);this.Ta(this.Sa,this.za,this.Aa);this.r.className="pkVisibleStatus";var e=this.i;window.setTimeout(function(){e.focus()},0)}else if(a=="hidden"){if(y.m&&this.n)this.n.innerText="";else if(this.n)if(y.m)this.n.innerText="";else this.n.textContent="";this.Ta(j,this.za,this.Aa);this.r.className="pkHiddenStatus";this.i.value="";this.h=-1}if(b){a=y.ob();d||(d=a.height-this.r.offsetHeight);c||(c=0);this.r.style.top=
d;this.r.style.left=c}};l.Pc=function(){var a=this;window.setTimeout(function(){a.Sa&&a.u.style.display=="block"&&a.Ta(a.Sa,a.za,a.Aa)},0)};
l.Ec=function(a,b,d){if(this.i.value.length===0)this.f=this.A;if(a.keyCode!=y.C.ga&&a.keyCode!=y.C.fa&&a.keyCode!=y.C.T&&a.keyCode!=y.C.va)if(this.i.value.length){this.f=this.pb(this.A,this.i.value,50);this.h=-1;if(this.f.length>0){this.R(this.f[0]);this.h=0}else this.R(this.Oc)}else this.R(this.la);if(a.keyCode==y.C.T)if(!this.i.readOnly){if(this.f&&this.f.length>0&&this.h>=0&&this.i.value!=this.f[this.h]&&(this.f[this.h].indexOf("<")<0||this.f[this.h].indexOf("<")>=0&&this.f[this.h].split(" ").length>
this.i.value.split(" ").length))this.Cb();var c=this.i.value;a=(y.m?this.n.innerText:this.n.textContent).toLowerCase();var e=a.indexOf("<"),f;if(e>=0){f=c.substr(0,e-1).toLowerCase();c=f+" "+c.substr(e)}else f=c=c.toLowerCase();e=j;if(b)e=this.gc.call(this,c,a,b);if(d&&!e){b=this.lb(c,a);d(f,this.na[a],this.Gc[a],b)}this.i.value=""}};
l.Dc=function(a){if(a.keyCode==y.C.ga&&this.f&&this.f.length>0)this.Tc();else if(a.keyCode==y.C.fa&&this.f&&this.f.length>0)this.Nc();else a.keyCode==y.C.va&&this.f&&this.f.length>0&&this.Cb()};l.Ta=function(a,b,d){if(a){this.u.className="pkBackgroundShow";this.u.style.display="block";a=y.ob();this.u.style.width=a.width+"px";this.u.style.height=a.height+"px";if(b)this.u.style.backgroundColor=b;d&&this.u.style.setProperty("-moz-opacity",d/100,"")}else this.u.style.display="none"};
l.pb=function(a,b,d){for(var c=a,e=a,f=b.split(" "),g=0,k;k=f[g];g++){e=c;c=[];if(k!==""){k=y.Wc(k);var p=new RegExp("(^|\\W+)"+k,"i");k=0;for(var m;m=e[k];k++)String(m).match(p)&&c.push(m)}}e=a;for(k=0;m=e[k];k++){a=m.split(" ");f=[];for(g=0;p=a[g];g++){if(p.charAt(0)=="<")break;f.push(p)}g=f.join(" ");b.indexOf(g)===0&&c.push(m)}c.length>d&&c.slice(0,d-1);return c};
l.lb=function(a,b){a=a.replace(/\s+/g," ");b=b.replace(/\s+/g," ");var d=b.indexOf("<");if(d<0)return[];b=b.substr(d);a=a.substr(d);d=a.split(",");var c=b.split(",");if(d.length!=c.length)return[];for(var e=[],f=0,g,k;(g=d[f])&&(k=c[f]);f++){g=y.tb(y.Bb(g));k=y.tb(y.Bb(k));k.match(y.Gb)&&e.push(g)}return e};l.gc=function(a,b,d){this.lb(a,b);if((a=d[b])&&a[this.X]){a=a[this.X]+"(args);";window.setTimeout(a,0);return h}else return j};
l.Tc=function(){if(this.h<0)this.h=0;this.h=(this.h||this.f.length)-1;this.h>=0&&this.R(this.f[this.h])};l.Nc=function(){this.h=(this.h+1)%this.f.length;this.h<this.f.length&&this.R(this.f[this.h])};l.Cb=function(){this.i.value=this.f[this.h>=0?this.h:0];this.f=this.pb(this.A,this.i.value,50);this.W&&y.L&&this.W.q(this.i.value);this.h=0};
l.R=function(a){if(!this.n){this.n=document.createElement("div");this.n.id="listElem_"+Math.floor(Math.random()*1001);this.gb.appendChild(this.n)}if(y.m)this.n.innerText=a;else this.n.textContent=a;this.W&&y.L&&this.W.Ua(this.n,j)};l.Qa=function(){y.Qa()};y.Wa=function(a){this.wa=a};
y.Wa.prototype.Fc=function(a,b,d){if(b.wa)if(a.keyCode){var c=""+a.keyCode,e=String.fromCharCode(a.keyCode).toLowerCase();if(a.ctrlKey){c="Ctrl+"+c;e="Ctrl+"+e}if(a.altKey){c="Alt+"+c;e="Alt+"+e}if(a.shiftKey){c="Shift+"+c;e="Shift+"+e}a=i;(a=b.wa[e])||(a=b.wa[c]);if(a)(b=a[d.X]?a[d.X]:a["*"])&&b()}};y.fc=function(a,b){this.width=a?a:undefined;this.height=b?b:undefined};y.tb=function(a){return a.replace(y.Sb,"")};y.Bb=function(a){return a.replace(y.ac,"")};
y.Wc=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
y.ob=function(){var a=0,b=0;if(typeof window.innerWidth=="number"){a=window.innerWidth;b=window.innerHeight}else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){a=document.documentElement.clientWidth;b=document.documentElement.clientHeight}else if(document.body&&(document.body.clientWidth||document.body.clientHeight)){a=document.body.clientWidth;b=document.body.clientHeight}return new y.fc(a,b)};y.m=j;y.L=j;
y.Zc=function(){var a=navigator.userAgent.toLowerCase();y.L=a.indexOf("gecko")!=-1;y.m=a.indexOf("msie")!=-1&&a.indexOf("opera")==-1};y.Zc();y.ua={ga:y.m?"onkeyup":"keyup",fa:y.m?"onkeydown":"keydown",rd:y.m?"onkeypress":"keypress",nd:y.m?"onclick":"click",$b:y.m?"onresize":"resize",qd:y.m?"onfocus":"focus",md:y.m?"onblur":"blur"};y.hb=".pkHiddenStatus {display: none; position: absolute;}.pkVisibleStatus {display: block; position: absolute; left: 2px; top: 2px; line-height: 1.2em; z-index: 10001; background-color: #000000; padding: 2px; color: #fff; font-family: Arial, Sans-serif; font-size: 20px; filter: alpha(opacity=80); -moz-opacity: .80;}.pkOpaqueCompletionText {border-style: none; background-color:transparent; font-family: Arial, Helvetica, sans-serif; font-size: 35px; font-weight: bold; color: #fff; width: 1000px; height: 50px;}.pkBackgroundShow {position: absolute; width: 0px;height: 0px; background-color: #000000; filter: alpha(opacity=70);  -moz-opacity: .70; left: 0px; top: 0px; z-index: 10000;}";
y.Qa=function(){var a,b;if(a=document.getElementsByTagName("head")[0]){b=document.createElement("style");b.type="text/css";if(y.m)b.Dd=y.hb;else if(y.L)b.innerHTML=y.hb;a.appendChild(b)}};y.ud=function(a){var b=document.getElementsByTagName("head")[0],d=document.createElement("link");d.type="text/css";d.rel="stylesheet";d.href=a;b.appendChild(d)};y.C={ga:38,fa:40,T:13,va:9};var axsFinance={};axsFinance.b={ha:" up by ",ec:"+",ea:" down by ",Mb:"-",td:"-",dc:"to",Qb:"The following shortcut keys are available.",Zb:"{0}, {1}, change {2}.",Ib:"{0} with symbol {2} is traded on {1} for {3} which changed {4}. Market capitalization {5}.",Ub:"{0} with symbol {1} has net asset value {2} which changed {3}.",Wb:"not announced"};axsFinance.yb={};axsFinance.La={};axsFinance.La[axsFinance.b.Mb]=axsFinance.b.ea;axsFinance.La[axsFinance.b.ec]=axsFinance.b.ha;axsFinance.jd={};
axsFinance.Hb='<cnr next="RIGHT l" prev="LEFT h"><target title="Markets" hotkey="m">(//li[@class="nav-item"])[1]//a</target><target title="News" hotkey="e">(//li[@class="nav-item"])[2]//a</target><target title="Portfolios" hotkey="o">(//li[@class="nav-item"])[3]//a</target><target title="Stock screener" hotkey="s">(//li[@class="nav-item"])[4]//a</target><target title="Google domestic trends" hotkey="g">(//li[@class="nav-item"])[5]//a</target><target title="Show all" hotkey="a">//a[contains(@href,"restype=t")]</target><target title="Show companies" hotkey="c">//a[contains(@href,"restype=company")]</target><target title="Show funds" hotkey="f">//a[contains(@href,"restype=mutualfund")]</target><target title="Go to link" hotkey="ENTER">.//descendant-or-self::a</target><target title="Read index description" hotkey="r" action="CALL:axsFinance.readIndexDescription">id("page-content") | //div[@class="g-c"]/div[@class="g-wrap"]</target><list title="Domestic trends" next="DOWN j" prev="UP k" fwd="n" back="p"><item>//li[@class="navsub"]</item></list><list title="Recent quotes" next="DOWN j" prev="UP k" fwd="n" back="p" type="dynamic" onEmpty="No recent quotes"><item action="CALL:axsFinance.readRecentQuote">id("rq")//tr</item><target title="Create portfolio from quotes" hotkey="t" onEmpty="No recent quotes.">id("rq-create")</target></list><list title="Recent activity" next="DOWN j" prev="UP k" fwd="n" back="p" type="dynamic" onEmpty="No recent activities"><item>//li[@class="ra-entry"]//a</item></list><list title="Companies" next="DOWN j" prev="UP k" fwd="n" back="p" onEmpty="No companies"><item action="CALL:axsFinance.readCompany">id("company_results")/tbody/tr[not(@class="tptr")]</item><target title="Next page wrap" trigger="listTail">//div[@class="SP_arrow_next"]</target><target title="Previous page wrap" trigger="listHead">//div[@class="SP_arrow_previous"]</target><target title="Next page" hotkey="x">//div[@class="SP_arrow_next"]</target><target title="Previous page" hotkey="v">//div[@class="SP_arrow_previous"]</target><target title="First page" hotkey="[">//div[@class="SP_arrow_first"]</target><target title="Last page" hotkey="]">//div[@class="SP_arrow_last"]</target></list><list title="Mutual funds" next="DOWN j" prev="UP k" fwd="n" back="p" onEmpty="No mutual funds"><item action="CALL:axsFinance.readMutualFund">id("mf_results")/tbody/tr[not(@class="tptr")]</item><target title="Next page" trigger="listTail">//div[@class="SP_arrow_next"]</target><target title="Previous page" trigger="listHead">//div[@class="SP_arrow_previous"]</target><target title="Next page" hotkey="x">//div[@class="SP_arrow_next"]</target><target title="Previous page" hotkey="v">//div[@class="SP_arrow_previous"]</target><target title="First page" hotkey="[">//div[@class="SP_arrow_first"]</target><target title="Last page" hotkey="]">//div[@class="SP_arrow_last"]</target></list></cnr>';
axsFinance.j=i;axsFinance.z=i;axsFinance.O=i;axsFinance.eb=i;axsFinance.zb=i;axsFinance.$=2.5;
axsFinance.Hc=function(){axsFinance.j=new n(h);axsFinance.z=new o(axsFinance.j);axsFinance.z.Lc(axsFinance.Hb,i);axsFinance.O=new w(axsFinance.j);axsFinance.z.bd(axsFinance.O);axsFinance.O.Ra(axsFinance.$);axsFinance.eb=new x(h);axsFinance.z.dd(axsFinance.eb);axsFinance.zb=new y("list",axsFinance.j);axsFinance.z.cd(axsFinance.zb,".");document.addEventListener("keypress",axsFinance.Q,h);document.addEventListener("DOMNodeInserted",axsFinance.Vc,j);axsFinance.kc()};
axsFinance.kc=function(){var a="",b="//h3";b=axsFinance.j.B(b,document.body)[0];a=a+" "+axsFinance.M(b.textContent);b='id("results-header")/div[@class="g-unit g-first"]/span/text()';var d=axsFinance.j.B(b,document.body);b=0;for(var c;c=d[b];b++)a=a+" "+axsFinance.M(c.textContent);a+=".";b='id("results-header")/div[@class!="g-unit g-first"]';d=axsFinance.j.B(b,document.body);for(b=0;c=d[b];b++)a=a+" "+axsFinance.M(c.textContent);a=a.replace("- -","").replace(" - "," "+axsFinance.b.dc+" ");axsFinance.j.q(a)};
axsFinance.Vc=function(a){a.target.className==="d-quotes"&&axsFinance.z.Uc("Recent quotes")};axsFinance.readRecentQuote=function(a){axsFinance.Oa(a.k,"./td[not(.//b)]",axsFinance.b.Zb)};axsFinance.readCompany=function(a){axsFinance.Oa(a.k,'./td[@class!="asterisk lft"]',axsFinance.b.Ib)};axsFinance.readMutualFund=function(a){axsFinance.Oa(a.k,"./td",axsFinance.b.Ub)};
axsFinance.Oa=function(a,b,d){b=axsFinance.j.B(b,a);for(var c=[],e=0,f=b.length;e<f;e++){var g=axsFinance.Ac(b[e]);g=axsFinance.M(g);c[e]=g?axsFinance.Qc(g):axsFinance.b.Wb}d=axsFinance.Rc(d,c);axsFinance.hd(a,d)};axsFinance.Ac=function(a){var b="",d='.//descendant-or-self::*[not(contains(@style,"display: none;"))]/text()';a=axsFinance.j.B(d,a);d=0;for(var c=a.length;d<c;d++)b=b+a[d].textContent+" ";return axsFinance.M(b)};
axsFinance.readIndexDescription=function(a){a=a.k;a.focus();a=axsFinance.M(a.textContent);alert(a);axsFinance.j.q(a)};axsFinance.hd=function(a,b){axsFinance.O.view(a);axsFinance.j.q(b);a.scrollIntoView(h);axsFinance.j.qa(a)};axsFinance.Rc=function(a,b){for(var d=new String(a),c=0;c<b.length;c++)d=d.replace("{"+c+"}",b[c]);return d};
axsFinance.Qc=function(a){var b="";if(a==="")return a;a=axsFinance.M(a);var d=axsFinance.yb[a];if(d!=undefined)return d;a=a.split(" ");for(d=0;a[d];d++){var c=a[d],e=axsFinance.yb[c];if(e!=undefined)c=e;else{if(c.length>0&&c.charAt(0)==="(")c=c.substring(1);if(c.length>1&&c.charAt(c.length-1)===")")c=c.substring(0,c.length-1);e=axsFinance.La[c.charAt(0)];if(e!=undefined)c=e+" "+c.substring(1);e=c.charAt(c.length-1);e=axsFinance.jd[e];if(e!=undefined)c=c.substring(0,c.length-1)+" "+e}b=b+" "+c}return b};
axsFinance.M=function(a){a=a.replace(/^\s\s*/,"").replace(/\s\s*$/,"");a=a.replace(/\s+/g," ");return a.replace(/\n+/g,"").replace(/\r+/g,"")};axsFinance.Q=function(a){if(a.ctrlKey)return h;if(a.keyCode==27){axsFinance.j.D.blur();return j}if(axsFinance.j.oa)return h;a.charCode==46&&axsFinance.z.Db();if(a=axsFinance.pc[a.charCode])return a();return h};
axsFinance.pc={47:function(){document.getElementById("searchbox").focus();document.getElementById("searchbox").select();return j},63:function(){var a=axsFinance.b.Qb+axsFinance.z.Ic()+axsFinance.z.Bc();axsFinance.j.q(a);return j},45:function(){axsFinance.$-=0.1;axsFinance.O.Ra(axsFinance.$);return j},61:function(){axsFinance.$+=0.1;axsFinance.O.Ra(axsFinance.$);return j}};window.addEventListener("load",axsFinance.Hc,j); })();
