(function() { 
var h=false,i=null,j=true,m=function(a){this.hc=0;this.fa=i;this.Qb=h;this.F=i;this.qa=h;var b=this,d=function(e){b.F=e.target;if(e.target.tagName=="INPUT"||e.target.tagName=="SELECT"||e.target.tagName=="TEXTAREA")b.qa=j;return j};document.addEventListener("focus",d,j);var c=function(e){b.Va(b.F,"aria-activedescendant");b.F=i;if(e.target.tagName=="INPUT"||e.target.tagName=="SELECT"||e.target.tagName=="TEXTAREA")b.qa=h;return j};document.addEventListener("blur",c,j);if(a){this.Qb=j;document.addEventListener("keypress",
function(e){b.Gd(e,b)},j);document.body.Hd=j}this.Ca=document.body};m.prototype.C=function(){var a=this.Ca;while(a.nodeType!=9)a=a.parentNode;return a};
m.prototype.ab=function(a,b){a.id||this.mb(a);if(b){this.S(a,"live","rude");this.S(a,"atomic","true");var d=this.C(),c=d.createElement("div");c.textContent=" ";c.name="AxsJAX_dummyNode";a.lastChild&&a.lastChild.name&&a.lastChild.name==c.name&&a.removeChild(a.lastChild);a.appendChild(c)}else{var e=this.Zc(a,"role");this.S(a,"role","row");var f=this.F;if(!f||f.nodeType==9){this.Ca.tabIndex=-1;f=this.Ca}this.S(f,"activedescendant",i);f.focus();this.S(f,"activedescendant",a.id);var g=this;window.setTimeout(function(){e?
g.S(a,"role",e):g.Va(a,"role")},0)}};
m.prototype.A=function(a,b){var d="AxsJAX_pixelAudioNode",c="AxsJAX_pixelAudioNode",e="data:image/gif;base64,R0lGODlhAQABAIAAANvf7wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",f=this.C(),g=i;if(b){if(b.previousSibling&&b.previousSibling.name==c)g=b.previousSibling;else{g=f.createElement("img");g.name=c;g.setAttribute("tabindex",0);g.style.outline="none";g.src=e;b.parentNode.insertBefore(g,b);this.Tc(g)}g.setAttribute("alt",a);g.setAttribute("title",a);window.setTimeout(function(){g.blur();g.focus()},0)}else{g=
f.getElementById(d);if(g&&g.alt==a)a=a+" ";if(!g){g=f.createElement("img");g.id=d;g.src=e;f.body.appendChild(g)}g.setAttribute("alt",a);g.setAttribute("title",a);this.ab(g)}};
m.prototype.rb=function(a,b){var d=this.C(),c=d.createEvent("MouseEvents");c.initMouseEvent("mousedown",j,j,d.defaultView,1,0,0,0,0,h,h,b,h,0,i);try{a.dispatchEvent(c)}catch(e){}c=d.createEvent("MouseEvents");c.initMouseEvent("mouseup",j,j,d.defaultView,1,0,0,0,0,h,h,b,h,0,i);try{a.dispatchEvent(c)}catch(e){}c=d.createEvent("MouseEvents");c.initMouseEvent("click",j,j,d.defaultView,1,0,0,0,0,h,h,b,h,0,i);try{a.dispatchEvent(c)}catch(e){}if(a.tagName=="A"&&a.href&&(a.href.indexOf("http")===0||a.href.indexOf("javascript:")===
0))if(b)window.open(a.href);else document.location=a.href};m.prototype.mb=function(a,b){if(!a)return"";if(a.id)return a.id;var d=b||"AxsJAX_ID_";a.id=d+this.hc++;return a.id};m.prototype.Oa=function(a){if(!a)return h;if(a.tagName=="A"||a.tagName=="INPUT"){this.fa=a;return j}var b=a.getElementsByTagName("*");for(var d=0,c;c=b[d];d++)if(c.tagName=="A"||c.tagName=="INPUT"||c.hasAttribute("tabindex")&&c.tabIndex!=-1){this.fa=c;return j}return h};
m.prototype.Gd=function(a,b){if(!b.Qb)return j;if(a.keyCode==9&&b.fa){b.fa.focus();b.fa=i}return j};m.prototype.ad=function(a){this.ab(a);a.scrollIntoView(j);this.Oa(a)};m.prototype.S=function(a,b,d){if(!a)return;b=b.toLowerCase();switch(b){case "live":b="aria-live";break;case "activedescendant":b="aria-activedescendant";break;case "atomic":b="aria-atomic";break;default:break}a.setAttribute(b,d)};m.prototype.Zc=function(a,b){return a.getAttribute(b)};
m.prototype.Va=function(a,b){a&&a.removeAttribute&&a.removeAttribute(b)};m.prototype.Tc=function(a){var b=this.mb(a),d=this.C(),c=d.baseURI,e=c.indexOf("#");if(e!=-1)c=c.substring(0,e);d.location=c+"#"+b};m.prototype.O=function(a,b){try{var d=b.ownerDocument.evaluate(a,b,i,XPathResult.ORDERED_NODE_ITERATOR_TYPE,i)}catch(c){return[]}var e=[];for(var f=d.iterateNext();f;f=d.iterateNext())e.push(f);return e};var o=function(a){this.ta="";this.va="";this.c=[];this.a=0;this.d=[];this.o=i;this.ga=[];this.K={};this.L={};this.N=[];this.J=[];this.g=a;this.G=i;this.z=i;this.I=i;this.lc="list";this.gb="item";this.lb="wrap";this.R=i};o.b={qc:"next list",uc:"previous list",fc:"go forward",ec:"go backwards",Zb:"cycle next",$b:"cycle previous",xc:"Select available action",rc:"No available actions",jb:"Page up",ib:"Page down",V:"Enter",Ld:"Escape",Kd:"Delete",Aa:"Up",eb:"Down",hb:"Left",kb:"Right"};
o.prototype.Bd=function(a,b){if(b){this.z=a;this.z.i===i&&this.Oc();var d=this,c=new Array(b);this.u(c,this.K,this.L,function(){d.Ed()})}};o.prototype.db=function(a){var b=j;if(a.type=="dynamic"&&a.l.length===0){this.G!==i&&this.G.view(i);a.l=this.ra(a.ua);a.p=this.Ib(a.ua);if(this.c[this.a]===a)this.d[this.a]=-1;else for(var d=0,c;c=this.c[d];d++)if(c===a){this.d[d]=-1;break}}if(a.l.length===0&&a.Ha===i)b=h;return b};
o.prototype.ub=function(){var a=this.P(),b=a.Ha,d=i;if(b!==i){this.ja(b);d=this.Ja(b.action)}if(d===i){this.Gc();this.I!==i&&this.I.play(this.lc)}};o.prototype.md=function(){if(this.c.length<1)return i;for(var a=0;this.c[a];a++){this.a++;if(this.a>=this.c.length)this.a=0;if(this.db(this.c[this.a]))break}return this.P()};o.prototype.sd=function(){if(this.c.length<1)return i;for(var a=0;this.c[a];a++){this.a--;if(this.a<0)this.a=this.c.length-1;if(this.db(this.c[this.a]))break}return this.P()};
o.prototype.P=function(){return this.c[this.a]};o.prototype.Gc=function(){this.g.A(this.P().title)};
o.prototype.Qa=function(){if(this.c.length<1)return i;var a=this.c[this.a],b=a.l;if(b.length<1)return i;if(this.o){var d=this.o.k.U[this.a];if(typeof d!="undefined")this.d[this.a]=d}this.d[this.a]++;var c=h;if(this.d[this.a]>=b.length){this.d[this.a]=0;c=j}var e=this.d[this.a];if(b[e].k.parentNode===i){this.G!==i&&this.G.view(i);a.l=this.ra(a.ua);this.d[this.a]=0;e=this.d[this.a]}this.o=b[e];if(this.I!==i)c?this.I.play(this.lb):this.I.play(this.gb);return this.o};
o.prototype.Vc=function(){var a=this.c[this.a],b=this.d[this.a];if(a.bb!==i&&b+1>=a.l.length){this.ja(a.bb);this.d[this.a]=0;return i}var d=this.Qa();return d};
o.prototype.Nb=function(){if(this.c.length<1)return i;var a=this.c[this.a],b=a.l;if(b.length<1)return i;if(this.o){var d=this.o.k.U[this.a];if(typeof d!="undefined")this.d[this.a]=d}this.d[this.a]--;var c=h;if(this.d[this.a]<0){this.d[this.a]=b.length-1;c=j}var e=this.d[this.a];if(b[e].k.parentNode===i){this.G!==i&&this.G.view(i);a.l=this.ra(a.ua);this.d[this.a]=a.l.length;e=this.d[this.a]}this.o=b[e];if(this.I!==i)c?this.I.play(this.lb):this.I.play(this.gb);return this.o};
o.prototype.Jc=function(){var a=this.c[this.a],b=this.d[this.a];if(a.Ma!==i&&b-1<=-1){this.ja(a.Ma);this.d[this.a]=a.l.length;return i}var d=this.Nb();return d};o.prototype.tb=function(){if(this.c.length<1)return i;if(this.o){var a=this.o.k.U[this.a];if(typeof a!="undefined")this.d[this.a]=a}var b=this.c[this.a],d=b.l,c=this.d[this.a];this.o=d[c];return this.o};o.prototype.Ja=function(a){var b=i;if(a!==i&&a.indexOf&&a.indexOf("CALL:")===0&&a.indexOf("(")===-1)try{b=eval(a.substring(5))}catch(d){}return b};
o.prototype.W=function(a){if(a!==i){var b=this,d=function(){var g=b.Ja(a.action);if(g)g(a);else{b.G!==i&&b.G.view(a.k);b.g.ad(a.k)}};if(this.g.F&&this.g.F.blur){var c=this.g.F;this.g.F=i;c.removeAttribute&&this.g.Va(c,"aria-activedescendant");var e=function(g){g.target.removeEventListener("blur",e,j);d()};c.addEventListener("blur",e,j);c.blur()}else d()}else{var f=this.c[this.a];f.type=="dynamic"&&this.g.A(f.onEmpty)}};
o.prototype.u=function(a,b,d,c){for(var e=0,f;f=a[e];e++)if(f=="LEFT")d[37]=c;else if(f=="UP")d[38]=c;else if(f=="RIGHT")d[39]=c;else if(f=="DOWN")d[40]=c;else if(f=="PGUP")d[33]=c;else if(f=="PGDOWN")d[34]=c;else if(f=="ENTER")d[13]=c;else if(f=="ESC")d[27]=c;else if(f=="DEL")d[46]=c;else b[f.charCodeAt(0)]=c};
o.prototype.la=function(a,b,d){var c=[];if(a==="")return;c=a.split(" ");var e=this;if(d=="prev")this.u(c,this.N[b],this.J[b],function(){e.W(e.Nb())});else if(d=="next")this.u(c,this.N[b],this.J[b],function(){e.W(e.Qa())});else d=="back"?this.u(c,this.N[b],this.J[b],function(){e.W(e.Jc())}):this.u(c,this.N[b],this.J[b],function(){e.W(e.Vc())})};
o.prototype.Ic=function(a,b,d){var c=[];if(a==="")return;c=a.split(" ");var e=this;this.u(c,this.K,this.L,function(){if(!e.db(e.c[b])){e.g.A(d);return}e.a=b;e.W(e.Qa())})};o.prototype.Hc=function(a,b){var d=[];if(a==="")return;d=a.split(" ");var c=this;this.u(d,this.K,this.L,function(){c.g.A(b)})};o.prototype.nb=function(a,b,d){var c=[];if(a.hotkey==="")return;c=a.hotkey.split(" ");var e=this;this.u(c,b,d,function(){e.ja(a)})};
o.prototype.ja=function(a){var b=a.t,d=this.g.C().documentElement;if(b.indexOf(".")===0)d=this.tb().k;var c=this.g.O(b,d);if(c.length<1)this.g.A(a.onEmpty);else{var e=this.Ja(a.action);if(e){var f={};f.action=a.action;f.k=c[0];e(f)}else{this.g.rb(c[0],h);c[0].scrollIntoView(j)}this.g.Oa(c[0])}};o.prototype.wb=function(a,b){var d=i,c=this.a;if(c<this.J.length)d=this.J[c][a]||this.N[c][b]||i;if(d===i)d=this.L[a]||this.K[b];return d};
o.prototype.ld=function(a,b){var d={};d.Gb=[];var c=new DOMParser,e=c.parseFromString(a,"text/xml"),f=e.getElementsByTagName("list"),g,k;for(g=0,k;k=f[g];g++){var l={};l.title=k.getAttribute("title");l.hotkey=k.getAttribute("hotkey");l.Pa=k.getAttribute("next");l.Ta=k.getAttribute("prev");l.Uc=k.getAttribute("fwd");l.back=k.getAttribute("back");l.onEmpty=k.getAttribute("onEmpty");l.type=k.getAttribute("type");var n,p,q,r,s;l.l=[];var t=k.getElementsByTagName("item");for(n=0;p=t[n];n++){var x={};x.t=
p.textContent;if(p.attributes instanceof NamedNodeMap){r=p.attributes;s=r.length;for(q=0;q<s;q++){var w=r.item(q);x[w.nodeName]=w.value}}l.l.push(x)}l.p=[];var B=k.getElementsByTagName("target");for(n=0;p=B[n];n++){var v={};v.t=p.textContent;if(p.attributes instanceof NamedNodeMap){r=p.attributes;s=r.length;for(q=0;q<s;q++){var w=r.item(q);v[w.nodeName]=w.value}}l.p.push(v)}d.Gb.push(l)}d.p=[];var A,C=e.firstChild;for(g=0,A;A=C.childNodes[g];g++)if(A.tagName=="target"){var v={};v.t=A.textContent;
if(A.attributes instanceof NamedNodeMap){r=A.attributes;s=r.length;for(q=0;q<s;q++){var w=r.item(q);v[w.nodeName]=w.value}}d.p.push(v)}d.Pa=C.getAttribute("next");d.Ta=C.getAttribute("prev");if(b===i||typeof b=="undefined")this.Jb(d,b);else{var G=new (function(H,D,E,F){b(C,D,E,F)});this.Jb(d,G)}};
o.prototype.$c=function(){var a=this.Ka(),b="";for(var d=0,c;c=a[d];d++)b=b+c.da+", "+c.title+". ";b=b+this.ta+", "+o.b.qc;b=b+this.va+", "+o.b.uc;b=b.replace("PGUP",o.b.jb);b=b.replace("PGDOWN",o.b.ib);b=b.replace("ENTER",o.b.V);b=b.replace("DEL",o.b.cc);b=b.replace("UP",o.b.Aa);b=b.replace("DOWN",o.b.eb);b=b.replace("LEFT",o.b.hb);b=b.replace("RIGHT",o.b.kb);return b};
o.prototype.hd=function(){var a=this.La(),b="";for(var d=0,c;c=a[d];d++)b=b+c.da+", "+c.title+". ";var e=this.P();if(e.Ra!=="")b=b+e.Ra+", "+o.b.Zb+". ";if(e.Ua!=="")b=b+e.Ua+", "+o.b.$b+". ";if(e.Ia!=="")b=b+e.Ia+", "+o.b.fc+". ";if(e.Da!=="")b=b+e.Da+", "+o.b.ec+". ";b=b.replace("PGUP",o.b.jb);b=b.replace("PGDOWN",o.b.ib);b=b.replace("ENTER",o.b.V);b=b.replace("DEL",o.b.cc);b=b.replace("UP",o.b.Aa);b=b.replace("DOWN",o.b.eb);b=b.replace("LEFT",o.b.hb);b=b.replace("RIGHT",o.b.kb);return b};
o.prototype.Ad=function(a){this.G=a};o.prototype.Cd=function(a){this.I=a};o.prototype.Ed=function(){if(this.z===i)return;var a=this.Ka(),b=this.La();if(a.length+b.length===0){this.g.A(o.b.rc);return}var d=[],c=0,e="";for(c=0;e=b[c];c++)d.push(e.title);for(c=0;e=a[c];c++)d.push(e.title);this.z.yd(d);this.z.Rb("visible",j,40,20)};
o.prototype.Ka=function(){var a=[],b;for(var d=0,c;c=this.c[d];d++)if(c.ba!==""){b={};b.title=c.title;b.da=c.ba;a.push(b)}for(var e=0,f;f=this.ga[e];e++)if(this.Db(f)){b={};b.title=f.title;b.da=f.hotkey;a.push(b)}return a};o.prototype.La=function(){var a=[],b=this.P();for(var d=0,c;c=b.p[d];d++)if(this.Db(c)){var e={};e.title=c.title;e.da=c.hotkey;a.push(e)}return a};
o.prototype.Oc=function(){var a=this.g.C().body,b=this,d=function(c,e){var f=b.La(),g=b.Ka(),k=f.concat(g),l=k[e].da,n=l.split(" ")[0],p=-1,q=-1;if(n=="LEFT")p=37;else if(n=="UP")p=38;else if(n=="RIGHT")p=39;else if(n=="DOWN")p=40;else if(n=="PGUP")p=33;else if(n=="PGDOWN")p=34;else if(n=="ENTER")p=13;else if(n=="DEL")p=46;else if(n=="ESC")p=27;else q=n.charCodeAt(0);b.z.i.blur();var r=b.wb(p,q);r&&r()};this.z.Mc(a,50,d,i,this.Qd,h);this.z.zd(o.b.xc);this.z.wd(j);this.z.Wa()};
o.prototype.Db=function(a){var b=h;if(a.hotkey!==""){var d=a.t,c=this.g.C().body;if(d.indexOf(".")===0){var e=this.tb();if(e)c=e.k}var f=this.g.O(d,c);if(f.length>0)b=j}return b};
o.prototype.Jb=function(a,b){this.c=[];this.a=0;this.d=[];var d=[],c,e;for(c=0,e;e=a.Gb[c];c++){var f={};f.Sd=i;f.ua=e;f.title=e.title||"";f.ba=e.hotkey||"";f.Ra=e.Pa||"";f.Ua=e.Ta||"";f.Ia=e.Uc||"";f.Da=e.back||"";f.onEmpty=e.onEmpty||"";f.type=e.type||"";f.bb=i;f.Ma=i;f.Ha=i;f.l=this.ra(e);f.p=this.Ib(e);for(var g=0,k;k=f.p[g];g++)if(k.trigger=="listTail")f.bb=k;else if(k.trigger=="listHead")f.Ma=k;else if(k.trigger=="listEntry")f.Ha=k;if(f.l.length>0||f.type=="dynamic"){this.c.push(f);this.d.push(-1)}else f.ba!==
""&&d.push(f)}this.ga=[];this.$d=0;var l;if(a.p)for(c=0,l;l=a.p[c];c++){var n={};n.t=l.t;n.t=n.t.replace(/^\s\s*/,"").replace(/\s\s*$/,"");n.title=l.title||"";n.trigger=l.trigger||"key";n.hotkey=l.hotkey||"";n.action=l.action||"click";n.onEmpty=l.onEmpty||"";this.ga.push(n)}this.R!==i&&document.removeEventListener("keypress",this.R,j);b===i||typeof b=="undefined"?this.Dd(a,d):b(a,this.c,d,this.ga)};
o.prototype.ra=function(a){var b=[];if(!a.l)return b;for(var d=0,c;c=a.l[d];d++)try{var e=c.t.replace(/^\s\s*/,"").replace(/\s\s*$/,""),f=this.g.C().documentElement,g=this.g.O(e,f),k=c.index||"0",l=parseInt(k,10),n=g.length-l,p=c.Td||"*";if(p!="*")n=parseInt(p,10);var q=n+l,r=c.action||i;while(l<q){var s={};s.action=r;s.k=g[l];if(typeof s.k!="undefined"){if(typeof s.k.U=="undefined")s.k.U={};s.k.U[this.c.length]=b.length;b.push(s)}l++}}catch(t){}return b};
o.prototype.Ib=function(a){var b=[];if(!a.p)return b;for(var d=0,c;c=a.p[d];d++){var e={};e.t=c.t.replace(/^\s\s*/,"").replace(/\s\s*$/,"");e.title=c.title||"";e.trigger=c.trigger||"key";e.hotkey=c.hotkey||"";e.action=c.action||"click";e.onEmpty=c.onEmpty||"";b.push(e)}return b};
o.prototype.Dd=function(a,b){var d=this,c;this.K={};this.L={};this.N=[];this.J=[];var e;for(c=0,e;e=this.ga[c];c++)this.nb(e,this.K,this.L);var f=[];this.ta=a.Pa||"";if(this.ta!=="")f=this.ta.split(" ");this.u(f,this.K,this.L,function(){d.md();d.ub()});f=[];this.va=a.Ta||"";if(this.va!=="")f=this.va.split(" ");this.u(f,this.K,this.L,function(){d.sd();d.ub()});var g;for(c=0,g;g=this.c[c];c++){var k={},l={};this.N.push(k);this.J.push(l);this.la(g.Ra,c,"next");this.la(g.Ua,c,"prev");this.la(g.Ia,c,"fwd");
this.la(g.Da,c,"back");this.Ic(g.ba,c,g.onEmpty);var n;for(n=0,e;e=g.p[n];n++)this.nb(e,k,l)}var p;for(c=0,p;p=b[c];c++)this.Hc(p.ba,p.onEmpty);this.R=function(q){if(q.ctrlKey)return j;if(d.g.qa)return j;var r=d.wb(q.keyCode,q.charCode);if(r)return r()};document.addEventListener("keypress",this.R,j)};var u=function(a){this.j=a;this.sa=1.5;this.padding=-1;this.vd=0;this.ka=a.C();this.f=this.ka.createElement("span");this.f.style.backgroundColor="#CCE6FF";this.f.style.borderColor="#0000CC";this.f.style.borderWidth="medium";this.f.style.borderStyle="groove";this.f.style.position="absolute";this.f.style.display="none";this.ka.body.appendChild(this.f);this.pb=function(){}};u.Ac={Od:0,dc:1};
u.prototype.view=function(a){while(this.f.firstChild)this.f.removeChild(this.f.firstChild);if(a===i){this.f.style.display="none";return}var b=0,d=0,c=a;if(c.offsetParent){b=c.offsetLeft;d=c.offsetTop;c=c.offsetParent;while(c!==i){b+=c.offsetLeft;d+=c.offsetTop;c=c.offsetParent}}this.f.appendChild(a.cloneNode(j));this.f.style.top=d+"px";this.f.style.left=b+"px";this.f.style.zIndex=999;this.f.style.display="block";this.Hb()};u.prototype.Xa=function(a){this.sa=a;this.Hb()};
u.prototype.Hb=function(){this.ka.body.removeChild(this.f);this.jd();this.Rc();this.Ec();this.ka.body.appendChild(this.f);this.pb&&this.pb(this.f);if(this.vd==u.Ac.dc){var a=this;window.setTimeout(function(){a.f.scrollIntoView(j)},0)}};u.prototype.Ec=function(){if(this.padding<0)return;var a="//*[not(.//*)]",b=this.j.O(a,this.f);for(var d=0,c;c=b[d];d++)c.style.padding=this.padding+"px"};
u.prototype.Rc=function(){var a=this.f.getElementsByTagName("img");for(var b=0,d;d=a[b];b++){if(!d.hasAttribute("Axs_OrigHeight")){d.setAttribute("Axs_OrigHeight",d.height);d.setAttribute("Axs_OrigWidth",d.width)}d.height=d.getAttribute("Axs_OrigHeight")*this.sa;d.width=d.getAttribute("Axs_OrigWidth")*this.sa}};u.prototype.jd=function(){var a=this.sa*0.52;this.f.style.fontSizeAdjust=a;var b=this.f.getElementsByTagName("*");for(var d=0,c;c=b[d];d++)c.style.setProperty("line-height","normal","important")};var y=function(a){var b="http://google-axsjax.googlecode.com/svn/trunk/";this.Qc=b+"common/earcons/axsEarcons.swf?sound=";this.w=i;this.oa=a;this.$a=b+"thirdparty/soundmanager2/";this.m=i;this.Q=h;this.Sb="minimal";this.ma=h;this.Na=0};
y.prototype.Ab=function(){if(this.oa)return;if(this.Q)return;if(this.ma)return;this.ma=j;this.Na=0;if(this.m!==i){this.m.parentNode.removeChild(this.m);this.m=i}this.m=document.createElement("iframe");var a=document.location.toString();if(a.indexOf("#")!=-1)a=a.substring(0,a.indexOf("#"));this.m.src=this.$a+"AxsJAX_SM2_Linker.html#Verbosity="+this.Sb+",Parent="+a;this.m.width="0%";this.m.height="0%";this.m.style.top="-1000";this.m.style.left="-1000";this.m.style.position="absolute";document.getElementsByTagName("body")[0].appendChild(this.m);
this.qb()};y.prototype.qb=function(){if(document.location.hash=="#InitSuccess"){this.Q=j;this.ma=h;return}if(this.Sb=="none"&&this.Na>0){this.Q=j;this.ma=h;return}var a=this;window.setTimeout(function(){a.qb()},100);this.Na++};y.prototype.play=function(a){var b=this.rd(a);if(this.oa||b)return;if(!this.Q){this.Ab();var d=this;window.setTimeout(function(){d.play(a)},500);return}this.m.src=this.$a+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Play("+a+")"};
y.prototype.stop=function(){if(this.w){this.w.parentNode.removeChild(this.w);this.w=i}if(this.oa)return;if(!this.Q)return;this.m.src=this.$a+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Stop()"};y.prototype.getTime=function(){if(this.oa)return-1;if(!this.Q)return-1;var a="Time=",b=unescape(document.location.hash);if(b.indexOf(a)==-1)return-1;var d=b.indexOf(a)+a.length,c=parseInt(b.substring(d),10);return c};
y.prototype.rd=function(a){var b="";switch(a){case "alert":b="alert";break;case "deselect":b="deselect";break;case "item":b="item";break;case "list":b="list";break;case "select":b="select";break;case "success":b="success";break;case "wrap":b="wrap";break;default:}if(b==="")return;if(this.w===i){this.w=document.createElement("embed");this.w.height=0;this.w.width=0;document.body.appendChild(this.w)}this.w.src=this.Qc+b};var z=function(a,b){this.Z=a;this.r=i;this.i=i;this.v=i;this.n=i;this.sb=i;this.na="Enter Completion";this.od="No completions found";this.Y=i;this.B=[];this.kd={};this.h=-1;this.zb=h;this.Ya=h;this.Ea="#000000";this.Fa=0;this.ed={};this.pa={};this.Rd={};if(b&&z.ca)this.Y=b;var d=this;this.X(window,z.ya.vc,function(c){d.pd.call(d,c)},i)};z.Vb=/^\<[A-Z|a-z|0-9|\-|\_]+\>$/;z.kc=/^(\s|\r|\n)+/;z.wc=/(\s|\r|\n)+$/;
z.prototype.X=function(a,b,d,c){if(z.ca&&d)a.addEventListener(b,d,j);else z.s&&d&&a.attachEvent(b,function(g){d(g)});if(c){var e=new z.fb(c),f=this;this.X(a,b,function(g){e.dd(g,e,f)},i)}};
z.prototype.Mc=function(a,b,d,c,e,f){var g=this,k,l,n,p,q;this.r&&this.r.parentNode.removeChild(this.r);do{k="completionField_"+Math.floor(Math.random()*1001);l="txt_"+k;p="div_"+k;q="bgdiv_"+k;n=document.getElementById(k)}while(n);var r=document.createElement("div");r.id=q;r.style.display="none";var s=document.createElement("div");s.id=k;s.style.position="absolute";var t=document.createElement("input");t.type="text";t.id=l;t.size=b;t.value="";t.onkeypress=function(v){v.stopPropagation();if(v.keyCode==
z.D.za)return h};t.readOnly=f;if(f)t.style.fontSize=0;var x=document.createElement("div");x.id=p;x.setAttribute("tabindex",0);x.setAttribute("role","row");s.appendChild(x);s.appendChild(t);a.appendChild(r);a.appendChild(s);this.r=s;this.i=t;this.v=r;this.sb=x;this.r.className="pkHiddenStatus";this.i.className="pkOpaqueCompletionText";this.v.className="pkBackgroundHide";if(e){this.B=e;this.kd[this.Z]=[e,this.na];this.e=this.B;for(var w=0,B;B=this.B[w];w++)this.pa[B.toLowerCase()]=w;this.h=-1}this.X(this.i,
z.ya.ia,function(v){g.cd.call(g,v,c,d)},i);this.X(this.i,z.ya.ha,function(v){g.bd.call(g,v)},i);this.X(this.i,"blur",function(){g.zb&&g.Rb("hidden")},i)};z.prototype.wd=function(a){this.zb=a};z.prototype.zd=function(a){this.na=a};z.prototype.yd=function(a){this.B=a;this.e=this.B;this.pa={};for(var b=0,d;d=this.B[b];b++)this.pa[d.toLowerCase()]=b;this.h=-1};
z.prototype.Rb=function(a,b,d,c){if(a=="visible"){this.r.className=="pkHiddenStatus"&&this.T(this.na);this.Za(this.Ya,this.Ea,this.Fa);this.r.className="pkVisibleStatus";var e=this.i;window.setTimeout(function(){e.focus()},0)}else if(a=="hidden"){if(z.s&&this.n)this.n.innerText="";else if(this.n)this.n.textContent="";this.Za(h,this.Ea,this.Fa);this.r.className="pkHiddenStatus";this.i.value="";this.h=-1}if(b){var f=z.xb();d||(d=f.height-this.r.offsetHeight);c||(c=0);this.r.style.top=d;this.r.style.left=
c}};z.prototype.pd=function(){var a=this;window.setTimeout(function(){a.Ya&&a.v.style.display=="block"&&a.Za(a.Ya,a.Ea,a.Fa)},0)};
z.prototype.cd=function(a,b,d){if(this.i.value.length===0)this.e=this.B;if(a.keyCode!=z.D.ia&&a.keyCode!=z.D.ha&&a.keyCode!=z.D.V&&a.keyCode!=z.D.za)if(this.i.value.length){this.e=this.yb(this.B,this.i.value,50);this.h=-1;if(this.e.length>0){this.T(this.e[0]);this.h=0}else this.T(this.od)}else this.T(this.na);if(a.keyCode==z.D.V){if(this.i.readOnly)return;if(this.e&&this.e.length>0&&this.i.value!=this.e[this.h]&&(this.e[this.h].indexOf("<")<0||this.e[this.h].indexOf("<")>=0&&this.e[this.h].split(" ").length>
this.i.value.split(" ").length))this.Pb();var c=this.i.value,e=(z.s?this.n.innerText:this.n.textContent).toLowerCase(),f=e.indexOf("<"),g;if(f>=0){g=c.substr(0,f-1).toLowerCase();c=g+" "+c.substr(f)}else{c=c.toLowerCase();g=c}var k=h;if(b)k=this.Dc.call(this,c,e,b);if(d&&!k){var l=this.vb(c,e);d(g,this.pa[e],this.ed[e],l)}this.i.value=""}};
z.prototype.bd=function(a){if(a.keyCode==z.D.ia&&this.e&&this.e.length>0)this.td();else if(a.keyCode==z.D.ha&&this.e&&this.e.length>0)this.nd();else a.keyCode==z.D.za&&this.e&&this.e.length>0&&this.Pb()};z.prototype.Za=function(a,b,d){if(a){this.v.className="pkBackgroundShow";this.v.style.display="block";var c=z.xb();this.v.style.width=c.width+"px";this.v.style.height=c.height+"px";if(b)this.v.style.backgroundColor=b;d&&this.v.style.setProperty("-moz-opacity",d/100,"")}else this.v.style.display="none"};
z.prototype.yb=function(a,b,d){var c=a,e=a,f=b.split(" ");for(var g=0,k;k=f[g];g++){e=c;c=[];if(k!==""){var l=z.ud(k),n=new RegExp("(^|\\W+)"+l,"i");for(var p=0,q;q=e[p];p++)String(q).match(n)&&c.push(q)}}e=a;for(p=0;q=e[p];p++){var r=q.split(" "),s=[],t;for(g=0;t=r[g];g++){if(t.charAt(0)=="<")break;s.push(t)}var x=s.join(" ");b.indexOf(x)===0&&c.push(q)}c.length>d&&c.slice(0,d-1);return c};
z.prototype.vb=function(a,b){a=a.replace(/\s+/g," ");b=b.replace(/\s+/g," ");var d=b.indexOf("<");if(d<0)return[];b=b.substr(d);a=a.substr(d);var c=a.split(","),e=b.split(",");if(c.length!=e.length)return[];var f=[];for(var g=0,k,l;(k=c[g])&&(l=e[g]);g++){k=z.Eb(z.Ob(k));l=z.Eb(z.Ob(l));l.match(z.Vb)&&f.push(k)}return f};z.prototype.Dc=function(a,b,d){this.vb(a,b);var c=d[b];if(c&&c[this.Z]){var e=c[this.Z]+"(args);";window.setTimeout(e,0);return j}else return h};
z.prototype.td=function(){if(this.h<0)this.h=0;this.h=(this.h||this.e.length)-1;this.h>=0&&this.T(this.e[this.h])};z.prototype.nd=function(){this.h=(this.h+1)%this.e.length;this.h<this.e.length&&this.T(this.e[this.h])};z.prototype.Pb=function(){this.i.value=this.e[this.h>=0?this.h:0];this.e=this.yb(this.B,this.i.value,50);this.Y&&z.ca&&this.Y.A(this.i.value);this.h=0};
z.prototype.T=function(a){if(!this.n){this.n=document.createElement("div");this.n.id="listElem_"+Math.floor(Math.random()*1001);this.sb.appendChild(this.n)}if(z.s)this.n.innerText=a;else this.n.textContent=a;this.Y&&z.ca&&this.Y.ab(this.n,h)};z.prototype.Wa=function(){z.Wa()};z.fb=function(a){this.Ba=a};
z.fb.prototype.dd=function(a,b,d){if(!b.Ba)return;if(a.keyCode){var c=""+a.keyCode,e=String.fromCharCode(a.keyCode).toLowerCase();if(a.ctrlKey){c="Ctrl+"+c;e="Ctrl+"+e}if(a.altKey){c="Alt+"+c;e="Alt+"+e}if(a.shiftKey){c="Shift+"+c;e="Shift+"+e}var f=i;f=b.Ba[e];f||(f=b.Ba[c]);if(f){var g=f[d.Z]?f[d.Z]:f["*"];g&&g()}}};z.Bc=function(a,b){this.width=a?a:undefined;this.height=b?b:undefined};z.Eb=function(a){return a.replace(z.kc,"")};z.Ob=function(a){return a.replace(z.wc,"")};
z.ud=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
z.xb=function(){var a=0,b=0;if(typeof window.innerWidth=="number"){a=window.innerWidth;b=window.innerHeight}else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){a=document.documentElement.clientWidth;b=document.documentElement.clientHeight}else if(document.body&&(document.body.clientWidth||document.body.clientHeight)){a=document.body.clientWidth;b=document.body.clientHeight}return new z.Bc(a,b)};z.s=h;z.ca=h;
z.xd=function(){var a=navigator.userAgent.toLowerCase();z.ca=a.indexOf("gecko")!=-1;z.s=a.indexOf("msie")!=-1&&a.indexOf("opera")==-1};z.xd();z.ya={ia:z.s?"onkeyup":"keyup",ha:z.s?"onkeydown":"keydown",Nd:z.s?"onkeypress":"keypress",Jd:z.s?"onclick":"click",vc:z.s?"onresize":"resize",Md:z.s?"onfocus":"focus",Id:"blur"};z.Nc=".pkHiddenStatus {display: none; position: absolute;}.pkVisibleStatus {display: block; position: absolute; left: 2px; top: 2px; line-height: 1.2em; z-index: 10001; background-color: #000000; padding: 2px; color: #fff; font-family: Arial, Sans-serif; font-size: 20px; filter: alpha(opacity=80); -moz-opacity: .80;}.pkOpaqueCompletionText {border-style: none; background-color:transparent; font-family: Arial, Helvetica, sans-serif; font-size: 35px; font-weight: bold; color: #fff; width: 1000px; height: 50px;}.pkBackgroundShow {position: absolute; width: 0px;height: 0px; background-color: #000000; filter: alpha(opacity=70);  -moz-opacity: .70; left: 0px; top: 0px; z-index: 10000;}";
z.Wa=function(){var a,b;a=document.getElementsByTagName("head")[0];if(!a)return;b=document.createElement("style");b.type="text/css";b.innerHTML=z.Nc;a.appendChild(b)};z.D={ia:38,ha:40,V:13,za:9};var axsFinance={};axsFinance.b={Cc:'id("{0}")//tr[position() &gt;= {1} and position() &lt;= {2}]',nc:"03",mc:"March",jc:"06",ic:"June",zc:"09",yc:"September",bc:"12",ac:"December",tc:"-",sc:"Not available",Ub:"&",Tb:"and",pc:"-",oc:"minus "};axsFinance.Yb='<cnr next="RIGHT l" prev="LEFT h"><target title="Quarterly data" hotkey="q" onEmpty="Quarterly data already opened" action="CALL:axsFinance.storeCurrentPositionAndClickOnLink">id("interim")[@class="nac"]</target><target title="Annual data" hotkey="a" onEmpty="Annual data already opened" action="CALL:axsFinance.storeCurrentPositionAndClickOnLink">id("annual")[@class="nac"]</target><target title="Income statement" hotkey="i" onEmpty="Income statement already opened">id("inc")[@class="nac"]</target><target title="Balance sheet" hotkey="b" onEmpty="Balance sheet already opened">id("bal")[@class="nac"]</target><target title="Cash flow" hotkey="c" onEmpty="Cash flow already opened">id("cas")[@class="nac"]</target><target title="Stock screener" hotkey="s">//a[@class="screener-link"]</target>';
axsFinance.Wb='<list title="{0}" fwd="DOWN j n" back="UP k p"><item action="CALL:axsFinance.readTableRow">{1}</item></list>';axsFinance.Xb="</cnr>";axsFinance.Zd=-1;axsFinance.Vd=i;axsFinance.Wd="";axsFinance.Ud=h;axsFinance.H={};axsFinance.H[axsFinance.b.nc]=axsFinance.b.mc;axsFinance.H[axsFinance.b.jc]=axsFinance.b.ic;axsFinance.H[axsFinance.b.zc]=axsFinance.b.yc;axsFinance.H[axsFinance.b.bc]=axsFinance.b.ac;axsFinance.H[axsFinance.b.tc]=axsFinance.b.sc;axsFinance.H[axsFinance.b.Ub]=axsFinance.b.Tb;
axsFinance.Ga={};axsFinance.Ga[axsFinance.b.pc]=axsFinance.b.oc;axsFinance.Ga[axsFinance.b.Pd]=axsFinance.b.Aa;axsFinance.Lc={};axsFinance.gc="The following shortcut keys are available. ";axsFinance.aa={};axsFinance.xa=300;axsFinance.j=i;axsFinance.q=i;axsFinance.M=i;axsFinance.ob=i;axsFinance.Xd=i;axsFinance.Mb=i;axsFinance.ea=2.5;axsFinance.$=i;axsFinance.Yd=0;axsFinance.Fb="";axsFinance.wa="incinterimdiv";
axsFinance.Bb=function(){axsFinance.j=new m(j);axsFinance.M=new u(axsFinance.j);axsFinance.M.Xa(axsFinance.ea);axsFinance.ob=new y(j);axsFinance.q=new o(axsFinance.j);axsFinance.q.Ad(axsFinance.M);axsFinance.Mb=new z("list",axsFinance.j);axsFinance.Cb();axsFinance.q.Cd(axsFinance.ob);var a=axsFinance.R;document.addEventListener("keypress",a,j);a=axsFinance.Pc;document.addEventListener("DOMSubtreeModified",a,j)};
axsFinance.Cb=function(){var a=axsFinance.Yc();axsFinance.Fb=a;var b=axsFinance.Wc();axsFinance.q.ld(b);axsFinance.q.Bd(axsFinance.Mb,".")};axsFinance.Fc=function(){var a='//a[(@id="inc" or @id="bal" or @id="cas" or @id="interim" or @id="annual") and @class="ac"]',b=axsFinance.j.O(a,document.body),d=b[0].textContent,c=b[1].textContent,e=d+" "+c;axsFinance.j.A(e,i)};
axsFinance.storeCurrentPositionAndClickOnLink=function(a){var b=axsFinance.q.a,d=axsFinance.q.d[b],c={};c.gd=b;c.fd=d;axsFinance.$=c;var e=a.k;axsFinance.j.rb(e,h)};
axsFinance.Wc=function(){var a=axsFinance.Yb,b="",d="",c=2,e=0,f='id("'+axsFinance.wa+'")//tr',g=axsFinance.j.O(f,document.body);for(var k=0,l;l=g[k];k++)if(l.childNodes.length===1||k===g.length-1){e=k;if(l.childNodes.length>1||k===g.length-1)e++;d=g[k-1].childNodes[1].textContent;d=axsFinance.Lb(d);b=axsFinance.Xc(d,c,e);a=a+b;c=e+2}a=a+axsFinance.Xb;return a};
axsFinance.Xc=function(a,b,d){var c=new Array(axsFinance.wa,b,d),e=axsFinance.Sa(axsFinance.b.Cc,c);c=new Array(a,e);var f=axsFinance.Sa(axsFinance.Wb,c);return f};axsFinance.Yc=function(){var a='id("'+axsFinance.wa+'")//tr[@class="hdgr"]//td[not(@align)]',b=axsFinance.j.O(a,document.body),d="{0}, ";for(var c=0,e;e=b[c];c++){var f=e.textContent,g=f.lastIndexOf(" "),k=f.substring(g+1);f=f.substring(0,g);f=f+" "+axsFinance.qd(k);var l=c+1;d=d+f+", {"+l+"}. "}d=axsFinance.Kb(d);return d};
axsFinance.qd=function(a){var b=a.split("-"),d=b[0],c=b[1],e=axsFinance.H[c]+" "+d;return e};axsFinance.readTableRow=function(a){var b=a.k,d=[];for(var c=1,e;e=b.childNodes[c];c=c+2)d.push(axsFinance.Lb(e.textContent));var f=axsFinance.Sa(axsFinance.Fb,d);axsFinance.Fd(b,f)};
axsFinance.Pc=function(a){var b=a.target;if(b.id=="incinterimdiv"||b.id=="incannualdiv"||b.id=="balinterimdiv"||b.id=="balannualdiv"||b.id=="casinterimdiv"||b.id=="casannualdiv"){axsFinance.wa=b.id;var d=function(){axsFinance.Cb();axsFinance.Fc();if(axsFinance.$){var c=axsFinance.$.gd,e=axsFinance.$.fd;axsFinance.q.a=c;axsFinance.q.d[c]=e;axsFinance.$=i}axsFinance.M.view(i)};axsFinance.Sc(d,a)}};
axsFinance.Sc=function(a,b){if(axsFinance.aa[a.toString()]){b.cb=(new Date).getTime()+axsFinance.xa;axsFinance.aa[a.toString()]=b;return}b.cb=(new Date).getTime()+axsFinance.xa;axsFinance.aa[a.toString()]=b;var d=function(){var c=(new Date).getTime(),e=a.toString(),f=axsFinance.aa[e];if(f.cb>c)window.setTimeout(d,f.cb-c);else{a(f);axsFinance.aa[a.toString()]=i}};window.setTimeout(d,axsFinance.xa)};axsFinance.Fd=function(a,b){axsFinance.M.view(a);axsFinance.j.A(b);a.scrollIntoView(j);axsFinance.j.Oa(a)};
axsFinance.Sa=function(a,b){var d=new String(a);for(var c=0;c<b.length;c++){var e=new RegExp("{("+c+")}","g");d=d.replace(e,b[c])}return d};
axsFinance.Lb=function(a){var b="";if(a==="")return a;a=axsFinance.Kb(a);var d=axsFinance.H[a];if(d!=undefined)return d;var c=a.split(" ");for(var e=0;c[e];e++){var f=c[e],g=axsFinance.H[f];if(g!=undefined)f=g;else{if(f.length>0&&f.charAt(0)==="(")f=f.substring(1);if(f.length>1&&f.charAt(f.length-1)===")")f=f.substring(0,f.length-1);var k=axsFinance.Ga[f.charAt(0)];if(k!=undefined)f=k+" "+f.substring(1);var l=f.charAt(f.length-1),n=axsFinance.Lc[l];if(n!=undefined)f=f.substring(0,f.length-1)+" "+
n}b=b+" "+f}return b};axsFinance.Kb=function(a){a=a.replace(/^\s\s*/,"").replace(/\s\s*$/,"");a=a.replace(/\s+/g," ");return a.replace(/\n+/g,"").replace(/\r+/g,"")};axsFinance.R=function(a){if(a.ctrlKey)return j;if(a.keyCode==27){axsFinance.j.F.blur();return h}if(axsFinance.j.qa)return j;var b=axsFinance.Kc[a.charCode];if(b)return b();return j};
axsFinance.Kc={47:function(){document.getElementById("searchbox").focus();document.getElementById("searchbox").select();return h},63:function(){var a=axsFinance.gc+axsFinance.q.hd()+axsFinance.q.$c();axsFinance.j.A(a);return h},45:function(){axsFinance.ea-=0.1;axsFinance.M.Xa(axsFinance.ea);return h},61:function(){axsFinance.ea+=0.1;axsFinance.M.Xa(axsFinance.ea);return h}};axsFinance.Ab=function(a){a.target.className=="nav"&&axsFinance.Bb()};window.addEventListener("load",axsFinance.Bb,j);
 })();
