(function() { 
var h=false,i=null,j=true,k=function(a){this.ec=0;this.da=i;this.Ob=h;this.p=i;this.R=h;var b=this,d=function(e){b.p=e.target;if(e.target.tagName=="INPUT"||e.target.tagName=="SELECT"||e.target.tagName=="TEXTAREA")b.R=j;return j};document.addEventListener("focus",d,j);var c=function(e){b.Xa(b.p,"aria-activedescendant");b.p=i;if(e.target.tagName=="INPUT"||e.target.tagName=="SELECT"||e.target.tagName=="TEXTAREA")b.R=h;return j};document.addEventListener("blur",c,j);if(a){this.Ob=j;document.addEventListener("keypress",
function(e){b.rd(e,b)},j);document.body.sd=j}this.Ca=document.body};k.prototype.D=function(){var a=this.Ca;while(a.nodeType!=9)a=a.parentNode;return a};
k.prototype.cb=function(a,b){a.id||this.la(a);if(b){this.S(a,"live","rude");this.S(a,"atomic","true");var d=this.D(),c=d.createElement("div");c.textContent=" ";c.name="AxsJAX_dummyNode";a.lastChild&&a.lastChild.name&&a.lastChild.name==c.name&&a.removeChild(a.lastChild);a.appendChild(c)}else{var e=this.Kc(a,"role");this.S(a,"role","row");var f=this.p;if(!f||f.nodeType==9){this.Ca.tabIndex=-1;f=this.Ca}this.S(f,"activedescendant",i);f.focus();this.S(f,"activedescendant",a.id);var g=this;window.setTimeout(function(){e?
g.S(a,"role",e):g.Xa(a,"role")},0)}};
k.prototype.n=function(a,b){var d="AxsJAX_pixelAudioNode",c="AxsJAX_pixelAudioNode",e="data:image/gif;base64,R0lGODlhAQABAIAAANvf7wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",f=this.D(),g=i;if(b){if(b.previousSibling&&b.previousSibling.name==c)g=b.previousSibling;else{g=f.createElement("img");g.name=c;g.setAttribute("tabindex",0);g.style.outline="none";g.src=e;b.parentNode.insertBefore(g,b);this.Hc(g)}g.setAttribute("alt",a);g.setAttribute("title",a);window.setTimeout(function(){g.blur();g.focus()},0)}else{g=
f.getElementById(d);if(g&&g.alt==a)a=a+" ";if(!g){g=f.createElement("img");g.id=d;g.src=e;f.body.appendChild(g)}g.setAttribute("alt",a);g.setAttribute("title",a);this.cb(g)}};
k.prototype.Bc=function(a,b){var d=this.D(),c=d.createEvent("MouseEvents");c.initMouseEvent("mousedown",j,j,d.defaultView,1,0,0,0,0,h,h,b,h,0,i);try{a.dispatchEvent(c)}catch(e){}c=d.createEvent("MouseEvents");c.initMouseEvent("mouseup",j,j,d.defaultView,1,0,0,0,0,h,h,b,h,0,i);try{a.dispatchEvent(c)}catch(e){}c=d.createEvent("MouseEvents");c.initMouseEvent("click",j,j,d.defaultView,1,0,0,0,0,h,h,b,h,0,i);try{a.dispatchEvent(c)}catch(e){}if(a.tagName=="A"&&a.href&&(a.href.indexOf("http")===0||a.href.indexOf("javascript:")===
0))if(b)window.open(a.href);else document.location=a.href};k.prototype.la=function(a,b){if(!a)return"";if(a.id)return a.id;var d=b||"AxsJAX_ID_";a.id=d+this.ec++;return a.id};k.prototype.sa=function(a){if(!a)return h;if(a.tagName=="A"||a.tagName=="INPUT"){this.da=a;return j}var b=a.getElementsByTagName("*");for(var d=0,c;c=b[d];d++)if(c.tagName=="A"||c.tagName=="INPUT"||c.hasAttribute("tabindex")&&c.tabIndex!=-1){this.da=c;return j}return h};
k.prototype.rd=function(a,b){if(!b.Ob)return j;if(a.keyCode==9&&b.da){b.da.focus();b.da=i}return j};k.prototype.Mc=function(a){this.cb(a);a.scrollIntoView(j);this.sa(a)};k.prototype.S=function(a,b,d){if(!a)return;b=b.toLowerCase();switch(b){case "live":b="aria-live";break;case "activedescendant":b="aria-activedescendant";break;case "atomic":b="aria-atomic";break;default:break}a.setAttribute(b,d)};k.prototype.Kc=function(a,b){return a.getAttribute(b)};
k.prototype.Xa=function(a,b){a&&a.removeAttribute&&a.removeAttribute(b)};k.prototype.Hc=function(a){var b=this.la(a),d=this.D(),c=d.baseURI,e=c.indexOf("#");if(e!=-1)c=c.substring(0,e);d.location=c+"#"+b};k.prototype.P=function(a,b){try{var d=b.ownerDocument.evaluate(a,b,i,XPathResult.ORDERED_NODE_ITERATOR_TYPE,i)}catch(c){return[]}var e=[];for(var f=d.iterateNext();f;f=d.iterateNext())e.push(f);return e};var o=function(a){this.ua="";this.ya="";this.c=[];this.a=0;this.g=[];this.q=i;this.ea=[];this.K={};this.L={};this.N=[];this.I=[];this.h=a;this.G=i;this.A=i;this.H=i;this.gc="list";this.hb="item";this.nb="wrap";this.J=i};o.b={hc:"next list",lc:"previous list",cc:"go forward",bc:"go backwards",Wb:"cycle next",Xb:"cycle previous",oc:"Select available action",ic:"No available actions",lb:"Page up",kb:"Page down",V:"Enter",wd:"Escape",vd:"Delete",ia:"Up",fa:"Down",ib:"Left",mb:"Right"};
o.prototype.md=function(a,b){if(b){this.A=a;this.A.j===i&&this.Ec();var d=this,c=new Array(b);this.v(c,this.K,this.L,function(){d.pd()})}};o.prototype.eb=function(a){var b=j;if(a.type=="dynamic"&&a.l.length===0){this.G!==i&&this.G.view(i);a.l=this.ra(a.wa);a.r=this.Gb(a.wa);if(this.c[this.a]===a)this.g[this.a]=-1;else for(var d=0,c;c=this.c[d];d++)if(c===a){this.g[d]=-1;break}}if(a.l.length===0&&a.Ja===i)b=h;return b};
o.prototype.vb=function(){var a=this.O(),b=a.Ja,d=i;if(b!==i){this.ja(b);d=this.La(b.action)}if(d===i){this.vc();this.H!==i&&this.H.play(this.gc)}};o.prototype.Wc=function(){if(this.c.length<1)return i;for(var a=0;this.c[a];a++){this.a++;if(this.a>=this.c.length)this.a=0;if(this.eb(this.c[this.a]))break}return this.O()};o.prototype.ad=function(){if(this.c.length<1)return i;for(var a=0;this.c[a];a++){this.a--;if(this.a<0)this.a=this.c.length-1;if(this.eb(this.c[this.a]))break}return this.O()};
o.prototype.O=function(){return this.c[this.a]};o.prototype.vc=function(){this.h.n(this.O().title)};
o.prototype.Ta=function(){if(this.c.length<1)return i;var a=this.c[this.a],b=a.l;if(b.length<1)return i;if(this.q){var d=this.q.k.U[this.a];if(typeof d!="undefined")this.g[this.a]=d}this.g[this.a]++;var c=h;if(this.g[this.a]>=b.length){this.g[this.a]=0;c=j}var e=this.g[this.a];if(b[e].k.parentNode===i){this.G!==i&&this.G.view(i);a.l=this.ra(a.wa);this.g[this.a]=0;e=this.g[this.a]}this.q=b[e];if(this.H!==i)c?this.H.play(this.nb):this.H.play(this.hb);return this.q};
o.prototype.Jc=function(){var a=this.c[this.a],b=this.g[this.a];if(a.db!==i&&b+1>=a.l.length){this.ja(a.db);this.g[this.a]=0;return i}var d=this.Ta();return d};
o.prototype.Kb=function(){if(this.c.length<1)return i;var a=this.c[this.a],b=a.l;if(b.length<1)return i;if(this.q){var d=this.q.k.U[this.a];if(typeof d!="undefined")this.g[this.a]=d}this.g[this.a]--;var c=h;if(this.g[this.a]<0){this.g[this.a]=b.length-1;c=j}var e=this.g[this.a];if(b[e].k.parentNode===i){this.G!==i&&this.G.view(i);a.l=this.ra(a.wa);this.g[this.a]=a.l.length;e=this.g[this.a]}this.q=b[e];if(this.H!==i)c?this.H.play(this.nb):this.H.play(this.hb);return this.q};
o.prototype.zc=function(){var a=this.c[this.a],b=this.g[this.a];if(a.Pa!==i&&b-1<=-1){this.ja(a.Pa);this.g[this.a]=a.l.length;return i}var d=this.Kb();return d};o.prototype.ub=function(){if(this.c.length<1)return i;if(this.q){var a=this.q.k.U[this.a];if(typeof a!="undefined")this.g[this.a]=a}var b=this.c[this.a],d=b.l,c=this.g[this.a];this.q=d[c];return this.q};o.prototype.La=function(a){var b=i;if(a!==i&&a.indexOf&&a.indexOf("CALL:")===0&&a.indexOf("(")===-1)try{b=eval(a.substring(5))}catch(d){}return b};
o.prototype.W=function(a){if(a!==i){var b=this,d=function(){var g=b.La(a.action);if(g)g(a);else{b.G!==i&&b.G.view(a.k);b.h.Mc(a.k)}};if(this.h.p&&this.h.p.blur){var c=this.h.p;this.h.p=i;c.removeAttribute&&this.h.Xa(c,"aria-activedescendant");var e=function(g){g.target.removeEventListener("blur",e,j);d()};c.addEventListener("blur",e,j);c.blur()}else d()}else{var f=this.c[this.a];f.type=="dynamic"&&this.h.n(f.onEmpty)}};
o.prototype.v=function(a,b,d,c){for(var e=0,f;f=a[e];e++)if(f=="LEFT")d[37]=c;else if(f=="UP")d[38]=c;else if(f=="RIGHT")d[39]=c;else if(f=="DOWN")d[40]=c;else if(f=="PGUP")d[33]=c;else if(f=="PGDOWN")d[34]=c;else if(f=="ENTER")d[13]=c;else if(f=="ESC")d[27]=c;else if(f=="DEL")d[46]=c;else b[f.charCodeAt(0)]=c};
o.prototype.ma=function(a,b,d){var c=[];if(a==="")return;c=a.split(" ");var e=this;if(d=="prev")this.v(c,this.N[b],this.I[b],function(){e.W(e.Kb())});else if(d=="next")this.v(c,this.N[b],this.I[b],function(){e.W(e.Ta())});else d=="back"?this.v(c,this.N[b],this.I[b],function(){e.W(e.zc())}):this.v(c,this.N[b],this.I[b],function(){e.W(e.Jc())})};
o.prototype.yc=function(a,b,d){var c=[];if(a==="")return;c=a.split(" ");var e=this;this.v(c,this.K,this.L,function(){if(!e.eb(e.c[b])){e.h.n(d);return}e.a=b;e.W(e.Ta())})};o.prototype.xc=function(a,b){var d=[];if(a==="")return;d=a.split(" ");var c=this;this.v(d,this.K,this.L,function(){c.h.n(b)})};o.prototype.ob=function(a,b,d){var c=[];if(a.hotkey==="")return;c=a.hotkey.split(" ");var e=this;this.v(c,b,d,function(){e.ja(a)})};
o.prototype.ja=function(a){var b=a.u,d=this.h.D().documentElement;if(b.indexOf(".")===0)d=this.ub().k;var c=this.h.P(b,d);if(c.length<1)this.h.n(a.onEmpty);else{var e=this.La(a.action);if(e){var f={};f.action=a.action;f.k=c[0];e(f)}else{this.h.Bc(c[0],h);c[0].scrollIntoView(j)}this.h.sa(c[0])}};o.prototype.Ma=function(a,b){var d=i,c=this.a;if(c<this.I.length)d=this.I[c][a]||this.N[c][b]||i;if(d===i)d=this.L[a]||this.K[b];return d};
o.prototype.Vc=function(a,b){var d={};d.Eb=[];var c=new DOMParser,e=c.parseFromString(a,"text/xml"),f=e.getElementsByTagName("list"),g,l;for(g=0,l;l=f[g];g++){var m={};m.title=l.getAttribute("title");m.hotkey=l.getAttribute("hotkey");m.Sa=l.getAttribute("next");m.Va=l.getAttribute("prev");m.Ic=l.getAttribute("fwd");m.back=l.getAttribute("back");m.onEmpty=l.getAttribute("onEmpty");m.type=l.getAttribute("type");var n,p,q,r,s;m.l=[];var t=l.getElementsByTagName("item");for(n=0;p=t[n];n++){var x={};x.u=
p.textContent;if(p.attributes instanceof NamedNodeMap){r=p.attributes;s=r.length;for(q=0;q<s;q++){var w=r.item(q);x[w.nodeName]=w.value}}m.l.push(x)}m.r=[];var B=l.getElementsByTagName("target");for(n=0;p=B[n];n++){var v={};v.u=p.textContent;if(p.attributes instanceof NamedNodeMap){r=p.attributes;s=r.length;for(q=0;q<s;q++){var w=r.item(q);v[w.nodeName]=w.value}}m.r.push(v)}d.Eb.push(m)}d.r=[];var A,C=e.firstChild;for(g=0,A;A=C.childNodes[g];g++)if(A.tagName=="target"){var v={};v.u=A.textContent;
if(A.attributes instanceof NamedNodeMap){r=A.attributes;s=r.length;for(q=0;q<s;q++){var w=r.item(q);v[w.nodeName]=w.value}}d.r.push(v)}d.Sa=C.getAttribute("next");d.Va=C.getAttribute("prev");if(b===i||typeof b=="undefined")this.Hb(d,b);else{var G=new (function(H,D,E,F){b(C,D,E,F)});this.Hb(d,G)}};
o.prototype.Lc=function(){var a=this.Na(),b="";for(var d=0,c;c=a[d];d++)b=b+c.ba+", "+c.title+". ";b=b+this.ua+", "+o.b.hc;b=b+this.ya+", "+o.b.lc;b=b.replace("PGUP",o.b.lb);b=b.replace("PGDOWN",o.b.kb);b=b.replace("ENTER",o.b.V);b=b.replace("DEL",o.b.Yb);b=b.replace("UP",o.b.ia);b=b.replace("DOWN",o.b.fa);b=b.replace("LEFT",o.b.ib);b=b.replace("RIGHT",o.b.mb);return b};
o.prototype.Sc=function(){var a=this.Oa(),b="";for(var d=0,c;c=a[d];d++)b=b+c.ba+", "+c.title+". ";var e=this.O();if(e.Ua!=="")b=b+e.Ua+", "+o.b.Wb+". ";if(e.Wa!=="")b=b+e.Wa+", "+o.b.Xb+". ";if(e.Ka!=="")b=b+e.Ka+", "+o.b.cc+". ";if(e.Da!=="")b=b+e.Da+", "+o.b.bc+". ";b=b.replace("PGUP",o.b.lb);b=b.replace("PGDOWN",o.b.kb);b=b.replace("ENTER",o.b.V);b=b.replace("DEL",o.b.Yb);b=b.replace("UP",o.b.ia);b=b.replace("DOWN",o.b.fa);b=b.replace("LEFT",o.b.ib);b=b.replace("RIGHT",o.b.mb);return b};
o.prototype.ld=function(a){this.G=a};o.prototype.nd=function(a){this.H=a};o.prototype.pd=function(){if(this.A===i)return;var a=this.Na(),b=this.Oa();if(a.length+b.length===0){this.h.n(o.b.ic);return}var d=[],c=0,e="";for(c=0;e=b[c];c++)d.push(e.title);for(c=0;e=a[c];c++)d.push(e.title);this.A.hd(d);this.A.Pb("visible",j,40,20)};
o.prototype.Na=function(){var a=[],b;for(var d=0,c;c=this.c[d];d++)if(c.$!==""){b={};b.title=c.title;b.ba=c.$;a.push(b)}for(var e=0,f;f=this.ea[e];e++)if(this.Cb(f)){b={};b.title=f.title;b.ba=f.hotkey;a.push(b)}return a};o.prototype.Oa=function(){var a=[],b=this.O();for(var d=0,c;c=b.r[d];d++)if(this.Cb(c)){var e={};e.title=c.title;e.ba=c.hotkey;a.push(e)}return a};
o.prototype.Ec=function(){var a=this.h.D().body,b=this,d=function(c,e){var f=b.Oa(),g=b.Na(),l=f.concat(g),m=l[e].ba,n=m.split(" ")[0],p=-1,q=-1;if(n=="LEFT")p=37;else if(n=="UP")p=38;else if(n=="RIGHT")p=39;else if(n=="DOWN")p=40;else if(n=="PGUP")p=33;else if(n=="PGDOWN")p=34;else if(n=="ENTER")p=13;else if(n=="DEL")p=46;else if(n=="ESC")p=27;else q=n.charCodeAt(0);b.A.j.blur();var r=b.Ma(p,q);r&&r()};this.A.Cc(a,50,d,i,this.Ad,h);this.A.jd(o.b.oc);this.A.fd(j);this.A.Ya()};
o.prototype.Cb=function(a){var b=h;if(a.hotkey!==""){var d=a.u,c=this.h.D().body;if(d.indexOf(".")===0){var e=this.ub();if(e)c=e.k}var f=this.h.P(d,c);if(f.length>0)b=j}return b};
o.prototype.Hb=function(a,b){this.c=[];this.a=0;this.g=[];var d=[],c,e;for(c=0,e;e=a.Eb[c];c++){var f={};f.Cd=i;f.wa=e;f.title=e.title||"";f.$=e.hotkey||"";f.Ua=e.Sa||"";f.Wa=e.Va||"";f.Ka=e.Ic||"";f.Da=e.back||"";f.onEmpty=e.onEmpty||"";f.type=e.type||"";f.db=i;f.Pa=i;f.Ja=i;f.l=this.ra(e);f.r=this.Gb(e);for(var g=0,l;l=f.r[g];g++)if(l.trigger=="listTail")f.db=l;else if(l.trigger=="listHead")f.Pa=l;else if(l.trigger=="listEntry")f.Ja=l;if(f.l.length>0||f.type=="dynamic"){this.c.push(f);this.g.push(-1)}else f.$!==
""&&d.push(f)}this.ea=[];this.Fd=0;var m;if(a.r)for(c=0,m;m=a.r[c];c++){var n={};n.u=m.u;n.u=n.u.replace(/^\s\s*/,"").replace(/\s\s*$/,"");n.title=m.title||"";n.trigger=m.trigger||"key";n.hotkey=m.hotkey||"";n.action=m.action||"click";n.onEmpty=m.onEmpty||"";this.ea.push(n)}this.J!==i&&document.removeEventListener("keypress",this.J,j);b===i||typeof b=="undefined"?this.od(a,d):b(a,this.c,d,this.ea)};
o.prototype.ra=function(a){var b=[];if(!a.l)return b;for(var d=0,c;c=a.l[d];d++)try{var e=c.u.replace(/^\s\s*/,"").replace(/\s\s*$/,""),f=this.h.D().documentElement,g=this.h.P(e,f),l=c.index||"0",m=parseInt(l,10),n=g.length-m,p=c.Dd||"*";if(p!="*")n=parseInt(p,10);var q=n+m,r=c.action||i;while(m<q){var s={};s.action=r;s.k=g[m];if(typeof s.k!="undefined"){if(typeof s.k.U=="undefined")s.k.U={};s.k.U[this.c.length]=b.length;b.push(s)}m++}}catch(t){}return b};
o.prototype.Gb=function(a){var b=[];if(!a.r)return b;for(var d=0,c;c=a.r[d];d++){var e={};e.u=c.u.replace(/^\s\s*/,"").replace(/\s\s*$/,"");e.title=c.title||"";e.trigger=c.trigger||"key";e.hotkey=c.hotkey||"";e.action=c.action||"click";e.onEmpty=c.onEmpty||"";b.push(e)}return b};
o.prototype.od=function(a,b){var d=this,c;this.K={};this.L={};this.N=[];this.I=[];var e;for(c=0,e;e=this.ea[c];c++)this.ob(e,this.K,this.L);var f=[];this.ua=a.Sa||"";if(this.ua!=="")f=this.ua.split(" ");this.v(f,this.K,this.L,function(){d.Wc();d.vb()});f=[];this.ya=a.Va||"";if(this.ya!=="")f=this.ya.split(" ");this.v(f,this.K,this.L,function(){d.ad();d.vb()});var g;for(c=0,g;g=this.c[c];c++){var l={},m={};this.N.push(l);this.I.push(m);this.ma(g.Ua,c,"next");this.ma(g.Wa,c,"prev");this.ma(g.Ka,c,"fwd");
this.ma(g.Da,c,"back");this.yc(g.$,c,g.onEmpty);var n;for(n=0,e;e=g.r[n];n++)this.ob(e,l,m)}var p;for(c=0,p;p=b[c];c++)this.xc(p.$,p.onEmpty);this.J=function(q){if(q.ctrlKey)return j;if(d.h.R)return j;var r=d.Ma(q.keyCode,q.charCode);if(r)return r()};document.addEventListener("keypress",this.J,j)};var u=function(a){this.d=a;this.ta=1.5;this.padding=-1;this.ed=0;this.ka=a.D();this.f=this.ka.createElement("span");this.f.style.backgroundColor="#CCE6FF";this.f.style.borderColor="#0000CC";this.f.style.borderWidth="medium";this.f.style.borderStyle="groove";this.f.style.position="absolute";this.f.style.display="none";this.ka.body.appendChild(this.f);this.qb=function(){}};u.pc={zd:0,$b:1};
u.prototype.view=function(a){while(this.f.firstChild)this.f.removeChild(this.f.firstChild);if(a===i){this.f.style.display="none";return}var b=0,d=0,c=a;if(c.offsetParent){b=c.offsetLeft;d=c.offsetTop;c=c.offsetParent;while(c!==i){b+=c.offsetLeft;d+=c.offsetTop;c=c.offsetParent}}this.f.appendChild(a.cloneNode(j));this.f.style.top=d+"px";this.f.style.left=b+"px";this.f.style.zIndex=999;this.f.style.display="block";this.Fb()};u.prototype.Za=function(a){this.ta=a;this.Fb()};
u.prototype.Fb=function(){this.ka.body.removeChild(this.f);this.Tc();this.Gc();this.tc();this.ka.body.appendChild(this.f);this.qb&&this.qb(this.f);if(this.ed==u.pc.$b){var a=this;window.setTimeout(function(){a.f.scrollIntoView(j)},0)}};u.prototype.tc=function(){if(this.padding<0)return;var a="//*[not(.//*)]",b=this.d.P(a,this.f);for(var d=0,c;c=b[d];d++)c.style.padding=this.padding+"px"};
u.prototype.Gc=function(){var a=this.f.getElementsByTagName("img");for(var b=0,d;d=a[b];b++){if(!d.hasAttribute("Axs_OrigHeight")){d.setAttribute("Axs_OrigHeight",d.height);d.setAttribute("Axs_OrigWidth",d.width)}d.height=d.getAttribute("Axs_OrigHeight")*this.ta;d.width=d.getAttribute("Axs_OrigWidth")*this.ta}};u.prototype.Tc=function(){var a=this.ta*0.52;this.f.style.fontSizeAdjust=a;var b=this.f.getElementsByTagName("*");for(var d=0,c;c=b[d];d++)c.style.setProperty("line-height","normal","important")};var y=function(a){var b="http://google-axsjax.googlecode.com/svn/trunk/";this.Fc=b+"common/earcons/axsEarcons.swf?sound=";this.z=i;this.pa=a;this.bb=b+"thirdparty/soundmanager2/";this.m=i;this.Q=h;this.Qb="minimal";this.na=h;this.Ra=0};
y.prototype.Qa=function(){if(this.pa)return;if(this.Q)return;if(this.na)return;this.na=j;this.Ra=0;if(this.m!==i){this.m.parentNode.removeChild(this.m);this.m=i}this.m=document.createElement("iframe");var a=document.location.toString();if(a.indexOf("#")!=-1)a=a.substring(0,a.indexOf("#"));this.m.src=this.bb+"AxsJAX_SM2_Linker.html#Verbosity="+this.Qb+",Parent="+a;this.m.width="0%";this.m.height="0%";this.m.style.top="-1000";this.m.style.left="-1000";this.m.style.position="absolute";document.getElementsByTagName("body")[0].appendChild(this.m);
this.sb()};y.prototype.sb=function(){if(document.location.hash=="#InitSuccess"){this.Q=j;this.na=h;return}if(this.Qb=="none"&&this.Ra>0){this.Q=j;this.na=h;return}var a=this;window.setTimeout(function(){a.sb()},100);this.Ra++};y.prototype.play=function(a){var b=this.$c(a);if(this.pa||b)return;if(!this.Q){this.Qa();var d=this;window.setTimeout(function(){d.play(a)},500);return}this.m.src=this.bb+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Play("+a+")"};
y.prototype.stop=function(){if(this.z){this.z.parentNode.removeChild(this.z);this.z=i}if(this.pa)return;if(!this.Q)return;this.m.src=this.bb+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Stop()"};y.prototype.getTime=function(){if(this.pa)return-1;if(!this.Q)return-1;var a="Time=",b=unescape(document.location.hash);if(b.indexOf(a)==-1)return-1;var d=b.indexOf(a)+a.length,c=parseInt(b.substring(d),10);return c};
y.prototype.$c=function(a){var b="";switch(a){case "alert":b="alert";break;case "deselect":b="deselect";break;case "item":b="item";break;case "list":b="list";break;case "select":b="select";break;case "success":b="success";break;case "wrap":b="wrap";break;default:}if(b==="")return;if(this.z===i){this.z=document.createElement("embed");this.z.height=0;this.z.width=0;document.body.appendChild(this.z)}this.z.src=this.Fc+b};var z=function(a,b){this.Z=a;this.s=i;this.j=i;this.w=i;this.o=i;this.tb=i;this.oa="Enter Completion";this.Yc="No completions found";this.Y=i;this.C=[];this.Uc={};this.i=-1;this.Ab=h;this.$a=h;this.Ea="#000000";this.Fa=0;this.Qc={};this.qa={};this.Bd={};if(b&&z.aa)this.Y=b;var d=this;this.X(window,z.za.mc,function(c){d.Zc.call(d,c)},i)};z.Sb=/^\<[A-Z|a-z|0-9|\-|\_]+\>$/;z.fc=/^(\s|\r|\n)+/;z.nc=/(\s|\r|\n)+$/;
z.prototype.X=function(a,b,d,c){if(z.aa&&d)a.addEventListener(b,d,j);else z.t&&d&&a.attachEvent(b,function(g){d(g)});if(c){var e=new z.gb(c),f=this;this.X(a,b,function(g){e.Pc(g,e,f)},i)}};
z.prototype.Cc=function(a,b,d,c,e,f){var g=this,l,m,n,p,q;this.s&&this.s.parentNode.removeChild(this.s);do{l="completionField_"+Math.floor(Math.random()*1001);m="txt_"+l;p="div_"+l;q="bgdiv_"+l;n=document.getElementById(l)}while(n);var r=document.createElement("div");r.id=q;r.style.display="none";var s=document.createElement("div");s.id=l;s.style.position="absolute";var t=document.createElement("input");t.type="text";t.id=m;t.size=b;t.value="";t.onkeypress=function(v){v.stopPropagation();if(v.keyCode==
z.F.Aa)return h};t.readOnly=f;if(f)t.style.fontSize=0;var x=document.createElement("div");x.id=p;x.setAttribute("tabindex",0);x.setAttribute("role","row");s.appendChild(x);s.appendChild(t);a.appendChild(r);a.appendChild(s);this.s=s;this.j=t;this.w=r;this.tb=x;this.s.className="pkHiddenStatus";this.j.className="pkOpaqueCompletionText";this.w.className="pkBackgroundHide";if(e){this.C=e;this.Uc[this.Z]=[e,this.oa];this.e=this.C;for(var w=0,B;B=this.C[w];w++)this.qa[B.toLowerCase()]=w;this.i=-1}this.X(this.j,
z.za.ha,function(v){g.Oc.call(g,v,c,d)},i);this.X(this.j,z.za.ga,function(v){g.Nc.call(g,v)},i);this.X(this.j,"blur",function(){g.Ab&&g.Pb("hidden")},i)};z.prototype.fd=function(a){this.Ab=a};z.prototype.jd=function(a){this.oa=a};z.prototype.hd=function(a){this.C=a;this.e=this.C;this.qa={};for(var b=0,d;d=this.C[b];b++)this.qa[d.toLowerCase()]=b;this.i=-1};
z.prototype.Pb=function(a,b,d,c){if(a=="visible"){this.s.className=="pkHiddenStatus"&&this.T(this.oa);this.ab(this.$a,this.Ea,this.Fa);this.s.className="pkVisibleStatus";var e=this.j;window.setTimeout(function(){e.focus()},0)}else if(a=="hidden"){if(z.t&&this.o)this.o.innerText="";else if(this.o)this.o.textContent="";this.ab(h,this.Ea,this.Fa);this.s.className="pkHiddenStatus";this.j.value="";this.i=-1}if(b){var f=z.yb();d||(d=f.height-this.s.offsetHeight);c||(c=0);this.s.style.top=d;this.s.style.left=
c}};z.prototype.Zc=function(){var a=this;window.setTimeout(function(){a.$a&&a.w.style.display=="block"&&a.ab(a.$a,a.Ea,a.Fa)},0)};
z.prototype.Oc=function(a,b,d){if(this.j.value.length===0)this.e=this.C;if(a.keyCode!=z.F.ha&&a.keyCode!=z.F.ga&&a.keyCode!=z.F.V&&a.keyCode!=z.F.Aa)if(this.j.value.length){this.e=this.zb(this.C,this.j.value,50);this.i=-1;if(this.e.length>0){this.T(this.e[0]);this.i=0}else this.T(this.Yc)}else this.T(this.oa);if(a.keyCode==z.F.V){if(this.j.readOnly)return;if(this.e&&this.e.length>0&&this.j.value!=this.e[this.i]&&(this.e[this.i].indexOf("<")<0||this.e[this.i].indexOf("<")>=0&&this.e[this.i].split(" ").length>
this.j.value.split(" ").length))this.Mb();var c=this.j.value,e=(z.t?this.o.innerText:this.o.textContent).toLowerCase(),f=e.indexOf("<"),g;if(f>=0){g=c.substr(0,f-1).toLowerCase();c=g+" "+c.substr(f)}else{c=c.toLowerCase();g=c}var l=h;if(b)l=this.sc.call(this,c,e,b);if(d&&!l){var m=this.wb(c,e);d(g,this.qa[e],this.Qc[e],m)}this.j.value=""}};
z.prototype.Nc=function(a){if(a.keyCode==z.F.ha&&this.e&&this.e.length>0)this.bd();else if(a.keyCode==z.F.ga&&this.e&&this.e.length>0)this.Xc();else a.keyCode==z.F.Aa&&this.e&&this.e.length>0&&this.Mb()};z.prototype.ab=function(a,b,d){if(a){this.w.className="pkBackgroundShow";this.w.style.display="block";var c=z.yb();this.w.style.width=c.width+"px";this.w.style.height=c.height+"px";if(b)this.w.style.backgroundColor=b;d&&this.w.style.setProperty("-moz-opacity",d/100,"")}else this.w.style.display="none"};
z.prototype.zb=function(a,b,d){var c=a,e=a,f=b.split(" ");for(var g=0,l;l=f[g];g++){e=c;c=[];if(l!==""){var m=z.dd(l),n=new RegExp("(^|\\W+)"+m,"i");for(var p=0,q;q=e[p];p++)String(q).match(n)&&c.push(q)}}e=a;for(p=0;q=e[p];p++){var r=q.split(" "),s=[],t;for(g=0;t=r[g];g++){if(t.charAt(0)=="<")break;s.push(t)}var x=s.join(" ");b.indexOf(x)===0&&c.push(q)}c.length>d&&c.slice(0,d-1);return c};
z.prototype.wb=function(a,b){a=a.replace(/\s+/g," ");b=b.replace(/\s+/g," ");var d=b.indexOf("<");if(d<0)return[];b=b.substr(d);a=a.substr(d);var c=a.split(","),e=b.split(",");if(c.length!=e.length)return[];var f=[];for(var g=0,l,m;(l=c[g])&&(m=e[g]);g++){l=z.Db(z.Lb(l));m=z.Db(z.Lb(m));m.match(z.Sb)&&f.push(l)}return f};z.prototype.sc=function(a,b,d){this.wb(a,b);var c=d[b];if(c&&c[this.Z]){var e=c[this.Z]+"(args);";window.setTimeout(e,0);return j}else return h};
z.prototype.bd=function(){if(this.i<0)this.i=0;this.i=(this.i||this.e.length)-1;this.i>=0&&this.T(this.e[this.i])};z.prototype.Xc=function(){this.i=(this.i+1)%this.e.length;this.i<this.e.length&&this.T(this.e[this.i])};z.prototype.Mb=function(){this.j.value=this.e[this.i>=0?this.i:0];this.e=this.zb(this.C,this.j.value,50);this.Y&&z.aa&&this.Y.n(this.j.value);this.i=0};
z.prototype.T=function(a){if(!this.o){this.o=document.createElement("div");this.o.id="listElem_"+Math.floor(Math.random()*1001);this.tb.appendChild(this.o)}if(z.t)this.o.innerText=a;else this.o.textContent=a;this.Y&&z.aa&&this.Y.cb(this.o,h)};z.prototype.Ya=function(){z.Ya()};z.gb=function(a){this.Ba=a};
z.gb.prototype.Pc=function(a,b,d){if(!b.Ba)return;if(a.keyCode){var c=""+a.keyCode,e=String.fromCharCode(a.keyCode).toLowerCase();if(a.ctrlKey){c="Ctrl+"+c;e="Ctrl+"+e}if(a.altKey){c="Alt+"+c;e="Alt+"+e}if(a.shiftKey){c="Shift+"+c;e="Shift+"+e}var f=i;f=b.Ba[e];f||(f=b.Ba[c]);if(f){var g=f[d.Z]?f[d.Z]:f["*"];g&&g()}}};z.rc=function(a,b){this.width=a?a:undefined;this.height=b?b:undefined};z.Db=function(a){return a.replace(z.fc,"")};z.Lb=function(a){return a.replace(z.nc,"")};
z.dd=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
z.yb=function(){var a=0,b=0;if(typeof window.innerWidth=="number"){a=window.innerWidth;b=window.innerHeight}else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){a=document.documentElement.clientWidth;b=document.documentElement.clientHeight}else if(document.body&&(document.body.clientWidth||document.body.clientHeight)){a=document.body.clientWidth;b=document.body.clientHeight}return new z.rc(a,b)};z.t=h;z.aa=h;
z.gd=function(){var a=navigator.userAgent.toLowerCase();z.aa=a.indexOf("gecko")!=-1;z.t=a.indexOf("msie")!=-1&&a.indexOf("opera")==-1};z.gd();z.za={ha:z.t?"onkeyup":"keyup",ga:z.t?"onkeydown":"keydown",yd:z.t?"onkeypress":"keypress",ud:z.t?"onclick":"click",mc:z.t?"onresize":"resize",xd:z.t?"onfocus":"focus",td:"blur"};z.Dc=".pkHiddenStatus {display: none; position: absolute;}.pkVisibleStatus {display: block; position: absolute; left: 2px; top: 2px; line-height: 1.2em; z-index: 10001; background-color: #000000; padding: 2px; color: #fff; font-family: Arial, Sans-serif; font-size: 20px; filter: alpha(opacity=80); -moz-opacity: .80;}.pkOpaqueCompletionText {border-style: none; background-color:transparent; font-family: Arial, Helvetica, sans-serif; font-size: 35px; font-weight: bold; color: #fff; width: 1000px; height: 50px;}.pkBackgroundShow {position: absolute; width: 0px;height: 0px; background-color: #000000; filter: alpha(opacity=70);  -moz-opacity: .70; left: 0px; top: 0px; z-index: 10000;}";
z.Ya=function(){var a,b;a=document.getElementsByTagName("head")[0];if(!a)return;b=document.createElement("style");b.type="text/css";b.innerHTML=z.Dc;a.appendChild(b)};z.F={ha:38,ga:40,V:13,Aa:9};var axsFinance={};axsFinance.dc="The following shortcut keys are available. ";axsFinance.b={jb:"or",ia:" up by ",qc:"+",fa:" down by ",Zb:"-",jc:" percent",kc:"%",ac:"Google Finance",Ub:"Currency converter opened",fb:"Currency converter closed",Rb:"Amount",Vb:"Conversion result."};axsFinance.Ib={};axsFinance.Ha={};axsFinance.Ha[axsFinance.b.Zb]=axsFinance.b.fa;axsFinance.Ha[axsFinance.b.qc]=axsFinance.b.ia;axsFinance.rb={};axsFinance.rb[axsFinance.b.kc]=axsFinance.b.jc;axsFinance.Tb='<cnr next="RIGHT l" prev="LEFT h"><target title="Announce currency ratio" hotkey="t" action="CALL:axsFinance.announceCurrencyRatio">//html</target><target title="View reversed ratio" hotkey="v">id("currency_reverse")</target><target title="Open or close currency converter" hotkey="c" action="CALL:axsFinance.openCloseCurrencyConverter">//html</target><list title="News" next="DOWN j" prev="UP k" fwd="n" back="p" type="dynamic"><item action="CALL:axsFinance.readNewsDesc">id("newsmovingdiv")//div[@class="inner"]//tbody</item><target title="Go to link" hotkey="ENTER">.//a</target><target title="View all news" hotkey="a">//a[contains(text(), "View all news for")]</target><target title="Subscribe" hotkey="s">//a[./img[@id="subscribe"]]</target><target title="Related articles" hotkey="r" onEmpty="No related articles available">./../../..//a[@class="g bld" or @class="rl" or @class="rg"]</target></list><list title="Value in other currencies" next="DOWN j" prev="UP k" fwd="n" back="p" type="dynamic"><item action="CALL:axsFinance.readInOtherCurrency">//table[@class="related-currencies"]//tr</item><target title="See ratio with that currency" hotkey="ENTER">.//a</target></list></cnr>';
axsFinance.d=i;axsFinance.B=i;axsFinance.M=i;axsFinance.pb=i;axsFinance.Jb=i;axsFinance.ca=2.5;axsFinance.Ga=i;axsFinance.Ia=h;
axsFinance.Qa=function(){axsFinance.d=new k(j);axsFinance.B=new o(axsFinance.d);axsFinance.B.Vc(axsFinance.Tb,i);axsFinance.M=new u(axsFinance.d);axsFinance.M.Za(axsFinance.ca);axsFinance.B.ld(axsFinance.M);axsFinance.pb=new y(j);axsFinance.B.nd(axsFinance.pb);axsFinance.Jb=new z("list",axsFinance.d);axsFinance.B.md(axsFinance.Jb,".");document.addEventListener("keypress",axsFinance.J,j);var a=document.getElementById("searchbox"),b=axsFinance.Bb;a.addEventListener("keypress",b,j);axsFinance.wc();axsFinance.instrumentInnerIframe()};
axsFinance.wc=function(){var a='id("companyheader")//h1',b=axsFinance.d.P(a,document.body)[0];if(b){var d=axsFinance.xa(b.textContent);d=axsFinance.b.ac+". "+d;var c=axsFinance.xb(),e=d+" "+c;axsFinance.d.n(e)}};
axsFinance.instrumentInnerIframe=function(){var a=document.getElementsByTagName("IFRAME")[0],b="currency_converter_result",d=a.contentDocument.getElementById(b);if(a.contentDocument.Rc===undefined&&d){var c=axsFinance.J;a.contentDocument.addEventListener("keypress",c,j);c=axsFinance.B.J;a.contentDocument.addEventListener("keypress",c,j);c=function(){a.contentDocument.Rc=j;axsFinance.instrumentInnerIframe();axsFinance.openCloseCurrencyConverter(i)};a.contentDocument.addEventListener("submit",c,j);
c=function(e){axsFinance.d.p=e.target;if(e.target.tagName=="INPUT"||e.target.tagName=="SELECT"||e.target.tagName=="TEXTAREA")axsFinance.d.R=j;return j};a.contentDocument.addEventListener("focus",c,j);c=function(e){axsFinance.d.p=i;if(e.target.tagName=="INPUT"||e.target.tagName=="SELECT"||e.target.tagName=="TEXTAREA")axsFinance.d.R=h;return j};a.contentDocument.addEventListener("blur",c,j);axsFinance.kd(a);axsFinance.cd()}else window.setTimeout(axsFinance.instrumentInnerIframe,100)};
axsFinance.cd=function(){var a=document.getElementsByTagName("IFRAME")[0],b="currency_converter_result",d=a.contentDocument.getElementById(b),c=axsFinance.va(d.textContent);if(c!==""){var e=axsFinance.b.fb;e=e+" "+axsFinance.b.Vb+" "+c;axsFinance.M.view(d);d.scrollIntoView(j);axsFinance.d.sa(d);window.setTimeout(function(){axsFinance.d.n(e)},0)}};
axsFinance.Bb=function(a){axsFinance.d.n("");a.target.blur();a.stopPropagation();a.preventDefault();var b=axsFinance.B.Ma(a.keyCode,a.charCode);b&&b();var d=axsFinance.Bb,c=document.getElementById("searchbox");c.removeEventListener("keypress",d,j)};axsFinance.announceCurrencyRatio=function(){var a=axsFinance.xb();axsFinance.d.n(a)};
axsFinance.xb=function(){var a=document.getElementById("currency_value"),b=a.textContent;b=b.replace("(",axsFinance.b.jb+" ");var d=a.childNodes[9].textContent,c=b.indexOf(d);b=b.substring(0,c-2);b=axsFinance.xa(b);return b};axsFinance.readNewsDesc=function(a){var b=a.k,d='.//td[@class="title" or @class="source"]',c=axsFinance.d.P(d,b),e=c[0].textContent+". ";e=e+c[1].childNodes[0].textContent;e=e+c[1].childNodes[1].textContent;e=axsFinance.va(e);axsFinance.Nb(a.k,e)};
axsFinance.readInOtherCurrency=function(a){var b=a.k,d=b.childNodes[1].textContent,c=b.childNodes[3].textContent;c=axsFinance.va(c);var e=c.indexOf(" ");if(e>-1)c=c.substring(e);var f=b.childNodes[5].textContent;f=axsFinance.uc(f);var g=b.childNodes[7].childNodes[1].textContent;g=axsFinance.xa(g);var l=b.childNodes[7].childNodes[3].textContent;l=axsFinance.xa(l);var m=d+" "+c+" "+f;m=m+" "+g+" "+axsFinance.b.jb+" "+l;axsFinance.Nb(b,m)};
axsFinance.openCloseCurrencyConverter=function(){if(axsFinance.Ia){axsFinance.Ia=h;var a=document.getElementsByTagName("INPUT")[0];a.focus();axsFinance.d.n(axsFinance.b.fb);a.blur()}else{axsFinance.Ia=j;var b=document.getElementsByTagName("IFRAME")[0],a=b.contentDocument.getElementsByTagName("INPUT")[0],d=a.title;a.title=axsFinance.b.Ub+". "+a.title;a.title=d;var c=function(){a.focus();a.select()};window.setTimeout(c,0)}};
axsFinance.kd=function(a){var b=a.contentDocument.getElementsByTagName("INPUT"),d=b[0];d.title=axsFinance.b.Rb;var c=b[1],e=a.contentDocument.getElementsByTagName("SELECT"),f=e[0],g=document.createTextNode("From currency: "),l=axsFinance.d.la(f),m=document.createElement("LABEL");m.setAttribute("for",l);m.appendChild(g);f.parentNode.insertBefore(m,f);var n=e[1],g=document.createTextNode("To currency: "),l=axsFinance.d.la(n),m=document.createElement("LABEL");m.setAttribute("for",l);m.appendChild(g);
n.parentNode.insertBefore(m,n);var p=new Array(d,f,n,c);axsFinance.Ga=p};axsFinance.qd=function(a){var b=a.target,d=axsFinance.Ga,c=d.length,e=-1;for(var f=0,g;g=d[f];f++)if(b===g){e=f;break}if(a.shiftKey){e--;if(e<0)e=c-1}else{e++;if(e==c)e=0}var l=d[e];l.focus();l.tagName=="INPUT"&&l.select();a.stopPropagation();a.preventDefault()};axsFinance.Nb=function(a,b){axsFinance.M.view(a);axsFinance.d.n(b);a.scrollIntoView(j);axsFinance.d.sa(a)};
axsFinance.uc=function(a){var b="";for(var d=0;d<a.length;d++){b=b+a.charAt(d);if(d<a.length-1)b=b+" "}return b};
axsFinance.xa=function(a){var b="";if(a==="")return a;a=axsFinance.va(a);var d=axsFinance.Ib[a];if(d!=undefined)return d;var c=a.split(" ");for(var e=0,f;f=c[e];e++){var g=axsFinance.Ib[f];if(g!=undefined)f=g;else{if(f.length>0&&f.charAt(0)==="(")f=f.substring(1);if(f.length>1&&f.charAt(f.length-1)===")")f=f.substring(0,f.length-1);var l=axsFinance.Ha[f.charAt(0)];if(l!=undefined)f=l+" "+f.substring(1);var m=f.charAt(f.length-1),n=axsFinance.rb[m];if(n!=undefined)f=f.substring(0,f.length-1)+" "+n}b=
b+" "+f}return b};axsFinance.va=function(a){var b=new String(a);b=b.replace(/^\s\s*/,"").replace(/\s\s*$/,"");b=b.replace(/\s+/g," ");return b.replace(/\n+/g,"").replace(/\r+/g,"")};axsFinance.J=function(a){if(a.ctrlKey)return j;if(a.keyCode==27){axsFinance.d.p&&axsFinance.d.p.blur();return h}a.keyCode==9&&axsFinance.Ga!==i&&axsFinance.qd(a);if(axsFinance.d.R)return j;var b=axsFinance.Ac[a.charCode];if(b)return b();return j};
axsFinance.Ac={47:function(){axsFinance.Ed=j;document.getElementById("searchbox").focus();document.getElementById("searchbox").select();return h},63:function(){var a=axsFinance.dc+axsFinance.B.Sc()+axsFinance.B.Lc();axsFinance.d.n(a);return h},45:function(){axsFinance.ca-=0.1;axsFinance.M.Za(axsFinance.ca);return h},61:function(){axsFinance.ca+=0.1;axsFinance.M.Za(axsFinance.ca);return h}};window.addEventListener("load",axsFinance.Qa,j);
 })();
