(function() { 
var AxsJAX=function(useTabKeyFix){this.ID_NUM_=0;this.tabbingStartPosNode=null;this.tabKeyFixOn=false;this.lastFocusedNode=null;this.inputFocused=false;var self=this,focusHandler=function(evt){self.lastFocusedNode=evt.target;if(evt.target.tagName=="INPUT"||evt.target.tagName=="SELECT"||evt.target.tagName=="TEXTAREA")self.inputFocused=true;return true};document.addEventListener("focus",focusHandler,true);var blurHandler=function(evt){self.removeAttributeOf(self.lastFocusedNode,"aria-activedescendant");
self.lastFocusedNode=null;if(evt.target.tagName=="INPUT"||evt.target.tagName=="SELECT"||evt.target.tagName=="TEXTAREA")self.inputFocused=false;return true};document.addEventListener("blur",blurHandler,true);if(useTabKeyFix){this.tabKeyFixOn=true;document.addEventListener("keypress",function(event){self.tabKeyHandler(event,self)},true);document.body.AXSJAX_TABKEYFIX_ADDED=true}this.activeParent=document.body};
AxsJAX.prototype.getActiveDocument=function(){var activeDoc=this.activeParent;while(activeDoc.nodeType!=9)activeDoc=activeDoc.parentNode;return activeDoc};
AxsJAX.prototype.speakNode=function(targetNode,opt_noFocusChange){targetNode.id||this.assignId(targetNode);if(opt_noFocusChange){this.setAttributeOf(targetNode,"live","rude");this.setAttributeOf(targetNode,"atomic","true");var activeDoc=this.getActiveDocument(),dummyNode=activeDoc.createElement("div");dummyNode.textContent=" ";dummyNode.name="AxsJAX_dummyNode";targetNode.lastChild&&targetNode.lastChild.name&&targetNode.lastChild.name==dummyNode.name&&targetNode.removeChild(targetNode.lastChild);targetNode.appendChild(dummyNode)}else{var oldRole=
this.getAttributeOf(targetNode,"role");this.setAttributeOf(targetNode,"role","row");var currentFocusedNode=this.lastFocusedNode;if(!currentFocusedNode||currentFocusedNode.nodeType==9){this.activeParent.tabIndex=-1;currentFocusedNode=this.activeParent}this.setAttributeOf(currentFocusedNode,"activedescendant",null);currentFocusedNode.focus();this.setAttributeOf(currentFocusedNode,"activedescendant",targetNode.id);var self=this;window.setTimeout(function(){oldRole?self.setAttributeOf(targetNode,"role",
oldRole):self.removeAttributeOf(targetNode,"role")},0)}};
AxsJAX.prototype.speakTextViaNode=function(textString,opt_anchorNode){var pixelId="AxsJAX_pixelAudioNode",pixelName="AxsJAX_pixelAudioNode",encodedClearPixel="data:image/gif;base64,R0lGODlhAQABAIAAANvf7wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",activeDoc=this.getActiveDocument(),pixelNode=null;if(opt_anchorNode){if(opt_anchorNode.previousSibling&&opt_anchorNode.previousSibling.name==pixelName)pixelNode=opt_anchorNode.previousSibling;else{pixelNode=activeDoc.createElement("img");pixelNode.name=pixelName;
pixelNode.setAttribute("tabindex",0);pixelNode.style.outline="none";pixelNode.src=encodedClearPixel;opt_anchorNode.parentNode.insertBefore(pixelNode,opt_anchorNode);this.forceATSync(pixelNode)}pixelNode.setAttribute("alt",textString);pixelNode.setAttribute("title",textString);window.setTimeout(function(){pixelNode.blur();pixelNode.focus()},0)}else{pixelNode=activeDoc.getElementById(pixelId);if(pixelNode&&pixelNode.alt==textString)textString=textString+" ";if(!pixelNode){pixelNode=activeDoc.createElement("img");
pixelNode.id=pixelId;pixelNode.src=encodedClearPixel;activeDoc.body.appendChild(pixelNode)}pixelNode.setAttribute("alt",textString);pixelNode.setAttribute("title",textString);this.speakNode(pixelNode)}};
AxsJAX.prototype.clickElem=function(targetNode,shiftKey){var activeDoc=this.getActiveDocument(),evt=activeDoc.createEvent("MouseEvents");evt.initMouseEvent("mousedown",true,true,activeDoc.defaultView,1,0,0,0,0,false,false,shiftKey,false,0,null);try{targetNode.dispatchEvent(evt)}catch(e){}evt=activeDoc.createEvent("MouseEvents");evt.initMouseEvent("mouseup",true,true,activeDoc.defaultView,1,0,0,0,0,false,false,shiftKey,false,0,null);try{targetNode.dispatchEvent(evt)}catch(e){}evt=activeDoc.createEvent("MouseEvents");
evt.initMouseEvent("click",true,true,activeDoc.defaultView,1,0,0,0,0,false,false,shiftKey,false,0,null);try{targetNode.dispatchEvent(evt)}catch(e){}if(targetNode.tagName=="A"&&targetNode.href&&(targetNode.href.indexOf("http")===0||targetNode.href.indexOf("javascript:")===0))if(shiftKey)window.open(targetNode.href);else document.location=targetNode.href};
AxsJAX.prototype.assignId=function(targetNode,opt_prefixString){if(!targetNode)return"";if(targetNode.id)return targetNode.id;var prefix=opt_prefixString||"AxsJAX_ID_";targetNode.id=prefix+this.ID_NUM_++;return targetNode.id};AxsJAX.prototype.tabKeyHandler=function(evt,selfRef){if(!selfRef.tabKeyFixOn)return true;if(evt.keyCode==9&&selfRef.tabbingStartPosNode){selfRef.tabbingStartPosNode.focus();selfRef.tabbingStartPosNode=null}return true};
AxsJAX.prototype.setAttributeOf=function(targetNode,attribute,value){if(!targetNode)return;attribute=attribute.toLowerCase();switch(attribute){case "live":attribute="aria-live";break;case "activedescendant":attribute="aria-activedescendant";break;case "atomic":attribute="aria-atomic";break;default:break}targetNode.setAttribute(attribute,value)};AxsJAX.prototype.getAttributeOf=function(targetNode,attribute){return targetNode.getAttribute(attribute)};
AxsJAX.prototype.removeAttributeOf=function(targetNode,attribute){targetNode&&targetNode.removeAttribute&&targetNode.removeAttribute(attribute)};AxsJAX.prototype.forceATSync=function(targetNode){var id=this.assignId(targetNode),activeDoc=this.getActiveDocument(),loc=activeDoc.baseURI,indexOfHash=loc.indexOf("#");if(indexOfHash!=-1)loc=loc.substring(0,indexOfHash);activeDoc.location=loc+"#"+id};
AxsJAX.prototype.evalXPath=function(expression,rootNode){try{var xpathIterator=rootNode.ownerDocument.evaluate(expression,rootNode,null,XPathResult.ORDERED_NODE_ITERATOR_TYPE,null)}catch(err){return[]}var results=[];for(var xpathNode=xpathIterator.iterateNext();xpathNode;xpathNode=xpathIterator.iterateNext())results.push(xpathNode);return results};var AxsSound=function(earconsOnly){var baseURL="http://google-axsjax.googlecode.com/svn/trunk/";this.earconsSwf=baseURL+"common/earcons/axsEarcons.swf?sound=";this.earconsObj=null;this.earconsOnly=earconsOnly;this.sm2BaseURL=baseURL+"thirdparty/soundmanager2/";this.sm2LinkerFrame=null;this.initSucceeded=false;this.verbosity="minimal";this.busyInitializing=false;this.initChecks=0};
AxsSound.prototype.init=function(){if(this.earconsOnly)return;if(this.initSucceeded)return;if(this.busyInitializing)return;this.busyInitializing=true;this.initChecks=0;if(this.sm2LinkerFrame!==null){this.sm2LinkerFrame.parentNode.removeChild(this.sm2LinkerFrame);this.sm2LinkerFrame=null}this.sm2LinkerFrame=document.createElement("iframe");var loc=document.location.toString();if(loc.indexOf("#")!=-1)loc=loc.substring(0,loc.indexOf("#"));this.sm2LinkerFrame.src=this.sm2BaseURL+"AxsJAX_SM2_Linker.html#Verbosity="+
this.verbosity+",Parent="+loc;this.sm2LinkerFrame.width="0%";this.sm2LinkerFrame.height="0%";this.sm2LinkerFrame.style.top="-1000";this.sm2LinkerFrame.style.left="-1000";this.sm2LinkerFrame.style.position="absolute";document.getElementsByTagName("body")[0].appendChild(this.sm2LinkerFrame);this.checkInitStatus()};
AxsSound.prototype.checkInitStatus=function(){if(document.location.hash=="#InitSuccess"){this.initSucceeded=true;this.busyInitializing=false;return}if(this.verbosity=="none"&&this.initChecks>0){this.initSucceeded=true;this.busyInitializing=false;return}var self=this;window.setTimeout(function(){self.checkInitStatus()},100);this.initChecks++};
AxsSound.prototype.play=function(url){var playedEarcon=this.playEarcon(url);if(this.earconsOnly||playedEarcon)return;if(!this.initSucceeded){this.init();var self=this;window.setTimeout(function(){self.play(url)},500);return}this.sm2LinkerFrame.src=this.sm2BaseURL+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Play("+url+")"};
AxsSound.prototype.stop=function(){if(this.earconsObj){this.earconsObj.parentNode.removeChild(this.earconsObj);this.earconsObj=null}if(this.earconsOnly)return;if(!this.initSucceeded)return;this.sm2LinkerFrame.src=this.sm2BaseURL+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Stop()"};
AxsSound.prototype.getTime=function(){if(this.earconsOnly)return-1;if(!this.initSucceeded)return-1;var timeKeyword="Time=",timeStr=unescape(document.location.hash);if(timeStr.indexOf(timeKeyword)==-1)return-1;var timeStart=timeStr.indexOf(timeKeyword)+timeKeyword.length,time=parseInt(timeStr.substring(timeStart),10);return time};
AxsSound.prototype.playEarcon=function(earcon){var earconCMD="";switch(earcon){case "alert":earconCMD="alert";break;case "deselect":earconCMD="deselect";break;case "item":earconCMD="item";break;case "list":earconCMD="list";break;case "select":earconCMD="select";break;case "success":earconCMD="success";break;case "wrap":earconCMD="wrap";break;default:}if(earconCMD==="")return;if(this.earconsObj===null){this.earconsObj=document.createElement("embed");this.earconsObj.height=0;this.earconsObj.width=0;
document.body.appendChild(this.earconsObj)}this.earconsObj.src=this.earconsSwf+earconCMD};var axsSky={};axsSky.HELP_STRING="The following shortcut keys are available. N, go to the next item. P, go to the previous item. Enter, open the current item. T, go to the top menu. Escape, stop the podcast that is currently playing. ";axsSky.ITEMS_LOADED="Items loaded.";axsSky.axsJAXObj=null;axsSky.axsSoundObj=null;axsSky.itemsArray=[];axsSky.itemsIndex=-1;axsSky.currentItem=null;axsSky.insertCount=0;
axsSky.init=function(){axsSky.axsJAXObj=new AxsJAX(true);axsSky.axsSoundObj=new AxsSound(false);axsSky.axsSoundObj.init();document.addEventListener("keypress",axsSky.keyHandler,true);window.addEventListener("DOMNodeInserted",axsSky.domInsertionHandler,true);axsSky.getItems()};
axsSky.domInsertionHandler=function(evt){var target=evt.target;if(target.firstChild&&target.firstChild.id=="infoScrollDiv"){var rootNode=document.getElementById("infoScrollDiv"),xpath='.//a[contains(@href,".mp3")]',podcastLink=axsSky.axsJAXObj.evalXPath(xpath,rootNode)[0];if(podcastLink&&axsSky.insertCount>0){axsSky.axsSoundObj.play(podcastLink.href);axsSky.insertCount=0}else if(podcastLink)axsSky.insertCount++;else{xpath=".//td";var tds=axsSky.axsJAXObj.evalXPath(xpath,rootNode),content="";for(var i=
0,td;td=tds[i];i++)content=content+td.textContent+". ";axsSky.axsJAXObj.speakTextViaNode(content)}}else if(target.className=="slideTable")axsSky.getItems();else target.parentNode&&target.parentNode.id=="myTooltip"&&axsSky.axsJAXObj.speakTextViaNode(target.textContent)};axsSky.getItems=function(){var rootNode=document.getElementById("slider"),xpath=".//span";axsSky.itemsArray=axsSky.axsJAXObj.evalXPath(xpath,rootNode);axsSky.itemsIndex=-1;axsSky.axsJAXObj.speakTextViaNode(axsSky.ITEMS_LOADED)};
axsSky.nextItem=function(){axsSky.axsSoundObj.stop();axsSky.itemsIndex++;if(axsSky.itemsIndex>=axsSky.itemsArray.length)axsSky.itemsIndex=0;axsSky.goToCurrentItem()};axsSky.prevItem=function(){axsSky.axsSoundObj.stop();axsSky.itemsIndex--;if(axsSky.itemsIndex<0)axsSky.itemsIndex=axsSky.itemsArray.length-1;axsSky.goToCurrentItem()};
axsSky.goToCurrentItem=function(){var activeDoc=axsSky.axsJAXObj.getActiveDocument(),evt=activeDoc.createEvent("MouseEvents");evt.initMouseEvent("mouseout",true,true,activeDoc.defaultView,1,0,0,0,0,false,false,false,false,0,null);try{axsSky.currentItem.dispatchEvent(evt)}catch(e){}axsSky.currentItem=axsSky.itemsArray[axsSky.itemsIndex];evt=activeDoc.createEvent("MouseEvents");evt.initMouseEvent("mouseover",true,true,activeDoc.defaultView,1,0,0,0,0,false,false,false,false,0,null);try{axsSky.currentItem.dispatchEvent(evt)}catch(e){}axsSky.currentItem.lastChild.tagName==
"DIV"&&axsSky.axsJAXObj.speakTextViaNode(axsSky.currentItem.lastChild.textContent)};axsSky.activateItem=function(){axsSky.axsJAXObj.clickElem(axsSky.currentItem,false)};axsSky.goToHome=function(){axsSky.axsSoundObj.stop();var rootNode=document.getElementById("sliderHeader"),xpath=".//span[@class='fakeLinkWS']",homeLink=axsSky.axsJAXObj.evalXPath(xpath,rootNode)[0];axsSky.axsJAXObj.clickElem(homeLink,false)};
axsSky.keyHandler=function(evt){if(evt.ctrlKey)return true;if(evt.keyCode==27){axsSky.axsSoundObj.stop();axsSky.axsJAXObj.lastFocusedNode.blur();return false}if(axsSky.axsJAXObj.inputFocused)return true;if(axsSky.axsJAXObj.lastFocusedNode.tagName=="A")return true;var command=axsSky.keyCodeMap[evt.keyCode]||axsSky.charCodeMap[evt.charCode];if(command)return command();return true};axsSky.keyCodeMap={13:axsSky.activateItem};
axsSky.charCodeMap={63:function(){axsSky.axsJAXObj.speakTextViaNode(axsSky.HELP_STRING);return false},110:axsSky.nextItem,112:axsSky.prevItem,116:axsSky.goToHome};window.setTimeout(axsSky.init,500);
 })();
