(function() { 
var g=false,h=null,j=true,k=function(b){this.bb=0;this.M=h;this.Pa=g;this.q=h;this.T=g;var a=this,d=function(e){a.q=e.target;if(e.target.tagName=="INPUT"||e.target.tagName=="SELECT"||e.target.tagName=="TEXTAREA")a.T=j;return j};document.addEventListener("focus",d,j);var c=function(e){a.ma(a.q,"aria-activedescendant");a.q=h;if(e.target.tagName=="INPUT"||e.target.tagName=="SELECT"||e.target.tagName=="TEXTAREA")a.T=g;return j};document.addEventListener("blur",c,j);if(b){this.Pa=j;document.addEventListener("keypress",
function(e){a.Sb(e,a)},j);document.body.Tb=j}this.aa=document.body};k.prototype.t=function(){var b=this.aa;while(b.nodeType!=9)b=b.parentNode;return b};
k.prototype.Oa=function(b,a){b.id||this.Aa(b);if(a){this.H(b,"live","rude");this.H(b,"atomic","true");var d=this.t(),c=d.createElement("div");c.textContent=" ";c.name="AxsJAX_dummyNode";b.lastChild&&b.lastChild.name&&b.lastChild.name==c.name&&b.removeChild(b.lastChild);b.appendChild(c)}else{var e=this.tb(b,"role");this.H(b,"role","row");var f=this.q;if(!f||f.nodeType==9){this.aa.tabIndex=-1;f=this.aa}this.H(f,"activedescendant",h);f.focus();this.H(f,"activedescendant",b.id);var i=this;window.setTimeout(function(){e?
i.H(b,"role",e):i.ma(b,"role")},0)}};
k.prototype.z=function(b,a){var d="AxsJAX_pixelAudioNode",c="AxsJAX_pixelAudioNode",e="data:image/gif;base64,R0lGODlhAQABAIAAANvf7wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",f=this.t(),i=h;if(a){if(a.previousSibling&&a.previousSibling.name==c)i=a.previousSibling;else{i=f.createElement("img");i.name=c;i.setAttribute("tabindex",0);i.style.outline="none";i.src=e;a.parentNode.insertBefore(i,a);this.pb(i)}i.setAttribute("alt",b);i.setAttribute("title",b);window.setTimeout(function(){i.blur();i.focus()},0)}else{i=
f.getElementById(d);if(i&&i.alt==b)b=b+" ";if(!i){i=f.createElement("img");i.id=d;i.src=e;f.body.appendChild(i)}i.setAttribute("alt",b);i.setAttribute("title",b);this.Oa(i)}};
k.prototype.mb=function(b,a){var d=this.t(),c=d.createEvent("MouseEvents");c.initMouseEvent("mousedown",j,j,d.defaultView,1,0,0,0,0,g,g,a,g,0,h);try{b.dispatchEvent(c)}catch(e){}c=d.createEvent("MouseEvents");c.initMouseEvent("mouseup",j,j,d.defaultView,1,0,0,0,0,g,g,a,g,0,h);try{b.dispatchEvent(c)}catch(e){}c=d.createEvent("MouseEvents");c.initMouseEvent("click",j,j,d.defaultView,1,0,0,0,0,g,g,a,g,0,h);try{b.dispatchEvent(c)}catch(e){}if(b.tagName=="A"&&b.href&&(b.href.indexOf("http")===0||b.href.indexOf("javascript:")===
0))if(a)window.open(b.href);else document.location=b.href};k.prototype.Aa=function(b,a){if(!b)return"";if(b.id)return b.id;var d=a||"AxsJAX_ID_";b.id=d+this.bb++;return b.id};k.prototype.La=function(b){if(!b)return g;if(b.tagName=="A"||b.tagName=="INPUT"){this.M=b;return j}var a=b.getElementsByTagName("*");for(var d=0,c;c=a[d];d++)if(c.tagName=="A"||c.tagName=="INPUT"||c.hasAttribute("tabindex")&&c.tabIndex!=-1){this.M=c;return j}return g};
k.prototype.Sb=function(b,a){if(!a.Pa)return j;if(b.keyCode==9&&a.M){a.M.focus();a.M=h}return j};k.prototype.Eb=function(b){this.Oa(b);b.scrollIntoView(j);this.La(b)};k.prototype.H=function(b,a,d){if(!b)return;a=a.toLowerCase();switch(a){case "live":a="aria-live";break;case "activedescendant":a="aria-activedescendant";break;case "atomic":a="aria-atomic";break;default:break}b.setAttribute(a,d)};k.prototype.tb=function(b,a){return b.getAttribute(a)};
k.prototype.ma=function(b,a){b&&b.removeAttribute&&b.removeAttribute(a)};k.prototype.pb=function(b){var a=this.Aa(b),d=this.t(),c=d.baseURI,e=c.indexOf("#");if(e!=-1)c=c.substring(0,e);d.location=c+"#"+a};k.prototype.j=function(b,a){try{var d=a.ownerDocument.evaluate(b,a,h,XPathResult.ORDERED_NODE_ITERATOR_TYPE,h)}catch(c){return[]}var e=[];for(var f=d.iterateNext();f;f=d.iterateNext())e.push(f);return e};var n=function(b){this.Y="";this.$="";this.b=[];this.a=0;this.d=[];this.l=h;this.N=[];this.A={};this.B={};this.w=[];this.u=[];this.g=b;this.r=h;this.ac=h;this.s=h;this.cb="list";this.ta="item";this.za="wrap";this.G=h};n.e={db:"next list",eb:"previous list",$a:"go forward",Za:"go backwards",Va:"cycle next",Wa:"cycle previous",Yb:"Select available action",Xb:"No available actions",wa:"Page up",va:"Page down",sa:"Enter",Vb:"Escape",Ub:"Delete",ya:"Up",ra:"Down",ua:"Left",xa:"Right"};
n.prototype.qa=function(b){var a=j;if(b.type=="dynamic"&&b.h.length===0){this.r!==h&&this.r.view(h);b.h=this.V(b.Z);b.m=this.Ka(b.Z);if(this.b[this.a]===b)this.d[this.a]=-1;else for(var d=0,c;c=this.b[d];d++)if(c===b){this.d[d]=-1;break}}if(b.h.length===0&&b.ca===h)a=g;return a};n.prototype.Ga=function(){var b=this.D(),a=b.ca,d=h;if(a!==h){this.O(a);d=this.ea(a.action)}if(d===h){this.hb();this.s!==h&&this.s.play(this.cb)}};
n.prototype.Jb=function(){if(this.b.length<1)return h;for(var b=0;this.b[b];b++){this.a++;if(this.a>=this.b.length)this.a=0;if(this.qa(this.b[this.a]))break}return this.D()};n.prototype.Lb=function(){if(this.b.length<1)return h;for(var b=0;this.b[b];b++){this.a--;if(this.a<0)this.a=this.b.length-1;if(this.qa(this.b[this.a]))break}return this.D()};n.prototype.D=function(){return this.b[this.a]};n.prototype.hb=function(){this.g.z(this.D().title)};
n.prototype.X=function(){if(this.b.length<1)return h;var b=this.b[this.a],a=b.h;if(a.length<1)return h;if(this.l){var d=this.l.i.I[this.a];if(typeof d!="undefined")this.d[this.a]=d}this.d[this.a]++;var c=g;if(this.d[this.a]>=a.length){this.d[this.a]=0;c=j}var e=this.d[this.a];if(a[e].i.parentNode===h){this.r!==h&&this.r.view(h);b.h=this.V(b.Z);this.d[this.a]=0;e=this.d[this.a]}this.l=a[e];if(this.s!==h)c?this.s.play(this.za):this.s.play(this.ta);return this.l};
n.prototype.sb=function(){var b=this.b[this.a],a=this.d[this.a];if(b.pa!==h&&a+1>=b.h.length){this.O(b.pa);this.d[this.a]=0;return h}var d=this.X();return d};
n.prototype.Na=function(){if(this.b.length<1)return h;var b=this.b[this.a],a=b.h;if(a.length<1)return h;if(this.l){var d=this.l.i.I[this.a];if(typeof d!="undefined")this.d[this.a]=d}this.d[this.a]--;var c=g;if(this.d[this.a]<0){this.d[this.a]=a.length-1;c=j}var e=this.d[this.a];if(a[e].i.parentNode===h){this.r!==h&&this.r.view(h);b.h=this.V(b.Z);this.d[this.a]=b.h.length;e=this.d[this.a]}this.l=a[e];if(this.s!==h)c?this.s.play(this.za):this.s.play(this.ta);return this.l};
n.prototype.kb=function(){var b=this.b[this.a],a=this.d[this.a];if(b.fa!==h&&a-1<=-1){this.O(b.fa);this.d[this.a]=b.h.length;return h}var d=this.Na();return d};n.prototype.Fa=function(){if(this.b.length<1)return h;if(this.l){var b=this.l.i.I[this.a];if(typeof b!="undefined")this.d[this.a]=b}var a=this.b[this.a],d=a.h,c=this.d[this.a];this.l=d[c];return this.l};n.prototype.ea=function(b){var a=h;if(b!==h&&b.indexOf&&b.indexOf("CALL:")===0&&b.indexOf("(")===-1)try{a=eval(b.substring(5))}catch(d){}return a};
n.prototype.J=function(b){if(b!==h){var a=this,d=function(){var i=a.ea(b.action);if(i)i(b);else{a.r!==h&&a.r.view(b.i);a.g.Eb(b.i)}};if(this.g.q&&this.g.q.blur){var c=this.g.q;this.g.q=h;c.removeAttribute&&this.g.ma(c,"aria-activedescendant");var e=function(i){i.target.removeEventListener("blur",e,j);d()};c.addEventListener("blur",e,j);c.blur()}else d()}else{var f=this.b[this.a];f.type=="dynamic"&&this.g.z(f.onEmpty)}};
n.prototype.p=function(b,a,d,c){for(var e=0,f;f=b[e];e++)if(f=="LEFT")d[37]=c;else if(f=="UP")d[38]=c;else if(f=="RIGHT")d[39]=c;else if(f=="DOWN")d[40]=c;else if(f=="PGUP")d[33]=c;else if(f=="PGDOWN")d[34]=c;else if(f=="ENTER")d[13]=c;else if(f=="ESC")d[27]=c;else if(f=="DEL")d[46]=c;else a[f.charCodeAt(0)]=c};
n.prototype.Q=function(b,a,d){var c=[];if(b==="")return;c=b.split(" ");var e=this;if(d=="prev")this.p(c,this.w[a],this.u[a],function(){e.J(e.Na())});else if(d=="next")this.p(c,this.w[a],this.u[a],function(){e.J(e.X())});else d=="back"?this.p(c,this.w[a],this.u[a],function(){e.J(e.kb())}):this.p(c,this.w[a],this.u[a],function(){e.J(e.sb())})};
n.prototype.jb=function(b,a,d){var c=[];if(b==="")return;c=b.split(" ");var e=this;this.p(c,this.A,this.B,function(){if(!e.qa(e.b[a])){e.g.z(d);return}e.a=a;e.J(e.X())})};n.prototype.ib=function(b,a){var d=[];if(b==="")return;d=b.split(" ");var c=this;this.p(d,this.A,this.B,function(){c.g.z(a)})};n.prototype.Ba=function(b,a,d){var c=[];if(b.hotkey==="")return;c=b.hotkey.split(" ");var e=this;this.p(c,a,d,function(){e.O(b)})};
n.prototype.O=function(b){var a=b.n,d=this.g.t().documentElement;if(a.indexOf(".")===0)d=this.Fa().i;var c=this.g.j(a,d);if(c.length<1)this.g.z(b.onEmpty);else{var e=this.ea(b.action);if(e){var f={};f.action=b.action;f.i=c[0];e(f)}else{this.g.mb(c[0],g);c[0].scrollIntoView(j)}this.g.La(c[0])}};n.prototype.wb=function(b,a){var d=h,c=this.a;if(c<this.u.length)d=this.u[c][b]||this.w[c][a]||h;if(d===h)d=this.B[b]||this.A[a];return d};
n.prototype.Ib=function(b,a){var d={};d.Ia=[];var c=new DOMParser,e=c.parseFromString(b,"text/xml"),f=e.getElementsByTagName("list"),i,m;for(i=0,m;m=f[i];i++){var l={};l.title=m.getAttribute("title");l.hotkey=m.getAttribute("hotkey");l.ia=m.getAttribute("next");l.ka=m.getAttribute("prev");l.rb=m.getAttribute("fwd");l.back=m.getAttribute("back");l.onEmpty=m.getAttribute("onEmpty");l.type=m.getAttribute("type");var o,q,p,s,t;l.h=[];var B=m.getElementsByTagName("item");for(o=0;q=B[o];o++){var A={};A.n=
q.textContent;if(q.attributes instanceof NamedNodeMap){s=q.attributes;t=s.length;for(p=0;p<t;p++){var v=s.item(p);A[v.nodeName]=v.value}}l.h.push(A)}l.m=[];var C=m.getElementsByTagName("target");for(o=0;q=C[o];o++){var w={};w.n=q.textContent;if(q.attributes instanceof NamedNodeMap){s=q.attributes;t=s.length;for(p=0;p<t;p++){var v=s.item(p);w[v.nodeName]=v.value}}l.m.push(w)}d.Ia.push(l)}d.m=[];var y,z=e.firstChild;for(i=0,y;y=z.childNodes[i];i++)if(y.tagName=="target"){var w={};w.n=y.textContent;
if(y.attributes instanceof NamedNodeMap){s=y.attributes;t=s.length;for(p=0;p<t;p++){var v=s.item(p);w[v.nodeName]=v.value}}d.m.push(w)}d.ia=z.getAttribute("next");d.ka=z.getAttribute("prev");if(a===h||typeof a=="undefined")this.Ma(d,a);else{var G=new (function(H,D,E,F){a(z,D,E,F)});this.Ma(d,G)}};
n.prototype.Db=function(){var b=this.xb(),a="";for(var d=0,c;c=b[d];d++)a=a+c.U+", "+c.title+". ";a=a+this.Y+", "+n.e.db;a=a+this.$+", "+n.e.eb;a=a.replace("PGUP",n.e.wa);a=a.replace("PGDOWN",n.e.va);a=a.replace("ENTER",n.e.sa);a=a.replace("DEL",n.e.Xa);a=a.replace("UP",n.e.ya);a=a.replace("DOWN",n.e.ra);a=a.replace("LEFT",n.e.ua);a=a.replace("RIGHT",n.e.xa);return a};
n.prototype.Gb=function(){var b=this.yb(),a="";for(var d=0,c;c=b[d];d++)a=a+c.U+", "+c.title+". ";var e=this.D();if(e.ja!=="")a=a+e.ja+", "+n.e.Va+". ";if(e.la!=="")a=a+e.la+", "+n.e.Wa+". ";if(e.da!=="")a=a+e.da+", "+n.e.$a+". ";if(e.ba!=="")a=a+e.ba+", "+n.e.Za+". ";a=a.replace("PGUP",n.e.wa);a=a.replace("PGDOWN",n.e.va);a=a.replace("ENTER",n.e.sa);a=a.replace("DEL",n.e.Xa);a=a.replace("UP",n.e.ya);a=a.replace("DOWN",n.e.ra);a=a.replace("LEFT",n.e.ua);a=a.replace("RIGHT",n.e.xa);return a};
n.prototype.Ob=function(b){this.r=b};n.prototype.Pb=function(b){this.s=b};n.prototype.xb=function(){var b=[],a;for(var d=0,c;c=this.b[d];d++)if(c.K!==""){a={};a.title=c.title;a.U=c.K;b.push(a)}for(var e=0,f;f=this.N[e];e++)if(this.Ha(f)){a={};a.title=f.title;a.U=f.hotkey;b.push(a)}return b};n.prototype.yb=function(){var b=[],a=this.D();for(var d=0,c;c=a.m[d];d++)if(this.Ha(c)){var e={};e.title=c.title;e.U=c.hotkey;b.push(e)}return b};
n.prototype.Ha=function(b){var a=g;if(b.hotkey!==""){var d=b.n,c=this.g.t().body;if(d.indexOf(".")===0){var e=this.Fa();if(e)c=e.i}var f=this.g.j(d,c);if(f.length>0)a=j}return a};
n.prototype.Ma=function(b,a){this.b=[];this.a=0;this.d=[];var d=[],c,e;for(c=0,e;e=b.Ia[c];c++){var f={};f.Zb=h;f.Z=e;f.title=e.title||"";f.K=e.hotkey||"";f.ja=e.ia||"";f.la=e.ka||"";f.da=e.rb||"";f.ba=e.back||"";f.onEmpty=e.onEmpty||"";f.type=e.type||"";f.pa=h;f.fa=h;f.ca=h;f.h=this.V(e);f.m=this.Ka(e);for(var i=0,m;m=f.m[i];i++)if(m.trigger=="listTail")f.pa=m;else if(m.trigger=="listHead")f.fa=m;else if(m.trigger=="listEntry")f.ca=m;if(f.h.length>0||f.type=="dynamic"){this.b.push(f);this.d.push(-1)}else f.K!==
""&&d.push(f)}this.N=[];this.bc=0;var l;if(b.m)for(c=0,l;l=b.m[c];c++){var o={};o.n=l.n;o.n=o.n.replace(/^\s\s*/,"").replace(/\s\s*$/,"");o.title=l.title||"";o.trigger=l.trigger||"key";o.hotkey=l.hotkey||"";o.action=l.action||"click";o.onEmpty=l.onEmpty||"";this.N.push(o)}this.G!==h&&document.removeEventListener("keypress",this.G,j);a===h||typeof a=="undefined"?this.Qb(b,d):a(b,this.b,d,this.N)};
n.prototype.V=function(b){var a=[];if(!b.h)return a;for(var d=0,c;c=b.h[d];d++)try{var e=c.n.replace(/^\s\s*/,"").replace(/\s\s*$/,""),f=this.g.t().documentElement,i=this.g.j(e,f),m=c.index||"0",l=parseInt(m,10),o=i.length-l,q=c.$b||"*";if(q!="*")o=parseInt(q,10);var p=o+l,s=c.action||h;while(l<p){var t={};t.action=s;t.i=i[l];if(typeof t.i!="undefined"){if(typeof t.i.I=="undefined")t.i.I={};t.i.I[this.b.length]=a.length;a.push(t)}l++}}catch(B){}return a};
n.prototype.Ka=function(b){var a=[];if(!b.m)return a;for(var d=0,c;c=b.m[d];d++){var e={};e.n=c.n.replace(/^\s\s*/,"").replace(/\s\s*$/,"");e.title=c.title||"";e.trigger=c.trigger||"key";e.hotkey=c.hotkey||"";e.action=c.action||"click";e.onEmpty=c.onEmpty||"";a.push(e)}return a};
n.prototype.Qb=function(b,a){var d=this,c;this.A={};this.B={};this.w=[];this.u=[];var e;for(c=0,e;e=this.N[c];c++)this.Ba(e,this.A,this.B);var f=[];this.Y=b.ia||"";if(this.Y!=="")f=this.Y.split(" ");this.p(f,this.A,this.B,function(){d.Jb();d.Ga()});f=[];this.$=b.ka||"";if(this.$!=="")f=this.$.split(" ");this.p(f,this.A,this.B,function(){d.Lb();d.Ga()});var i;for(c=0,i;i=this.b[c];c++){var m={},l={};this.w.push(m);this.u.push(l);this.Q(i.ja,c,"next");this.Q(i.la,c,"prev");this.Q(i.da,c,"fwd");this.Q(i.ba,
c,"back");this.jb(i.K,c,i.onEmpty);var o;for(o=0,e;e=i.m[o];o++)this.Ba(e,m,l)}var q;for(c=0,q;q=a[c];c++)this.ib(q.K,q.onEmpty);this.G=function(p){if(p.ctrlKey)return j;if(d.g.T)return j;var s=d.wb(p.keyCode,p.charCode);if(s)return s()};document.addEventListener("keypress",this.G,j)};var r=function(b){var a="http://google-axsjax.googlecode.com/svn/trunk/";this.nb=a+"common/earcons/axsEarcons.swf?sound=";this.o=h;this.S=b;this.oa=a+"thirdparty/soundmanager2/";this.k=h;this.F=g;this.Qa="minimal";this.R=g;this.ha=0};
r.prototype.ga=function(){if(this.S)return;if(this.F)return;if(this.R)return;this.R=j;this.ha=0;if(this.k!==h){this.k.parentNode.removeChild(this.k);this.k=h}this.k=document.createElement("iframe");var b=document.location.toString();if(b.indexOf("#")!=-1)b=b.substring(0,b.indexOf("#"));this.k.src=this.oa+"AxsJAX_SM2_Linker.html#Verbosity="+this.Qa+",Parent="+b;this.k.width="0%";this.k.height="0%";this.k.style.top="-1000";this.k.style.left="-1000";this.k.style.position="absolute";document.getElementsByTagName("body")[0].appendChild(this.k);
this.Ea()};r.prototype.Ea=function(){if(document.location.hash=="#InitSuccess"){this.F=j;this.R=g;return}if(this.Qa=="none"&&this.ha>0){this.F=j;this.R=g;return}var b=this;window.setTimeout(function(){b.Ea()},100);this.ha++};r.prototype.play=function(b){var a=this.Kb(b);if(this.S||a)return;if(!this.F){this.ga();var d=this;window.setTimeout(function(){d.play(b)},500);return}this.k.src=this.oa+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Play("+b+")"};
r.prototype.stop=function(){if(this.o){this.o.parentNode.removeChild(this.o);this.o=h}if(this.S)return;if(!this.F)return;this.k.src=this.oa+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Stop()"};r.prototype.getTime=function(){if(this.S)return-1;if(!this.F)return-1;var b="Time=",a=unescape(document.location.hash);if(a.indexOf(b)==-1)return-1;var d=a.indexOf(b)+b.length,c=parseInt(a.substring(d),10);return c};
r.prototype.Kb=function(b){var a="";switch(b){case "alert":a="alert";break;case "deselect":a="deselect";break;case "item":a="item";break;case "list":a="list";break;case "select":a="select";break;case "success":a="success";break;case "wrap":a="wrap";break;default:}if(a==="")return;if(this.o===h){this.o=document.createElement("embed");this.o.height=0;this.o.width=0;document.body.appendChild(this.o)}this.o.src=this.nb+a};var u=function(b){this.f=b;this.W=1.5;this.padding=-1;this.Nb=0;this.P=b.t();this.c=this.P.createElement("span");this.c.style.backgroundColor="#CCE6FF";this.c.style.borderColor="#0000CC";this.c.style.borderWidth="medium";this.c.style.borderStyle="groove";this.c.style.position="absolute";this.c.style.display="none";this.P.body.appendChild(this.c);this.Da=function(){}};u.fb={Wb:0,Ya:1};
u.prototype.view=function(b){while(this.c.firstChild)this.c.removeChild(this.c.firstChild);if(b===h){this.c.style.display="none";return}var a=0,d=0,c=b;if(c.offsetParent){a=c.offsetLeft;d=c.offsetTop;c=c.offsetParent;while(c!==h){a+=c.offsetLeft;d+=c.offsetTop;c=c.offsetParent}}this.c.appendChild(b.cloneNode(j));this.c.style.top=d+"px";this.c.style.left=a+"px";this.c.style.zIndex=999;this.c.style.display="block";this.Ja()};u.prototype.na=function(b){this.W=b;this.Ja()};
u.prototype.Ja=function(){this.P.body.removeChild(this.c);this.Hb();this.ob();this.gb();this.P.body.appendChild(this.c);this.Da&&this.Da(this.c);if(this.Nb==u.fb.Ya){var b=this;window.setTimeout(function(){b.c.scrollIntoView(j)},0)}};u.prototype.gb=function(){if(this.padding<0)return;var b="//*[not(.//*)]",a=this.f.j(b,this.c);for(var d=0,c;c=a[d];d++)c.style.padding=this.padding+"px"};
u.prototype.ob=function(){var b=this.c.getElementsByTagName("img");for(var a=0,d;d=b[a];a++){if(!d.hasAttribute("Axs_OrigHeight")){d.setAttribute("Axs_OrigHeight",d.height);d.setAttribute("Axs_OrigWidth",d.width)}d.height=d.getAttribute("Axs_OrigHeight")*this.W;d.width=d.getAttribute("Axs_OrigWidth")*this.W}};u.prototype.Hb=function(){var b=this.W*0.52;this.c.style.fontSizeAdjust=b;var a=this.c.getElementsByTagName("*");for(var d=0,c;c=a[d];d++)c.style.setProperty("line-height","normal","important")};var x={};x.ab="The following shortcut keys are available. ";x.Sa=" averages out to ";x.Ra=" Accepts Google Checkout. ";x.Ta=" Buy this at ";x.Ua=" Buy this ";x.f=h;x.v=h;x.C=h;x.Ca=h;x.L=1.5;
x.ga=function(){x.f=new k(j);x.v=new n(x.f);x.qb();document.addEventListener("keypress",x.G,j);var b='<cnr next="RIGHT l" prev="LEFT h">  <list title="Cycle Results" next="DOWN j" prev="UP k" fwd="n" back="p" hotkey="n">    <item>      /html/body/table[3]/tbody/tr[not(@class)]    </item>    <target title="Next page" trigger="listTail">      id("nn")/..    </target>    <target title="Previous page" trigger="listHead">      id("np")/..    </target>\t    <target title="Go to result" hotkey="ENTER">      ./td[contains(@class,"ps-rcont")]//a    </target>  </list>  <list title="Sponsored links" next="DOWN j" prev="UP k" hotkey="a">    <item>      id("AXSJAX_SPONSOREDLINKS_SECTION")/span    </item>\t<target title="Go to result" hotkey="ENTER">      .//a    </target>  </list>  <list title="Refine by price" next="DOWN j" prev="UP k">    <item>      id("attr-div")//a[contains(@href,"lnk=prsugg")]    </item>    <target title="Perform refinement" hotkey="ENTER">      .    </target>\t\t<target title = "Display prices" trigger="listEntry">\t  id("attr-div")//a[contains(@href,"lnk=prsugg")]/../following-sibling::li[@class="nav"]/a[contains(text(),"More")]\t</target>  </list>    <list title="Refine by brand" next="DOWN j" prev="UP k">    <item>      id("attr-div")//a[contains(@href,"lnk=brsugg")]    </item>    <target title="Perform refinement" hotkey="ENTER">      .    </target>\t<target title = "Display brands" trigger="listEntry">\t  id("attr-div")//a[contains(@href,"lnk=brsugg")]/../following-sibling::li[@class="nav"]/a[contains(text(),"More")]\t</target>  </list>    <list title="Refine by store" next="DOWN j" prev="UP k">    <item>      id("attr-div")//a[contains(@href,"lnk=storesugg")]    </item>    <target title="Perform refinement" hotkey="ENTER">      .    </target>\t<target title = "Display stores" trigger="listEntry">\t  id("attr-div")//a[contains(@href,"lnk=storesugg")]/../following-sibling::li[@class="nav"]/a[contains(text(),"More")]\t</target>  </list>    <list title="Refine by merchant rating" next="DOWN j" prev="UP k">    <item>      id("attr-div")//a[contains(@href,"lnk=merchant_review")]    </item>    <target title="Perform refinement" hotkey="ENTER">      .    </target>\t<target title = "Display merchant rating" trigger="listEntry">\t  id("attr-div")//a[contains(@href,"lnk=merchant_review")]/../following-sibling::li[@class="nav"]/a[contains(text(),"More")]\t</target>  </list>    <list title="Refine by related searches" next="DOWN j" prev="UP k">    <item>      id("attr-div")//a[contains(@href,"lnk=qsugt")]    </item>    <target title="Perform refinement" hotkey="ENTER">      .    </target>\t<target title = "Display related searches" trigger="listEntry">\t  id("attr-div")//a[contains(@href,"lnk=qsugt")]/../following-sibling::li[@class="nav"]/a[contains(text(),"More")]\t</target>  </list>  </cnr>';x.v.Ib(b,
h);x.C=new u(x.f);x.v.Ob(x.C);x.C.na(x.L);x.Ca=new r(j);x.v.Pb(x.Ca);window.setTimeout(x.Mb,500)};x.Mb=function(){x.Rb(x.v.X())};x.Rb=function(b){var a=b.i,d=x.Cb(a),c=x.vb(a),e=x.zb(a),f=x.Bb(a),i=x.Ab(a),m=x.ub(a),l=d+". "+e+". "+c+f+". "+i+m;x.C.view(a);a.scrollIntoView(j);x.f.z(l)};x.Cb=function(b){var a=".//h2/a",d=x.f.j(a,b)[0];return d.textContent};
x.vb=function(b){var a=x.f.j(".//font",b)[0],d="";if(!a){var c=".//td[contains(@class,'ps-rcont')]";a=x.f.j(c,b)[0]}for(var e=0,f;f=a.childNodes[e];e++)if(f.nodeName=="#text"||f.nodeName=="B"||f.nodeName=="SPAN")d=d+f.textContent;return d};x.zb=function(b){var a=".//b[contains(@class,'ps-larger-t')]",d=x.f.j(a,b)[0];return d.textContent};
x.Bb=function(b){var a=".//nobr/a",d=x.f.j(a,b)[0];if(d)return x.Ta+d.textContent;else{var c=".//b[contains(@class,'ps-larger-t')]/../..",e=x.f.j(c,b)[0],f=e.childNodes[3];return x.Ua+f.textContent}};x.Ab=function(b){var a=".//nobr/a/img[contains(@src,'star')]",d=x.f.j(a,b)[0],c=".//nobr/a[contains(text(),'ratings')]",e=x.f.j(c,b)[0],f="";if(d)f=e.textContent+x.Sa+d.alt+". ";return f};x.ub=function(b){var a=".//a[contains(@class,'checkout')]",d=x.f.j(a,b)[0];if(d)return x.Ra;return""};
x.qb=function(){var b='//font[@class="s"]/..',a=x.f.j(b,document.body)[0];if(!a)return;b='//font[@class="s"]/../font';var d=x.f.j(b,document.body),c=d.length,e=c/3;if(d.length%3!=0)return;var f=[],i=0,m=window.content.document.createElement("br");for(i=0;i<c;i=i+3){var l=window.content.document.createElement("span");l.appendChild(d[i].cloneNode(j));l.appendChild(m.cloneNode(j));l.appendChild(d[i+1].cloneNode(j));l.appendChild(m.cloneNode(j));l.appendChild(d[i+2].cloneNode(j));l.appendChild(m.cloneNode(j));
l.appendChild(m.cloneNode(j));f.push(l)}while(a.firstChild)a.removeChild(a.firstChild);for(i=0;i<e;i++)a.appendChild(f[i]);a.id="AXSJAX_SPONSOREDLINKS_SECTION"};x.G=function(b){if(b.ctrlKey)return j;if(b.keyCode==27){x.f.q.blur();return g}if(x.f.T)return j;var a=x.Fb[b.keyCode]||x.lb[b.charCode];if(a)return a();return j};x.Fb={};
x.lb={47:function(){document.getElementsByName("q")[0].focus();document.getElementsByName("q")[0].select();return g},45:function(){x.L-=0.1;x.C.na(x.L);return g},61:function(){x.L+=0.1;x.C.na(x.L);return g},63:function(){var b=x.ab+x.v.Gb()+x.v.Db();x.f.z(b);return g}};x.ga();
 })();
