(function() { 
var a=function(b){this.T=0;this.D=null;this.P=false;this.s=null;this.K=false;var c=this,e=function(f){c.s=f.target;if(f.target.tagName=="INPUT"||f.target.tagName=="SELECT"||f.target.tagName=="TEXTAREA")c.K=true;return true};document.addEventListener("focus",e,true);var d=function(f){c.M(c.s,"aria-activedescendant");c.s=null;if(f.target.tagName=="INPUT"||f.target.tagName=="SELECT"||f.target.tagName=="TEXTAREA")c.K=false;return true};document.addEventListener("blur",d,true);if(b){this.P=true;document.addEventListener("keypress",
function(f){c.ea(f,c)},true);document.body.ga=true}this.u=document.body};a.prototype.r=function(){var b=this.u;while(b.nodeType!=9)b=b.parentNode;return b};a.prototype.O=function(b,c){if(!b.id)this.F(b);if(c){this.n(b,"live","rude");this.n(b,"atomic","true");var e=this.r(),d=e.createElement("div");d.textContent=" ";d.name="AxsJAX_dummyNode";if(b.lastChild&&b.lastChild.name&&b.lastChild.name==d.name)b.removeChild(b.lastChild);b.appendChild(d)}else{var f=this.Y(b,"role");this.n(b,"role","row");var h=
this.s;if(!h||h.nodeType==9){this.u.tabIndex=-1;h=this.u}this.n(h,"activedescendant",null);h.focus();this.n(h,"activedescendant",b.id);var g=this;window.setTimeout(function(){if(f)g.n(b,"role",f);else g.M(b,"role")},0)}};a.prototype.g=function(b,c){var e="AxsJAX_pixelAudioNode",d="AxsJAX_pixelAudioNode",f="data:image/gif;base64,R0lGODlhAQABAIAAANvf7wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",h=this.r(),g=null;if(c){if(c.previousSibling&&c.previousSibling.name==d)g=c.previousSibling;else{g=h.createElement("img");
g.name=d;g.setAttribute("tabindex",0);g.style.outline="none";g.src=f;c.parentNode.insertBefore(g,c);this.X(g)}g.setAttribute("alt",b);g.setAttribute("title",b);window.setTimeout(function(){g.blur();g.focus()},0)}else{g=h.getElementById(e);if(!g){g=h.createElement("img");g.id=e;g.src=f;h.body.appendChild(g)}g.setAttribute("alt",b);g.setAttribute("title",b);this.O(g)}};a.prototype.v=function(b,c){var e=this.r(),d=e.createEvent("MouseEvents");d.initMouseEvent("mousedown",true,true,e.defaultView,1,0,
0,0,0,false,false,c,false,0,null);try{b.dispatchEvent(d)}catch(f){}d=e.createEvent("MouseEvents");d.initMouseEvent("mouseup",true,true,e.defaultView,1,0,0,0,0,false,false,c,false,0,null);try{b.dispatchEvent(d)}catch(f){}d=e.createEvent("MouseEvents");d.initMouseEvent("click",true,true,e.defaultView,1,0,0,0,0,false,false,c,false,0,null);try{b.dispatchEvent(d)}catch(f){}if(b.tagName=="A"&&b.href&&(b.href.indexOf("http")===0||b.href.indexOf("javascript:")===0))if(c)window.open(b.href);else document.location=
b.href};a.prototype.F=function(b,c){if(!b)return"";if(b.id)return b.id;var e=c||"AxsJAX_ID_";b.id=e+this.T++;return b.id};a.prototype.ea=function(b,c){if(!c.P)return true;if(b.keyCode==9&&c.D){c.D.focus();c.D=null}return true};a.prototype.n=function(b,c,e){if(!b)return;c=c.toLowerCase();switch(c){case "live":c="aria-live";break;case "activedescendant":c="aria-activedescendant";break;case "atomic":c="aria-atomic";break;default:break}b.setAttribute(c,e)};a.prototype.Y=function(b,c){return b.getAttribute(c)};
a.prototype.M=function(b,c){if(b&&b.removeAttribute)b.removeAttribute(c)};a.prototype.X=function(b){var c=this.F(b),e=this.r(),d=e.ha,f=d.indexOf("#");if(f!=-1)d=d.substring(0,f);e.location=d+"#"+c};var i=function(b){var c="http://google-axsjax.googlecode.com/svn/trunk/";this.W=c+"common/earcons/axsEarcons.swf?sound=";this.i=null;this.q=b;this.C=c+"thirdparty/soundmanager2/";this.e=null;this.m=false;this.R="minimal";this.p=false;this.A=0};i.prototype.z=function(){if(this.q)return;if(this.m)return;if(this.p)return;this.p=true;this.A=0;if(this.e!==null){this.e.parentNode.removeChild(this.e);this.e=null}this.e=document.createElement("iframe");var b=document.location.toString();if(b.indexOf("#")!=
-1)b=b.substring(0,b.indexOf("#"));this.e.src=this.C+"AxsJAX_SM2_Linker.html#Verbosity="+this.R+",Parent="+b;this.e.width="0%";this.e.height="0%";this.e.style.top="-1000";this.e.style.left="-1000";this.e.style.position="absolute";document.getElementsByTagName("body")[0].appendChild(this.e);this.G()};i.prototype.G=function(){if(document.location.hash=="#InitSuccess"){this.m=true;this.p=false;return}if(this.R=="none"&&this.A>0){this.m=true;this.p=false;return}var b=this;window.setTimeout(function(){b.G()},
100);this.A++};i.prototype.play=function(b){var c=this.aa(b);if(this.q||c)return;if(!this.m){this.z();var e=this;window.setTimeout(function(){e.play(b)},500);return}this.e.src=this.C+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Play("+b+")"};i.prototype.stop=function(){if(this.i){this.i.parentNode.removeChild(this.i);this.i=null}if(this.q)return;if(!this.m)return;this.e.src=this.C+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Stop()"};i.prototype.getTime=function(){if(this.q)return-1;if(!this.m)return-1;var b="Time=",
c=unescape(document.location.hash);if(c.indexOf(b)==-1)return-1;var e=c.indexOf(b)+b.length,d=parseInt(c.substring(e),10);return d};i.prototype.aa=function(b){var c="";switch(b){case "alert":c="alert";break;case "deselect":c="deselect";break;case "item":c="item";break;case "list":c="list";break;case "select":c="select";break;case "success":c="success";break;case "wrap":c="wrap";break;default:}if(c==="")return;if(this.i===null){this.i=document.createElement("embed");this.i.height=0;this.i.width=0;
document.body.appendChild(this.i)}this.i.src=this.W+c};var j={};j.B=false;j.b=0;j.a=0;j.l=11;j.k=10;j.S="The following keys are available. N, start a new game. Arrow keys or H,J,K,L, navigate the board one ball at a time. A,E,T,B, jump to the edges of the board. Capital R,G,B,Y,P, jump to the next ball of that color. R, read the current row. C, read the current column. S, read the current stats. Equals, read the current number of balls remaining for each color. Space, click on the current ball. The first click selects the group and the second click confirms the selection.D, deselect the unconfirmed selection.U, undoes the last confirmed selection.";
j.t=null;j.d=new a(false);j.c=new i(true);j.f=function(){j.t.style.outline="none";var b=j.h(j.b,j.a),c=j.w(b),e=c+j.b+", "+j.a+".";b.alt=e;b.style.outline="black solid thin";j.t=b;j.d.O(b)};j.U={"s_green.gif":"Selected Green. ","s_blue.gif":"Selected Blue. ","s_purple.gif":"Selected Purple. ","s_red.gif":"Selected  Red. ","s_yellow.gif":"Selected Yellow. ","p_green.gif":"Green, ","p_blue.gif":"Blue, ","p_purple.gif":"Purple, ","p_red.gif":"Red, ","p_yellow.gif":"Yellow, ","p_white.gif":"dot, "};j.w=
function(b){var c=j.U[j.j(b)];return c};j.j=function(b){var c=b.src.toString(),e=c.lastIndexOf("/");return c.substring(e+1)};j.h=function(b,c){var e=b.toString(),d=c.toString();if(e.length<2)e="0"+e;if(d.length<2)d="0"+d;var f="r"+e+"c"+d;return document.getElementById(f)};j.N=function(){var b=document.getElementById("blockcount").textContent,c=document.getElementById("blockscore").textContent,e=document.getElementById("userscore").textContent;if(b===0)j.d.g("Score is "+e);else j.d.g(b+" blocks add "+
c+" to "+e)};j.ba=function(){var b=document.getElementById("red").textContent,c=document.getElementById("yellow").textContent,e=document.getElementById("green").textContent,d=document.getElementById("blue").textContent,f=document.getElementById("purple").textContent;j.d.g(b+" reds, "+c+" yellows, "+e+" greens, "+d+" blues, "+f+" purples.")};j.da=function(){var b="R "+j.b+": ",c=j.J();if(c==-1){b=b+"all blank!";c=j.k+1}else if(c>1)b=b+c+" blanks, ";else c=0;for(var e=c;e<=j.k;e++)b=b+j.w(j.h(j.b,e));
j.d.g(b)};j.ca=function(){var b="C "+j.a+": ",c=j.I();if(c==-1){b=b+"all blank!";c=j.l+1}else if(c>1)b=b+c+" blanks, ";else c=0;for(var e=c;e<=j.l;e++)b=b+j.w(j.h(e,j.a));j.d.g(b)};j.I=function(){for(var b=0;b<=j.l;b++){var c=j.h(b,j.a);if(j.j(c)!="p_white.gif")return b}return-1};j.J=function(){for(var b=0;b<=j.k;b++){var c=j.h(j.b,b);if(j.j(c)!="p_white.gif")return b}return-1};j.L=function(b,c){var e=j.h(b,c),d=j.j(e);if(d.indexOf("s_")===0)return true;return false};j.o=function(b){var c="p_"+b+
".gif",e="s_"+b+".gif",d=j.a,f=j.b,h=null;d++;for(;d<=j.k;d++){h=j.h(f,d);if(j.j(h)==c||j.j(h)==e){if(d+1==j.a||d-1==j.a)j.c.play("item");else j.c.play("list");j.a=d;j.b=f;j.f();return}}f++;for(;f<=j.l;f++)for(d=0;d<=j.k;d++){h=j.h(f,d);if(j.j(h)==c||j.j(h)==e){if(d==j.a&&(f+1==j.b||f-1==j.b))j.c.play("item");else j.c.play("list");j.a=d;j.b=f;j.f();return}}f=0;for(;f<=j.l;f++)for(d=0;d<=j.k;d++){h=j.h(f,d);if(j.j(h)==c||j.j(h)==e){j.c.play("wrap");j.a=d;j.b=f;j.f();return}}j.d.g("No "+b+" left.")};
j.fa=function(){var b=document.getElementById("menu-undo");if(b.disabled===true)j.d.g("Nothing to undo.");else{j.d.v(b,false);j.d.g("Last action undone.")}};j.Q=function(){j.b--;if(j.b<0){j.c.play("alert");j.b=0}else j.c.play("item");j.f()};j.H=function(){j.b++;if(j.b>j.l){j.c.play("alert");j.b=j.l}else j.c.play("item");j.f()};j.left=function(){j.a--;if(j.a<0){j.c.play("alert");j.a=0}else j.c.play("item");j.f()};j.right=function(){j.a++;if(j.a>j.k){j.c.play("alert");j.a=j.k}else j.c.play("item");
j.f()};j.$=function(b){if(b.charCode==110){j.b=0;j.a=0;j.d.v(document.getElementById("menu-start"),false);j.f();j.B=false}if(b.charCode==63)j.d.g(j.S);if(j.B===true)return false;var c=j.Z[b.keyCode]||j.V[b.charCode];if(c)return c();return false};j.z=function(){j.t=j.h(j.b,j.a);j.t.style.outline="black solid thin";document.addEventListener("keypress",j.$,true);alert=function(b){j.B=true;window.setTimeout(function(){j.d.g(b)},0)}};j.Z={38:j.Q,40:j.H,37:j.left,39:j.right};j.V={117:j.fa,97:function(){j.c.play("list");
var b=j.J();if(b!=-1)j.a=b;j.f()},101:function(){j.c.play("list");j.a=j.k;j.f()},116:function(){j.c.play("list");var b=j.I();if(b!=-1)j.b=b;j.f()},98:function(){j.c.play("list");j.b=j.l;j.f()},61:j.ba,107:j.Q,104:j.left,106:j.H,108:j.right,32:function(){var b=false;if(j.L(j.b,j.a))b=true;j.d.v(j.h(j.b,j.a),false);if(j.L(j.b,j.a)){j.c.play("select");j.N()}else{if(b)j.c.play("success");else j.c.play("alert");var c=document.getElementById("userscore").textContent;j.d.g("Total "+c)}},115:j.N,99:j.ca,
114:j.da,100:function(){j.c.play("deselect");jb.ia();j.d.g("Deselected. ")},82:function(){j.o("red")},71:function(){j.o("green")},66:function(){j.o("blue")},89:function(){j.o("yellow")},80:function(){j.o("purple")}};j.z();
 })();
