(function() { 
var b=false,f=null,h=true,k=function(a){this.A=0;this.p=f;this.w=b;this.b=f;this.e=b;var c=this,i=function(e){c.b=e.target;if(e.target.tagName=="INPUT"||e.target.tagName=="SELECT"||e.target.tagName=="TEXTAREA")c.e=h;return h};document.addEventListener("focus",i,h);var g=function(e){c.v(c.b,"aria-activedescendant");c.b=f;if(e.target.tagName=="INPUT"||e.target.tagName=="SELECT"||e.target.tagName=="TEXTAREA")c.e=b;return h};document.addEventListener("blur",g,h);if(a){this.w=h;document.addEventListener("keypress",
function(e){c.N(e,c)},h);document.body.O=h}this.m=document.body};k.prototype.n=function(){var a=this.m;while(a.nodeType!=9)a=a.parentNode;return a};
k.prototype.M=function(a,c){a.id||this.q(a);if(c){this.f(a,"live","rude");this.f(a,"atomic","true");var i=this.n(),g=i.createElement("div");g.textContent=" ";g.name="AxsJAX_dummyNode";a.lastChild&&a.lastChild.name&&a.lastChild.name==g.name&&a.removeChild(a.lastChild);a.appendChild(g)}else{var e=this.K(a,"role");this.f(a,"role","row");var j=this.b;if(!j||j.nodeType==9){this.m.tabIndex=-1;j=this.m}this.f(j,"activedescendant",f);j.focus();this.f(j,"activedescendant",a.id);var d=this;window.setTimeout(function(){e?
d.f(a,"role",e):d.v(a,"role")},0)}};
k.prototype.o=function(a,c){var i="AxsJAX_pixelAudioNode",g="AxsJAX_pixelAudioNode",e="data:image/gif;base64,R0lGODlhAQABAIAAANvf7wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",j=this.n(),d=f;if(c){if(c.previousSibling&&c.previousSibling.name==g)d=c.previousSibling;else{d=j.createElement("img");d.name=g;d.setAttribute("tabindex",0);d.style.outline="none";d.src=e;c.parentNode.insertBefore(d,c);this.J(d)}d.setAttribute("alt",a);d.setAttribute("title",a);window.setTimeout(function(){d.blur();d.focus()},0)}else{d=
j.getElementById(i);if(d&&d.alt==a)a=a+" ";if(!d){d=j.createElement("img");d.id=i;d.src=e;j.body.appendChild(d)}d.setAttribute("alt",a);d.setAttribute("title",a);this.M(d)}};k.prototype.q=function(a,c){if(!a)return"";if(a.id)return a.id;var i=c||"AxsJAX_ID_";a.id=i+this.A++;return a.id};k.prototype.N=function(a,c){if(!c.w)return h;if(a.keyCode==9&&c.p){c.p.focus();c.p=f}return h};
k.prototype.f=function(a,c,i){if(!a)return;c=c.toLowerCase();switch(c){case "live":c="aria-live";break;case "activedescendant":c="aria-activedescendant";break;case "atomic":c="aria-atomic";break;default:break}a.setAttribute(c,i)};k.prototype.K=function(a,c){return a.getAttribute(c)};k.prototype.v=function(a,c){a&&a.removeAttribute&&a.removeAttribute(c)};k.prototype.J=function(a){var c=this.q(a),i=this.n(),g=i.baseURI,e=g.indexOf("#");if(e!=-1)g=g.substring(0,e);i.location=g+"#"+c};
k.prototype.s=function(a,c){try{var i=c.ownerDocument.evaluate(a,c,f,XPathResult.ORDERED_NODE_ITERATOR_TYPE,f)}catch(g){return[]}var e=[];for(var j=i.iterateNext();j;j=i.iterateNext())e.push(j);return e};var l={};l.i="AxsJAX_srcText";l.l="AxsJAX_origText";l.B="There is no next page.";l.C="There is no previous page.";l.z="The following shortcut keys are available. Down arrow or N, go to the next result. Up arrow or P, go to the previous result. Right arrow or J, cycle to the next result. Left arrow or K, cycle to the previous result. G, toggle between the snippet provided by Google Image Search and the alt text from the source of image. Slash, jump to the search field. Escape, leave the search field. ";
l.d=f;l.c=[];l.a=0;l.e=b;l.b=f;l.j=b;l.g=f;l.L=function(){l.d=new k(h);document.addEventListener("keypress",l.G,h);document.addEventListener("focus",l.I,h);document.addEventListener("blur",l.D,h);l.F();l.j=b;window.setTimeout(l.h,100)};l.I=function(a){l.b=a.target;if(a.target.tagName=="INPUT"||a.target.tagName=="TEXTAREA")l.e=h};l.D=function(a){l.b=f;if(a.target.tagName=="INPUT"||a.target.tagName=="TEXTAREA")l.e=b};
l.G=function(a){if(a.ctrlKey)return h;if(a.keyCode==27){l.b.blur();return b}if(l.e)return h;if(a.charCode==106){l.h(h);return b}if(a.charCode==107){l.k(h);return b}if(a.charCode==110){l.h(b);return b}if(a.charCode==112){l.k(b);return b}if(a.charCode==47){document.getElementsByName("q")[0].focus();document.getElementsByName("q")[0].select();return b}if(a.charCode==103){var c=l.c[l.a];if(c.alt==c.getAttribute(l.l))l.H();else{c.alt=c.getAttribute(l.l);c.parentNode.blur();c.parentNode.focus()}return b}if(a.keyCode==
33){l.u();return b}if(a.keyCode==34){l.t();return b}if(a.keyCode==38){l.k(b);return b}if(a.keyCode==37){l.k(h);return b}if(a.keyCode==40){l.h(b);return b}if(a.keyCode==39){l.h(h);return b}if(a.charCode==63){l.d.o(l.z);return b}return h};
l.F=function(){l.c=[];l.a=-1;var a=document.getElementById("ImgContent"),c=l.d.s("table/tbody/tr[*]/td[contains(@id,'tDataImage')]",a),i=l.d.s("table/tbody/tr[*]/*[contains(@id,'tDataText')]",a);for(var g=0,e;e=c[g];g++){var j=e.firstChild.firstChild;j.setAttribute(l.l,i[g].textContent);j.setAttribute(l.i,"");j.alt=i[g].textContent;l.c.push(j)}};l.h=function(a){l.a++;if(l.a>=l.c.length)if(a)l.a=0;else{l.a=-1;l.t();return}var c=l.c[l.a];c.parentNode.focus()};
l.k=function(a){l.a--;if(l.a<0)if(a)l.a=l.c.length-1;else{l.u();return}var c=l.c[l.a];c.parentNode.focus()};l.t=function(){var a=document.getElementById("nn");if(!a){l.d.o(l.B);return}document.location=a.parentNode.href};l.u=function(){var a=document.getElementById("np");if(!a){l.d.o(l.C);return}document.location=a.parentNode.href};
l.H=function(){var a=l.c[l.a];if(a.getAttribute(l.i)){a.alt=a.getAttribute(l.i);a.parentNode.blur();a.parentNode.focus();return}if(l.j)return;l.j=h;var c=a.parentNode.href,i="/imgres?imgurl=",g="&imgrefurl=",e="&h=",j=c.substring(c.indexOf(i)+i.length,c.indexOf(g)),d=c.substring(c.indexOf(g)+g.length,c.indexOf(e));l.g=document.createElement("iframe");l.g.src=d+"#AxsJAX_Cmd=GetImgText(AxsJAX_Img="+j+",AxsJAX_ParentURL="+document.location;document.body.appendChild(l.g);window.setTimeout(function(){l.r(a)},
100)};l.r=function(a){if(!document.location.hash){window.setTimeout(function(){l.r(a)},100);return}var c=unescape(document.location.hash);if(c=="#NULL")c="No alt text available.";c=c.substr(1);document.location.hash="#";document.body.removeChild(l.g);l.g=f;a.setAttribute(l.i,c);a.alt=c;a.parentNode.blur();a.parentNode.focus();l.j=b};l.L();
 })();
