(function() { 
var b=function(a){this.A=0;this.p=null;this.w=false;this.b=null;this.e=false;var c=this,g=function(d){c.b=d.target;if(d.target.tagName=="INPUT"||d.target.tagName=="SELECT"||d.target.tagName=="TEXTAREA")c.e=true;return true};document.addEventListener("focus",g,true);var f=function(d){c.v(c.b,"aria-activedescendant");c.b=null;if(d.target.tagName=="INPUT"||d.target.tagName=="SELECT"||d.target.tagName=="TEXTAREA")c.e=false;return true};document.addEventListener("blur",f,true);if(a){this.w=true;document.addEventListener("keypress",
function(d){c.N(d,c)},true);document.body.O=true}this.m=document.body};b.prototype.n=function(){var a=this.m;while(a.nodeType!=9)a=a.parentNode;return a};b.prototype.M=function(a,c){if(!a.id)this.q(a);if(c){this.f(a,"live","rude");this.f(a,"atomic","true");var g=this.n(),f=g.createElement("div");f.textContent=" ";f.name="AxsJAX_dummyNode";if(a.lastChild&&a.lastChild.name&&a.lastChild.name==f.name)a.removeChild(a.lastChild);a.appendChild(f)}else{var d=this.K(a,"role");this.f(a,"role","row");var h=
this.b;if(!h||h.nodeType==9){this.m.tabIndex=-1;h=this.m}this.f(h,"activedescendant",null);h.focus();this.f(h,"activedescendant",a.id);var e=this;window.setTimeout(function(){if(d)e.f(a,"role",d);else e.v(a,"role")},0)}};b.prototype.o=function(a,c){var g="AxsJAX_pixelAudioNode",f="AxsJAX_pixelAudioNode",d="data:image/gif;base64,R0lGODlhAQABAIAAANvf7wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",h=this.n(),e=null;if(c){if(c.previousSibling&&c.previousSibling.name==f)e=c.previousSibling;else{e=h.createElement("img");
e.name=f;e.setAttribute("tabindex",0);e.style.outline="none";e.src=d;c.parentNode.insertBefore(e,c);this.J(e)}e.setAttribute("alt",a);e.setAttribute("title",a);window.setTimeout(function(){e.blur();e.focus()},0)}else{e=h.getElementById(g);if(!e){e=h.createElement("img");e.id=g;e.src=d;h.body.appendChild(e)}e.setAttribute("alt",a);e.setAttribute("title",a);this.M(e)}};b.prototype.q=function(a,c){if(!a)return"";if(a.id)return a.id;var g=c||"AxsJAX_ID_";a.id=g+this.A++;return a.id};b.prototype.N=function(a,
c){if(!c.w)return true;if(a.keyCode==9&&c.p){c.p.focus();c.p=null}return true};b.prototype.f=function(a,c,g){if(!a)return;c=c.toLowerCase();switch(c){case "live":c="aria-live";break;case "activedescendant":c="aria-activedescendant";break;case "atomic":c="aria-atomic";break;default:break}a.setAttribute(c,g)};b.prototype.K=function(a,c){return a.getAttribute(c)};b.prototype.v=function(a,c){if(a&&a.removeAttribute)a.removeAttribute(c)};b.prototype.J=function(a){var c=this.q(a),g=this.n(),f=g.P,d=f.indexOf("#");
if(d!=-1)f=f.substring(0,d);g.location=f+"#"+c};b.prototype.s=function(a,c){try{var g=c.ownerDocument.evaluate(a,c,null,XPathResult.ORDERED_NODE_ITERATOR_TYPE,null)}catch(f){return[]}var d=[];for(var h=g.iterateNext();h;h=g.iterateNext())d.push(h);return d};var i={};i.i="AxsJAX_srcText";i.l="AxsJAX_origText";i.B="There is no next page.";i.C="There is no previous page.";i.z="The following shortcut keys are available. Down arrow or N, go to the next result. Up arrow or P, go to the previous result. Right arrow or J, cycle to the next result. Left arrow or K, cycle to the previous result. G, toggle between the snippet provided by Google Image Search and the alt text from the source of image. Slash, jump to the search field. Escape, leave the search field. ";
i.d=null;i.c=[];i.a=0;i.e=false;i.b=null;i.j=false;i.g=null;i.L=function(){i.d=new b(true);document.addEventListener("keypress",i.G,true);document.addEventListener("focus",i.I,true);document.addEventListener("blur",i.D,true);i.F();i.j=false;window.setTimeout(i.h,100)};i.I=function(a){i.b=a.target;if(a.target.tagName=="INPUT"||a.target.tagName=="TEXTAREA")i.e=true};i.D=function(a){i.b=null;if(a.target.tagName=="INPUT"||a.target.tagName=="TEXTAREA")i.e=false};i.G=function(a){if(a.ctrlKey)return true;
if(a.keyCode==27){i.b.blur();return false}if(i.e)return true;if(a.charCode==106){i.h(true);return false}if(a.charCode==107){i.k(true);return false}if(a.charCode==110){i.h(false);return false}if(a.charCode==112){i.k(false);return false}if(a.charCode==47){document.getElementsByName("q")[0].focus();document.getElementsByName("q")[0].select();return false}if(a.charCode==103){var c=i.c[i.a];if(c.alt==c.getAttribute(i.l))i.H();else{c.alt=c.getAttribute(i.l);c.parentNode.blur();c.parentNode.focus()}return false}if(a.keyCode==
33){i.u();return false}if(a.keyCode==34){i.t();return false}if(a.keyCode==38){i.k(false);return false}if(a.keyCode==37){i.k(true);return false}if(a.keyCode==40){i.h(false);return false}if(a.keyCode==39){i.h(true);return false}if(a.charCode==63){i.d.o(i.z);return false}return true};i.F=function(){i.c=[];i.a=-1;var a=document.getElementById("ImgContent"),c=i.d.s("table/tbody/tr[*]/td[contains(@id,'tDataImage')]",a),g=i.d.s("table/tbody/tr[*]/*[contains(@id,'tDataText')]",a);for(var f=0,d;d=c[f];f++){var h=
d.firstChild.firstChild;h.setAttribute(i.l,g[f].textContent);h.setAttribute(i.i,"");h.alt=g[f].textContent;i.c.push(h)}};i.h=function(a){i.a++;if(i.a>=i.c.length)if(!a){i.a=-1;i.t();return}else i.a=0;var c=i.c[i.a];c.parentNode.focus()};i.k=function(a){i.a--;if(i.a<0)if(!a){i.u();return}else i.a=i.c.length-1;var c=i.c[i.a];c.parentNode.focus()};i.t=function(){var a=document.getElementById("nn");if(!a){i.d.o(i.B);return}document.location=a.parentNode.href};i.u=function(){var a=document.getElementById("np");
if(!a){i.d.o(i.C);return}document.location=a.parentNode.href};i.H=function(){var a=i.c[i.a];if(a.getAttribute(i.i)){a.alt=a.getAttribute(i.i);a.parentNode.blur();a.parentNode.focus();return}if(i.j)return;i.j=true;var c=a.parentNode.href,g="/imgres?imgurl=",f="&imgrefurl=",d="&h=",h=c.substring(c.indexOf(g)+g.length,c.indexOf(f)),e=c.substring(c.indexOf(f)+f.length,c.indexOf(d));i.g=document.createElement("iframe");i.g.src=e+"#AxsJAX_Cmd=GetImgText(AxsJAX_Img="+h+",AxsJAX_ParentURL="+document.location;
document.body.appendChild(i.g);window.setTimeout(function(){i.r(a)},100)};i.r=function(a){if(!document.location.hash){window.setTimeout(function(){i.r(a)},100);return}var c=unescape(document.location.hash);if(c=="#NULL")c="No alt text available.";c=c.substr(1);document.location.hash="#";document.body.removeChild(i.g);i.g=null;a.setAttribute(i.i,c);a.alt=c;a.parentNode.blur();a.parentNode.focus();i.j=false};i.L();
 })();
