(function() { 
var f=false,g=null,i=true,k=function(a){this.cb=0;this.O=g;this.Ta=f;this.p=g;this.W=f;var b=this,d=function(e){b.p=e.target;if(e.target.tagName=="INPUT"||e.target.tagName=="SELECT"||e.target.tagName=="TEXTAREA")b.W=i;return i};document.addEventListener("focus",d,i);var c=function(e){b.qa(b.p,"aria-activedescendant");b.p=g;if(e.target.tagName=="INPUT"||e.target.tagName=="SELECT"||e.target.tagName=="TEXTAREA")b.W=f;return i};document.addEventListener("blur",c,i);if(a){this.Ta=i;document.addEventListener("keypress",
function(e){b.Tb(e,b)},i);document.body.Ub=i}this.fa=document.body};k.prototype.t=function(){var a=this.fa;while(a.nodeType!=9)a=a.parentNode;return a};
k.prototype.Sa=function(a,b){a.id||this.Ea(a);if(b){this.J(a,"live","rude");this.J(a,"atomic","true");var d=this.t(),c=d.createElement("div");c.textContent=" ";c.name="AxsJAX_dummyNode";a.lastChild&&a.lastChild.name&&a.lastChild.name==c.name&&a.removeChild(a.lastChild);a.appendChild(c)}else{var e=this.xb(a,"role");this.J(a,"role","row");var h=this.p;if(!h||h.nodeType==9){this.fa.tabIndex=-1;h=this.fa}this.J(h,"activedescendant",g);h.focus();this.J(h,"activedescendant",a.id);var j=this;window.setTimeout(function(){e?
j.J(a,"role",e):j.qa(a,"role")},0)}};
k.prototype.z=function(a,b){var d="AxsJAX_pixelAudioNode",c="AxsJAX_pixelAudioNode",e="data:image/gif;base64,R0lGODlhAQABAIAAANvf7wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",h=this.t(),j=g;if(b){if(b.previousSibling&&b.previousSibling.name==c)j=b.previousSibling;else{j=h.createElement("img");j.name=c;j.setAttribute("tabindex",0);j.style.outline="none";j.src=e;b.parentNode.insertBefore(j,b);this.vb(j)}j.setAttribute("alt",a);j.setAttribute("title",a);window.setTimeout(function(){j.blur();j.focus()},0)}else{j=
h.getElementById(d);if(j&&j.alt==a)a=a+" ";if(!j){j=h.createElement("img");j.id=d;j.src=e;h.body.appendChild(j)}j.setAttribute("alt",a);j.setAttribute("title",a);this.Sa(j)}};
k.prototype.qb=function(a,b){var d=this.t(),c=d.createEvent("MouseEvents");c.initMouseEvent("mousedown",i,i,d.defaultView,1,0,0,0,0,f,f,b,f,0,g);try{a.dispatchEvent(c)}catch(e){}c=d.createEvent("MouseEvents");c.initMouseEvent("mouseup",i,i,d.defaultView,1,0,0,0,0,f,f,b,f,0,g);try{a.dispatchEvent(c)}catch(e){}c=d.createEvent("MouseEvents");c.initMouseEvent("click",i,i,d.defaultView,1,0,0,0,0,f,f,b,f,0,g);try{a.dispatchEvent(c)}catch(e){}if(a.tagName=="A"&&a.href&&(a.href.indexOf("http")===0||a.href.indexOf("javascript:")===
0))if(b)window.open(a.href);else document.location=a.href};k.prototype.Ea=function(a,b){if(!a)return"";if(a.id)return a.id;var d=b||"AxsJAX_ID_";a.id=d+this.cb++;return a.id};k.prototype.Qa=function(a){if(!a)return f;if(a.tagName=="A"||a.tagName=="INPUT"){this.O=a;return i}var b=a.getElementsByTagName("*");for(var d=0,c;c=b[d];d++)if(c.tagName=="A"||c.tagName=="INPUT"||c.hasAttribute("tabindex")&&c.tabIndex!=-1){this.O=c;return i}return f};
k.prototype.Tb=function(a,b){if(!b.Ta)return i;if(a.keyCode==9&&b.O){b.O.focus();b.O=g}return i};k.prototype.Ma=function(a){this.Sa(a);a.scrollIntoView(i);this.Qa(a)};k.prototype.J=function(a,b,d){if(!a)return;b=b.toLowerCase();switch(b){case "live":b="aria-live";break;case "activedescendant":b="aria-activedescendant";break;case "atomic":b="aria-atomic";break;default:break}a.setAttribute(b,d)};k.prototype.xb=function(a,b){return a.getAttribute(b)};
k.prototype.qa=function(a,b){a&&a.removeAttribute&&a.removeAttribute(b)};k.prototype.vb=function(a){var b=this.Ea(a),d=this.t(),c=d.baseURI,e=c.indexOf("#");if(e!=-1)c=c.substring(0,e);d.location=c+"#"+b};k.prototype.V=function(a,b){try{var d=b.ownerDocument.evaluate(a,b,g,XPathResult.ORDERED_NODE_ITERATOR_TYPE,g)}catch(c){return[]}var e=[];for(var h=d.iterateNext();h;h=d.iterateNext())e.push(h);return e};var l=function(a){this.ba="";this.da="";this.b=[];this.a=0;this.e=[];this.l=g;this.P=[];this.B={};this.C={};this.A=[];this.u=[];this.g=a;this.q=g;this.dc=g;this.r=g;this.db="list";this.xa="item";this.Da="wrap";this.X=g};l.f={eb:"next list",hb:"previous list",ab:"go forward",$a:"go backwards",Wa:"cycle next",Xa:"cycle previous",$b:"Select available action",Yb:"No available actions",Aa:"Page up",za:"Page down",wa:"Enter",Wb:"Escape",Vb:"Delete",Ca:"Up",va:"Down",ya:"Left",Ba:"Right"};
l.prototype.ua=function(a){var b=i;if(a.type=="dynamic"&&a.h.length===0){this.q!==g&&this.q.view(g);a.h=this.Z(a.ca);a.j=this.Pa(a.ca);if(this.b[this.a]===a)this.e[this.a]=-1;else for(var d=0,c;c=this.b[d];d++)if(c===a){this.e[d]=-1;break}}if(a.h.length===0&&a.ia===g)b=f;return b};l.prototype.Ja=function(){var a=this.G(),b=a.ia,d=g;if(b!==g){this.Q(b);d=this.ka(b.action)}if(d===g){this.lb();this.r!==g&&this.r.play(this.db)}};
l.prototype.Jb=function(){if(this.b.length<1)return g;for(var a=0;this.b[a];a++){this.a++;if(this.a>=this.b.length)this.a=0;if(this.ua(this.b[this.a]))break}return this.G()};l.prototype.Lb=function(){if(this.b.length<1)return g;for(var a=0;this.b[a];a++){this.a--;if(this.a<0)this.a=this.b.length-1;if(this.ua(this.b[this.a]))break}return this.G()};l.prototype.G=function(){return this.b[this.a]};l.prototype.lb=function(){this.g.z(this.G().title)};
l.prototype.aa=function(){if(this.b.length<1)return g;var a=this.b[this.a],b=a.h;if(b.length<1)return g;if(this.l){var d=this.l.i.K[this.a];if(typeof d!="undefined")this.e[this.a]=d}this.e[this.a]++;var c=f;if(this.e[this.a]>=b.length){this.e[this.a]=0;c=i}var e=this.e[this.a];if(b[e].i.parentNode===g){this.q!==g&&this.q.view(g);a.h=this.Z(a.ca);this.e[this.a]=0;e=this.e[this.a]}this.l=b[e];if(this.r!==g)c?this.r.play(this.Da):this.r.play(this.xa);return this.l};
l.prototype.wb=function(){var a=this.b[this.a],b=this.e[this.a];if(a.ta!==g&&b+1>=a.h.length){this.Q(a.ta);this.e[this.a]=0;return g}var d=this.aa();return d};
l.prototype.Ra=function(){if(this.b.length<1)return g;var a=this.b[this.a],b=a.h;if(b.length<1)return g;if(this.l){var d=this.l.i.K[this.a];if(typeof d!="undefined")this.e[this.a]=d}this.e[this.a]--;var c=f;if(this.e[this.a]<0){this.e[this.a]=b.length-1;c=i}var e=this.e[this.a];if(b[e].i.parentNode===g){this.q!==g&&this.q.view(g);a.h=this.Z(a.ca);this.e[this.a]=a.h.length;e=this.e[this.a]}this.l=b[e];if(this.r!==g)c?this.r.play(this.Da):this.r.play(this.xa);return this.l};
l.prototype.ob=function(){var a=this.b[this.a],b=this.e[this.a];if(a.la!==g&&b-1<=-1){this.Q(a.la);this.e[this.a]=a.h.length;return g}var d=this.Ra();return d};l.prototype.ha=function(){if(this.b.length<1)return g;if(this.l){var a=this.l.i.K[this.a];if(typeof a!="undefined")this.e[this.a]=a}var b=this.b[this.a],d=b.h,c=this.e[this.a];this.l=d[c];return this.l};l.prototype.ka=function(a){var b=g;if(a!==g&&a.indexOf&&a.indexOf("CALL:")===0&&a.indexOf("(")===-1)try{b=eval(a.substring(5))}catch(d){}return b};
l.prototype.L=function(a){if(a!==g){var b=this,d=function(){var j=b.ka(a.action);if(j)j(a);else{b.q!==g&&b.q.view(a.i);b.g.Ma(a.i)}};if(this.g.p&&this.g.p.blur){var c=this.g.p;this.g.p=g;c.removeAttribute&&this.g.qa(c,"aria-activedescendant");var e=function(j){j.target.removeEventListener("blur",e,i);d()};c.addEventListener("blur",e,i);c.blur()}else d()}else{var h=this.b[this.a];h.type=="dynamic"&&this.g.z(h.onEmpty)}};
l.prototype.o=function(a,b,d,c){for(var e=0,h;h=a[e];e++)if(h=="LEFT")d[37]=c;else if(h=="UP")d[38]=c;else if(h=="RIGHT")d[39]=c;else if(h=="DOWN")d[40]=c;else if(h=="PGUP")d[33]=c;else if(h=="PGDOWN")d[34]=c;else if(h=="ENTER")d[13]=c;else if(h=="ESC")d[27]=c;else if(h=="DEL")d[46]=c;else b[h.charCodeAt(0)]=c};
l.prototype.S=function(a,b,d){var c=[];if(a==="")return;c=a.split(" ");var e=this;if(d=="prev")this.o(c,this.A[b],this.u[b],function(){e.L(e.Ra())});else if(d=="next")this.o(c,this.A[b],this.u[b],function(){e.L(e.aa())});else d=="back"?this.o(c,this.A[b],this.u[b],function(){e.L(e.ob())}):this.o(c,this.A[b],this.u[b],function(){e.L(e.wb())})};
l.prototype.nb=function(a,b,d){var c=[];if(a==="")return;c=a.split(" ");var e=this;this.o(c,this.B,this.C,function(){if(!e.ua(e.b[b])){e.g.z(d);return}e.a=b;e.L(e.aa())})};l.prototype.mb=function(a,b){var d=[];if(a==="")return;d=a.split(" ");var c=this;this.o(d,this.B,this.C,function(){c.g.z(b)})};l.prototype.Fa=function(a,b,d){var c=[];if(a.hotkey==="")return;c=a.hotkey.split(" ");var e=this;this.o(c,b,d,function(){e.Q(a)})};
l.prototype.Q=function(a){var b=a.c,d=this.g.t().documentElement;if(b.indexOf(".")===0)d=this.ha().i;var c=this.g.V(b,d);if(c.length<1)this.g.z(a.onEmpty);else{var e=this.ka(a.action);if(e){var h={};h.action=a.action;h.i=c[0];e(h)}else{this.g.qb(c[0],f);c[0].scrollIntoView(i)}this.g.Qa(c[0])}};l.prototype.yb=function(a,b){var d=g,c=this.a;if(c<this.u.length)d=this.u[c][a]||this.A[c][b]||g;if(d===g)d=this.C[a]||this.B[b];return d};
l.prototype.Bb=function(){var a=this.zb(),b="";for(var d=0,c;c=a[d];d++)b=b+c.Y+", "+c.title+". ";b=b+this.ba+", "+l.f.eb;b=b+this.da+", "+l.f.hb;b=b.replace("PGUP",l.f.Aa);b=b.replace("PGDOWN",l.f.za);b=b.replace("ENTER",l.f.wa);b=b.replace("DEL",l.f.Ya);b=b.replace("UP",l.f.Ca);b=b.replace("DOWN",l.f.va);b=b.replace("LEFT",l.f.ya);b=b.replace("RIGHT",l.f.Ba);return b};
l.prototype.Gb=function(){var a=this.Ab(),b="";for(var d=0,c;c=a[d];d++)b=b+c.Y+", "+c.title+". ";var e=this.G();if(e.oa!=="")b=b+e.oa+", "+l.f.Wa+". ";if(e.pa!=="")b=b+e.pa+", "+l.f.Xa+". ";if(e.ja!=="")b=b+e.ja+", "+l.f.ab+". ";if(e.ga!=="")b=b+e.ga+", "+l.f.$a+". ";b=b.replace("PGUP",l.f.Aa);b=b.replace("PGDOWN",l.f.za);b=b.replace("ENTER",l.f.wa);b=b.replace("DEL",l.f.Ya);b=b.replace("UP",l.f.Ca);b=b.replace("DOWN",l.f.va);b=b.replace("LEFT",l.f.ya);b=b.replace("RIGHT",l.f.Ba);return b};
l.prototype.Ob=function(a){this.q=a};l.prototype.Pb=function(a){this.r=a};l.prototype.zb=function(){var a=[],b;for(var d=0,c;c=this.b[d];d++)if(c.M!==""){b={};b.title=c.title;b.Y=c.M;a.push(b)}for(var e=0,h;h=this.P[e];e++)if(this.Na(h)){b={};b.title=h.title;b.Y=h.hotkey;a.push(b)}return a};l.prototype.Ab=function(){var a=[],b=this.G();for(var d=0,c;c=b.j[d];d++)if(this.Na(c)){var e={};e.title=c.title;e.Y=c.hotkey;a.push(e)}return a};
l.prototype.Na=function(a){var b=f;if(a.hotkey!==""){var d=a.c,c=this.g.t().body;if(d.indexOf(".")===0){var e=this.ha();if(e)c=e.i}var h=this.g.V(d,c);if(h.length>0)b=i}return b};
l.prototype.Ib=function(a,b){this.b=[];this.a=0;this.e=[];var d=[],c,e;for(c=0,e;e=a.Fb[c];c++){var h={};h.bc=g;h.ca=e;h.title=e.title||"";h.M=e.hotkey||"";h.oa=e.v||"";h.pa=e.w||"";h.ja=e.H||"";h.ga=e.back||"";h.onEmpty=e.onEmpty||"";h.type=e.type||"";h.ta=g;h.la=g;h.ia=g;h.h=this.Z(e);h.j=this.Pa(e);for(var j=0,p;p=h.j[j];j++)if(p.trigger=="listTail")h.ta=p;else if(p.trigger=="listHead")h.la=p;else if(p.trigger=="listEntry")h.ia=p;if(h.h.length>0||h.type=="dynamic"){this.b.push(h);this.e.push(-1)}else h.M!==
""&&d.push(h)}this.P=[];this.ec=0;var m;if(a.j)for(c=0,m;m=a.j[c];c++){var n={};n.c=m.c;n.c=n.c.replace(/^\s\s*/,"").replace(/\s\s*$/,"");n.title=m.title||"";n.trigger=m.trigger||"key";n.hotkey=m.hotkey||"";n.action=m.action||"click";n.onEmpty=m.onEmpty||"";this.P.push(n)}this.X!==g&&document.removeEventListener("keypress",this.X,i);b===g||typeof b=="undefined"?this.Qb(a,d):b(a,this.b,d,this.P)};
l.prototype.Z=function(a){var b=[];if(!a.h)return b;for(var d=0,c;c=a.h[d];d++)try{var e=c.c.replace(/^\s\s*/,"").replace(/\s\s*$/,""),h=this.g.t().documentElement,j=this.g.V(e,h),p=c.index||"0",m=parseInt(p,10),n=j.length-m,r=c.F||"*";if(r!="*")n=parseInt(r,10);var u=n+m,v=c.action||g;while(m<u){var s={};s.action=v;s.i=j[m];if(typeof s.i!="undefined"){if(typeof s.i.K=="undefined")s.i.K={};s.i.K[this.b.length]=b.length;b.push(s)}m++}}catch(w){}return b};
l.prototype.Pa=function(a){var b=[];if(!a.j)return b;for(var d=0,c;c=a.j[d];d++){var e={};e.c=c.c.replace(/^\s\s*/,"").replace(/\s\s*$/,"");e.title=c.title||"";e.trigger=c.trigger||"key";e.hotkey=c.hotkey||"";e.action=c.action||"click";e.onEmpty=c.onEmpty||"";b.push(e)}return b};
l.prototype.Qb=function(a,b){var d=this,c;this.B={};this.C={};this.A=[];this.u=[];var e;for(c=0,e;e=this.P[c];c++)this.Fa(e,this.B,this.C);var h=[];this.ba=a.v||"";if(this.ba!=="")h=this.ba.split(" ");this.o(h,this.B,this.C,function(){d.Jb();d.Ja()});h=[];this.da=a.w||"";if(this.da!=="")h=this.da.split(" ");this.o(h,this.B,this.C,function(){d.Lb();d.Ja()});var j;for(c=0,j;j=this.b[c];c++){var p={},m={};this.A.push(p);this.u.push(m);this.S(j.oa,c,"next");this.S(j.pa,c,"prev");this.S(j.ja,c,"fwd");
this.S(j.ga,c,"back");this.nb(j.M,c,j.onEmpty);var n;for(n=0,e;e=j.j[n];n++)this.Fa(e,p,m)}var r;for(c=0,r;r=b[c];c++)this.mb(r.M,r.onEmpty);this.X=function(u){if(u.ctrlKey)return i;if(d.g.W)return i;var v=d.yb(u.keyCode,u.charCode);if(v)return v()};document.addEventListener("keypress",this.X,i)};var o=function(a){this.m=a;this.$=1.5;this.padding=-1;this.Nb=0;this.R=a.t();this.d=this.R.createElement("span");this.d.style.backgroundColor="#CCE6FF";this.d.style.borderColor="#0000CC";this.d.style.borderWidth="medium";this.d.style.borderStyle="groove";this.d.style.position="absolute";this.d.style.display="none";this.R.body.appendChild(this.d);this.Ha=function(){}};o.ib={Xb:0,Za:1};
o.prototype.view=function(a){while(this.d.firstChild)this.d.removeChild(this.d.firstChild);if(a===g){this.d.style.display="none";return}var b=0,d=0,c=a;if(c.offsetParent){b=c.offsetLeft;d=c.offsetTop;c=c.offsetParent;while(c!==g){b+=c.offsetLeft;d+=c.offsetTop;c=c.offsetParent}}this.d.appendChild(a.cloneNode(i));this.d.style.top=d+"px";this.d.style.left=b+"px";this.d.style.zIndex=999;this.d.style.display="block";this.Oa()};o.prototype.ra=function(a){this.$=a;this.Oa()};
o.prototype.Oa=function(){this.R.body.removeChild(this.d);this.Hb();this.tb();this.kb();this.R.body.appendChild(this.d);this.Ha&&this.Ha(this.d);if(this.Nb==o.ib.Za){var a=this;window.setTimeout(function(){a.d.scrollIntoView(i)},0)}};o.prototype.kb=function(){if(this.padding<0)return;var a="//*[not(.//*)]",b=this.m.V(a,this.d);for(var d=0,c;c=b[d];d++)c.style.padding=this.padding+"px"};
o.prototype.tb=function(){var a=this.d.getElementsByTagName("img");for(var b=0,d;d=a[b];b++){if(!d.hasAttribute("Axs_OrigHeight")){d.setAttribute("Axs_OrigHeight",d.height);d.setAttribute("Axs_OrigWidth",d.width)}d.height=d.getAttribute("Axs_OrigHeight")*this.$;d.width=d.getAttribute("Axs_OrigWidth")*this.$}};o.prototype.Hb=function(){var a=this.$*0.52;this.d.style.fontSizeAdjust=a;var b=this.d.getElementsByTagName("*");for(var d=0,c;c=b[d];d++)c.style.setProperty("line-height","normal","important")};var q=function(a){var b="http://google-axsjax.googlecode.com/svn/trunk/";this.sb=b+"common/earcons/axsEarcons.swf?sound=";this.n=g;this.U=a;this.sa=b+"thirdparty/soundmanager2/";this.k=g;this.I=f;this.Ua="minimal";this.T=f;this.na=0};
q.prototype.ma=function(){if(this.U)return;if(this.I)return;if(this.T)return;this.T=i;this.na=0;if(this.k!==g){this.k.parentNode.removeChild(this.k);this.k=g}this.k=document.createElement("iframe");var a=document.location.toString();if(a.indexOf("#")!=-1)a=a.substring(0,a.indexOf("#"));this.k.src=this.sa+"AxsJAX_SM2_Linker.html#Verbosity="+this.Ua+",Parent="+a;this.k.width="0%";this.k.height="0%";this.k.style.top="-1000";this.k.style.left="-1000";this.k.style.position="absolute";document.getElementsByTagName("body")[0].appendChild(this.k);
this.Ia()};q.prototype.Ia=function(){if(document.location.hash=="#InitSuccess"){this.I=i;this.T=f;return}if(this.Ua=="none"&&this.na>0){this.I=i;this.T=f;return}var a=this;window.setTimeout(function(){a.Ia()},100);this.na++};q.prototype.play=function(a){var b=this.Kb(a);if(this.U||b)return;if(!this.I){this.ma();var d=this;window.setTimeout(function(){d.play(a)},500);return}this.k.src=this.sa+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Play("+a+")"};
q.prototype.stop=function(){if(this.n){this.n.parentNode.removeChild(this.n);this.n=g}if(this.U)return;if(!this.I)return;this.k.src=this.sa+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Stop()"};q.prototype.getTime=function(){if(this.U)return-1;if(!this.I)return-1;var a="Time=",b=unescape(document.location.hash);if(b.indexOf(a)==-1)return-1;var d=b.indexOf(a)+a.length,c=parseInt(b.substring(d),10);return c};
q.prototype.Kb=function(a){var b="";switch(a){case "alert":b="alert";break;case "deselect":b="deselect";break;case "item":b="item";break;case "list":b="list";break;case "select":b="select";break;case "success":b="success";break;case "wrap":b="wrap";break;default:}if(b==="")return;if(this.n===g){this.n=document.createElement("embed");this.n.height=0;this.n.width=0;document.body.appendChild(this.n)}this.n.src=this.sb+b};var t={};t.Va="http://www.google.com/cse?cx=000183394137052953072%3Azc1orsc6mbq&q=";t.jb="http://www.google.com/search?q=";t.bb="The following shortcut keys are available. ";t.ea="Slash, enter search field. Escape, leave search field. Equals, enlarge the current item. Minus, shrink the current item. ";t.Zb="Searches related to:";t.fb="You are already on Google accessible search.";t.gb="You are already on Google web search.";t.ac="Sponsored link. ";t.m=g;t.s=g;t.D=g;t.N=1.5;t.Ga=g;
t.ma=function(){t.m=new k(i);t.s=new l(t.m);document.addEventListener("keypress",t.ub,i);var a={Fb:[{title:"One Box",hotkey:"1",v:"DOWN j",w:"UP k",H:g,back:g,onEmpty:"There is no one box on this page.",type:g,h:[{c:'id("res")//div[contains(@class,"rbt")]',F:"1"},{c:'//tr[@class="std"]/..',F:"1"},{c:'id("res")/div[@class="e"]/table[not(contains(@id,"brs"))]/..',F:"1"},{c:'id("res")/p[*]',F:"1",cc:"Use [*] since some one boxes have an extra node at the start."},{c:'//td/h2[@class="r"]/..',F:"1"}],
j:[]},{title:"Results",hotkey:"n",v:"DOWN j",w:"UP k",H:"n",back:"p",onEmpty:g,type:g,h:[{c:'id("res")/div[@class="med"]',F:"1"},{c:'id("res")//*[@class="g"]'}],j:[{c:'id("nn")/..',title:"Next page",trigger:"listTail"},{c:'id("np")/..',title:"Prev page",trigger:"listHead"}]},{title:"Sponsored Links",hotkey:"a",v:"DOWN j",w:"UP k",H:g,back:g,onEmpty:"There are no sponsored links on this page.",type:g,h:[{c:'id("tads")//li'},{c:'id("mbEnd")//li'}],j:[]},{title:"Related Searches",hotkey:"s",v:"DOWN j",
w:"UP k",H:g,back:g,onEmpty:"There are no related searches.",type:g,h:[{c:'id("brs")//a/b/..'}],j:[]},{title:"Alternate Search Categories",hotkey:"c",v:"DOWN j",w:"UP k",H:g,back:g,onEmpty:"There are no other categories to search within.",type:g,h:[{c:'id("prs")/a'}],j:[]},{title:"Google Services",hotkey:"g",v:"DOWN j",w:"UP k",H:g,back:g,onEmpty:g,type:g,h:[{c:'id("gbar")//a[@class="gb1"]'},{c:'id("gbar")//a[@class="gb2"]'},{c:'id("gb")//a'}],j:[]}],j:[{c:'id("nn")/..',title:"Next page",hotkey:"PGDOWN"},
{c:'id("np")/..',title:"Previous page",hotkey:"PGUP"}],v:"RIGHT l",w:"LEFT h"};t.s.Ib(a,g);t.ea=t.s.Bb()+t.ea;t.D=new o(t.m);t.s.Ob(t.D);t.D.ra(t.N);t.Ga=new q(i);t.s.Pb(t.Ga);window.setTimeout(t.Mb,100)};t.Mb=function(){var a=t.s.aa().i;t.D.view(a);t.m.Ma(a)};t.Cb=function(){var a=t.Ka();if(a==="")return;document.location=a};t.Db=function(){var a=t.Ka();if(a==="")return;window.open(a)};t.Ka=function(){var a=t.s.ha();if(typeof a=="undefined")return"";var b=a.i;return b.tagName=="A"?b.href:b.getElementsByTagName("a")[0].href};
t.La=function(){var a=document.baseURI,b=a.indexOf("q=")+2,d=a.indexOf("&",b);if(d==-1)d=a.length;return a.substring(b,d)};t.Rb=function(){if(document.baseURI.indexOf("http://www.google.com/custom")===0||document.baseURI.indexOf("http://www.google.com/cse")===0){t.m.z(t.fb);return}var a=t.La();document.location=t.Va+a};t.Sb=function(){if(document.baseURI.indexOf("http://www.google.com/search")===0){t.m.z(t.gb);return}var a=t.La();document.location=t.jb+a};t.Eb=function(){t.N+=0.1;t.D.ra(t.N)};
t.rb=function(){t.N-=0.1;t.D.ra(t.N)};t.ub=function(a){if(a.ctrlKey)return i;if(a.keyCode==27){t.m.p.blur();return f}if(t.m.W)return i;if(a.keyCode==13){a.shiftKey?t.Db():t.Cb();return f}var b=t.pb[a.charCode];if(b)return b();return i};
t.pb={63:function(){var a=t.bb+t.s.Gb()+t.ea;t.m.z(a);return f},45:function(){t.rb();return f},61:function(){t.Eb();return f},47:function(){document.getElementsByName("q")[0].focus();document.getElementsByName("q")[0].select();return f},65:function(){t.Rb();return f},87:function(){t.Sb();return f}};window.addEventListener("load",t.ma,i);t.ma();
 })();
