(function() { 
var f=false,g=null,i=true,k=function(a){this.cb=0;this.P=g;this.Ta=f;this.p=g;this.W=f;var b=this,d=function(e){b.p=e.target;if(e.target.tagName=="INPUT"||e.target.tagName=="SELECT"||e.target.tagName=="TEXTAREA")b.W=i;return i};document.addEventListener("focus",d,i);var c=function(e){b.ra(b.p,"aria-activedescendant");b.p=g;if(e.target.tagName=="INPUT"||e.target.tagName=="SELECT"||e.target.tagName=="TEXTAREA")b.W=f;return i};document.addEventListener("blur",c,i);if(a){this.Ta=i;document.addEventListener("keypress",
function(e){b.Vb(e,b)},i);document.body.Wb=i}this.fa=document.body};k.prototype.t=function(){var a=this.fa;while(a.nodeType!=9)a=a.parentNode;return a};
k.prototype.Sa=function(a,b){a.id||this.Fa(a);if(b){this.K(a,"live","rude");this.K(a,"atomic","true");var d=this.t(),c=d.createElement("div");c.textContent=" ";c.name="AxsJAX_dummyNode";a.lastChild&&a.lastChild.name&&a.lastChild.name==c.name&&a.removeChild(a.lastChild);a.appendChild(c)}else{var e=this.yb(a,"role");this.K(a,"role","row");var h=this.p;if(!h||h.nodeType==9){this.fa.tabIndex=-1;h=this.fa}this.K(h,"activedescendant",g);h.focus();this.K(h,"activedescendant",a.id);var j=this;window.setTimeout(function(){e?
j.K(a,"role",e):j.ra(a,"role")},0)}};
k.prototype.z=function(a,b){var d="AxsJAX_pixelAudioNode",c="AxsJAX_pixelAudioNode",e="data:image/gif;base64,R0lGODlhAQABAIAAANvf7wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",h=this.t(),j=g;if(b){if(b.previousSibling&&b.previousSibling.name==c)j=b.previousSibling;else{j=h.createElement("img");j.name=c;j.setAttribute("tabindex",0);j.style.outline="none";j.src=e;b.parentNode.insertBefore(j,b);this.wb(j)}j.setAttribute("alt",a);j.setAttribute("title",a);window.setTimeout(function(){j.blur();j.focus()},0)}else{j=
h.getElementById(d);if(j&&j.alt==a)a=a+" ";if(!j){j=h.createElement("img");j.id=d;j.src=e;h.body.appendChild(j)}j.setAttribute("alt",a);j.setAttribute("title",a);this.Sa(j)}};
k.prototype.qb=function(a,b){var d=this.t(),c=d.createEvent("MouseEvents");c.initMouseEvent("mousedown",i,i,d.defaultView,1,0,0,0,0,f,f,b,f,0,g);try{a.dispatchEvent(c)}catch(e){}c=d.createEvent("MouseEvents");c.initMouseEvent("mouseup",i,i,d.defaultView,1,0,0,0,0,f,f,b,f,0,g);try{a.dispatchEvent(c)}catch(e){}c=d.createEvent("MouseEvents");c.initMouseEvent("click",i,i,d.defaultView,1,0,0,0,0,f,f,b,f,0,g);try{a.dispatchEvent(c)}catch(e){}if(a.tagName=="A"&&a.href&&(a.href.indexOf("http")===0||a.href.indexOf("javascript:")===
0))if(b)window.open(a.href);else document.location=a.href};k.prototype.Fa=function(a,b){if(!a)return"";if(a.id)return a.id;var d=b||"AxsJAX_ID_";a.id=d+this.cb++;return a.id};k.prototype.Qa=function(a){if(!a)return f;if(a.tagName=="A"||a.tagName=="INPUT"){this.P=a;return i}var b=a.getElementsByTagName("*");for(var d=0,c;c=b[d];d++)if(c.tagName=="A"||c.tagName=="INPUT"||c.hasAttribute("tabindex")&&c.tabIndex!=-1){this.P=c;return i}return f};
k.prototype.Vb=function(a,b){if(!b.Ta)return i;if(a.keyCode==9&&b.P){b.P.focus();b.P=g}return i};k.prototype.Ma=function(a){this.Sa(a);a.scrollIntoView(i);this.Qa(a)};k.prototype.K=function(a,b,d){if(!a)return;b=b.toLowerCase();switch(b){case "live":b="aria-live";break;case "activedescendant":b="aria-activedescendant";break;case "atomic":b="aria-atomic";break;default:break}a.setAttribute(b,d)};k.prototype.yb=function(a,b){return a.getAttribute(b)};
k.prototype.ra=function(a,b){a&&a.removeAttribute&&a.removeAttribute(b)};k.prototype.wb=function(a){var b=this.Fa(a),d=this.t(),c=d.baseURI,e=c.indexOf("#");if(e!=-1)c=c.substring(0,e);d.location=c+"#"+b};k.prototype.H=function(a,b){try{var d=b.ownerDocument.evaluate(a,b,g,XPathResult.ORDERED_NODE_ITERATOR_TYPE,g)}catch(c){return[]}var e=[];for(var h=d.iterateNext();h;h=d.iterateNext())e.push(h);return e};var l=function(a){this.ba="";this.da="";this.b=[];this.a=0;this.e=[];this.m=g;this.Q=[];this.C={};this.D={};this.B=[];this.u=[];this.g=a;this.q=g;this.fc=g;this.r=g;this.db="list";this.ya="item";this.Ea="wrap";this.X=g};l.f={eb:"next list",hb:"previous list",ab:"go forward",$a:"go backwards",Wa:"cycle next",Xa:"cycle previous",bc:"Select available action",$b:"No available actions",Ba:"Page up",Aa:"Page down",xa:"Enter",Yb:"Escape",Xb:"Delete",Da:"Up",wa:"Down",za:"Left",Ca:"Right"};
l.prototype.va=function(a){var b=i;if(a.type=="dynamic"&&a.h.length===0){this.q!==g&&this.q.view(g);a.h=this.Z(a.ca);a.j=this.Pa(a.ca);if(this.b[this.a]===a)this.e[this.a]=-1;else for(var d=0,c;c=this.b[d];d++)if(c===a){this.e[d]=-1;break}}if(a.h.length===0&&a.ja===g)b=f;return b};l.prototype.Ja=function(){var a=this.G(),b=a.ja,d=g;if(b!==g){this.R(b);d=this.la(b.action)}if(d===g){this.lb();this.r!==g&&this.r.play(this.db)}};
l.prototype.Kb=function(){if(this.b.length<1)return g;for(var a=0;this.b[a];a++){this.a++;if(this.a>=this.b.length)this.a=0;if(this.va(this.b[this.a]))break}return this.G()};l.prototype.Mb=function(){if(this.b.length<1)return g;for(var a=0;this.b[a];a++){this.a--;if(this.a<0)this.a=this.b.length-1;if(this.va(this.b[this.a]))break}return this.G()};l.prototype.G=function(){return this.b[this.a]};l.prototype.lb=function(){this.g.z(this.G().title)};
l.prototype.aa=function(){if(this.b.length<1)return g;var a=this.b[this.a],b=a.h;if(b.length<1)return g;if(this.m){var d=this.m.i.L[this.a];if(typeof d!="undefined")this.e[this.a]=d}this.e[this.a]++;var c=f;if(this.e[this.a]>=b.length){this.e[this.a]=0;c=i}var e=this.e[this.a];if(b[e].i.parentNode===g){this.q!==g&&this.q.view(g);a.h=this.Z(a.ca);this.e[this.a]=0;e=this.e[this.a]}this.m=b[e];if(this.r!==g)c?this.r.play(this.Ea):this.r.play(this.ya);return this.m};
l.prototype.xb=function(){var a=this.b[this.a],b=this.e[this.a];if(a.ua!==g&&b+1>=a.h.length){this.R(a.ua);this.e[this.a]=0;return g}var d=this.aa();return d};
l.prototype.Ra=function(){if(this.b.length<1)return g;var a=this.b[this.a],b=a.h;if(b.length<1)return g;if(this.m){var d=this.m.i.L[this.a];if(typeof d!="undefined")this.e[this.a]=d}this.e[this.a]--;var c=f;if(this.e[this.a]<0){this.e[this.a]=b.length-1;c=i}var e=this.e[this.a];if(b[e].i.parentNode===g){this.q!==g&&this.q.view(g);a.h=this.Z(a.ca);this.e[this.a]=a.h.length;e=this.e[this.a]}this.m=b[e];if(this.r!==g)c?this.r.play(this.Ea):this.r.play(this.ya);return this.m};
l.prototype.ob=function(){var a=this.b[this.a],b=this.e[this.a];if(a.ma!==g&&b-1<=-1){this.R(a.ma);this.e[this.a]=a.h.length;return g}var d=this.Ra();return d};l.prototype.ia=function(){if(this.b.length<1)return g;if(this.m){var a=this.m.i.L[this.a];if(typeof a!="undefined")this.e[this.a]=a}var b=this.b[this.a],d=b.h,c=this.e[this.a];this.m=d[c];return this.m};l.prototype.la=function(a){var b=g;if(a!==g&&a.indexOf&&a.indexOf("CALL:")===0&&a.indexOf("(")===-1)try{b=eval(a.substring(5))}catch(d){}return b};
l.prototype.M=function(a){if(a!==g){var b=this,d=function(){var j=b.la(a.action);if(j)j(a);else{b.q!==g&&b.q.view(a.i);b.g.Ma(a.i)}};if(this.g.p&&this.g.p.blur){var c=this.g.p;this.g.p=g;c.removeAttribute&&this.g.ra(c,"aria-activedescendant");var e=function(j){j.target.removeEventListener("blur",e,i);d()};c.addEventListener("blur",e,i);c.blur()}else d()}else{var h=this.b[this.a];h.type=="dynamic"&&this.g.z(h.onEmpty)}};
l.prototype.o=function(a,b,d,c){for(var e=0,h;h=a[e];e++)if(h=="LEFT")d[37]=c;else if(h=="UP")d[38]=c;else if(h=="RIGHT")d[39]=c;else if(h=="DOWN")d[40]=c;else if(h=="PGUP")d[33]=c;else if(h=="PGDOWN")d[34]=c;else if(h=="ENTER")d[13]=c;else if(h=="ESC")d[27]=c;else if(h=="DEL")d[46]=c;else b[h.charCodeAt(0)]=c};
l.prototype.T=function(a,b,d){var c=[];if(a==="")return;c=a.split(" ");var e=this;if(d=="prev")this.o(c,this.B[b],this.u[b],function(){e.M(e.Ra())});else if(d=="next")this.o(c,this.B[b],this.u[b],function(){e.M(e.aa())});else d=="back"?this.o(c,this.B[b],this.u[b],function(){e.M(e.ob())}):this.o(c,this.B[b],this.u[b],function(){e.M(e.xb())})};
l.prototype.nb=function(a,b,d){var c=[];if(a==="")return;c=a.split(" ");var e=this;this.o(c,this.C,this.D,function(){if(!e.va(e.b[b])){e.g.z(d);return}e.a=b;e.M(e.aa())})};l.prototype.mb=function(a,b){var d=[];if(a==="")return;d=a.split(" ");var c=this;this.o(d,this.C,this.D,function(){c.g.z(b)})};l.prototype.Ga=function(a,b,d){var c=[];if(a.hotkey==="")return;c=a.hotkey.split(" ");var e=this;this.o(c,b,d,function(){e.R(a)})};
l.prototype.R=function(a){var b=a.c,d=this.g.t().documentElement;if(b.indexOf(".")===0)d=this.ia().i;var c=this.g.H(b,d);if(c.length<1)this.g.z(a.onEmpty);else{var e=this.la(a.action);if(e){var h={};h.action=a.action;h.i=c[0];e(h)}else{this.g.qb(c[0],f);c[0].scrollIntoView(i)}this.g.Qa(c[0])}};l.prototype.zb=function(a,b){var d=g,c=this.a;if(c<this.u.length)d=this.u[c][a]||this.B[c][b]||g;if(d===g)d=this.D[a]||this.C[b];return d};
l.prototype.Cb=function(){var a=this.Ab(),b="";for(var d=0,c;c=a[d];d++)b=b+c.Y+", "+c.title+". ";b=b+this.ba+", "+l.f.eb;b=b+this.da+", "+l.f.hb;b=b.replace("PGUP",l.f.Ba);b=b.replace("PGDOWN",l.f.Aa);b=b.replace("ENTER",l.f.xa);b=b.replace("DEL",l.f.Ya);b=b.replace("UP",l.f.Da);b=b.replace("DOWN",l.f.wa);b=b.replace("LEFT",l.f.za);b=b.replace("RIGHT",l.f.Ca);return b};
l.prototype.Hb=function(){var a=this.Bb(),b="";for(var d=0,c;c=a[d];d++)b=b+c.Y+", "+c.title+". ";var e=this.G();if(e.pa!=="")b=b+e.pa+", "+l.f.Wa+". ";if(e.qa!=="")b=b+e.qa+", "+l.f.Xa+". ";if(e.ka!=="")b=b+e.ka+", "+l.f.ab+". ";if(e.ga!=="")b=b+e.ga+", "+l.f.$a+". ";b=b.replace("PGUP",l.f.Ba);b=b.replace("PGDOWN",l.f.Aa);b=b.replace("ENTER",l.f.xa);b=b.replace("DEL",l.f.Ya);b=b.replace("UP",l.f.Da);b=b.replace("DOWN",l.f.wa);b=b.replace("LEFT",l.f.za);b=b.replace("RIGHT",l.f.Ca);return b};
l.prototype.Pb=function(a){this.q=a};l.prototype.Rb=function(a){this.r=a};l.prototype.Ab=function(){var a=[],b;for(var d=0,c;c=this.b[d];d++)if(c.N!==""){b={};b.title=c.title;b.Y=c.N;a.push(b)}for(var e=0,h;h=this.Q[e];e++)if(this.Na(h)){b={};b.title=h.title;b.Y=h.hotkey;a.push(b)}return a};l.prototype.Bb=function(){var a=[],b=this.G();for(var d=0,c;c=b.j[d];d++)if(this.Na(c)){var e={};e.title=c.title;e.Y=c.hotkey;a.push(e)}return a};
l.prototype.Na=function(a){var b=f;if(a.hotkey!==""){var d=a.c,c=this.g.t().body;if(d.indexOf(".")===0){var e=this.ia();if(e)c=e.i}var h=this.g.H(d,c);if(h.length>0)b=i}return b};
l.prototype.Jb=function(a,b){this.b=[];this.a=0;this.e=[];var d=[],c,e;for(c=0,e;e=a.Gb[c];c++){var h={};h.dc=g;h.ca=e;h.title=e.title||"";h.N=e.hotkey||"";h.pa=e.v||"";h.qa=e.w||"";h.ka=e.I||"";h.ga=e.back||"";h.onEmpty=e.onEmpty||"";h.type=e.type||"";h.ua=g;h.ma=g;h.ja=g;h.h=this.Z(e);h.j=this.Pa(e);for(var j=0,p;p=h.j[j];j++)if(p.trigger=="listTail")h.ua=p;else if(p.trigger=="listHead")h.ma=p;else if(p.trigger=="listEntry")h.ja=p;if(h.h.length>0||h.type=="dynamic"){this.b.push(h);this.e.push(-1)}else h.N!==
""&&d.push(h)}this.Q=[];this.gc=0;var m;if(a.j)for(c=0,m;m=a.j[c];c++){var n={};n.c=m.c;n.c=n.c.replace(/^\s\s*/,"").replace(/\s\s*$/,"");n.title=m.title||"";n.trigger=m.trigger||"key";n.hotkey=m.hotkey||"";n.action=m.action||"click";n.onEmpty=m.onEmpty||"";this.Q.push(n)}this.X!==g&&document.removeEventListener("keypress",this.X,i);b===g||typeof b=="undefined"?this.Sb(a,d):b(a,this.b,d,this.Q)};
l.prototype.Z=function(a){var b=[];if(!a.h)return b;for(var d=0,c;c=a.h[d];d++)try{var e=c.c.replace(/^\s\s*/,"").replace(/\s\s*$/,""),h=this.g.t().documentElement,j=this.g.H(e,h),p=c.index||"0",m=parseInt(p,10),n=j.length-m,r=c.F||"*";if(r!="*")n=parseInt(r,10);var u=n+m,v=c.action||g;while(m<u){var s={};s.action=v;s.i=j[m];if(typeof s.i!="undefined"){if(typeof s.i.L=="undefined")s.i.L={};s.i.L[this.b.length]=b.length;b.push(s)}m++}}catch(w){}return b};
l.prototype.Pa=function(a){var b=[];if(!a.j)return b;for(var d=0,c;c=a.j[d];d++){var e={};e.c=c.c.replace(/^\s\s*/,"").replace(/\s\s*$/,"");e.title=c.title||"";e.trigger=c.trigger||"key";e.hotkey=c.hotkey||"";e.action=c.action||"click";e.onEmpty=c.onEmpty||"";b.push(e)}return b};
l.prototype.Sb=function(a,b){var d=this,c;this.C={};this.D={};this.B=[];this.u=[];var e;for(c=0,e;e=this.Q[c];c++)this.Ga(e,this.C,this.D);var h=[];this.ba=a.v||"";if(this.ba!=="")h=this.ba.split(" ");this.o(h,this.C,this.D,function(){d.Kb();d.Ja()});h=[];this.da=a.w||"";if(this.da!=="")h=this.da.split(" ");this.o(h,this.C,this.D,function(){d.Mb();d.Ja()});var j;for(c=0,j;j=this.b[c];c++){var p={},m={};this.B.push(p);this.u.push(m);this.T(j.pa,c,"next");this.T(j.qa,c,"prev");this.T(j.ka,c,"fwd");
this.T(j.ga,c,"back");this.nb(j.N,c,j.onEmpty);var n;for(n=0,e;e=j.j[n];n++)this.Ga(e,p,m)}var r;for(c=0,r;r=b[c];c++)this.mb(r.N,r.onEmpty);this.X=function(u){if(u.ctrlKey)return i;if(d.g.W)return i;var v=d.zb(u.keyCode,u.charCode);if(v)return v()};document.addEventListener("keypress",this.X,i)};var o=function(a){this.l=a;this.$=1.5;this.padding=-1;this.Ob=0;this.S=a.t();this.d=this.S.createElement("span");this.d.style.backgroundColor="#CCE6FF";this.d.style.borderColor="#0000CC";this.d.style.borderWidth="medium";this.d.style.borderStyle="groove";this.d.style.position="absolute";this.d.style.display="none";this.S.body.appendChild(this.d);this.ha=function(){}};o.ib={Zb:0,Za:1};
o.prototype.view=function(a){while(this.d.firstChild)this.d.removeChild(this.d.firstChild);if(a===g){this.d.style.display="none";return}var b=0,d=0,c=a;if(c.offsetParent){b=c.offsetLeft;d=c.offsetTop;c=c.offsetParent;while(c!==g){b+=c.offsetLeft;d+=c.offsetTop;c=c.offsetParent}}this.d.appendChild(a.cloneNode(i));this.d.style.top=d+"px";this.d.style.left=b+"px";this.d.style.zIndex=999;this.d.style.display="block";this.Oa()};o.prototype.sa=function(a){this.$=a;this.Oa()};
o.prototype.Oa=function(){this.S.body.removeChild(this.d);this.Ib();this.tb();this.kb();this.S.body.appendChild(this.d);this.ha&&this.ha(this.d);if(this.Ob==o.ib.Za){var a=this;window.setTimeout(function(){a.d.scrollIntoView(i)},0)}};o.prototype.kb=function(){if(this.padding<0)return;var a="//*[not(.//*)]",b=this.l.H(a,this.d);for(var d=0,c;c=b[d];d++)c.style.padding=this.padding+"px"};
o.prototype.tb=function(){var a=this.d.getElementsByTagName("img");for(var b=0,d;d=a[b];b++){if(!d.hasAttribute("Axs_OrigHeight")){d.setAttribute("Axs_OrigHeight",d.height);d.setAttribute("Axs_OrigWidth",d.width)}d.height=d.getAttribute("Axs_OrigHeight")*this.$;d.width=d.getAttribute("Axs_OrigWidth")*this.$}};o.prototype.Ib=function(){var a=this.$*0.52;this.d.style.fontSizeAdjust=a;var b=this.d.getElementsByTagName("*");for(var d=0,c;c=b[d];d++)c.style.setProperty("line-height","normal","important")};
o.prototype.Qb=function(a){this.ha=a};var q=function(a){var b="http://google-axsjax.googlecode.com/svn/trunk/";this.sb=b+"common/earcons/axsEarcons.swf?sound=";this.n=g;this.V=a;this.ta=b+"thirdparty/soundmanager2/";this.k=g;this.J=f;this.Ua="minimal";this.U=f;this.oa=0};
q.prototype.na=function(){if(this.V)return;if(this.J)return;if(this.U)return;this.U=i;this.oa=0;if(this.k!==g){this.k.parentNode.removeChild(this.k);this.k=g}this.k=document.createElement("iframe");var a=document.location.toString();if(a.indexOf("#")!=-1)a=a.substring(0,a.indexOf("#"));this.k.src=this.ta+"AxsJAX_SM2_Linker.html#Verbosity="+this.Ua+",Parent="+a;this.k.width="0%";this.k.height="0%";this.k.style.top="-1000";this.k.style.left="-1000";this.k.style.position="absolute";document.getElementsByTagName("body")[0].appendChild(this.k);
this.Ia()};q.prototype.Ia=function(){if(document.location.hash=="#InitSuccess"){this.J=i;this.U=f;return}if(this.Ua=="none"&&this.oa>0){this.J=i;this.U=f;return}var a=this;window.setTimeout(function(){a.Ia()},100);this.oa++};q.prototype.play=function(a){var b=this.Lb(a);if(this.V||b)return;if(!this.J){this.na();var d=this;window.setTimeout(function(){d.play(a)},500);return}this.k.src=this.ta+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Play("+a+")"};
q.prototype.stop=function(){if(this.n){this.n.parentNode.removeChild(this.n);this.n=g}if(this.V)return;if(!this.J)return;this.k.src=this.ta+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Stop()"};q.prototype.getTime=function(){if(this.V)return-1;if(!this.J)return-1;var a="Time=",b=unescape(document.location.hash);if(b.indexOf(a)==-1)return-1;var d=b.indexOf(a)+a.length,c=parseInt(b.substring(d),10);return c};
q.prototype.Lb=function(a){var b="";switch(a){case "alert":b="alert";break;case "deselect":b="deselect";break;case "item":b="item";break;case "list":b="list";break;case "select":b="select";break;case "success":b="success";break;case "wrap":b="wrap";break;default:}if(b==="")return;if(this.n===g){this.n=document.createElement("embed");this.n.height=0;this.n.width=0;document.body.appendChild(this.n)}this.n.src=this.sb+b};var t={};t.Va="http://www.google.com/cse?cx=000183394137052953072%3Azc1orsc6mbq&q=";t.jb="http://www.google.com/search?q=";t.bb="The following shortcut keys are available. ";t.ea="Slash, enter search field. Escape, leave search field. Equals, enlarge the current item. Minus, shrink the current item. ";t.ac="Searches related to:";t.fb="You are already on Google accessible search.";t.gb="You are already on Google web search.";t.cc="Sponsored link. ";t.l=g;t.s=g;t.A=g;t.O=1.5;t.Ha=g;
t.na=function(){t.l=new k(i);t.s=new l(t.l);document.addEventListener("keypress",t.ub,i);var a={Gb:[{title:"One Box",hotkey:"1",v:"DOWN j",w:"UP k",I:g,back:g,onEmpty:"There is no one box on this page.",type:g,h:[{c:'//tr[@class="std"]/..[count(ancestor-or-self::*[count(preceding-sibling::*/descendant-or-self::li[@class="g"])>0]) = 0]',F:"1"},{c:'id("res")/div[@class="e"]/table[not(contains(@id,"brs"))]/..[count(ancestor-or-self::*[count(preceding-sibling::*/descendant-or-self::li[@class="g"])>0]) = 0]',
F:"1"},{c:'id("res")/p[*]',F:"1",ec:"Use [*] since some one boxes have an extra node at the start."},{c:'//td/h2[@class="r"]/..',F:"1"}],j:[]},{title:"Results",hotkey:"n",v:"DOWN j",w:"UP k",I:"n",back:"p",onEmpty:g,type:g,h:[{c:'id("res")/div[@class="med"]',F:"1"},{c:'id("res")//*[@class="g"]/*/.. | id("res")//li[descendant::p[@class="g"] and not(descendant::div[@class="g"])] | id("res")//li[count(descendant-or-self::*[@class="g"])=0 and descendant::h3[@class="r"]]'},{c:'id("res")/div[@class="e"]/table[not(contains(@id,"brs"))]/..[count(ancestor-or-self::*[count(preceding-sibling::*/descendant-or-self::li[@class="g"])>0]) > 0]',
F:"1"}],j:[{c:'id("nn")/..',title:"Next page",trigger:"listTail"},{c:'id("np")/..',title:"Prev page",trigger:"listHead"}]},{title:"Sponsored Links",hotkey:"a",v:"DOWN j",w:"UP k",I:g,back:g,onEmpty:"There are no sponsored links on this page.",type:g,h:[{c:'id("tads")//li'},{c:'id("mbEnd")//li'}],j:[]},{title:"Related Searches",hotkey:"s",v:"DOWN j",w:"UP k",I:g,back:g,onEmpty:"There are no related searches.",type:g,h:[{c:'id("brs")//a/b/..'}],j:[]},{title:"Alternate Search Categories",hotkey:"c",
v:"DOWN j",w:"UP k",I:g,back:g,onEmpty:"There are no other categories to search within.",type:g,h:[{c:'id("prs")/a'}],j:[]},{title:"Google Services",hotkey:"g",v:"DOWN j",w:"UP k",I:g,back:g,onEmpty:g,type:g,h:[{c:'id("gbar")//a[@class="gb1"]'},{c:'id("gbar")//a[@class="gb2"]'},{c:'id("gb")//a'}],j:[]}],j:[{c:'id("nn")/..',title:"Next page",hotkey:"PGDOWN"},{c:'id("np")/..',title:"Previous page",hotkey:"PGUP"}],v:"RIGHT l",w:"LEFT h"};t.s.Jb(a,g);t.ea=t.s.Cb()+t.ea;t.A=new o(t.l);t.s.Pb(t.A);t.A.sa(t.O);
t.A.Qb(t.vb);t.Ha=new q(i);t.s.Rb(t.Ha);window.setTimeout(t.Nb,100)};t.Nb=function(){var a=t.s.aa().i;t.A.view(a);t.l.Ma(a)};t.Db=function(){var a=t.Ka();if(a==="")return;document.location=a};t.Eb=function(){var a=t.Ka();if(a==="")return;window.open(a)};t.Ka=function(){var a=t.s.ia();if(typeof a=="undefined")return"";var b=a.i;return b.tagName=="A"?b.href:b.getElementsByTagName("a")[0].href};
t.La=function(){var a=document.baseURI,b=a.indexOf("q=")+2,d=a.indexOf("&",b);if(d==-1)d=a.length;return a.substring(b,d)};t.Tb=function(){if(document.baseURI.indexOf("http://www.google.com/custom")===0||document.baseURI.indexOf("http://www.google.com/cse")===0){t.l.z(t.fb);return}var a=t.La();document.location=t.Va+a};t.Ub=function(){if(document.baseURI.indexOf("http://www.google.com/search")===0){t.l.z(t.gb);return}var a=t.La();document.location=t.jb+a};t.Fb=function(){t.O+=0.1;t.A.sa(t.O)};
t.rb=function(){t.O-=0.1;t.A.sa(t.O)};t.vb=function(a){var b=t.l.H('.//table[contains(@class,"ti")]',a)[0];if(b){var d=t.l.H(".//img[@alt]",b)[0].alt,c=document.createElement("span");c.textContent=d;b.parentNode.replaceChild(c,b)}};t.ub=function(a){if(a.ctrlKey)return i;if(a.keyCode==27){t.l.p.blur();return f}if(t.l.W)return i;if(a.keyCode==13){a.shiftKey?t.Eb():t.Db();return f}var b=t.pb[a.charCode];if(b)return b();return i};
t.pb={63:function(){var a=t.bb+t.s.Hb()+t.ea;t.l.z(a);return f},45:function(){t.rb();return f},61:function(){t.Fb();return f},47:function(){document.getElementsByName("q")[0].focus();document.getElementsByName("q")[0].select();return f},65:function(){t.Tb();return f},87:function(){t.Ub();return f}};t.na();
 })();
