(function() { 
var g=false,h=null,j=true,k,m=function(a){this.ID_NUM_=0;this.tabbingStartPosNode=h;this.tabKeyFixOn=g;this.lastFocusedNode=h;this.inputFocused=g;var b=this;this.activeParent=document.body;this.addFocusBlurMonitors();if(a){this.tabKeyFixOn=j;document.addEventListener("keypress",function(d){b.tabKeyHandler(d,b)},j);document.body.AXSJAX_TABKEYFIX_ADDED=j}};k=m.prototype;
k.addFocusBlurMonitors=function(){var a=this.getActiveDocument(),b=this,d=function(e){b.lastFocusedNode=e.target;if(e.target.tagName=="INPUT"||e.target.tagName=="SELECT"||e.target.tagName=="TEXTAREA")b.inputFocused=j;return j};a.addEventListener("focus",d,j);var c=function(e){b.removeAttributeOf(b.lastFocusedNode,"aria-activedescendant");b.lastFocusedNode=h;if(e.target.tagName=="INPUT"||e.target.tagName=="SELECT"||e.target.tagName=="TEXTAREA")b.inputFocused=g;return j};a.addEventListener("blur",c,
j)};k.getActiveDocument=function(){var a=this.activeParent;while(a.nodeType!=9)a=a.parentNode;return a};
k.speakNode=function(a,b){a.id||this.assignId(a);if(b){this.setAttributeOf(a,"live","rude");this.setAttributeOf(a,"atomic","true");var d=this.getActiveDocument(),c=d.createElement("div");c.textContent=" ";c.name="AxsJAX_dummyNode";a.lastChild&&a.lastChild.name&&a.lastChild.name==c.name&&a.removeChild(a.lastChild);a.appendChild(c)}else{var e=this.getAttributeOf(a,"role");this.setAttributeOf(a,"role","row");var f=this.lastFocusedNode;if(!f||f.nodeType==9){this.activeParent.tabIndex=-1;f=this.activeParent}this.setAttributeOf(f,
"activedescendant",h);f.focus&&f.focus();this.setAttributeOf(f,"activedescendant",a.id);var i=this;window.setTimeout(function(){e?i.setAttributeOf(a,"role",e):i.removeAttributeOf(a,"role")},0)}};
k.speakTextViaNode=function(a,b){var d="AxsJAX_pixelAudioNode",c="AxsJAX_pixelAudioNode",e="data:image/gif;base64,R0lGODlhAQABAIAAANvf7wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",f=this.getActiveDocument(),i=h;if(b){if(b.previousSibling&&b.previousSibling.name==c)i=b.previousSibling;else{i=f.createElement("img");i.name=c;i.setAttribute("tabindex",0);i.style.outline="none";i.src=e;b.parentNode.insertBefore(i,b);this.forceATSync(i)}i.setAttribute("alt",a);i.setAttribute("title",a);window.setTimeout(function(){i.blur();
i.focus()},0)}else{if((i=f.getElementById(d))&&i.alt==a)a=a+" ";if(!i){i=f.createElement("img");i.id=d;i.src=e;f.body.appendChild(i)}i.setAttribute("alt",a);i.setAttribute("title",a);this.speakNode(i)}};
k.clickElem=function(a,b){var d=this.getActiveDocument(),c=d.createEvent("MouseEvents");c.initMouseEvent("mousedown",j,j,d.defaultView,1,0,0,0,0,g,g,b,g,0,h);try{a.dispatchEvent(c)}catch(e){}c=d.createEvent("MouseEvents");c.initMouseEvent("mouseup",j,j,d.defaultView,1,0,0,0,0,g,g,b,g,0,h);try{a.dispatchEvent(c)}catch(e){}c=d.createEvent("MouseEvents");c.initMouseEvent("click",j,j,d.defaultView,1,0,0,0,0,g,g,b,g,0,h);try{a.dispatchEvent(c)}catch(e){}var f=a.getAttribute("href");if(a.tagName=="A"&&
f&&f!="#")if(b)window.open(a.href);else document.location=a.href};k.assignId=function(a,b){if(!a)return"";if(a.id)return a.id;var d=b||"AxsJAX_ID_";return a.id=d+this.ID_NUM_++};k.markPosition=function(a){if(!a)return g;if(a.tagName=="A"||a.tagName=="INPUT"){this.tabbingStartPosNode=a;return j}var b=a.getElementsByTagName("*");for(var d=0,c;c=b[d];d++)if(c.tagName=="A"||c.tagName=="INPUT"||c.hasAttribute("tabindex")&&c.tabIndex!=-1){this.tabbingStartPosNode=c;return j}return g};
k.tabKeyHandler=function(a,b){if(!b.tabKeyFixOn)return j;if(a.keyCode==9&&b.tabbingStartPosNode){b.tabbingStartPosNode.focus();b.tabbingStartPosNode=h}return j};k.goTo=function(a){this.speakNode(a);a.scrollIntoView(j);this.markPosition(a)};k.setAttributeOf=function(a,b,d){if(!!a){b=b.toLowerCase();switch(b){case "live":b="aria-live";break;case "activedescendant":b="aria-activedescendant";break;case "atomic":b="aria-atomic";break;default:break}a.setAttribute(b,d)}};k.getAttributeOf=function(a,b){return a.getAttribute(b)};
k.removeAttributeOf=function(a,b){a&&a.removeAttribute&&a.removeAttribute(b)};k.forceATSync=function(a){var b=this.assignId(a),d=this.getActiveDocument(),c=d.baseURI,e=c.indexOf("#");if(e!=-1)c=c.substring(0,e);d.location=c+"#"+b};k.evalXPath=function(a,b){try{var d=b.ownerDocument.evaluate(a,b,h,XPathResult.ORDERED_NODE_ITERATOR_TYPE,h)}catch(c){return[]}var e=[];for(var f=d.iterateNext();f;f=d.iterateNext())e.push(f);return e};var x=function(a){this.prevListKeys=this.nextListKeys="";this.navArray=[];this.navListIdx=0;this.navItemIdxs=[];this.lastItem=h;this.targetsArray=[];this.topCharCodeMap={};this.topKeyCodeMap={};this.charCodeMaps=[];this.keyCodeMaps=[];this.axs_=a;this.pk_=this.lens_=h;this.snd_=h;this.LIST_SND="list";this.ITEM_SND="item";this.WRAP_SND="wrap";this.keyHandler=h};
x.str={NEXT_LIST:"next list",PREV_LIST:"previous list",GO_FORWARD:"go forward",GO_BACKWARDS:"go backwards",CYCLE_NEXT:"cycle next",CYCLE_PREV:"cycle previous",SELECT_ACTION:"Select available action",NO_AVAILABLE_ACTION:"No available actions",PGUP:"Page up",PGDOWN:"Page down",ENTER:"Enter",ESC:"Escape",DEL:"Delete",UP:"Up",DOWN:"Down",LEFT:"Left",RIGHT:"Right"};k=x.prototype;
k.validateList=function(a){var b=j;if(a.type=="dynamic"&&a.items.length===0){this.lens_!==h&&this.lens_.view(h);a.items=this.makeItemsArray(a.origListObj);a.targets=this.makeTargetsArray(a.origListObj);if(this.navArray[this.navListIdx]===a)this.navItemIdxs[this.navListIdx]=-1;else for(var d=0,c;c=this.navArray[d];d++)if(c===a){this.navItemIdxs[d]=-1;break}}if(a.items.length===0&&a.entryTarget===h)b=g;return b};
k.doListEntryActions=function(){var a=this.currentList(),b=a.entryTarget,d=h;if(b!==h){this.actOnTarget(b);d=this.getCallbackFunction(b.action)}if(d===h){this.announceCurrentList();this.snd_!==h&&this.snd_.play(this.LIST_SND)}};k.nextList=function(){if(this.navArray.length<1)return h;for(var a=0;this.navArray[a];a++){this.navListIdx++;if(this.navListIdx>=this.navArray.length)this.navListIdx=0;if(this.validateList(this.navArray[this.navListIdx]))break}return this.currentList()};
k.prevList=function(){if(this.navArray.length<1)return h;for(var a=0;this.navArray[a];a++){this.navListIdx--;if(this.navListIdx<0)this.navListIdx=this.navArray.length-1;if(this.validateList(this.navArray[this.navListIdx]))break}return this.currentList()};k.currentList=function(){return this.navArray[this.navListIdx]};k.announceCurrentList=function(){this.axs_.speakTextViaNode(this.currentList().title)};
k.nextItem=function(){if(this.navArray.length<1)return h;var a=this.navArray[this.navListIdx],b=a.items;if(b.length<1)return h;if(this.lastItem){var d=this.lastItem.elem.AxsNavInfo[this.navListIdx];if(typeof d!="undefined")this.navItemIdxs[this.navListIdx]=d}this.navItemIdxs[this.navListIdx]++;var c=g;if(this.navItemIdxs[this.navListIdx]>=b.length){this.navItemIdxs[this.navListIdx]=0;c=j}var e=this.navItemIdxs[this.navListIdx];if(b[e].elem.parentNode===h){this.lens_!==h&&this.lens_.view(h);a.items=
this.makeItemsArray(a.origListObj);this.navItemIdxs[this.navListIdx]=0;e=this.navItemIdxs[this.navListIdx]}this.lastItem=b[e];if(this.snd_!==h)c?this.snd_.play(this.WRAP_SND):this.snd_.play(this.ITEM_SND);return this.lastItem};k.fwdItem=function(){var a=this.navArray[this.navListIdx],b=this.navItemIdxs[this.navListIdx];if(a.tailTarget!==h&&b+1>=a.items.length){this.actOnTarget(a.tailTarget);this.navItemIdxs[this.navListIdx]=0;return h}var d=this.nextItem();return d};
k.prevItem=function(){if(this.navArray.length<1)return h;var a=this.navArray[this.navListIdx],b=a.items;if(b.length<1)return h;if(this.lastItem){var d=this.lastItem.elem.AxsNavInfo[this.navListIdx];if(typeof d!="undefined")this.navItemIdxs[this.navListIdx]=d}this.navItemIdxs[this.navListIdx]--;var c=g;if(this.navItemIdxs[this.navListIdx]<0){this.navItemIdxs[this.navListIdx]=b.length-1;c=j}var e=this.navItemIdxs[this.navListIdx];if(b[e].elem.parentNode===h){this.lens_!==h&&this.lens_.view(h);a.items=
this.makeItemsArray(a.origListObj);this.navItemIdxs[this.navListIdx]=a.items.length;e=this.navItemIdxs[this.navListIdx]}this.lastItem=b[e];if(this.snd_!==h)c?this.snd_.play(this.WRAP_SND):this.snd_.play(this.ITEM_SND);return this.lastItem};k.backItem=function(){var a=this.navArray[this.navListIdx],b=this.navItemIdxs[this.navListIdx];if(a.headTarget!==h&&b<=0){this.actOnTarget(a.headTarget);this.navItemIdxs[this.navListIdx]=a.items.length-1;return h}var d=this.prevItem();return d};
k.currentItem=function(){if(this.navArray.length<1)return h;if(this.lastItem){var a=this.lastItem.elem.AxsNavInfo[this.navListIdx];if(typeof a!="undefined")this.navItemIdxs[this.navListIdx]=a}var b=this.navArray[this.navListIdx],d=b.items,c=this.navItemIdxs[this.navListIdx];return this.lastItem=d[c]};k.getCallbackFunction=function(a){var b=h;if(a!==h&&a.indexOf&&a.indexOf("CALL:")===0&&a.indexOf("(")===-1)try{b=eval(a.substring(5))}catch(d){}return b};
k.actOnItem=function(a){if(a!==h){var b=this,d=function(){var i=b.getCallbackFunction(a.action);if(i)i(a);else{b.lens_!==h&&b.lens_.view(a.elem);b.axs_.goTo(a.elem)}};if(this.axs_.lastFocusedNode&&this.axs_.lastFocusedNode.blur){var c=this.axs_.lastFocusedNode;this.axs_.lastFocusedNode=h;c.removeAttribute&&this.axs_.removeAttributeOf(c,"aria-activedescendant");var e=function(i){i.target.removeEventListener("blur",e,j);d()};c.addEventListener("blur",e,j);c.blur()}else d()}else{var f=this.navArray[this.navListIdx];
f.type=="dynamic"&&this.axs_.speakTextViaNode(f.onEmpty)}};k.assignKeysToMethod=function(a,b,d,c){for(var e=0,f;f=a[e];e++)if(f=="LEFT")d[37]=c;else if(f=="UP")d[38]=c;else if(f=="RIGHT")d[39]=c;else if(f=="DOWN")d[40]=c;else if(f=="PGUP")d[33]=c;else if(f=="PGDOWN")d[34]=c;else if(f=="ENTER")d[13]=c;else if(f=="ESC")d[27]=c;else if(f=="DEL")d[46]=c;else b[f.charCodeAt(0)]=c};
k.assignItemKeys=function(a,b,d){var c=[];if(!(a==="")){c=a.split(" ");var e=this;if(d=="prev")this.assignKeysToMethod(c,this.charCodeMaps[b],this.keyCodeMaps[b],function(){e.actOnItem(e.prevItem())});else if(d=="next")this.assignKeysToMethod(c,this.charCodeMaps[b],this.keyCodeMaps[b],function(){e.actOnItem(e.nextItem())});else d=="back"?this.assignKeysToMethod(c,this.charCodeMaps[b],this.keyCodeMaps[b],function(){e.actOnItem(e.backItem())}):this.assignKeysToMethod(c,this.charCodeMaps[b],this.keyCodeMaps[b],
function(){e.actOnItem(e.fwdItem())})}};k.assignHotKeys=function(a,b,d){var c=[];if(!(a==="")){c=a.split(" ");var e=this;this.assignKeysToMethod(c,this.topCharCodeMap,this.topKeyCodeMap,function(){if(e.validateList(e.navArray[b])){e.navListIdx=b;e.actOnItem(e.nextItem())}else e.axs_.speakTextViaNode(d)})}};k.assignEmptyMsgKeys=function(a,b){var d=[];if(!(a==="")){d=a.split(" ");var c=this;this.assignKeysToMethod(d,this.topCharCodeMap,this.topKeyCodeMap,function(){c.axs_.speakTextViaNode(b)})}};
k.assignTargetKeys=function(a,b,d){var c=[];if(!(a.hotkey==="")){c=a.hotkey.split(" ");var e=this;this.assignKeysToMethod(c,b,d,function(){e.actOnTarget(a)})}};
k.actOnTarget=function(a){var b=a.xpath,d=this.axs_.getActiveDocument().documentElement;if(b.indexOf(".")===0)d=this.currentItem().elem;var c=this.axs_.evalXPath(b,d);if(c.length<1)this.axs_.speakTextViaNode(a.onEmpty);else{var e=this.getCallbackFunction(a.action);if(e){var f={};f.action=a.action;f.elem=c[0];e(f)}else{this.axs_.clickElem(c[0],g);c[0].scrollIntoView(j)}this.axs_.markPosition(c[0])}};
k.getFunctionForKey=function(a,b){var d=h,c=this.navListIdx;if(c<this.keyCodeMaps.length)d=this.keyCodeMaps[c][a]||this.charCodeMaps[c][b]||h;if(d===h)d=this.topKeyCodeMap[a]||this.topCharCodeMap[b];return d};
k.navInit=function(a,b){var d={};d.lists=[];var c=new DOMParser,e=c.parseFromString(a,"text/xml"),f=e.getElementsByTagName("list"),i,n;for(i=0,n;n=f[i];i++){var l={};l.title=n.getAttribute("title");l.hotkey=n.getAttribute("hotkey");l.next=n.getAttribute("next");l.prev=n.getAttribute("prev");l.fwd=n.getAttribute("fwd");l.back=n.getAttribute("back");l.onEmpty=n.getAttribute("onEmpty");l.type=n.getAttribute("type");var o,q,p,r,s;l.items=[];var A=n.getElementsByTagName("item");for(o=0;q=A[o];o++){var y=
{};y.xpath=q.textContent;if(q.attributes instanceof NamedNodeMap){r=q.attributes;s=r.length;for(p=0;p<s;p++){var t=r.item(p);y[t.nodeName]=t.value}}l.items.push(y)}l.targets=[];var C=n.getElementsByTagName("target");for(o=0;q=C[o];o++){var u={};u.xpath=q.textContent;if(q.attributes instanceof NamedNodeMap){r=q.attributes;s=r.length;for(p=0;p<s;p++){var t=r.item(p);u[t.nodeName]=t.value}}l.targets.push(u)}d.lists.push(l)}d.targets=[];var v,w=e.firstChild;for(i=0,v;v=w.childNodes[i];i++)if(v.tagName==
"target"){var u={};u.xpath=v.textContent;if(v.attributes instanceof NamedNodeMap){r=v.attributes;s=r.length;for(p=0;p<s;p++){var t=r.item(p);u[t.nodeName]=t.value}}d.targets.push(u)}d.next=w.getAttribute("next");d.prev=w.getAttribute("prev");if(b===h||typeof b=="undefined")this.navInitJson(d,b);else{var G=new (function(H,D,E,F){b(w,D,E,F)});this.navInitJson(d,G)}};
k.globalHelpString=function(){var a=this.getGlobalActions(),b="";for(var d=0,c;c=a[d];d++)b=b+c.keys+", "+c.title+". ";b=b+this.nextListKeys+", "+x.str.NEXT_LIST;b=b+this.prevListKeys+", "+x.str.PREV_LIST;b=b.replace("PGUP",x.str.PGUP);b=b.replace("PGDOWN",x.str.PGDOWN);b=b.replace("ENTER",x.str.ENTER);b=b.replace("DEL",x.str.DELETE);b=b.replace("UP",x.str.UP);b=b.replace("DOWN",x.str.DOWN);b=b.replace("LEFT",x.str.LEFT);return b=b.replace("RIGHT",x.str.RIGHT)};
k.localHelpString=function(){var a=this.getLocalActions(),b="";for(var d=0,c;c=a[d];d++)b=b+c.keys+", "+c.title+". ";var e=this.currentList();if(e.nextKeys!=="")b=b+e.nextKeys+", "+x.str.CYCLE_NEXT+". ";if(e.prevKeys!=="")b=b+e.prevKeys+", "+x.str.CYCLE_PREV+". ";if(e.fwdKeys!=="")b=b+e.fwdKeys+", "+x.str.GO_FORWARD+". ";if(e.backKeys!=="")b=b+e.backKeys+", "+x.str.GO_BACKWARDS+". ";b=b.replace("PGUP",x.str.PGUP);b=b.replace("PGDOWN",x.str.PGDOWN);b=b.replace("ENTER",x.str.ENTER);b=b.replace("DEL",
x.str.DELETE);b=b.replace("UP",x.str.UP);b=b.replace("DOWN",x.str.DOWN);b=b.replace("LEFT",x.str.LEFT);return b=b.replace("RIGHT",x.str.RIGHT)};k.setLens=function(a){this.lens_=a};k.setSound=function(a){this.snd_=a};k.refreshList=function(a){if(a===h)return g;var b=g;for(var d=0,c;c=this.navArray[d];d++)if(c.title==a){c.items=[];c.targets=[];b=this.validateList(c);break}return b};
k.getGlobalActions=function(){var a=[],b;for(var d=0,c;c=this.navArray[d];d++)if(c.hotKeys!==""){b={};b.title=c.title;b.keys=c.hotKeys;a.push(b)}for(var e=0,f;f=this.targetsArray[e];e++)if(this.isValidTargetAction(f)){b={};b.title=f.title;b.keys=f.hotkey;a.push(b)}return a};k.getLocalActions=function(){var a=[],b=this.currentList();for(var d=0,c;c=b.targets[d];d++)if(this.isValidTargetAction(c)){var e={};e.title=c.title;e.keys=c.hotkey;a.push(e)}return a};
k.isValidTargetAction=function(a){var b=g;if(a.hotkey!==""){var d=a.xpath,c=this.axs_.getActiveDocument().body;if(d.indexOf(".")===0){var e=this.currentItem();if(e)c=e.elem}var f=this.axs_.evalXPath(d,c);if(f.length>0)b=j}return b};
k.navInitJson=function(a,b){this.navArray=[];this.navListIdx=0;this.navItemIdxs=[];var d=[],c,e;for(c=0,e;e=a.lists[c];c++){var f={};f.cnrNode=h;f.origListObj=e;f.title=e.title||"";f.hotKeys=e.hotkey||"";f.nextKeys=e.next||"";f.prevKeys=e.prev||"";f.fwdKeys=e.fwd||"";f.backKeys=e.back||"";f.onEmpty=e.onEmpty||"";f.type=e.type||"";f.tailTarget=h;f.headTarget=h;f.entryTarget=h;f.items=this.makeItemsArray(e);f.targets=this.makeTargetsArray(e);for(var i=0,n;n=f.targets[i];i++)if(n.trigger=="listTail")f.tailTarget=
n;else if(n.trigger=="listHead")f.headTarget=n;else if(n.trigger=="listEntry")f.entryTarget=n;if(f.items.length>0||f.type=="dynamic"){this.navArray.push(f);this.navItemIdxs.push(-1)}else f.hotKeys!==""&&d.push(f)}this.targetsArray=[];this.targetsIdx=0;var l;if(a.targets)for(c=0,l;l=a.targets[c];c++){var o={};o.xpath=l.xpath;o.xpath=o.xpath.replace(/^\s\s*/,"").replace(/\s\s*$/,"");o.title=l.title||"";o.trigger=l.trigger||"key";o.hotkey=l.hotkey||"";o.action=l.action||"click";o.onEmpty=l.onEmpty||
"";this.targetsArray.push(o)}this.keyHandler!==h&&document.removeEventListener("keypress",this.keyHandler,j);b===h||typeof b=="undefined"?this.setUpNavKeys(a,d):b(a,this.navArray,d,this.targetsArray)};
k.makeItemsArray=function(a){var b=[];if(!a.items)return b;for(var d=0,c;c=a.items[d];d++)try{var e=c.xpath.replace(/^\s\s*/,"").replace(/\s\s*$/,""),f=this.axs_.getActiveDocument().documentElement,i=this.axs_.evalXPath(e,f),n=c.index||"0",l=parseInt(n,10),o=i.length-l,q=c.count||"*";if(q!="*")o=parseInt(q,10);var p=o+l,r=c.action||h;while(l<p){var s={};s.action=r;s.elem=i[l];if(typeof s.elem!="undefined"){if(typeof s.elem.AxsNavInfo=="undefined")s.elem.AxsNavInfo={};s.elem.AxsNavInfo[this.navArray.length]=
b.length;b.push(s)}l++}}catch(A){}return b};k.makeTargetsArray=function(a){var b=[];if(!a.targets)return b;for(var d=0,c;c=a.targets[d];d++){var e={};e.xpath=c.xpath.replace(/^\s\s*/,"").replace(/\s\s*$/,"");e.title=c.title||"";e.trigger=c.trigger||"key";e.hotkey=c.hotkey||"";e.action=c.action||"click";e.onEmpty=c.onEmpty||"";b.push(e)}return b};
k.setUpNavKeys=function(a,b){var d=this,c;this.topCharCodeMap={};this.topKeyCodeMap={};this.charCodeMaps=[];this.keyCodeMaps=[];var e;for(c=0,e;e=this.targetsArray[c];c++)this.assignTargetKeys(e,this.topCharCodeMap,this.topKeyCodeMap);var f=[];this.nextListKeys=a.next||"";if(this.nextListKeys!=="")f=this.nextListKeys.split(" ");this.assignKeysToMethod(f,this.topCharCodeMap,this.topKeyCodeMap,function(){d.nextList();d.doListEntryActions()});f=[];this.prevListKeys=a.prev||"";if(this.prevListKeys!==
"")f=this.prevListKeys.split(" ");this.assignKeysToMethod(f,this.topCharCodeMap,this.topKeyCodeMap,function(){d.prevList();d.doListEntryActions()});var i;for(c=0,i;i=this.navArray[c];c++){var n={},l={};this.charCodeMaps.push(n);this.keyCodeMaps.push(l);this.assignItemKeys(i.nextKeys,c,"next");this.assignItemKeys(i.prevKeys,c,"prev");this.assignItemKeys(i.fwdKeys,c,"fwd");this.assignItemKeys(i.backKeys,c,"back");this.assignHotKeys(i.hotKeys,c,i.onEmpty);var o;for(o=0,e;e=i.targets[o];o++)this.assignTargetKeys(e,
n,l)}var q;for(c=0,q;q=b[c];c++)this.assignEmptyMsgKeys(q.hotKeys,q.onEmpty);this.keyHandler=function(p){if(p.ctrlKey)return j;if(d.axs_.inputFocused)return j;var r=d.getFunctionForKey(p.keyCode,p.charCode);if(r)return r()};document.addEventListener("keypress",this.keyHandler,j)};var z=function(a){this.axsJAXObj=a;this.multiplier=1.5;this.padding=-1;this.scrollMode=0;this.activeDoc=a.getActiveDocument();this.lens=this.activeDoc.createElement("span");this.lens.style.backgroundColor="#CCE6FF";this.lens.style.borderColor="#0000CC";this.lens.style.borderWidth="medium";this.lens.style.borderStyle="groove";this.lens.style.position="absolute";this.lens.style.display="none";this.activeDoc.body.appendChild(this.lens);this.callback=function(){}};z.ScrollMode={NONE:0,FORCE_TO_LENS:1};
k=z.prototype;k.view=function(a){while(this.lens.firstChild)this.lens.removeChild(this.lens.firstChild);if(a===h)this.lens.style.display="none";else{var b=0,d=0,c=a;if(c.offsetParent){b=c.offsetLeft;d=c.offsetTop;c=c.offsetParent;while(c!==h){b+=c.offsetLeft;d+=c.offsetTop;c=c.offsetParent}}this.lens.appendChild(a.cloneNode(j));this.lens.style.top=d+"px";this.lens.style.left=b+"px";this.lens.style.zIndex=999;this.lens.style.display="block";this.magnify()}};
k.setMagnification=function(a){this.multiplier=a;this.magnify()};k.magnify=function(){this.activeDoc.body.removeChild(this.lens);this.magnifyText();this.enlargeImages();this.addPadding();this.activeDoc.body.appendChild(this.lens);this.callback&&this.callback(this.lens);if(this.scrollMode==z.ScrollMode.FORCE_TO_LENS){var a=this;window.setTimeout(function(){a.lens.scrollIntoView(j)},0)}};
k.addPadding=function(){if(!(this.padding<0)){var a="//*[not(.//*)]",b=this.axsJAXObj.evalXPath(a,this.lens);for(var d=0,c;c=b[d];d++)c.style.padding=this.padding+"px"}};k.enlargeImages=function(){var a=this.lens.getElementsByTagName("img");for(var b=0,d;d=a[b];b++){if(!d.hasAttribute("Axs_OrigHeight")){d.setAttribute("Axs_OrigHeight",d.height);d.setAttribute("Axs_OrigWidth",d.width)}d.height=d.getAttribute("Axs_OrigHeight")*this.multiplier;d.width=d.getAttribute("Axs_OrigWidth")*this.multiplier}};
k.magnifyText=function(){var a="fontSizeAdjust"in this.lens.style;if(a){var b=this.multiplier*0.52;this.lens.style.fontSizeAdjust=b}else{var d=this.multiplier*100+"%";this.lens.style.setProperty("font-size",d,"important")}var c=this.lens.getElementsByTagName("*");for(var e=0,f;f=c[e];e++){f.style.setProperty("line-height","normal","important");a||f.style.setProperty("font-size","100%","important")}};var B=function(a){var b="http://google-axsjax.googlecode.com/svn/trunk/";this.earconsSwf=b+"common/earcons/axsEarcons.swf?sound=";this.earconsObj=h;this.earconsOnly=a;this.sm2BaseURL=b+"thirdparty/soundmanager2/";this.sm2LinkerFrame=h;this.initSucceeded=g;this.verbosity="minimal";this.busyInitializing=g;this.initChecks=0};k=B.prototype;
k.init=function(){if(!this.earconsOnly)if(!this.initSucceeded)if(!this.busyInitializing){this.busyInitializing=j;this.initChecks=0;if(this.sm2LinkerFrame!==h){this.sm2LinkerFrame.parentNode.removeChild(this.sm2LinkerFrame);this.sm2LinkerFrame=h}this.sm2LinkerFrame=document.createElement("iframe");var a=document.location.toString();if(a.indexOf("#")!=-1)a=a.substring(0,a.indexOf("#"));this.sm2LinkerFrame.src=this.sm2BaseURL+"AxsJAX_SM2_Linker.html#Verbosity="+this.verbosity+",Parent="+a;this.sm2LinkerFrame.width=
"0%";this.sm2LinkerFrame.height="0%";this.sm2LinkerFrame.style.top="-1000";this.sm2LinkerFrame.style.left="-1000";this.sm2LinkerFrame.style.position="absolute";document.getElementsByTagName("body")[0].appendChild(this.sm2LinkerFrame);this.checkInitStatus()}};
k.checkInitStatus=function(){if(document.location.hash=="#InitSuccess"){this.initSucceeded=j;this.busyInitializing=g}else if(this.verbosity=="none"&&this.initChecks>0){this.initSucceeded=j;this.busyInitializing=g}else{var a=this;window.setTimeout(function(){a.checkInitStatus()},100);this.initChecks++}};
k.play=function(a){var b=this.playEarcon(a);if(!(this.earconsOnly||b))if(this.initSucceeded)this.sm2LinkerFrame.src=this.sm2BaseURL+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Play("+a+")";else{this.init();var d=this;window.setTimeout(function(){d.play(a)},500)}};k.stop=function(){if(this.earconsObj){this.earconsObj.parentNode.removeChild(this.earconsObj);this.earconsObj=h}if(!this.earconsOnly)if(!!this.initSucceeded)this.sm2LinkerFrame.src=this.sm2BaseURL+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Stop()"};
k.getTime=function(){if(this.earconsOnly)return-1;if(!this.initSucceeded)return-1;var a="Time=",b=unescape(document.location.hash);if(b.indexOf(a)==-1)return-1;var d=b.indexOf(a)+a.length,c=parseInt(b.substring(d),10);return c};
k.playEarcon=function(a){var b="";switch(a){case "alert":b="alert";break;case "deselect":b="deselect";break;case "item":b="item";break;case "list":b="list";break;case "select":b="select";break;case "success":b="success";break;case "wrap":b="wrap";break;default:}if(!(b==="")){if(this.earconsObj===h){this.earconsObj=document.createElement("embed");this.earconsObj.height=0;this.earconsObj.width=0;document.body.appendChild(this.earconsObj)}this.earconsObj.src=this.earconsSwf+b}};var axsModerator={};axsModerator.HELP="The following shortcut keys are available. ";axsModerator.axsJAXObj=h;axsModerator.axsNavObj=h;axsModerator.axsLensObj=h;axsModerator.axsSoundObj=h;axsModerator.magSize=1.5;
axsModerator.init=function(){axsModerator.axsJAXObj=new m(j);axsModerator.axsNavObj=new x(axsModerator.axsJAXObj);document.addEventListener("keypress",axsModerator.keyHandler,j);var a='<cnr next="RIGHT l" prev="LEFT h">     <list title="Featured question" next="DOWN j" prev="UP k" type="dynamic">    <item count="1">      //div[contains(@class, "moderator-featured")]/../../..[not(contains(@style, "display: none"))]//div[contains(@class, "moderator-featured")]    </item>\t<target title="Yes" hotkey="y" action="CALL:axsModerator.voteYes">\t .\t</target>\t<target title="No" hotkey="n" action="CALL:axsModerator.voteNo">\t .\t</target>\t<target title="Skip" hotkey="s" action="CALL:axsModerator.voteSkip">\t .\t</target>\t<target title="Repeat" hotkey="r" action="CALL:axsModerator.repeatFeaturedQuestion">\t .\t</target>  </list>  <list title="Questions" next="DOWN j" prev="UP k" type="dynamic">    <item>      //div[contains(@class, "QuestionListPanel")]/table/tbody/tr    </item>\t<target title="Yes" hotkey="y" action="CALL:axsModerator.voteYes">\t .\t</target>\t<target title="No" hotkey="n" action="CALL:axsModerator.voteNo">\t .\t</target>  </list>   <list title="Topics" fwd="DOWN j" back="UP k" type="dynamic">    <item index="5">      //div[contains(@class, "link link-regular ")]    </item>\t<target title="Go to topic" hotkey="ENTER" action="CALL:axsModerator.goToTopic">\t .//a\t</target>  </list>\t<target title="Ask a question" hotkey="a">\t //table[@class="AskMinimizedPanel"]//div[@class="goog-button-base-content"]\t</target></cnr>';axsModerator.axsNavObj.navInit(a,
h);axsModerator.axsLensObj=new z(axsModerator.axsJAXObj);axsModerator.axsNavObj.setLens(axsModerator.axsLensObj);axsModerator.axsLensObj.setMagnification(axsModerator.magSize);axsModerator.axsSoundObj=new B(j);axsModerator.axsNavObj.setSound(axsModerator.axsSoundObj);document.addEventListener("DOMAttrModified",axsModerator.domAttrModifiedHandler,j);axsModerator.axsNavObj.navListIdx=2;axsModerator.axsNavObj.fwdItem();axsModerator.goToTopic(axsModerator.axsNavObj.currentItem())};
axsModerator.refreshFeaturedQuestion=function(){if(axsModerator.axsNavObj.refreshList("Featured question")){axsModerator.axsNavObj.navListIdx=0;axsModerator.axsNavObj.fwdItem();var a=axsModerator.axsNavObj.currentItem().elem;a.addEventListener("DOMNodeInserted",axsModerator.featuredQuestionChangeHandler,j);axsModerator.featuredQuestionChangeHandler(h)}axsModerator.axsNavObj.refreshList("Questions")};
axsModerator.goToTopic=function(a){var b=a.elem,d=axsModerator.axsJAXObj.getActiveDocument(),c=d.createEvent("MouseEvents");c.initMouseEvent("click",j,j,d.defaultView,1,0,0,0,0,g,g,g,g,0,h);try{b.dispatchEvent(c)}catch(e){}};axsModerator.voteYes=function(a){var b=a.elem,d='.//div[contains(@class,"gwt-ToggleButton")]',c=axsModerator.axsJAXObj.evalXPath(d,b)[0];axsModerator.axsJAXObj.clickElem(c,g);axsModerator.axsJAXObj.speakTextViaNode("Press enter to confirm your yes vote.")};
axsModerator.voteNo=function(a){var b=a.elem,d='.//div[contains(@class,"gwt-ToggleButton")]',c=axsModerator.axsJAXObj.evalXPath(d,b)[1];axsModerator.axsJAXObj.clickElem(c,g);axsModerator.axsJAXObj.speakTextViaNode("Press enter to confirm your no vote.")};axsModerator.voteSkip=function(a){var b=a.elem,d='//div[(@class = "goog-button-base-content") and (text()="Skip")]',c=axsModerator.axsJAXObj.evalXPath(d,b)[0];axsModerator.axsJAXObj.clickElem(c,g)};
axsModerator.domAttrModifiedHandler=function(a){var b=a.target;if(b.className=="qdb-StatusBox"){axsModerator.axsLensObj.view(h);axsModerator.axsJAXObj.speakTextViaNode(b.textContent);b.textContent.indexOf("Loading")===0&&window.setTimeout(axsModerator.refreshFeaturedQuestion,500)}else b.className=="text text-error"&&axsModerator.axsJAXObj.speakTextViaNode(b.textContent)};
axsModerator.featuredQuestionChangeHandler=function(){var a=axsModerator.axsNavObj.currentItem().elem;axsModerator.axsNavObj.actOnItem(axsModerator.axsNavObj.currentItem());axsModerator.axsJAXObj.speakTextViaNode(a.textContent.replace("Voting is closed",""));axsModerator.axsLensObj.view(h)};axsModerator.repeatFeaturedQuestion=function(){axsModerator.featuredQuestionChangeHandler(h)};
axsModerator.keyHandler=function(a){if(a.ctrlKey)return j;if(a.keyCode==27){axsModerator.axsJAXObj.lastFocusedNode.blur();return g}if(axsModerator.axsJAXObj.inputFocused)return j;var b=axsModerator.keyCodeMap[a.keyCode]||axsModerator.charCodeMap[a.charCode];if(b)return b();return j};axsModerator.keyCodeMap={};
axsModerator.charCodeMap={45:function(){axsModerator.magSize-=0.1;axsModerator.axsLensObj.setMagnification(axsModerator.magSize);return g},61:function(){axsModerator.magSize+=0.1;axsModerator.axsLensObj.setMagnification(axsModerator.magSize);return g},63:function(){var a=axsModerator.HELP+axsModerator.axsNavObj.localHelpString()+axsModerator.axsNavObj.globalHelpString();axsModerator.axsJAXObj.speakTextViaNode(a);return g},47:function(){var a="//input",b=axsModerator.axsJAXObj.evalXPath(a,document.body)[0];
b.focus();b.select();return g}};window.setTimeout(axsModerator.init,1000);
 })();
