(function() { 
var JSCompiler_extractPrototype,AxsJAX=function(useTabKeyFix){this.ID_NUM_=0;this.tabbingStartPosNode=null;this.tabKeyFixOn=false;this.lastFocusedNode=null;this.inputFocused=false;var self=this;this.activeParent=document.body;this.addFocusBlurMonitors();if(useTabKeyFix){this.tabKeyFixOn=true;document.addEventListener("keypress",function(event){self.tabKeyHandler(event,self)},true);document.body.AXSJAX_TABKEYFIX_ADDED=true}};JSCompiler_extractPrototype=AxsJAX.prototype;
JSCompiler_extractPrototype.addFocusBlurMonitors=function(){var activeDoc=this.getActiveDocument(),self=this,focusHandler=function(evt){self.lastFocusedNode=evt.target;if(evt.target.tagName=="INPUT"||evt.target.tagName=="SELECT"||evt.target.tagName=="TEXTAREA")self.inputFocused=true;return true};activeDoc.addEventListener("focus",focusHandler,true);var blurHandler=function(evt){self.removeAttributeOf(self.lastFocusedNode,"aria-activedescendant");self.lastFocusedNode=null;if(evt.target.tagName=="INPUT"||
evt.target.tagName=="SELECT"||evt.target.tagName=="TEXTAREA")self.inputFocused=false;return true};activeDoc.addEventListener("blur",blurHandler,true)};JSCompiler_extractPrototype.getActiveDocument=function(){var activeDoc=this.activeParent;while(activeDoc.nodeType!=9)activeDoc=activeDoc.parentNode;return activeDoc};
JSCompiler_extractPrototype.speakNode=function(targetNode,opt_noFocusChange){targetNode.id||this.assignId(targetNode);if(opt_noFocusChange){this.setAttributeOf(targetNode,"live","rude");this.setAttributeOf(targetNode,"atomic","true");var activeDoc=this.getActiveDocument(),dummyNode=activeDoc.createElement("div");dummyNode.textContent=" ";dummyNode.name="AxsJAX_dummyNode";targetNode.lastChild&&targetNode.lastChild.name&&targetNode.lastChild.name==dummyNode.name&&targetNode.removeChild(targetNode.lastChild);
targetNode.appendChild(dummyNode)}else{var oldRole=this.getAttributeOf(targetNode,"role");this.setAttributeOf(targetNode,"role","row");var currentFocusedNode=this.lastFocusedNode;if(!currentFocusedNode||currentFocusedNode.nodeType==9){this.activeParent.tabIndex=-1;currentFocusedNode=this.activeParent}this.setAttributeOf(currentFocusedNode,"activedescendant",null);currentFocusedNode.focus&&currentFocusedNode.focus();this.setAttributeOf(currentFocusedNode,"activedescendant",targetNode.id);var self=
this;window.setTimeout(function(){oldRole?self.setAttributeOf(targetNode,"role",oldRole):self.removeAttributeOf(targetNode,"role")},0)}};
JSCompiler_extractPrototype.speakTextViaNode=function(textString,opt_anchorNode){var pixelId="AxsJAX_pixelAudioNode",pixelName="AxsJAX_pixelAudioNode",encodedClearPixel="data:image/gif;base64,R0lGODlhAQABAIAAANvf7wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",activeDoc=this.getActiveDocument(),pixelNode=null;if(opt_anchorNode){if(opt_anchorNode.previousSibling&&opt_anchorNode.previousSibling.name==pixelName)pixelNode=opt_anchorNode.previousSibling;else{pixelNode=activeDoc.createElement("img");pixelNode.name=
pixelName;pixelNode.setAttribute("tabindex",0);pixelNode.style.outline="none";pixelNode.src=encodedClearPixel;opt_anchorNode.parentNode.insertBefore(pixelNode,opt_anchorNode);this.forceATSync(pixelNode)}pixelNode.setAttribute("alt",textString);pixelNode.setAttribute("title",textString);window.setTimeout(function(){pixelNode.blur();pixelNode.focus()},0)}else{if((pixelNode=activeDoc.getElementById(pixelId))&&pixelNode.alt==textString)textString=textString+" ";if(!pixelNode){pixelNode=activeDoc.createElement("img");
pixelNode.id=pixelId;pixelNode.src=encodedClearPixel;activeDoc.body.appendChild(pixelNode)}pixelNode.setAttribute("alt",textString);pixelNode.setAttribute("title",textString);this.speakNode(pixelNode)}};
JSCompiler_extractPrototype.clickElem=function(targetNode,shiftKey){var activeDoc=this.getActiveDocument(),evt=activeDoc.createEvent("MouseEvents");evt.initMouseEvent("mousedown",true,true,activeDoc.defaultView,1,0,0,0,0,false,false,shiftKey,false,0,null);try{targetNode.dispatchEvent(evt)}catch(e){}evt=activeDoc.createEvent("MouseEvents");evt.initMouseEvent("mouseup",true,true,activeDoc.defaultView,1,0,0,0,0,false,false,shiftKey,false,0,null);try{targetNode.dispatchEvent(evt)}catch(e){}evt=activeDoc.createEvent("MouseEvents");
evt.initMouseEvent("click",true,true,activeDoc.defaultView,1,0,0,0,0,false,false,shiftKey,false,0,null);try{targetNode.dispatchEvent(evt)}catch(e){}var href=targetNode.getAttribute("href");if(targetNode.tagName=="A"&&href&&href!="#")if(shiftKey)window.open(targetNode.href);else document.location=targetNode.href};
JSCompiler_extractPrototype.assignId=function(targetNode,opt_prefixString){if(!targetNode)return"";if(targetNode.id)return targetNode.id;var prefix=opt_prefixString||"AxsJAX_ID_";return targetNode.id=prefix+this.ID_NUM_++};
JSCompiler_extractPrototype.markPosition=function(targetNode){if(!targetNode)return false;if(targetNode.tagName=="A"||targetNode.tagName=="INPUT"){this.tabbingStartPosNode=targetNode;return true}var allDescendants=targetNode.getElementsByTagName("*");for(var i=0,currentNode;currentNode=allDescendants[i];i++)if(currentNode.tagName=="A"||currentNode.tagName=="INPUT"||currentNode.hasAttribute("tabindex")&&currentNode.tabIndex!=-1){this.tabbingStartPosNode=currentNode;return true}return false};
JSCompiler_extractPrototype.tabKeyHandler=function(evt,selfRef){if(!selfRef.tabKeyFixOn)return true;if(evt.keyCode==9&&selfRef.tabbingStartPosNode){selfRef.tabbingStartPosNode.focus();selfRef.tabbingStartPosNode=null}return true};JSCompiler_extractPrototype.goTo=function(targetNode){this.speakNode(targetNode);targetNode.scrollIntoView(true);this.markPosition(targetNode)};
JSCompiler_extractPrototype.setAttributeOf=function(targetNode,attribute,value){if(!!targetNode){attribute=attribute.toLowerCase();switch(attribute){case "live":attribute="aria-live";break;case "activedescendant":attribute="aria-activedescendant";break;case "atomic":attribute="aria-atomic";break;default:break}targetNode.setAttribute(attribute,value)}};JSCompiler_extractPrototype.getAttributeOf=function(targetNode,attribute){return targetNode.getAttribute(attribute)};
JSCompiler_extractPrototype.removeAttributeOf=function(targetNode,attribute){targetNode&&targetNode.removeAttribute&&targetNode.removeAttribute(attribute)};JSCompiler_extractPrototype.forceATSync=function(targetNode){var id=this.assignId(targetNode),activeDoc=this.getActiveDocument(),loc=activeDoc.baseURI,indexOfHash=loc.indexOf("#");if(indexOfHash!=-1)loc=loc.substring(0,indexOfHash);activeDoc.location=loc+"#"+id};
JSCompiler_extractPrototype.evalXPath=function(expression,rootNode){try{var xpathIterator=rootNode.ownerDocument.evaluate(expression,rootNode,null,XPathResult.ORDERED_NODE_ITERATOR_TYPE,null)}catch(err){return[]}var results=[];for(var xpathNode=xpathIterator.iterateNext();xpathNode;xpathNode=xpathIterator.iterateNext())results.push(xpathNode);return results};var AxsNav=function(axsJAXObj){this.prevListKeys=this.nextListKeys="";this.navArray=[];this.navListIdx=0;this.navItemIdxs=[];this.lastItem=null;this.targetsArray=[];this.topCharCodeMap={};this.topKeyCodeMap={};this.charCodeMaps=[];this.keyCodeMaps=[];this.axs_=axsJAXObj;this.pk_=this.lens_=null;this.snd_=null;this.LIST_SND="list";this.ITEM_SND="item";this.WRAP_SND="wrap";this.keyHandler=null};
AxsNav.str={NEXT_LIST:"next list",PREV_LIST:"previous list",GO_FORWARD:"go forward",GO_BACKWARDS:"go backwards",CYCLE_NEXT:"cycle next",CYCLE_PREV:"cycle previous",SELECT_ACTION:"Select available action",NO_AVAILABLE_ACTION:"No available actions",PGUP:"Page up",PGDOWN:"Page down",ENTER:"Enter",ESC:"Escape",DEL:"Delete",UP:"Up",DOWN:"Down",LEFT:"Left",RIGHT:"Right"};JSCompiler_extractPrototype=AxsNav.prototype;
JSCompiler_extractPrototype.validateList=function(navList){var valid=true;if(navList.type=="dynamic"&&navList.items.length===0){this.lens_!==null&&this.lens_.view(null);navList.items=this.makeItemsArray(navList.origListObj);navList.targets=this.makeTargetsArray(navList.origListObj);if(this.navArray[this.navListIdx]===navList)this.navItemIdxs[this.navListIdx]=-1;else for(var i=0,tempList;tempList=this.navArray[i];i++)if(tempList===navList){this.navItemIdxs[i]=-1;break}}if(navList.items.length===0&&
navList.entryTarget===null)valid=false;return valid};JSCompiler_extractPrototype.doListEntryActions=function(){var currentList=this.currentList(),target=currentList.entryTarget,func=null;if(target!==null){this.actOnTarget(target);func=this.getCallbackFunction(target.action)}if(func===null){this.announceCurrentList();this.snd_!==null&&this.snd_.play(this.LIST_SND)}};
JSCompiler_extractPrototype.nextList=function(){if(this.navArray.length<1)return null;for(var i=0;this.navArray[i];i++){this.navListIdx++;if(this.navListIdx>=this.navArray.length)this.navListIdx=0;if(this.validateList(this.navArray[this.navListIdx]))break}return this.currentList()};JSCompiler_extractPrototype.prevList=function(){if(this.navArray.length<1)return null;for(var i=0;this.navArray[i];i++){this.navListIdx--;if(this.navListIdx<0)this.navListIdx=this.navArray.length-1;if(this.validateList(this.navArray[this.navListIdx]))break}return this.currentList()};
JSCompiler_extractPrototype.currentList=function(){return this.navArray[this.navListIdx]};JSCompiler_extractPrototype.announceCurrentList=function(){this.axs_.speakTextViaNode(this.currentList().title)};
JSCompiler_extractPrototype.nextItem=function(){if(this.navArray.length<1)return null;var currentList=this.navArray[this.navListIdx],items=currentList.items;if(items.length<1)return null;if(this.lastItem){var syncedIndex=this.lastItem.elem.AxsNavInfo[this.navListIdx];if(typeof syncedIndex!="undefined")this.navItemIdxs[this.navListIdx]=syncedIndex}this.navItemIdxs[this.navListIdx]++;var looped=false;if(this.navItemIdxs[this.navListIdx]>=items.length){this.navItemIdxs[this.navListIdx]=0;looped=true}var itemIndex=
this.navItemIdxs[this.navListIdx];if(items[itemIndex].elem.parentNode===null){this.lens_!==null&&this.lens_.view(null);currentList.items=this.makeItemsArray(currentList.origListObj);this.navItemIdxs[this.navListIdx]=0;itemIndex=this.navItemIdxs[this.navListIdx]}this.lastItem=items[itemIndex];if(this.snd_!==null)looped?this.snd_.play(this.WRAP_SND):this.snd_.play(this.ITEM_SND);return this.lastItem};
JSCompiler_extractPrototype.fwdItem=function(){var list=this.navArray[this.navListIdx],index=this.navItemIdxs[this.navListIdx];if(list.tailTarget!==null&&index+1>=list.items.length){this.actOnTarget(list.tailTarget);this.navItemIdxs[this.navListIdx]=0;return null}var item=this.nextItem();return item};
JSCompiler_extractPrototype.prevItem=function(){if(this.navArray.length<1)return null;var currentList=this.navArray[this.navListIdx],items=currentList.items;if(items.length<1)return null;if(this.lastItem){var syncedIndex=this.lastItem.elem.AxsNavInfo[this.navListIdx];if(typeof syncedIndex!="undefined")this.navItemIdxs[this.navListIdx]=syncedIndex}this.navItemIdxs[this.navListIdx]--;var looped=false;if(this.navItemIdxs[this.navListIdx]<0){this.navItemIdxs[this.navListIdx]=items.length-1;looped=true}var itemIndex=
this.navItemIdxs[this.navListIdx];if(items[itemIndex].elem.parentNode===null){this.lens_!==null&&this.lens_.view(null);currentList.items=this.makeItemsArray(currentList.origListObj);this.navItemIdxs[this.navListIdx]=currentList.items.length;itemIndex=this.navItemIdxs[this.navListIdx]}this.lastItem=items[itemIndex];if(this.snd_!==null)looped?this.snd_.play(this.WRAP_SND):this.snd_.play(this.ITEM_SND);return this.lastItem};
JSCompiler_extractPrototype.backItem=function(){var list=this.navArray[this.navListIdx],index=this.navItemIdxs[this.navListIdx];if(list.headTarget!==null&&index<=0){this.actOnTarget(list.headTarget);this.navItemIdxs[this.navListIdx]=list.items.length-1;return null}var item=this.prevItem();return item};
JSCompiler_extractPrototype.currentItem=function(){if(this.navArray.length<1)return null;if(this.lastItem){var syncedIndex=this.lastItem.elem.AxsNavInfo[this.navListIdx];if(typeof syncedIndex!="undefined")this.navItemIdxs[this.navListIdx]=syncedIndex}var currentList=this.navArray[this.navListIdx],items=currentList.items,itemIndex=this.navItemIdxs[this.navListIdx];return this.lastItem=items[itemIndex]};
JSCompiler_extractPrototype.getCallbackFunction=function(actionString){var callbackFunc=null;if(actionString!==null&&actionString.indexOf&&actionString.indexOf("CALL:")===0&&actionString.indexOf("(")===-1)try{callbackFunc=eval(actionString.substring(5))}catch(e){}return callbackFunc};
JSCompiler_extractPrototype.actOnItem=function(item){if(item!==null){var self=this,doAction=function(){var func=self.getCallbackFunction(item.action);if(func)func(item);else{self.lens_!==null&&self.lens_.view(item.elem);self.axs_.goTo(item.elem)}};if(this.axs_.lastFocusedNode&&this.axs_.lastFocusedNode.blur){var oldNode=this.axs_.lastFocusedNode;this.axs_.lastFocusedNode=null;oldNode.removeAttribute&&this.axs_.removeAttributeOf(oldNode,"aria-activedescendant");var tempBlurHandler=function(evt){evt.target.removeEventListener("blur",
tempBlurHandler,true);doAction()};oldNode.addEventListener("blur",tempBlurHandler,true);oldNode.blur()}else doAction()}else{var currentList=this.navArray[this.navListIdx];currentList.type=="dynamic"&&this.axs_.speakTextViaNode(currentList.onEmpty)}};
JSCompiler_extractPrototype.assignKeysToMethod=function(keyArray,charMap,keyMap,method){for(var i=0,key;key=keyArray[i];i++)if(key=="LEFT")keyMap[37]=method;else if(key=="UP")keyMap[38]=method;else if(key=="RIGHT")keyMap[39]=method;else if(key=="DOWN")keyMap[40]=method;else if(key=="PGUP")keyMap[33]=method;else if(key=="PGDOWN")keyMap[34]=method;else if(key=="ENTER")keyMap[13]=method;else if(key=="ESC")keyMap[27]=method;else if(key=="DEL")keyMap[46]=method;else charMap[key.charCodeAt(0)]=method};
JSCompiler_extractPrototype.assignItemKeys=function(keyStr,navListIdx,navTaskStr){var keys=[];if(!(keyStr==="")){keys=keyStr.split(" ");var self=this;if(navTaskStr=="prev")this.assignKeysToMethod(keys,this.charCodeMaps[navListIdx],this.keyCodeMaps[navListIdx],function(){self.actOnItem(self.prevItem())});else if(navTaskStr=="next")this.assignKeysToMethod(keys,this.charCodeMaps[navListIdx],this.keyCodeMaps[navListIdx],function(){self.actOnItem(self.nextItem())});else navTaskStr=="back"?this.assignKeysToMethod(keys,
this.charCodeMaps[navListIdx],this.keyCodeMaps[navListIdx],function(){self.actOnItem(self.backItem())}):this.assignKeysToMethod(keys,this.charCodeMaps[navListIdx],this.keyCodeMaps[navListIdx],function(){self.actOnItem(self.fwdItem())})}};
JSCompiler_extractPrototype.assignHotKeys=function(keyStr,navListIdx,emptyMsg){var keys=[];if(!(keyStr==="")){keys=keyStr.split(" ");var self=this;this.assignKeysToMethod(keys,this.topCharCodeMap,this.topKeyCodeMap,function(){if(self.validateList(self.navArray[navListIdx])){self.navListIdx=navListIdx;self.actOnItem(self.nextItem())}else self.axs_.speakTextViaNode(emptyMsg)})}};
JSCompiler_extractPrototype.assignEmptyMsgKeys=function(keyStr,emptyMsg){var keys=[];if(!(keyStr==="")){keys=keyStr.split(" ");var self=this;this.assignKeysToMethod(keys,this.topCharCodeMap,this.topKeyCodeMap,function(){self.axs_.speakTextViaNode(emptyMsg)})}};JSCompiler_extractPrototype.assignTargetKeys=function(target,charMap,keyMap){var keys=[];if(!(target.hotkey==="")){keys=target.hotkey.split(" ");var self=this;this.assignKeysToMethod(keys,charMap,keyMap,function(){self.actOnTarget(target)})}};
JSCompiler_extractPrototype.actOnTarget=function(target){var xpath=target.xpath,rootNode=this.axs_.getActiveDocument().documentElement;if(xpath.indexOf(".")===0)rootNode=this.currentItem().elem;var elems=this.axs_.evalXPath(xpath,rootNode);if(elems.length<1)this.axs_.speakTextViaNode(target.onEmpty);else{var func=this.getCallbackFunction(target.action);if(func){var item={};item.action=target.action;item.elem=elems[0];func(item)}else{this.axs_.clickElem(elems[0],false);elems[0].scrollIntoView(true)}this.axs_.markPosition(elems[0])}};
JSCompiler_extractPrototype.getFunctionForKey=function(keyCode,charCode){var command=null,idx=this.navListIdx;if(idx<this.keyCodeMaps.length)command=this.keyCodeMaps[idx][keyCode]||this.charCodeMaps[idx][charCode]||null;if(command===null)command=this.topKeyCodeMap[keyCode]||this.topCharCodeMap[charCode];return command};
JSCompiler_extractPrototype.navInit=function(cnrString,opt_customNavMethod){var cnrJson={};cnrJson.lists=[];var parser=new DOMParser,cnrDOM=parser.parseFromString(cnrString,"text/xml"),lists=cnrDOM.getElementsByTagName("list"),i,listNode;for(i=0,listNode;listNode=lists[i];i++){var navList={};navList.title=listNode.getAttribute("title");navList.hotkey=listNode.getAttribute("hotkey");navList.next=listNode.getAttribute("next");navList.prev=listNode.getAttribute("prev");navList.fwd=listNode.getAttribute("fwd");
navList.back=listNode.getAttribute("back");navList.onEmpty=listNode.getAttribute("onEmpty");navList.type=listNode.getAttribute("type");var j,entry,k,attributes,length;navList.items=[];var cnrItems=listNode.getElementsByTagName("item");for(j=0;entry=cnrItems[j];j++){var item={};item.xpath=entry.textContent;if(entry.attributes instanceof NamedNodeMap){attributes=entry.attributes;length=attributes.length;for(k=0;k<length;k++){var attrib=attributes.item(k);item[attrib.nodeName]=attrib.value}}navList.items.push(item)}navList.targets=
[];var cnrTargets=listNode.getElementsByTagName("target");for(j=0;entry=cnrTargets[j];j++){var target={};target.xpath=entry.textContent;if(entry.attributes instanceof NamedNodeMap){attributes=entry.attributes;length=attributes.length;for(k=0;k<length;k++){var attrib=attributes.item(k);target[attrib.nodeName]=attrib.value}}navList.targets.push(target)}cnrJson.lists.push(navList)}cnrJson.targets=[];var currentNode,cnrNode=cnrDOM.firstChild;for(i=0,currentNode;currentNode=cnrNode.childNodes[i];i++)if(currentNode.tagName==
"target"){var target={};target.xpath=currentNode.textContent;if(currentNode.attributes instanceof NamedNodeMap){attributes=currentNode.attributes;length=attributes.length;for(k=0;k<length;k++){var attrib=attributes.item(k);target[attrib.nodeName]=attrib.value}}cnrJson.targets.push(target)}cnrJson.next=cnrNode.getAttribute("next");cnrJson.prev=cnrNode.getAttribute("prev");if(opt_customNavMethod===null||typeof opt_customNavMethod=="undefined")this.navInitJson(cnrJson,opt_customNavMethod);else{var func=
new (function(dummyJson,navArray,emptyLists,targetsArray){opt_customNavMethod(cnrNode,navArray,emptyLists,targetsArray)});this.navInitJson(cnrJson,func)}};
JSCompiler_extractPrototype.globalHelpString=function(){var globalActions=this.getGlobalActions(),helpStr="";for(var i=0,action;action=globalActions[i];i++)helpStr=helpStr+action.keys+", "+action.title+". ";helpStr=helpStr+this.nextListKeys+", "+AxsNav.str.NEXT_LIST;helpStr=helpStr+this.prevListKeys+", "+AxsNav.str.PREV_LIST;helpStr=helpStr.replace("PGUP",AxsNav.str.PGUP);helpStr=helpStr.replace("PGDOWN",AxsNav.str.PGDOWN);helpStr=helpStr.replace("ENTER",AxsNav.str.ENTER);helpStr=helpStr.replace("DEL",
AxsNav.str.DELETE);helpStr=helpStr.replace("UP",AxsNav.str.UP);helpStr=helpStr.replace("DOWN",AxsNav.str.DOWN);helpStr=helpStr.replace("LEFT",AxsNav.str.LEFT);return helpStr=helpStr.replace("RIGHT",AxsNav.str.RIGHT)};
JSCompiler_extractPrototype.localHelpString=function(){var localActions=this.getLocalActions(),helpStr="";for(var i=0,action;action=localActions[i];i++)helpStr=helpStr+action.keys+", "+action.title+". ";var list=this.currentList();if(list.nextKeys!=="")helpStr=helpStr+list.nextKeys+", "+AxsNav.str.CYCLE_NEXT+". ";if(list.prevKeys!=="")helpStr=helpStr+list.prevKeys+", "+AxsNav.str.CYCLE_PREV+". ";if(list.fwdKeys!=="")helpStr=helpStr+list.fwdKeys+", "+AxsNav.str.GO_FORWARD+". ";if(list.backKeys!=="")helpStr=
helpStr+list.backKeys+", "+AxsNav.str.GO_BACKWARDS+". ";helpStr=helpStr.replace("PGUP",AxsNav.str.PGUP);helpStr=helpStr.replace("PGDOWN",AxsNav.str.PGDOWN);helpStr=helpStr.replace("ENTER",AxsNav.str.ENTER);helpStr=helpStr.replace("DEL",AxsNav.str.DELETE);helpStr=helpStr.replace("UP",AxsNav.str.UP);helpStr=helpStr.replace("DOWN",AxsNav.str.DOWN);helpStr=helpStr.replace("LEFT",AxsNav.str.LEFT);return helpStr=helpStr.replace("RIGHT",AxsNav.str.RIGHT)};
JSCompiler_extractPrototype.setLens=function(lens){this.lens_=lens};JSCompiler_extractPrototype.setSound=function(snd){this.snd_=snd};
JSCompiler_extractPrototype.getGlobalActions=function(){var globalActions=[],action;for(var i=0,list;list=this.navArray[i];i++)if(list.hotKeys!==""){action={};action.title=list.title;action.keys=list.hotKeys;globalActions.push(action)}for(var j=0,target;target=this.targetsArray[j];j++)if(this.isValidTargetAction(target)){action={};action.title=target.title;action.keys=target.hotkey;globalActions.push(action)}return globalActions};
JSCompiler_extractPrototype.getLocalActions=function(){var localActions=[],currentList=this.currentList();for(var i=0,target;target=currentList.targets[i];i++)if(this.isValidTargetAction(target)){var action={};action.title=target.title;action.keys=target.hotkey;localActions.push(action)}return localActions};
JSCompiler_extractPrototype.isValidTargetAction=function(target){var valid=false;if(target.hotkey!==""){var xPath=target.xpath,rootNode=this.axs_.getActiveDocument().body;if(xPath.indexOf(".")===0){var currentItem=this.currentItem();if(currentItem)rootNode=currentItem.elem}var nodes=this.axs_.evalXPath(xPath,rootNode);if(nodes.length>0)valid=true}return valid};
JSCompiler_extractPrototype.navInitJson=function(cnrJson,opt_customNavMethod){this.navArray=[];this.navListIdx=0;this.navItemIdxs=[];var emptyLists=[],i,currentList;for(i=0,currentList;currentList=cnrJson.lists[i];i++){var navList={};navList.cnrNode=null;navList.origListObj=currentList;navList.title=currentList.title||"";navList.hotKeys=currentList.hotkey||"";navList.nextKeys=currentList.next||"";navList.prevKeys=currentList.prev||"";navList.fwdKeys=currentList.fwd||"";navList.backKeys=currentList.back||
"";navList.onEmpty=currentList.onEmpty||"";navList.type=currentList.type||"";navList.tailTarget=null;navList.headTarget=null;navList.entryTarget=null;navList.items=this.makeItemsArray(currentList);navList.targets=this.makeTargetsArray(currentList);for(var j=0,listTarget;listTarget=navList.targets[j];j++)if(listTarget.trigger=="listTail")navList.tailTarget=listTarget;else if(listTarget.trigger=="listHead")navList.headTarget=listTarget;else if(listTarget.trigger=="listEntry")navList.entryTarget=listTarget;
if(navList.items.length>0||navList.type=="dynamic"){this.navArray.push(navList);this.navItemIdxs.push(-1)}else navList.hotKeys!==""&&emptyLists.push(navList)}this.targetsArray=[];this.targetsIdx=0;var currentTarget;if(cnrJson.targets)for(i=0,currentTarget;currentTarget=cnrJson.targets[i];i++){var target={};target.xpath=currentTarget.xpath;target.xpath=target.xpath.replace(/^\s\s*/,"").replace(/\s\s*$/,"");target.title=currentTarget.title||"";target.trigger=currentTarget.trigger||"key";target.hotkey=
currentTarget.hotkey||"";target.action=currentTarget.action||"click";target.onEmpty=currentTarget.onEmpty||"";this.targetsArray.push(target)}this.keyHandler!==null&&document.removeEventListener("keypress",this.keyHandler,true);opt_customNavMethod===null||typeof opt_customNavMethod=="undefined"?this.setUpNavKeys(cnrJson,emptyLists):opt_customNavMethod(cnrJson,this.navArray,emptyLists,this.targetsArray)};
JSCompiler_extractPrototype.makeItemsArray=function(jsonListObj){var itemsArray=[];if(!jsonListObj.items)return itemsArray;for(var i=0,entry;entry=jsonListObj.items[i];i++)try{var xpath=entry.xpath.replace(/^\s\s*/,"").replace(/\s\s*$/,""),htmlElem=this.axs_.getActiveDocument().documentElement,elems=this.axs_.evalXPath(xpath,htmlElem),idxStr=entry.index||"0",idx=parseInt(idxStr,10),count=elems.length-idx,countStr=entry.count||"*";if(countStr!="*")count=parseInt(countStr,10);var end=count+idx,action=
entry.action||null;while(idx<end){var item={};item.action=action;item.elem=elems[idx];if(typeof item.elem!="undefined"){if(typeof item.elem.AxsNavInfo=="undefined")item.elem.AxsNavInfo={};item.elem.AxsNavInfo[this.navArray.length]=itemsArray.length;itemsArray.push(item)}idx++}}catch(err){}return itemsArray};
JSCompiler_extractPrototype.makeTargetsArray=function(jsonListObj){var targetsArray=[];if(!jsonListObj.targets)return targetsArray;for(var i=0,entry;entry=jsonListObj.targets[i];i++){var target={};target.xpath=entry.xpath.replace(/^\s\s*/,"").replace(/\s\s*$/,"");target.title=entry.title||"";target.trigger=entry.trigger||"key";target.hotkey=entry.hotkey||"";target.action=entry.action||"click";target.onEmpty=entry.onEmpty||"";targetsArray.push(target)}return targetsArray};
JSCompiler_extractPrototype.setUpNavKeys=function(cnrJson,emptyLists){var self=this,i;this.topCharCodeMap={};this.topKeyCodeMap={};this.charCodeMaps=[];this.keyCodeMaps=[];var target;for(i=0,target;target=this.targetsArray[i];i++)this.assignTargetKeys(target,this.topCharCodeMap,this.topKeyCodeMap);var keys=[];this.nextListKeys=cnrJson.next||"";if(this.nextListKeys!=="")keys=this.nextListKeys.split(" ");this.assignKeysToMethod(keys,this.topCharCodeMap,this.topKeyCodeMap,function(){self.nextList();
self.doListEntryActions()});keys=[];this.prevListKeys=cnrJson.prev||"";if(this.prevListKeys!=="")keys=this.prevListKeys.split(" ");this.assignKeysToMethod(keys,this.topCharCodeMap,this.topKeyCodeMap,function(){self.prevList();self.doListEntryActions()});var list;for(i=0,list;list=this.navArray[i];i++){var charMap={},keyMap={};this.charCodeMaps.push(charMap);this.keyCodeMaps.push(keyMap);this.assignItemKeys(list.nextKeys,i,"next");this.assignItemKeys(list.prevKeys,i,"prev");this.assignItemKeys(list.fwdKeys,
i,"fwd");this.assignItemKeys(list.backKeys,i,"back");this.assignHotKeys(list.hotKeys,i,list.onEmpty);var j;for(j=0,target;target=list.targets[j];j++)this.assignTargetKeys(target,charMap,keyMap)}var emptyList;for(i=0,emptyList;emptyList=emptyLists[i];i++)this.assignEmptyMsgKeys(emptyList.hotKeys,emptyList.onEmpty);this.keyHandler=function(evt){if(evt.ctrlKey)return true;if(self.axs_.inputFocused)return true;var command=self.getFunctionForKey(evt.keyCode,evt.charCode);if(command)return command()};document.addEventListener("keypress",
this.keyHandler,true)};var AxsLens=function(axsJAXObj){this.axsJAXObj=axsJAXObj;this.multiplier=1.5;this.padding=-1;this.scrollMode=0;this.activeDoc=axsJAXObj.getActiveDocument();this.lens=this.activeDoc.createElement("span");this.lens.style.backgroundColor="#CCE6FF";this.lens.style.borderColor="#0000CC";this.lens.style.borderWidth="medium";this.lens.style.borderStyle="groove";this.lens.style.position="absolute";this.lens.style.display="none";this.activeDoc.body.appendChild(this.lens);this.callback=function(){}};
AxsLens.ScrollMode={NONE:0,FORCE_TO_LENS:1};JSCompiler_extractPrototype=AxsLens.prototype;
JSCompiler_extractPrototype.view=function(targetNode){while(this.lens.firstChild)this.lens.removeChild(this.lens.firstChild);if(targetNode===null)this.lens.style.display="none";else{var left=0,top=0,obj=targetNode;if(obj.offsetParent){left=obj.offsetLeft;top=obj.offsetTop;obj=obj.offsetParent;while(obj!==null){left+=obj.offsetLeft;top+=obj.offsetTop;obj=obj.offsetParent}}this.lens.appendChild(targetNode.cloneNode(true));this.lens.style.top=top+"px";this.lens.style.left=left+"px";this.lens.style.zIndex=
999;this.lens.style.display="block";this.magnify()}};JSCompiler_extractPrototype.setMagnification=function(multiplier){this.multiplier=multiplier;this.magnify()};
JSCompiler_extractPrototype.magnify=function(){this.activeDoc.body.removeChild(this.lens);this.magnifyText();this.enlargeImages();this.addPadding();this.activeDoc.body.appendChild(this.lens);this.callback&&this.callback(this.lens);if(this.scrollMode==AxsLens.ScrollMode.FORCE_TO_LENS){var self=this;window.setTimeout(function(){self.lens.scrollIntoView(true)},0)}};
JSCompiler_extractPrototype.addPadding=function(){if(!(this.padding<0)){var xPath="//*[not(.//*)]",leafNodes=this.axsJAXObj.evalXPath(xPath,this.lens);for(var i=0,leafNode;leafNode=leafNodes[i];i++)leafNode.style.padding=this.padding+"px"}};
JSCompiler_extractPrototype.enlargeImages=function(){var images=this.lens.getElementsByTagName("img");for(var i=0,image;image=images[i];i++){if(!image.hasAttribute("Axs_OrigHeight")){image.setAttribute("Axs_OrigHeight",image.height);image.setAttribute("Axs_OrigWidth",image.width)}image.height=image.getAttribute("Axs_OrigHeight")*this.multiplier;image.width=image.getAttribute("Axs_OrigWidth")*this.multiplier}};
JSCompiler_extractPrototype.magnifyText=function(){var hasFontSizeAdjust="fontSizeAdjust"in this.lens.style;if(hasFontSizeAdjust){var fontSizeAdjust=this.multiplier*0.52;this.lens.style.fontSizeAdjust=fontSizeAdjust}else{var adjustment=this.multiplier*100+"%";this.lens.style.setProperty("font-size",adjustment,"important")}var subnodes=this.lens.getElementsByTagName("*");for(var i=0,node;node=subnodes[i];i++){node.style.setProperty("line-height","normal","important");hasFontSizeAdjust||node.style.setProperty("font-size",
"100%","important")}};var AxsSound=function(earconsOnly){var baseURL="http://google-axsjax.googlecode.com/svn/trunk/";this.earconsSwf=baseURL+"common/earcons/axsEarcons.swf?sound=";this.earconsObj=null;this.earconsOnly=earconsOnly;this.sm2BaseURL=baseURL+"thirdparty/soundmanager2/";this.sm2LinkerFrame=null;this.initSucceeded=false;this.verbosity="minimal";this.busyInitializing=false;this.initChecks=0};JSCompiler_extractPrototype=AxsSound.prototype;
JSCompiler_extractPrototype.init=function(){if(!this.earconsOnly)if(!this.initSucceeded)if(!this.busyInitializing){this.busyInitializing=true;this.initChecks=0;if(this.sm2LinkerFrame!==null){this.sm2LinkerFrame.parentNode.removeChild(this.sm2LinkerFrame);this.sm2LinkerFrame=null}this.sm2LinkerFrame=document.createElement("iframe");var loc=document.location.toString();if(loc.indexOf("#")!=-1)loc=loc.substring(0,loc.indexOf("#"));this.sm2LinkerFrame.src=this.sm2BaseURL+"AxsJAX_SM2_Linker.html#Verbosity="+
this.verbosity+",Parent="+loc;this.sm2LinkerFrame.width="0%";this.sm2LinkerFrame.height="0%";this.sm2LinkerFrame.style.top="-1000";this.sm2LinkerFrame.style.left="-1000";this.sm2LinkerFrame.style.position="absolute";document.getElementsByTagName("body")[0].appendChild(this.sm2LinkerFrame);this.checkInitStatus()}};
JSCompiler_extractPrototype.checkInitStatus=function(){if(document.location.hash=="#InitSuccess"){this.initSucceeded=true;this.busyInitializing=false}else if(this.verbosity=="none"&&this.initChecks>0){this.initSucceeded=true;this.busyInitializing=false}else{var self=this;window.setTimeout(function(){self.checkInitStatus()},100);this.initChecks++}};
JSCompiler_extractPrototype.play=function(url){var playedEarcon=this.playEarcon(url);if(!(this.earconsOnly||playedEarcon))if(this.initSucceeded)this.sm2LinkerFrame.src=this.sm2BaseURL+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Play("+url+")";else{this.init();var self=this;window.setTimeout(function(){self.play(url)},500)}};
JSCompiler_extractPrototype.stop=function(){if(this.earconsObj){this.earconsObj.parentNode.removeChild(this.earconsObj);this.earconsObj=null}if(!this.earconsOnly)if(!!this.initSucceeded)this.sm2LinkerFrame.src=this.sm2BaseURL+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Stop()"};
JSCompiler_extractPrototype.getTime=function(){if(this.earconsOnly)return-1;if(!this.initSucceeded)return-1;var timeKeyword="Time=",timeStr=unescape(document.location.hash);if(timeStr.indexOf(timeKeyword)==-1)return-1;var timeStart=timeStr.indexOf(timeKeyword)+timeKeyword.length,time=parseInt(timeStr.substring(timeStart),10);return time};
JSCompiler_extractPrototype.playEarcon=function(earcon){var earconCMD="";switch(earcon){case "alert":earconCMD="alert";break;case "deselect":earconCMD="deselect";break;case "item":earconCMD="item";break;case "list":earconCMD="list";break;case "select":earconCMD="select";break;case "success":earconCMD="success";break;case "wrap":earconCMD="wrap";break;default:}if(!(earconCMD==="")){if(this.earconsObj===null){this.earconsObj=document.createElement("embed");this.earconsObj.height=0;this.earconsObj.width=
0;document.body.appendChild(this.earconsObj)}this.earconsObj.src=this.earconsSwf+earconCMD}};var axsModerator={};axsModerator.HELP="The following shortcut keys are available. ";axsModerator.axsJAXObj=null;axsModerator.axsNavObj=null;axsModerator.axsLensObj=null;axsModerator.axsSoundObj=null;axsModerator.magSize=1.5;
axsModerator.init=function(){axsModerator.axsJAXObj=new AxsJAX(true);axsModerator.axsNavObj=new AxsNav(axsModerator.axsJAXObj);document.addEventListener("keypress",axsModerator.keyHandler,true);var cnrString='<cnr next="RIGHT l" prev="LEFT h">     <list title="Featured question" next="DOWN j" prev="UP k">    <item>      //div[contains(@class, "featured") and not(contains(@class, "text-featured"))]    </item>\t<target title="Yes" hotkey="y" action="CALL:axsModerator.voteYes">\t .\t</target>\t<target title="No" hotkey="n" action="CALL:axsModerator.voteNo">\t .\t</target>\t<target title="Skip" hotkey="s" action="CALL:axsModerator.voteSkip">\t .\t</target>\t<target title="Repeat" hotkey="r" action="CALL:axsModerator.repeatFeaturedQuestion">\t .\t</target>  </list>  <list title="Questions" next="DOWN j" prev="UP k">    <item>      //table[contains(@class, "QuestionListPanel")]/tbody/tr    </item>\t<target title="Yes" hotkey="y" action="CALL:axsModerator.voteYes">\t .\t</target>\t<target title="No" hotkey="n" action="CALL:axsModerator.voteNo">\t .\t</target>  </list>   <list title="Topics" fwd="DOWN j" back="UP k">    <item>      //div[contains(@class, "fork")]/..//div[contains(@class, "link link-regular G1k55290GB")]    </item>\t<target title="Go to topic" hotkey="ENTER" action="CALL:axsModerator.goToTopic">\t .//a\t</target>  </list>\t<target title="Ask a question" hotkey="a">\t //table[@class="AskMinimizedPanel"]//div[@class="goog-button-base-content"]\t</target></cnr>';axsModerator.axsNavObj.navInit(cnrString,
null);axsModerator.axsLensObj=new AxsLens(axsModerator.axsJAXObj);axsModerator.axsNavObj.setLens(axsModerator.axsLensObj);axsModerator.axsLensObj.setMagnification(axsModerator.magSize);axsModerator.axsSoundObj=new AxsSound(true);axsModerator.axsNavObj.setSound(axsModerator.axsSoundObj);document.addEventListener("DOMAttrModified",axsModerator.domAttrModifiedHandler,true);var featuredQxpath='//div[contains(@class, "featured") and not(contains(@class, "text-featured"))]//div[contains(@class,"text text-less paragraph")]',
featuredQuestionNode=axsModerator.axsJAXObj.evalXPath(featuredQxpath,document.body)[0];if(featuredQuestionNode){featuredQuestionNode.addEventListener("DOMNodeInserted",axsModerator.featuredQuestionChangeHandler,true);axsModerator.axsNavObj.fwdItem();axsModerator.featuredQuestionChangeHandler(null)}};axsModerator.goToTopic=function(topicItem){var aElem=topicItem.elem,targUrl=aElem.href;window.content.document.location=targUrl;window.setTimeout(function(){window.location.reload()},1000)};
axsModerator.voteYes=function(questionItem){var questionElem=questionItem.elem,xpath='.//div[contains(@class,"gwt-ToggleButton")]',yesButton=axsModerator.axsJAXObj.evalXPath(xpath,questionElem)[0];axsModerator.axsJAXObj.clickElem(yesButton,false);axsModerator.axsJAXObj.speakTextViaNode("Press enter to confirm your yes vote.")};
axsModerator.voteNo=function(questionItem){var questionElem=questionItem.elem,xpath='.//div[contains(@class,"gwt-ToggleButton")]',noButton=axsModerator.axsJAXObj.evalXPath(xpath,questionElem)[1];axsModerator.axsJAXObj.clickElem(noButton,false);axsModerator.axsJAXObj.speakTextViaNode("Press enter to confirm your no vote.")};
axsModerator.voteSkip=function(questionItem){var questionElem=questionItem.elem,xpath='//div[(@class = "goog-button-base-content") and (text()="Skip")]',skipButton=axsModerator.axsJAXObj.evalXPath(xpath,questionElem)[0];axsModerator.axsJAXObj.clickElem(skipButton,false)};axsModerator.domAttrModifiedHandler=function(evt){var target=evt.target;target.className=="qdb-StatusBox"&&axsModerator.axsJAXObj.speakTextViaNode(target.textContent)};
axsModerator.featuredQuestionChangeHandler=function(){axsModerator.axsNavObj.actOnItem(axsModerator.axsNavObj.currentItem());axsModerator.axsLensObj.view(null)};axsModerator.repeatFeaturedQuestion=function(){axsModerator.featuredQuestionChangeHandler(null)};
axsModerator.keyHandler=function(evt){if(evt.ctrlKey)return true;if(evt.keyCode==27){axsModerator.axsJAXObj.lastFocusedNode.blur();return false}if(axsModerator.axsJAXObj.inputFocused)return true;var command=axsModerator.keyCodeMap[evt.keyCode]||axsModerator.charCodeMap[evt.charCode];if(command)return command();return true};axsModerator.keyCodeMap={};
axsModerator.charCodeMap={45:function(){axsModerator.magSize-=0.1;axsModerator.axsLensObj.setMagnification(axsModerator.magSize);return false},61:function(){axsModerator.magSize+=0.1;axsModerator.axsLensObj.setMagnification(axsModerator.magSize);return false},63:function(){var helpStr=axsModerator.HELP+axsModerator.axsNavObj.localHelpString()+axsModerator.axsNavObj.globalHelpString();axsModerator.axsJAXObj.speakTextViaNode(helpStr);return false},47:function(){var xpath="//input",search=axsModerator.axsJAXObj.evalXPath(xpath,
document.body)[0];search.focus();search.select();return false}};window.setTimeout(axsModerator.init,1000);
 })();
