(function() { 
var g=false,h=null,i=true,k,l=function(a){this.bb=0;this.O=h;this.Ta=g;this.s=h;this.W=g;var b=this;this.ba=document.body;this.gb();if(a){this.Ta=i;document.addEventListener("keypress",function(d){b.Jb(d,b)},i);document.body.Kb=i}};k=l.prototype;
k.gb=function(){var a=this.r(),b=this,d=function(e){b.s=e.target;if(e.target.tagName=="INPUT"||e.target.tagName=="SELECT"||e.target.tagName=="TEXTAREA")b.W=i;return i};a.addEventListener("focus",d,i);var c=function(e){b.pa(b.s,"aria-activedescendant");b.s=h;if(e.target.tagName=="INPUT"||e.target.tagName=="SELECT"||e.target.tagName=="TEXTAREA")b.W=g;return i};a.addEventListener("blur",c,i)};k.r=function(){var a=this.ba;while(a.nodeType!=9)a=a.parentNode;return a};
k.Sa=function(a,b){a.id||this.Da(a);if(b){this.J(a,"live","rude");this.J(a,"atomic","true");var d=this.r(),c=d.createElement("div");c.textContent=" ";c.name="AxsJAX_dummyNode";a.lastChild&&a.lastChild.name&&a.lastChild.name==c.name&&a.removeChild(a.lastChild);a.appendChild(c)}else{var e=this.sb(a,"role");this.J(a,"role","row");var f=this.s;if(!f||f.nodeType==9){this.ba.tabIndex=-1;f=this.ba}this.J(f,"activedescendant",h);f.focus&&f.focus();this.J(f,"activedescendant",a.id);var j=this;window.setTimeout(function(){e?
j.J(a,"role",e):j.pa(a,"role")},0)}};
k.v=function(a,b){var d="AxsJAX_pixelAudioNode",c="AxsJAX_pixelAudioNode",e="data:image/gif;base64,R0lGODlhAQABAIAAANvf7wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",f=this.r(),j=h;if(b){if(b.previousSibling&&b.previousSibling.name==c)j=b.previousSibling;else{j=f.createElement("img");j.name=c;j.setAttribute("tabindex",0);j.style.outline="none";j.src=e;b.parentNode.insertBefore(j,b);this.qb(j)}j.setAttribute("alt",a);j.setAttribute("title",a);window.setTimeout(function(){j.blur();j.focus()},0)}else{if((j=
f.getElementById(d))&&j.alt==a)a=a+" ";if(!j){j=f.createElement("img");j.id=d;j.src=e;f.body.appendChild(j)}j.setAttribute("alt",a);j.setAttribute("title",a);this.Sa(j)}};
k.U=function(a,b){var d=this.r(),c=d.createEvent("MouseEvents");c.initMouseEvent("mousedown",i,i,d.defaultView,1,0,0,0,0,g,g,b,g,0,h);try{a.dispatchEvent(c)}catch(e){}c=d.createEvent("MouseEvents");c.initMouseEvent("mouseup",i,i,d.defaultView,1,0,0,0,0,g,g,b,g,0,h);try{a.dispatchEvent(c)}catch(e){}c=d.createEvent("MouseEvents");c.initMouseEvent("click",i,i,d.defaultView,1,0,0,0,0,g,g,b,g,0,h);try{a.dispatchEvent(c)}catch(e){}var f=a.getAttribute("href");if(a.tagName=="A"&&f&&f!="#")if(b)window.open(a.href);
else document.location=a.href};k.Da=function(a,b){if(!a)return"";if(a.id)return a.id;var d=b||"AxsJAX_ID_";return a.id=d+this.bb++};k.Pa=function(a){if(!a)return g;if(a.tagName=="A"||a.tagName=="INPUT"){this.O=a;return i}var b=a.getElementsByTagName("*");for(var d=0,c;c=b[d];d++)if(c.tagName=="A"||c.tagName=="INPUT"||c.hasAttribute("tabindex")&&c.tabIndex!=-1){this.O=c;return i}return g};k.Jb=function(a,b){if(!b.Ta)return i;if(a.keyCode==9&&b.O){b.O.focus();b.O=h}return i};
k.xb=function(a){this.Sa(a);a.scrollIntoView(i);this.Pa(a)};k.J=function(a,b,d){if(!!a){b=b.toLowerCase();switch(b){case "live":b="aria-live";break;case "activedescendant":b="aria-activedescendant";break;case "atomic":b="aria-atomic";break;default:break}a.setAttribute(b,d)}};k.sb=function(a,b){return a.getAttribute(b)};k.pa=function(a,b){a&&a.removeAttribute&&a.removeAttribute(b)};
k.qb=function(a){var b=this.Da(a),d=this.r(),c=d.baseURI,e=c.indexOf("#");if(e!=-1)c=c.substring(0,e);d.location=c+"#"+b};k.q=function(a,b){try{var d=b.ownerDocument.evaluate(a,b,h,XPathResult.ORDERED_NODE_ITERATOR_TYPE,h)}catch(c){return[]}var e=[];for(var f=d.iterateNext();f;f=d.iterateNext())e.push(f);return e};var n=function(a){this.aa=this.Z="";this.b=[];this.a=0;this.d=[];this.k=h;this.P=[];this.A={};this.B={};this.z=[];this.w=[];this.f=a;this.Tb=this.t=h;this.u=h;this.cb="list";this.wa="item";this.Ca="wrap";this.H=h};n.e={db:"next list",eb:"previous list",$a:"go forward",Za:"go backwards",Va:"cycle next",Wa:"cycle previous",Pb:"Select available action",Ob:"No available actions",za:"Page up",ya:"Page down",va:"Enter",Mb:"Escape",Lb:"Delete",Ba:"Up",ua:"Down",xa:"Left",Aa:"Right"};k=n.prototype;
k.ta=function(a){var b=i;if(a.type=="dynamic"&&a.i.length===0){this.t!==h&&this.t.view(h);a.i=this.Y(a.$);a.l=this.Oa(a.$);if(this.b[this.a]===a)this.d[this.a]=-1;else for(var d=0,c;c=this.b[d];d++)if(c===a){this.d[d]=-1;break}}if(a.i.length===0&&a.ea===h)b=g;return b};k.Ia=function(){var a=this.F(),b=a.ea,d=h;if(b!==h){this.Q(b);d=this.ga(b.action)}if(d===h){this.ib();this.u!==h&&this.u.I(this.cb)}};
k.Cb=function(){if(this.b.length<1)return h;for(var a=0;this.b[a];a++){this.a++;if(this.a>=this.b.length)this.a=0;if(this.ta(this.b[this.a]))break}return this.F()};k.Eb=function(){if(this.b.length<1)return h;for(var a=0;this.b[a];a++){this.a--;if(this.a<0)this.a=this.b.length-1;if(this.ta(this.b[this.a]))break}return this.F()};k.F=function(){return this.b[this.a]};k.ib=function(){this.f.v(this.F().title)};
k.la=function(){if(this.b.length<1)return h;var a=this.b[this.a],b=a.i;if(b.length<1)return h;if(this.k){var d=this.k.h.K[this.a];if(typeof d!="undefined")this.d[this.a]=d}this.d[this.a]++;var c=g;if(this.d[this.a]>=b.length){this.d[this.a]=0;c=i}var e=this.d[this.a];if(b[e].h.parentNode===h){this.t!==h&&this.t.view(h);a.i=this.Y(a.$);this.d[this.a]=0;e=this.d[this.a]}this.k=b[e];if(this.u!==h)c?this.u.I(this.Ca):this.u.I(this.wa);return this.k};
k.Ka=function(){var a=this.b[this.a],b=this.d[this.a];if(a.sa!==h&&b+1>=a.i.length){this.Q(a.sa);this.d[this.a]=0;return h}var d=this.la();return d};
k.Ra=function(){if(this.b.length<1)return h;var a=this.b[this.a],b=a.i;if(b.length<1)return h;if(this.k){var d=this.k.h.K[this.a];if(typeof d!="undefined")this.d[this.a]=d}this.d[this.a]--;var c=g;if(this.d[this.a]<0){this.d[this.a]=b.length-1;c=i}var e=this.d[this.a];if(b[e].h.parentNode===h){this.t!==h&&this.t.view(h);a.i=this.Y(a.$);this.d[this.a]=a.i.length;e=this.d[this.a]}this.k=b[e];if(this.u!==h)c?this.u.I(this.Ca):this.u.I(this.wa);return this.k};
k.lb=function(){var a=this.b[this.a],b=this.d[this.a];if(a.ha!==h&&b<=0){this.Q(a.ha);this.d[this.a]=a.i.length-1;return h}var d=this.Ra();return d};k.da=function(){if(this.b.length<1)return h;if(this.k){var a=this.k.h.K[this.a];if(typeof a!="undefined")this.d[this.a]=a}var b=this.b[this.a],d=b.i,c=this.d[this.a];return this.k=d[c]};k.ga=function(a){var b=h;if(a!==h&&a.indexOf&&a.indexOf("CALL:")===0&&a.indexOf("(")===-1)try{b=eval(a.substring(5))}catch(d){}return b};
k.C=function(a){if(a!==h){var b=this,d=function(){var j=b.ga(a.action);if(j)j(a);else{b.t!==h&&b.t.view(a.h);b.f.xb(a.h)}};if(this.f.s&&this.f.s.blur){var c=this.f.s;this.f.s=h;c.removeAttribute&&this.f.pa(c,"aria-activedescendant");var e=function(j){j.target.removeEventListener("blur",e,i);d()};c.addEventListener("blur",e,i);c.blur()}else d()}else{var f=this.b[this.a];f.type=="dynamic"&&this.f.v(f.onEmpty)}};
k.o=function(a,b,d,c){for(var e=0,f;f=a[e];e++)if(f=="LEFT")d[37]=c;else if(f=="UP")d[38]=c;else if(f=="RIGHT")d[39]=c;else if(f=="DOWN")d[40]=c;else if(f=="PGUP")d[33]=c;else if(f=="PGDOWN")d[34]=c;else if(f=="ENTER")d[13]=c;else if(f=="ESC")d[27]=c;else if(f=="DEL")d[46]=c;else b[f.charCodeAt(0)]=c};
k.S=function(a,b,d){var c=[];if(!(a==="")){c=a.split(" ");var e=this;if(d=="prev")this.o(c,this.z[b],this.w[b],function(){e.C(e.Ra())});else if(d=="next")this.o(c,this.z[b],this.w[b],function(){e.C(e.la())});else d=="back"?this.o(c,this.z[b],this.w[b],function(){e.C(e.lb())}):this.o(c,this.z[b],this.w[b],function(){e.C(e.Ka())})}};k.kb=function(a,b,d){var c=[];if(!(a==="")){c=a.split(" ");var e=this;this.o(c,this.A,this.B,function(){if(e.ta(e.b[b])){e.a=b;e.C(e.la())}else e.f.v(d)})}};
k.jb=function(a,b){var d=[];if(!(a==="")){d=a.split(" ");var c=this;this.o(d,this.A,this.B,function(){c.f.v(b)})}};k.Ea=function(a,b,d){var c=[];if(!(a.hotkey==="")){c=a.hotkey.split(" ");var e=this;this.o(c,b,d,function(){e.Q(a)})}};k.Q=function(a){var b=a.m,d=this.f.r().documentElement;if(b.indexOf(".")===0)d=this.da().h;var c=this.f.q(b,d);if(c.length<1)this.f.v(a.onEmpty);else{var e=this.ga(a.action);if(e){var f={};f.action=a.action;f.h=c[0];e(f)}else{this.f.U(c[0],g);c[0].scrollIntoView(i)}this.f.Pa(c[0])}};
k.tb=function(a,b){var d=h,c=this.a;if(c<this.w.length)d=this.w[c][a]||this.z[c][b]||h;if(d===h)d=this.B[a]||this.A[b];return d};
k.Bb=function(a,b){var d={};d.Ma=[];var c=new DOMParser,e=c.parseFromString(a,"text/xml"),f=e.getElementsByTagName("list"),j,o;for(j=0,o;o=f[j];j++){var m={};m.title=o.getAttribute("title");m.hotkey=o.getAttribute("hotkey");m.ka=o.getAttribute("next");m.na=o.getAttribute("prev");m.rb=o.getAttribute("fwd");m.back=o.getAttribute("back");m.onEmpty=o.getAttribute("onEmpty");m.type=o.getAttribute("type");var p,r,q,s,t;m.i=[];var B=o.getElementsByTagName("item");for(p=0;r=B[p];p++){var z={};z.m=r.textContent;
if(r.attributes instanceof NamedNodeMap){s=r.attributes;t=s.length;for(q=0;q<t;q++){var u=s.item(q);z[u.nodeName]=u.value}}m.i.push(z)}m.l=[];var D=o.getElementsByTagName("target");for(p=0;r=D[p];p++){var v={};v.m=r.textContent;if(r.attributes instanceof NamedNodeMap){s=r.attributes;t=s.length;for(q=0;q<t;q++){var u=s.item(q);v[u.nodeName]=u.value}}m.l.push(v)}d.Ma.push(m)}d.l=[];var w,x=e.firstChild;for(j=0,w;w=x.childNodes[j];j++)if(w.tagName=="target"){var v={};v.m=w.textContent;if(w.attributes instanceof
NamedNodeMap){s=w.attributes;t=s.length;for(q=0;q<t;q++){var u=s.item(q);v[u.nodeName]=u.value}}d.l.push(v)}d.ka=x.getAttribute("next");d.na=x.getAttribute("prev");if(b===h||typeof b=="undefined")this.Qa(d,b);else{var H=new (function(I,E,F,G){b(x,E,F,G)});this.Qa(d,H)}};
k.wb=function(){var a=this.ub(),b="";for(var d=0,c;c=a[d];d++)b=b+c.X+", "+c.title+". ";b=b+this.Z+", "+n.e.db;b=b+this.aa+", "+n.e.eb;b=b.replace("PGUP",n.e.za);b=b.replace("PGDOWN",n.e.ya);b=b.replace("ENTER",n.e.va);b=b.replace("DEL",n.e.Xa);b=b.replace("UP",n.e.Ba);b=b.replace("DOWN",n.e.ua);b=b.replace("LEFT",n.e.xa);return b=b.replace("RIGHT",n.e.Aa)};
k.zb=function(){var a=this.vb(),b="";for(var d=0,c;c=a[d];d++)b=b+c.X+", "+c.title+". ";var e=this.F();if(e.ma!=="")b=b+e.ma+", "+n.e.Va+". ";if(e.oa!=="")b=b+e.oa+", "+n.e.Wa+". ";if(e.fa!=="")b=b+e.fa+", "+n.e.$a+". ";if(e.ca!=="")b=b+e.ca+", "+n.e.Za+". ";b=b.replace("PGUP",n.e.za);b=b.replace("PGDOWN",n.e.ya);b=b.replace("ENTER",n.e.va);b=b.replace("DEL",n.e.Xa);b=b.replace("UP",n.e.Ba);b=b.replace("DOWN",n.e.ua);b=b.replace("LEFT",n.e.xa);return b=b.replace("RIGHT",n.e.Aa)};
k.Gb=function(a){this.t=a};k.Hb=function(a){this.u=a};k.ub=function(){var a=[],b;for(var d=0,c;c=this.b[d];d++)if(c.L!==""){b={};b.title=c.title;b.X=c.L;a.push(b)}for(var e=0,f;f=this.P[e];e++)if(this.La(f)){b={};b.title=f.title;b.X=f.hotkey;a.push(b)}return a};k.vb=function(){var a=[],b=this.F();for(var d=0,c;c=b.l[d];d++)if(this.La(c)){var e={};e.title=c.title;e.X=c.hotkey;a.push(e)}return a};
k.La=function(a){var b=g;if(a.hotkey!==""){var d=a.m,c=this.f.r().body;if(d.indexOf(".")===0){var e=this.da();if(e)c=e.h}var f=this.f.q(d,c);if(f.length>0)b=i}return b};
k.Qa=function(a,b){this.b=[];this.a=0;this.d=[];var d=[],c,e;for(c=0,e;e=a.Ma[c];c++){var f={};f.Qb=h;f.$=e;f.title=e.title||"";f.L=e.hotkey||"";f.ma=e.ka||"";f.oa=e.na||"";f.fa=e.rb||"";f.ca=e.back||"";f.onEmpty=e.onEmpty||"";f.type=e.type||"";f.sa=h;f.ha=h;f.ea=h;f.i=this.Y(e);f.l=this.Oa(e);for(var j=0,o;o=f.l[j];j++)if(o.trigger=="listTail")f.sa=o;else if(o.trigger=="listHead")f.ha=o;else if(o.trigger=="listEntry")f.ea=o;if(f.i.length>0||f.type=="dynamic"){this.b.push(f);this.d.push(-1)}else f.L!==
""&&d.push(f)}this.P=[];this.Ub=0;var m;if(a.l)for(c=0,m;m=a.l[c];c++){var p={};p.m=m.m;p.m=p.m.replace(/^\s\s*/,"").replace(/\s\s*$/,"");p.title=m.title||"";p.trigger=m.trigger||"key";p.hotkey=m.hotkey||"";p.action=m.action||"click";p.onEmpty=m.onEmpty||"";this.P.push(p)}this.H!==h&&document.removeEventListener("keypress",this.H,i);b===h||typeof b=="undefined"?this.Ib(a,d):b(a,this.b,d,this.P)};
k.Y=function(a){var b=[];if(!a.i)return b;for(var d=0,c;c=a.i[d];d++)try{var e=c.m.replace(/^\s\s*/,"").replace(/\s\s*$/,""),f=this.f.r().documentElement,j=this.f.q(e,f),o=c.index||"0",m=parseInt(o,10),p=j.length-m,r=c.Rb||"*";if(r!="*")p=parseInt(r,10);var q=p+m,s=c.action||h;while(m<q){var t={};t.action=s;t.h=j[m];if(typeof t.h!="undefined"){if(typeof t.h.K=="undefined")t.h.K={};t.h.K[this.b.length]=b.length;b.push(t)}m++}}catch(B){}return b};
k.Oa=function(a){var b=[];if(!a.l)return b;for(var d=0,c;c=a.l[d];d++){var e={};e.m=c.m.replace(/^\s\s*/,"").replace(/\s\s*$/,"");e.title=c.title||"";e.trigger=c.trigger||"key";e.hotkey=c.hotkey||"";e.action=c.action||"click";e.onEmpty=c.onEmpty||"";b.push(e)}return b};
k.Ib=function(a,b){var d=this,c;this.A={};this.B={};this.z=[];this.w=[];var e;for(c=0,e;e=this.P[c];c++)this.Ea(e,this.A,this.B);var f=[];this.Z=a.ka||"";if(this.Z!=="")f=this.Z.split(" ");this.o(f,this.A,this.B,function(){d.Cb();d.Ia()});f=[];this.aa=a.na||"";if(this.aa!=="")f=this.aa.split(" ");this.o(f,this.A,this.B,function(){d.Eb();d.Ia()});var j;for(c=0,j;j=this.b[c];c++){var o={},m={};this.z.push(o);this.w.push(m);this.S(j.ma,c,"next");this.S(j.oa,c,"prev");this.S(j.fa,c,"fwd");this.S(j.ca,
c,"back");this.kb(j.L,c,j.onEmpty);var p;for(p=0,e;e=j.l[p];p++)this.Ea(e,o,m)}var r;for(c=0,r;r=b[c];c++)this.jb(r.L,r.onEmpty);this.H=function(q){if(q.ctrlKey)return i;if(d.f.W)return i;var s=d.tb(q.keyCode,q.charCode);if(s)return s()};document.addEventListener("keypress",this.H,i)};var y=function(a){this.g=a;this.N=1.5;this.padding=-1;this.Fb=0;this.R=a.r();this.c=this.R.createElement("span");this.c.style.backgroundColor="#CCE6FF";this.c.style.borderColor="#0000CC";this.c.style.borderWidth="medium";this.c.style.borderStyle="groove";this.c.style.position="absolute";this.c.style.display="none";this.R.body.appendChild(this.c);this.Ga=function(){}};y.fb={Nb:0,Ya:1};k=y.prototype;
k.view=function(a){while(this.c.firstChild)this.c.removeChild(this.c.firstChild);if(a===h)this.c.style.display="none";else{var b=0,d=0,c=a;if(c.offsetParent){b=c.offsetLeft;d=c.offsetTop;c=c.offsetParent;while(c!==h){b+=c.offsetLeft;d+=c.offsetTop;c=c.offsetParent}}this.c.appendChild(a.cloneNode(i));this.c.style.top=d+"px";this.c.style.left=b+"px";this.c.style.zIndex=999;this.c.style.display="block";this.Na()}};k.qa=function(a){this.N=a;this.Na()};
k.Na=function(){this.R.body.removeChild(this.c);this.Ab();this.pb();this.hb();this.R.body.appendChild(this.c);this.Ga&&this.Ga(this.c);if(this.Fb==y.fb.Ya){var a=this;window.setTimeout(function(){a.c.scrollIntoView(i)},0)}};k.hb=function(){if(!(this.padding<0)){var a="//*[not(.//*)]",b=this.g.q(a,this.c);for(var d=0,c;c=b[d];d++)c.style.padding=this.padding+"px"}};
k.pb=function(){var a=this.c.getElementsByTagName("img");for(var b=0,d;d=a[b];b++){if(!d.hasAttribute("Axs_OrigHeight")){d.setAttribute("Axs_OrigHeight",d.height);d.setAttribute("Axs_OrigWidth",d.width)}d.height=d.getAttribute("Axs_OrigHeight")*this.N;d.width=d.getAttribute("Axs_OrigWidth")*this.N}};
k.Ab=function(){var a="fontSizeAdjust"in this.c.style;if(a){var b=this.N*0.52;this.c.style.fontSizeAdjust=b}else{var d=this.N*100+"%";this.c.style.setProperty("font-size",d,"important")}var c=this.c.getElementsByTagName("*");for(var e=0,f;f=c[e];e++){f.style.setProperty("line-height","normal","important");a||f.style.setProperty("font-size","100%","important")}};var A=function(a){var b="http://google-axsjax.googlecode.com/svn/trunk/";this.ob=b+"common/earcons/axsEarcons.swf?sound=";this.n=h;this.V=a;this.ra=b+"thirdparty/soundmanager2/";this.j=h;this.G=g;this.Ua="minimal";this.T=g;this.ja=0};k=A.prototype;
k.ia=function(){if(!this.V)if(!this.G)if(!this.T){this.T=i;this.ja=0;if(this.j!==h){this.j.parentNode.removeChild(this.j);this.j=h}this.j=document.createElement("iframe");var a=document.location.toString();if(a.indexOf("#")!=-1)a=a.substring(0,a.indexOf("#"));this.j.src=this.ra+"AxsJAX_SM2_Linker.html#Verbosity="+this.Ua+",Parent="+a;this.j.width="0%";this.j.height="0%";this.j.style.top="-1000";this.j.style.left="-1000";this.j.style.position="absolute";document.getElementsByTagName("body")[0].appendChild(this.j);
this.Ha()}};k.Ha=function(){if(document.location.hash=="#InitSuccess"){this.G=i;this.T=g}else if(this.Ua=="none"&&this.ja>0){this.G=i;this.T=g}else{var a=this;window.setTimeout(function(){a.Ha()},100);this.ja++}};k.I=function(a){var b=this.Db(a);if(!(this.V||b))if(this.G)this.j.src=this.ra+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Play("+a+")";else{this.ia();var d=this;window.setTimeout(function(){d.I(a)},500)}};
k.stop=function(){if(this.n){this.n.parentNode.removeChild(this.n);this.n=h}if(!this.V)if(!!this.G)this.j.src=this.ra+"AxsJAX_SM2_Linker.html#AxsSoundCmd=Stop()"};k.getTime=function(){if(this.V)return-1;if(!this.G)return-1;var a="Time=",b=unescape(document.location.hash);if(b.indexOf(a)==-1)return-1;var d=b.indexOf(a)+a.length,c=parseInt(b.substring(d),10);return c};
k.Db=function(a){var b="";switch(a){case "alert":b="alert";break;case "deselect":b="deselect";break;case "item":b="item";break;case "list":b="list";break;case "select":b="select";break;case "success":b="success";break;case "wrap":b="wrap";break;default:}if(!(b==="")){if(this.n===h){this.n=document.createElement("embed");this.n.height=0;this.n.width=0;document.body.appendChild(this.n)}this.n.src=this.ob+b}};var C={};C.ab="The following shortcut keys are available. ";C.g=h;C.p=h;C.D=h;C.Fa=h;C.M=1.5;
C.ia=function(){C.g=new l(i);C.p=new n(C.g);document.addEventListener("keypress",C.H,i);var a='<cnr next="RIGHT l" prev="LEFT h">     <list title="Featured question" next="DOWN j" prev="UP k">    <item>      //div[contains(@class, "featured") and not(contains(@class, "text-featured"))]    </item>\t<target title="Yes" hotkey="y" action="CALL:axsModerator.voteYes">\t .\t</target>\t<target title="No" hotkey="n" action="CALL:axsModerator.voteNo">\t .\t</target>\t<target title="Skip" hotkey="s" action="CALL:axsModerator.voteSkip">\t .\t</target>\t<target title="Repeat" hotkey="r" action="CALL:axsModerator.featuredQuestionChangeHandler">\t .\t</target>  </list>  <list title="Questions" next="DOWN j" prev="UP k">    <item>      //table[contains(@class, "QuestionListPanel")]/tbody/tr    </item>\t<target title="Yes" hotkey="y" action="CALL:axsModerator.voteYes">\t .\t</target>\t<target title="No" hotkey="n" action="CALL:axsModerator.voteNo">\t .\t</target>  </list>   <list title="Topics" fwd="DOWN j" back="UP k">    <item>      //div[contains(@class, "fork")]/..//div[contains(@class, "link link-regular G1k55290GB")]    </item>\t<target title="Go to topic" hotkey="ENTER" action="CALL:axsModerator.goToTopic">\t .//a\t</target>  </list>\t<target title="Ask a question" hotkey="a">\t //table[@class="AskMinimizedPanel"]//div[@class="goog-button-base-content"]\t</target></cnr>';C.p.Bb(a,
h);C.D=new y(C.g);C.p.Gb(C.D);C.D.qa(C.M);C.Fa=new A(i);C.p.Hb(C.Fa);document.addEventListener("DOMAttrModified",C.nb,i);var b='//div[contains(@class, "featured") and not(contains(@class, "text-featured"))]//div[contains(@class,"text text-less paragraph")]',d=C.g.q(b,document.body)[0];if(d){d.addEventListener("DOMNodeInserted",C.Ja,i);C.p.Ka();C.Ja()}};C.Sb=function(a){var b=a.h,d=b.href;window.content.document.location=d;window.setTimeout(function(){window.location.reload()},1000)};
C.Xb=function(a){var b=a.h,d='.//div[contains(@class,"gwt-ToggleButton")]',c=C.g.q(d,b)[0];C.g.U(c,g);C.g.v("Press enter to confirm your yes vote.")};C.Vb=function(a){var b=a.h,d='.//div[contains(@class,"gwt-ToggleButton")]',c=C.g.q(d,b)[1];C.g.U(c,g);C.g.v("Press enter to confirm your no vote.")};C.Wb=function(a){var b=a.h,d='//div[(@class = "goog-button-base-content") and (text()="Skip")]',c=C.g.q(d,b)[0];C.g.U(c,g)};C.nb=function(a){var b=a.target;b.className=="qdb-StatusBox"&&C.g.v(b.textContent)};
C.Ja=function(){C.p.C(C.p.da());C.D.view(h)};C.H=function(a){if(a.ctrlKey)return i;if(a.keyCode==27){C.g.s.blur();return g}if(C.g.W)return i;var b=C.yb[a.keyCode]||C.mb[a.charCode];if(b)return b();return i};C.yb={};C.mb={45:function(){C.M-=0.1;C.D.qa(C.M);return g},61:function(){C.M+=0.1;C.D.qa(C.M);return g},63:function(){var a=C.ab+C.p.zb()+C.p.wb();C.g.v(a);return g},47:function(){var a="//input",b=C.g.q(a,document.body)[0];b.focus();b.select();return g}};window.setTimeout(C.ia,1000);
 })();
