(function() { 
var b=function(a){this.o=0;this.i=null;this.n=false;this.c=null;this.e=false;var c=this,e=function(d){c.c=d.target;if(d.target.tagName=="INPUT"||d.target.tagName=="SELECT"||d.target.tagName=="TEXTAREA")c.e=true;return true};document.addEventListener("focus",e,true);var f=function(d){c.l(c.c,"aria-activedescendant");c.c=null;if(d.target.tagName=="INPUT"||d.target.tagName=="SELECT"||d.target.tagName=="TEXTAREA")c.e=false;return true};document.addEventListener("blur",f,true);if(a){this.n=true;document.addEventListener("keypress",
function(d){c.H(d,c)},true);document.body.J=true}this.g=document.body};b.prototype.w=function(){var a=this.g;while(a.nodeType!=9)a=a.parentNode;return a};b.prototype.m=function(a,c){if(!a.id)this.p(a);if(c){this.d(a,"live","rude");this.d(a,"atomic","true");var e=this.w(),f=e.createElement("div");f.textContent=" ";f.name="AxsJAX_dummyNode";if(a.lastChild&&a.lastChild.name&&a.lastChild.name==f.name)a.removeChild(a.lastChild);a.appendChild(f)}else{var d=this.z(a,"role");this.d(a,"role","row");var g=
this.c;if(!g||g.nodeType==9){this.g.tabIndex=-1;g=this.g}this.d(g,"activedescendant",null);g.focus();this.d(g,"activedescendant",a.id);var i=this;window.setTimeout(function(){if(d)i.d(a,"role",d);else i.l(a,"role")},0)}};b.prototype.p=function(a,c){if(!a)return"";if(a.id)return a.id;var e=c||"AxsJAX_ID_";a.id=e+this.o++;return a.id};b.prototype.H=function(a,c){if(!c.n)return true;if(a.keyCode==9&&c.i){c.i.focus();c.i=null}return true};b.prototype.d=function(a,c,e){if(!a)return;c=c.toLowerCase();switch(c){case "live":c=
"aria-live";break;case "activedescendant":c="aria-activedescendant";break;case "atomic":c="aria-atomic";break;default:break}a.setAttribute(c,e)};b.prototype.z=function(a,c){return a.getAttribute(c)};b.prototype.l=function(a,c){if(a&&a.removeAttribute)a.removeAttribute(c)};b.prototype.t=function(a,c){try{var e=c.ownerDocument.evaluate(a,c,null,XPathResult.ORDERED_NODE_ITERATOR_TYPE,null)}catch(f){return[]}var d=[];for(var g=e.iterateNext();g;g=e.iterateNext())d.push(g);return d};var h={};h.I={ar2en:"en",de2en:"en",de2fr:"fr",el2en:"en",en2ar:"ar",en2de:"de",en2el:"el",en2es:"es",en2fr:"fr",en2it:"it",en2ja:"ja",en2ko:"ko",en2nl:"nl",en2ru:"ru",en2zh:"zh",es2en:"en",fr2de:"de",fr2en:"en",it2en:"en",ja2en:"en",ko2en:"en",nl2en:"en",ru2en:"en",zh2en:"en","ar2en@bot.talk.google.com":"en","de2en@bot.talk.google.com":"en","de2fr@bot.talk.google.com":"fr","el2en@bot.talk.google.com":"en","en2ar@bot.talk.google.com":"ar","en2de@bot.talk.google.com":"de","en2el@bot.talk.google.com":"el",
"en2es@bot.talk.google.com":"es","en2fr@bot.talk.google.com":"fr","en2it@bot.talk.google.com":"it","en2ja@bot.talk.google.com":"ja","en2ko@bot.talk.google.com":"ko","en2nl@bot.talk.google.com":"nl","en2ru@bot.talk.google.com":"ru","en2zh@bot.talk.google.com":"zh","es2en@bot.talk.google.com":"en","fr2de@bot.talk.google.com":"de","fr2en@bot.talk.google.com":"en","it2en@bot.talk.google.com":"en","ja2en@bot.talk.google.com":"en","ko2en@bot.talk.google.com":"en","nl2en@bot.talk.google.com":"en","ru2en@bot.talk.google.com":"en",
"zh2en@bot.talk.google.com":"en"};h.b=null;h.a=0;h.f=null;h.e=false;h.c=null;h.h=false;h.D=function(){h.f=new b(true);h.b=[];h.a=-1;document.addEventListener("keypress",h.u,true);document.addEventListener("focus",h.v,true);document.addEventListener("blur",h.q,true);document.addEventListener("DOMNodeInserted",h.s,true);h.h=false};h.r=function(){var a="//*[@aria-live]",c=h.f.t(a,document.body);for(var e=0,f;f=c[e];e++)f.removeAttribute("aria-live");h.h=true};h.v=function(a){h.c=a.target;if(a.target.tagName==
"INPUT"||a.target.tagName=="TEXTAREA")h.e=true};h.q=function(a){h.c=null;if(a.target.tagName=="INPUT"||a.target.tagName=="TEXTAREA")h.e=false};h.u=function(a){if(a.ctrlKey)return true;if(a.keyCode==27){h.c.blur();return false}if(a.keyCode==38){h.C();return false}if(a.keyCode==40){h.B();return false}return true};h.s=function(a){var c=a.target;if(c.tagName=="DIV"&&(c.className=="RNCQof"||c.className=="h8iICe")){if(!h.h)h.r();h.G(c);h.f.m(h.j(c),true);h.F(c)}};h.F=function(a){if(a.getElementsByTagName("SPAN").length>
1){h.b.push(a.getElementsByTagName("SPAN")[0]);h.b.push(a.getElementsByTagName("SPAN")[1])}else h.b.push(a)};h.G=function(a){var c=h.A(a),e=h.j(a),f=h.I[c];if(f)e.lang=f};h.A=function(a){var c="";c=a.getElementsByTagName("SPAN").length>1?a.getElementsByTagName("SPAN")[0].textContent:a.parentNode.getElementsByTagName("SPAN")[0].textContent;c=c.substring(0,c.indexOf(":"));return c};h.j=function(a){return a.getElementsByTagName("SPAN").length>1?a.getElementsByTagName("SPAN")[1]:a};h.k=function(a){a.scrollIntoView(true);
h.f.m(a,true)};h.B=function(){h.a++;if(h.a>=h.b.length)h.a=h.b.length-1;var a=h.b[h.a];h.k(a)};h.C=function(){h.a--;if(h.a<0)h.a=0;var a=h.b[h.a];h.k(a)};h.D();
 })();
