(function() { 
var a=false,g=null,i=true,k=function(b){this.ma=0;this.o=g;this.B=a;this.f=g;this.u=a;var c=this;this.s=document.body;this.L();if(b){this.B=i;document.addEventListener("keypress",function(d){c.S(d,c)},i);document.body.D=i}};
k.prototype.L=function(){var b=this.e(),c=this,d=function(f){c.f=f.target;if(f.target.tagName=="INPUT"||f.target.tagName=="SELECT"||f.target.tagName=="TEXTAREA")c.u=i;return i};b.addEventListener("focus",d,i);var e=function(f){c.Q(c.f,"aria-activedescendant");c.f=g;if(f.target.tagName=="INPUT"||f.target.tagName=="SELECT"||f.target.tagName=="TEXTAREA")c.u=a;return i};b.addEventListener("blur",e,i)};
k.prototype.$a=function(b){this.s=b;var c=this.e();if(this.B&&!c.body.D){var d=this;c.addEventListener("keypress",function(e){d.S(e,d)},i);c.body.D=i}this.L()};k.prototype.e=function(){var b=this.s;while(b.nodeType!=9)b=b.parentNode;return b};
k.prototype.ab=function(b,c){b.id||this.M(b);if(c){this.g(b,"live","rude");this.g(b,"atomic","true");var d=this.e(),e=d.createElement("div");e.textContent=" ";e.name="AxsJAX_dummyNode";b.lastChild&&b.lastChild.name&&b.lastChild.name==e.name&&b.removeChild(b.lastChild);b.appendChild(e)}else{var f=this.Ra(b,"role");this.g(b,"role","row");var h=this.f;if(!h||h.nodeType==9){this.s.tabIndex=-1;h=this.s}this.g(h,"activedescendant",g);h.focus();this.g(h,"activedescendant",b.id);var j=this;window.setTimeout(function(){f?
j.g(b,"role",f):j.Q(b,"role")},0)}};k.prototype.R=function(b){var c=window.content.document,d=c.createElement("span");d.id="AxsJAX_audioNode";this.g(d,"role","alert");d.style.position="absolute";d.style.left="-1000em";var e=c.getElementById(d.id);e&&c.body.removeChild(e);d.textContent=b;c.body.appendChild(d)};
k.prototype.d=function(b,c){var d="AxsJAX_pixelAudioNode",e="AxsJAX_pixelAudioNode",f="data:image/gif;base64,R0lGODlhAQABAIAAANvf7wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==",h=this.e(),j=g;if(c){if(c.previousSibling&&c.previousSibling.name==e)j=c.previousSibling;else{j=h.createElement("img");j.name=e;j.setAttribute("tabindex",0);j.style.outline="none";j.src=f;c.parentNode.insertBefore(j,c);this.Qa(j)}j.setAttribute("alt",b);j.setAttribute("title",b);window.setTimeout(function(){j.blur();j.focus()},0)}else{j=
h.getElementById(d);if(j&&j.alt==b)b=b+" ";if(!j){j=h.createElement("img");j.id=d;j.src=f;h.body.appendChild(j)}j.setAttribute("alt",b);j.setAttribute("title",b);this.ab(j)}};
k.prototype.z=function(b,c){var d=this.e(),e=d.createEvent("MouseEvents");e.initMouseEvent("mousedown",i,i,d.defaultView,1,0,0,0,0,a,a,c,a,0,g);try{b.dispatchEvent(e)}catch(f){}e=d.createEvent("MouseEvents");e.initMouseEvent("mouseup",i,i,d.defaultView,1,0,0,0,0,a,a,c,a,0,g);try{b.dispatchEvent(e)}catch(f){}e=d.createEvent("MouseEvents");e.initMouseEvent("click",i,i,d.defaultView,1,0,0,0,0,a,a,c,a,0,g);try{b.dispatchEvent(e)}catch(f){}if(b.tagName=="A"&&b.href&&(b.href.indexOf("http")===0||b.href.indexOf("javascript:")===
0))if(c)window.open(b.href);else document.location=b.href};k.prototype.Za=function(b,c,d,e,f){var h=0,j=0;if(c=="ENTER")h=13;else if(c.length==1)j=c.charCodeAt(0);var n=this.e(),m=n.createEvent("KeyboardEvent");m.eb("keypress",i,i,g,d,e,f,a,h,j);b.dispatchEvent(m)};k.prototype.M=function(b,c){if(!b)return"";if(b.id)return b.id;var d=c||"AxsJAX_ID_";b.id=d+this.ma++;return b.id};
k.prototype.Xa=function(b){if(!b)return a;if(b.tagName=="A"||b.tagName=="INPUT"){this.o=b;return i}var c=b.getElementsByTagName("*");for(var d=0,e;e=c[d];d++)if(e.tagName=="A"||e.tagName=="INPUT"||e.hasAttribute("tabindex")&&e.tabIndex!=-1){this.o=e;return i}return a};k.prototype.S=function(b,c){if(!c.B)return i;if(b.keyCode==9&&c.o){c.o.focus();c.o=g}return i};
k.prototype.g=function(b,c,d){if(!b)return;c=c.toLowerCase();switch(c){case "live":c="aria-live";break;case "activedescendant":c="aria-activedescendant";break;case "atomic":c="aria-atomic";break;default:break}b.setAttribute(c,d)};k.prototype.Ra=function(b,c){return b.getAttribute(c)};k.prototype.Q=function(b,c){b&&b.removeAttribute&&b.removeAttribute(c)};k.prototype.Qa=function(b){var c=this.M(b),d=this.e(),e=d.baseURI,f=e.indexOf("#");if(f!=-1)e=e.substring(0,f);d.location=e+"#"+c};
k.prototype.n=function(b,c){try{var d=c.ownerDocument.evaluate(b,c,g,XPathResult.ORDERED_NODE_ITERATOR_TYPE,g)}catch(e){return[]}var f=[];for(var h=d.iterateNext();h;h=d.iterateNext())f.push(h);return f};var l={};l.b={cb:"zeeTme",U:"ac-row",C:"ac-row active",na:"XoqCub",ja:"EGSDee",T:"P0GJpc",va:"m14Grb",ra:"yyT6sf",wa:"QhHSYc",l:"n1QcP",q:"rfza3e",k:"kyZrld",Z:"AG5mQe",F:"zyVlgb",G:"XZlFIc",Y:"rziBod",$:"HprMsc",V:"ilX2xb",W:"OvtWcf"};l.ia="Expand all";l.oa="Messages loaded.";l.Ja="Unread. ";l.ua="Red. ";l.w="Selected. ";l.i="Starred. ";l.v="Not ";l.Ia="To undo, press Z.";l.qa="New chat message from ";l.pa="Press escape to ignore the message. Press any other key to open a chat window.";l.ta=", online.";
l.sa=", offline.";l.la=", idle.";l.X="Chat buddies";l.ka="The following shortcut keys are available. Capital L, go to the quick nav select box for jumping to labels. J, go to the next conversation. K, go to the previous conversation. O, open the current conversation. N, go to the next message in the current conversation. P, go to the previous message in the current conversation. X, select conversation. S, star a message/conversation. Y, remove conversation from current view. M, mute conversation. Exclamation mark, report spam. Number sign, move to trash. Z, undo. C, compose. R, reply. A, reply all. F, forward message. Slash, jump to the search field. Escape, leave the search field. Period, more actions menu. ";
l.a=g;l.c=g;l.A=g;l.t=g;l.r=g;l.j=a;l.p=g;l.h=a;l.m=a;
l.Sa=function(b){var c;try{c=window.content.document;l.a=new k(i)}catch(d){alert("You are using a browser that does not fully support the features needed by the AxsJAX experiment. It's functionality will be available the next time you access your account from a supported browser.");return}l.c=b;l.r=g;l.j=a;l.p=g;l.h=a;l.m=a;c.addEventListener("keypress",l.Pa,i);c.addEventListener("DOMNodeInserted",l.Wa,i);var e=c.getElementById("canvas_frame").contentDocument;l.a.$a(e.body);e.addEventListener("DOMAttrModified",
l.Na,i);e.addEventListener("DOMNodeInserted",l.Oa,i);e.addEventListener("keypress",l.Ka,i);l.c.registerViewChangeCallback(l.bb);l.Ta();window.setTimeout(function(){l.N()},100);l.a.d(l.oa,g)};l.Pa=function(b){if(b.ctrlKey)return i;if(b.keyCode==27){l.a.f.blur();return a}if(l.a.u)return i;return i};l.Wa=function(b){var c=b.target,d=c.className;c.tagName=="DIV"&&d.indexOf(l.b.na)!=-1&&d.indexOf(l.b.ja)!=-1&&window.setTimeout(function(){l.La(c)},0)};
l.Ka=function(b){if(b.ctrlKey)return i;if(b.keyCode==27){l.a.f.blur();return a}if(l.a.f&&l.a.f==l.t)if(!l.m)if(b.keyCode==38||b.keyCode==40){l.m=i;window.setTimeout(l.Ma,10);return i}if(l.a.u)return i;if(b.charCode==76){l.A.getElementsByTagName("SELECT")[0].focus();return i}if(b.charCode==63){window.setTimeout(function(){l.a.d(l.ka)},0);return i}var c=l.c.getActiveViewType();if(c=="tl")if(!l.j)if(b.charCode==106||b.charCode==107){l.j=i;window.setTimeout(l.Ga,10);return i}if(c=="cv")if(!l.h)if(b.charCode==
110||b.charCode==112){l.h=i;window.setTimeout(l.ga,10);return i}};l.Na=function(b){var c=b.attrName,d=b.newValue,e=b.prevValue,f=b.target;if(c=="class"&&d.indexOf(l.b.T)!=-1){f.setAttribute("tabindex",0);var h=f.textContent;window.setTimeout(function(){f.focus();l.a.d(h,f)},0);return}if(c=="class"&&e==l.b.U&&d==l.b.C){l.t||l.N();l.O(f);return}if(l.c.getActiveViewType()=="tl")l.xa(b);else l.c.getActiveViewType()=="cv"&&l.aa(b)};l.Oa=function(b){l.c.getActiveViewType()=="tl"&&l.ya(b)};
l.bb=function(){var b=l.c.getActiveViewType();if(b=="tl")return;else if(b=="cv"){l.H();var c=l.c.getActiveViewElement();l.a.Za(c,"n",a,a,a)}};
l.xa=function(b){var c=b.attrName,d=b.newValue,e=b.prevValue,f=b.target,h="";if(c=="style"&&d=="visibility: visible;"){var j=f.parentNode.parentNode;l.K(j)}c=="class"&&e.indexOf(l.b.q)==-1&&d.indexOf(l.b.q)!=-1&&l.a.d(l.w);if(c=="class"&&e.indexOf(l.b.q)!=-1&&d.indexOf(l.b.q)==-1){h=l.v+l.w;l.a.d(h)}c=="class"&&e.indexOf(l.b.l)==-1&&d.indexOf(l.b.l)!=-1&&l.a.d(l.i);if(c=="class"&&e.indexOf(l.b.l)!=-1&&d.indexOf(l.b.l)==-1){h=l.v+l.i;l.a.d(h)}};
l.ya=function(b){var c=b.target;if(c.parentNode.className==l.b.va){var d=c.parentNode.firstChild.textContent,e=l.a.e(),f=e.getElementById("link_undo");if(f){l.a.Xa(f);d=d+l.Ia}l.a.d(d)}};l.Da=function(b){return b.className.indexOf(l.b.wa)!=-1};l.Ea=function(b){var c=b.getElementsByTagName("INPUT")[0];return c.checked};l.Fa=function(b){var c=b.childNodes[1];return c.className.indexOf(l.b.l)!=-1};l.Aa=function(b){return b.childNodes[2]};l.Ca=function(b){return b.childNodes[4].firstChild};l.Ba=function(b){return b.childNodes[4].lastChild};
l.za=function(b){return b.lastChild};l.K=function(b){if(!l.j)return;l.j=a;var c="";c=l.Da(b)?c+l.Ja:c+l.ua;if(l.Ea(b))c=c+l.w;if(l.Fa(b))c=c+l.i;c=c+l.Aa(b).textContent+". "+l.Ca(b).textContent+". "+l.Ba(b).textContent+". "+l.za(b).textContent+". ";l.a.d(c);l.r=b};l.Ha=function(){l.r&&l.K(l.r)};l.Ga=function(){l.c.getActiveViewType()=="tl"&&l.j&&l.Ha()};
l.aa=function(b){var c=b.attrName,d=b.newValue,e=b.prevValue,f=b.target;if(c=="class"&&d==l.b.Z){var h=f.nextSibling;if(h.tagName=="IMG")h=h.nextSibling;l.J(h)}c=="class"&&e.indexOf(l.b.k)==-1&&d.indexOf(l.b.k)!=-1&&l.a.d(l.i);if(c=="class"&&e.indexOf(l.b.k)!=-1&&d.indexOf(l.b.k)==-1){var j=l.v+l.i;l.a.d(j)}};l.fa=function(b){var c=l.ea(b);return c.className.indexOf(l.b.k)!=-1};l.ea=function(b){return b.getElementsByTagName("IMG")[0]};
l.I=function(b){var c=b.getElementsByTagName("TD");for(var d=0,e;e=c[d];d++){var f=e.className;if(f.indexOf(l.b.F)!=-1&&f.indexOf(l.b.G)!=-1)return e}return g};l.da=function(b){var c=l.I(b);if(!c||!c.nextSibling)return g;var d=c.nextSibling.className;if(d.indexOf(l.b.F)!=-1&&d.indexOf(l.b.G)!=-1)return c.nextSibling;return g};l.ca=function(b){var c=b.getElementsByTagName("SPAN");for(var d=0,e;e=c[d];d++)if(e.className==l.b.Y)return e;return g};
l.ba=function(b){if(b.childNodes.length>3)return b.childNodes[3];return g};l.H=function(){var b=window.content.document.getElementById("canvas_frame"),c=b.contentDocument.getElementsByTagName("U");for(var d=0,e;e=c[d];d++)if(e.textContent==l.ia){l.a.z(e.parentNode,a);return}};
l.J=function(b){if(!l.h)return;if(b.parentNode.className==l.b.$)l.h=a;else l.H();var c="";if(l.fa(b))c=c+l.i;var d=l.I(b),e=l.da(b),f=l.ca(b),h=l.ba(b);if(d)c=c+d.textContent+". ";if(e)c=c+e.textContent+". ";if(f)c=c+f.textContent+". ";if(h)c=c+h.textContent+". ";l.a.d(c,b);l.p=b};l.ha=function(){l.p&&l.J(l.p)};l.ga=function(){l.c.getActiveViewType()=="cv"&&l.h&&l.ha()};
l.Ta=function(){var b=l.c.addNavModule("Quick Nav"),c=l.P(),d=window.content.document.createElement("select");for(var e=0,f;f=c[e];e++){var h=window.content.document.createElement("option");h.textContent=f.textContent;d.appendChild(h)}d.addEventListener("keypress",l.Ya,i);b.appendChild(d);l.A=b.db()};l.P=function(){var b=l.c.getNavPaneElement(),c=".//DIV[contains(concat(' ', @class, ' '), '"+l.b.ra+"')]";return l.a.n(c,b)};l.Ya=function(b){b.keyCode==13&&l.Ua()};
l.Ua=function(){var b=l.P(),c=l.A.getElementsByTagName("SELECT")[0],d=c.selectedIndex;l.a.z(b[d].firstChild,a)};l.N=function(){var b=window.content.document.getElementById("canvas_frame"),c=b.contentDocument.body,d="//input[@label]";l.t=l.a.n(d,c)[0];l.t.title=l.X};l.O=function(b){l.m=a;var c="div/div[1]/div[1]",d=l.a.n(c,b)[0],e="",f=d.firstChild.className;e=f.indexOf(l.b.V)!=-1?l.ta:f.indexOf(l.b.W)!=-1?l.sa:l.la;var h=l.a.n("div/div[1]/div[2]",b)[0];l.a.R(h.textContent+e)};
l.Ma=function(){if(l.m){var b=window.content.document.getElementById("canvas_frame"),c=b.contentDocument.body,d="//div[@class='"+l.b.C+"']",e=l.a.n(d,c)[0];l.O(e)}};l.La=function(b){var c=b.getElementsByTagName("textarea")[0];c.addEventListener("keypress",function(f){if(f.keyCode==27)return i;var h=b.getElementsByTagName("img")[3];l.a.z(h,a);return a},i);c.focus();var d=b.getElementsByTagName("td")[1].textContent,e=l.qa+d+l.pa;l.a.R(e)};
l.Va=function(){typeof gmonkey=="object"&&gmonkey.load("1.0",l.Sa)};window.addEventListener("load",l.Va,i);
 })();
